Clear wkup_status register to avoid re-trigger if intr_state register
lowRISC/opentitan pull request #10034
Opened 2022-01-12 22:03 UTC by patel-madhuri

The sysrst_ctrl_combo_detect and sysrst_ctrl_common_vseq is updated with clear wkup_status register to avoid re-triggering of the 
intr_state register. 

Signed-off-by: Madhuri Patel <madhuri.patel@ensilica.com>

2022-01-13 01:59 UTC, weicaiyang commented on hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_base_vseq.sv
> +      if (rdata != 0) begin
nit: alignment

2022-01-13 01:59 UTC, weicaiyang commented on hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_base_vseq.sv
> +       csr_rd_check(ral.wkup_status, .compare_value(1));
since we just read it, perhaps just check rdata==1;

2022-01-13 01:59 UTC, weicaiyang commented on hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_common_vseq.sv
> +    uvm_reg_data_t rdata;
this variable is not used.

2022-01-13 01:59 UTC, weicaiyang commented on hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_common_vseq.sv
> +    clear_wkup_status_register();
I don't quite understand why interrupt will be re-triggered if wkup_status isn't clear. perhaps I miss something, but I don't find this in the spec.

@msfschaffner may know this better

2022-01-14 22:42 UTC, msfschaffner commented on hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_common_vseq.sv
> +    clear_wkup_status_register();
Ah - this behaves like this since we use the `wkup_status` (which is in the AON domain), synchronize it over, and connect it to the `event_intr_i` input of `prim_intr_hw` without any edge detection.

I will change this so that the interrupt can be cleared with having to clear the wkup status register first, see #10098.

Once that is merged, `clear_wkup_status_register` does not have to be called here anymore.

2022-01-18 19:44 UTC, weicaiyang commented
@patel-madhuri With the design update, the change in this PR is not really what it meant at the beginning. Can you update the commit message and title to reflect the current change, or just move those minor updates into other related PRs which may be even better.

2022-01-19 12:26 UTC, patel-madhuri commented
@weicaiyang I have updated the commit message and description of the PR. This change will fix the V1 regression failure which is the top priority. If I move this change to other PR it would take some time to merge the PR and till then V1 regression will keep failing. So I think its better to keep the change in this PR and merge this as soon as possible.

2022-01-19 16:39 UTC, weicaiyang approved these changes
LGTM, thanks

2022-01-19 16:41 UTC, weicaiyang commented
@matutem can you take a look at this PR? If looks good, please merge it

2022-01-21 06:48 UTC, matutem requested changes
Please fix the commit description per https://docs.opentitan.org/doc/project/detailed_contribution_guide/#what-should-commit-messages-look-like.

Specifically,
- The title should use imperative verb, so "Correct" instead of Corrected.
- Could you reword "combo detect register names in scoreboard".
- What about "Fix tl access handling in scoreboard"

2022-01-21 23:22 UTC, matutem approved these changes
LGTM

2022-01-22 00:32 UTC, msfschaffner commented
Thanks for the feedback everyone, merging this in now.

2022-01-22 00:32 UTC, merged