[flash_ctrl] Adding test host direct read,
lowRISC/opentitan pull request #10052
Opened 2022-01-13 14:45 UTC by nikola-miladinovic

adding randomization for scramble,ecc and he,

modifying scb for eflash ral checking support

Signed-off-by: Nikola Miladinovic <nikola.miladinovic@ensilica.com>

2022-01-13 20:53 UTC, matutem requested changes
Can you please modify the PR message per https://docs.opentitan.org/doc/ug/github_notes/, section "Working in your local repo".

2022-01-14 16:22 UTC, nikola-miladinovic commented
> Can you please modify the PR message per https://docs.opentitan.org/doc/ug/github_notes/, section "Working in your local repo".

Added message according to instructions.

2022-01-19 08:27 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_dir_rd_vseq.sv
> +  task body();
In the other tests which have loops for transaction, it make sense and it is used. For this test there is no loop for transactions so here randomization is done at cip lib and i would keep test as it is.

2022-01-19 20:46 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_dir_rd_vseq.sv
> +  task body();
This test corresponds to the "host_read_direct" testpoint? So the objective is performance measurements, is that why no extra randomization is required?

2022-01-19 20:54 UTC, matutem commented
Nikola, thanks for straightening the PR message somewhat. I am afraid the link I placed in my comment is wrong: please refer to https://docs.opentitan.org/doc/project/detailed_contribution_guide/#what-should-commit-messages-look-like for PR descriptions.

2022-01-19 23:48 UTC, matutem requested changes
How does this test fulfill the testpoint description: "Perform back-to-back direct reads via Host in order to test bandwidth of hardware host interface. In addition, perform stalls to test pipeline structure. Enable scramble to test pipeline structure."

Does it compute bandwidth to host? Can it? How does it stall the reads?

2022-01-19 23:48 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv
> +  virtual function void set_partition_pc(uint sel_data_part_pc = 100, uint sel_info_part_pc = 0,
It is best to avoid the constraint that things add up to 100. For example, you could compute the percentages based on the ratios of each part to the total of all, regardless of whether they add up to 100. Think of the "dist" systemverilog randomization construct.

2022-01-19 23:48 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_dir_rd_vseq.sv
> +    end
You seem to perform no checking on this data read... is that intentional? I think this test needs more comments describing what it is meant to do, and how it addresses the testpoint description in the testplan.

2022-01-20 12:50 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv
> +  virtual function void set_partition_pc(uint sel_data_part_pc = 100, uint sel_info_part_pc = 0,
> It is best to avoid the constraint that things add up to 100. For example, you could compute the percentages based on the ratios of each part to the total of all, regardless of whether they add up to 100. Think of the "dist" systemverilog randomization construct.

Agree. This code is inherited and instruction from @sriyerg  are to keep everything what is working.

2022-01-20 13:20 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_dir_rd_vseq.sv
> +  task body();
Objective is to test pipeline structure. Test was written that it has two parts: without and with scramble enabled. Data which are being read is from 10 to 16 (maximum that can be written). In order to send back to back transfers , special task do_direct_read() was written as non-blocking and also option: run_opts: ["+zero_delays=1"] was added. Stalls are seen on waves. Test was discovered RTL bug [#10001 ](url). Since I was investigating SRAM module and others, I think that this is best that TL IF can do in order to send read transactions.

2022-01-20 13:20 UTC, nikola-miladinovic commented
> How does this test fulfill the testpoint description: "Perform back-to-back direct reads via Host in order to test bandwidth of hardware host interface. In addition, perform stalls to test pipeline structure. Enable scramble to test pipeline structure."
> 
> Does it compute bandwidth to host? Can it? How does it stall the reads?

Answered in previous question.

2022-01-20 14:52 UTC, nikola-miladinovic commented
> Nikola, thanks for straightening the PR message somewhat. I am afraid the link I placed in my comment is wrong: please refer to https://docs.opentitan.org/doc/project/detailed_contribution_guide/#what-should-commit-messages-look-like for PR descriptions.

Ok, message is modified according these instructions.

2022-01-20 14:52 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_dir_rd_vseq.sv
> +    end
Comment for checking is added into test to state where it is done.

2022-01-24 18:12 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv
> +  virtual function void set_partition_pc(uint sel_data_part_pc = 100, uint sel_info_part_pc = 0,
@matutem, each of these input args to this function are indeed ratios. Except that the denominator (i.e. sum of all weights add up to 100). The other alternative is to make these `real`, with their sum totaling 1.0. The former seems simpler, unless you are suggesting some other way.

2022-01-24 18:41 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +  mailbox #(flash_trans_t) data_phase_mbox;
I think an SV queue should suffice. Also, this is specific to host read path - so perhaps prefix these variables with `eflash_` for clarity? As suggested above, make these `tl_seq_item` type instead.

2022-01-24 18:41 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +    `uvm_info(`gfn, $sformatf("Comparing 2 transactions:\nt1: %0p\nt2: %0p", t1, t2), UVM_HIGH)
Maybe skip this UVM info msg - this is a very trivial function.

2022-01-24 18:41 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +  } flash_trans_t;
I dont think this data structure is needed. These signals have nothing to do with flash. You can directly maintain a queue of `tl_seq_item` queue instead (replacing the mailbox below).

2022-01-24 18:41 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +                   "AddrPhase transaction not available in addr_phase_mbox")
Or, `DV_CHECK_GT(eflash_addr_phase_queue.size(), 0)`.

2022-01-24 18:41 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +    end
This would end up being simpler with SV queues as well.

2022-01-24 18:46 UTC, weicaiyang commented
@eshapira can you also review all the flash_ctrl PRs, as you need to use them for close-source. If something needs to be done differently, it's better to point it out now.

2022-01-24 18:46 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +    bit                  [TL_AIW-1:0] source;
These variables are unused.

2022-01-24 18:48 UTC, sriyerg commented
I left some comments. Still reviewing, thanks!

2022-01-25 14:59 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +    `uvm_info(`gfn, $sformatf("Comparing 2 transactions:\nt1: %0p\nt2: %0p", t1, t2), UVM_HIGH)
message has UVM_HIGH verbosity and it is helpful for debugging. I would keep it as it is since without switch -v h it is not visible.

2022-01-26 12:56 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +  mailbox #(flash_trans_t) data_phase_mbox;
Fixed.

2022-01-26 12:56 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +  } flash_trans_t;
Fixed.

2022-01-26 12:56 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +                   "AddrPhase transaction not available in addr_phase_mbox")
Fixed.

2022-01-26 12:57 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +    end
yes, fixed.

2022-01-26 12:57 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +    bit                  [TL_AIW-1:0] source;
removed, fixed.

2022-01-26 15:29 UTC, eshapira approved these changes
LGTM with one nit

2022-01-26 15:47 UTC, nikola-miladinovic commented
> How does this test fulfill the testpoint description: "Perform back-to-back direct reads via Host in order to test bandwidth of hardware host interface. In addition, perform stalls to test pipeline structure. Enable scramble to test pipeline structure."
> 
> Does it compute bandwidth to host? Can it? How does it stall the reads?

@matutem : Please revisit your change requests. From my side everything is done and fixed.

2022-01-26 20:01 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv
> +  virtual function void set_partition_pc(uint sel_data_part_pc = 100, uint sel_info_part_pc = 0,
Aha... good argument @eshapira.

2022-01-26 20:21 UTC, matutem requested changes
Nikola, the PR description has not been updated per "https://docs.opentitan.org/doc/project/detailed_contribution_guide/#what-should-commit-messages-look-like". Do you have a pending update?

2022-01-26 20:21 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_dir_rd_vseq.sv
> +                   "exp_data: 0x%0h != rd_trans: 0x%0h", flash_op_data[k], flash_rd_one_data))
Please use `DV_CHECK_EQ.

2022-01-26 20:23 UTC, matutem commented
Nikola, when you address the issues, please ping me, or click the "Re-request review" button next to my name under reviewers, so we can close on this ASAP.

2022-01-26 20:55 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +    `uvm_info(`gfn, $sformatf("Comparing 2 transactions:\nt1: %0p\nt2: %0p", t1, t2), UVM_HIGH)
I will suggest skipping this function entirely since you already have `tl_seq_item::compare()`.

2022-01-26 20:57 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      eflash_addr_phase_queue.push_back(addr_trans);
Can you not do this directly:
```
        eflash_addr_phase_queue.push_back(item);
```

Monitor already creates new items before sending over the TLM port. I am not sure I understand why an intermediate new item is created.

2022-01-26 20:59 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      `DV_CHECK_GT(eflash_addr_phase_queue.size(), 0)
```suggestion
      `DV_CHECK_GT_FATAL(eflash_addr_phase_queue.size(), 0)
```

Need to be fatal error since there is no point progressing beyond this. Error thrown is a fatal testbench coding issue.

2022-01-27 09:54 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_dir_rd_vseq.sv
> +                   "exp_data: 0x%0h != rd_trans: 0x%0h", flash_op_data[k], flash_rd_one_data))
OK for  usage of DV_CHECK_EQ and I modified commit message. now it looks like:

[flash_ctrl] ADD TEST FOR HOST DIRECT READ DATA

Add flash_ctrl_host_rd_dir_test. Add randomization
for scramble,ecc and he. Add checking host direct read
data transactions in scoreboard when scramble is disabled.

Signed-off-by: Nikola Miladinovic <nikola.miladinovic@ensilica.com>

2022-01-27 11:46 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +    `uvm_info(`gfn, $sformatf("Comparing 2 transactions:\nt1: %0p\nt2: %0p", t1, t2), UVM_HIGH)
We need to compare only specific fields, not entire transactions.

2022-01-27 12:02 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +    if (exp_data[0] != trans.d_data) begin
Ok, fixed.

2022-01-27 12:19 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      eflash_addr_phase_queue.push_back(addr_trans);
Ok, fixed.

2022-01-27 12:20 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      `DV_CHECK_GT(eflash_addr_phase_queue.size(), 0)
Ok, fixed.

2022-01-27 18:53 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      `DV_CHECK_EQ(eq_trans(addr_trans, data_trans), 1)
Could you expand `eq_trans` here inline? It is not expected to be called anywhere else, so no need of extra function. The suggestion below also does not modify the `item` that was pushed into addr phase queue. 
```systemverilog 
  // Check that this response belongs to the popped addr item.
  `DV_CHECK_EQ(word_align_addr(item.a_addr), word_align_addr(addr_item.a_addr))
  `DV_CHECK_EQ(item.a_source, addr_item.a_source)
```

2022-01-27 18:53 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      data_trans.a_source = item.d_source;
Same comment as above `data_trans` is not needed. Directly write `item` to `eflash_data_phase_queue`. 

Actually  `eflash_data_phase_queue` is not needed either. You can change the task `process_completed_trans()` to a function which takes the completed item as argument. You can then invoke the function at the end of `process_eflash_tl_d_chan_fifo()`.

2022-01-27 18:53 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      item.a_addr = word_align_addr(item.a_addr);
I will recommend avoiding modifying the packet directly. it may lead to more debug headache later. See my comment below for an alternative.

2022-01-27 18:53 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      eflash_data_phase_queue.push_back(data_trans);
As suggested in comment above. Replace this with the following call:
```systemverilog
  process_completed_trans(item); 
```

2022-01-27 18:53 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      process_completed_trans();
Based on suggestion below, this can be a function called by `process_eflash_tl_d_chan_fifo()`.

2022-01-27 19:37 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_dir_rd_vseq.sv
> +    flash_op.addr inside {[BytesPerBank * bank : BytesPerBank * (bank + 1) - BytesPerBank / 2]};
If you just randomize `addr` it will land in one of the banks. From the randomized addr, you can compute the bank. 

This constraint seems to be doing the reverse. Would you explain how is this useful?

2022-01-27 22:23 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_dir_rd_vseq.sv
> +  task body();
What @matutem is suggesting is to move the contents of the `body()` to a separate task, and call the task randomized number of times. Something like this:
```systemverilog
  virtual task do_test();
    ...
  endtask

  virtual task body();
    repeat (num_trans) begin
      // Randomize self
      `DV_CHECK_RANDOMIZE_FATAL(this)
      do_test(); 
    end 
  endtask
```

By doing so, in the same test, you would be testing multiple different MP region configurations (for example) one after the other, rather than test only one set of MP configurations.

2022-01-28 00:38 UTC, matutem approved these changes
Nikola, you have not changed the commit message.

Also, in some of the responses to comments you explained the test a bit more.
Those explanations should be captured in the testplan or the first few lines in the
*_vseq for the test.

It is important to adhere to these sorts of guidelines, or we will end up with a test
that is not clear and will be hard to maintain. Please keep this in mind going forward,
so the reviews can be more smooth.

Sri left some suggestions and comments. I am okay to commit this once those are
addressed.

2022-01-30 19:45 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_dir_rd_vseq.sv
> +    flash_op.addr inside {[BytesPerBank * bank : BytesPerBank * (bank + 1) - BytesPerBank / 2]};
Code is inherited from flash_ctrl_rand_ops_base_vseq.  It is very useful when banks need to be different like in phy arbitration test.

2022-01-30 19:46 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +    logic                [TL_DW-1:0] exp_data                          [$];
fixed. tool for checking put it.

2022-01-30 19:59 UTC, nikola-miladinovic commented
> Nikola, you have not changed the commit message.
> 
> Also, in some of the responses to comments you explained the test a bit more. Those explanations should be captured in the testplan or the first few lines in the *_vseq for the test.
> 
> It is important to adhere to these sorts of guidelines, or we will end up with a test that is not clear and will be hard to maintain. Please keep this in mind going forward, so the reviews can be more smooth.
> 
> Sri left some suggestions and comments. I am okay to commit this once those are addressed.

Thanks for approve. Anyway, I had updated message with capitalize Title, using imperativ and respecting length of line - if something is missing please let me know. I will update test _vseq accordingly.

2022-01-31 09:29 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_dir_rd_vseq.sv
> +  task body();
make sense. I will implement that.

2022-01-31 12:07 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +    flash_mem_addr_attrs             addr_attrs = new(flash_read.addr);
OK, removed flash_mem_addr_attrs             addr_attrs = new(flash_read.addr.

2022-01-31 13:19 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      `DV_CHECK_EQ(eq_trans(addr_trans, data_trans), 1)
Fixed.

2022-01-31 13:20 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      item.a_addr = word_align_addr(item.a_addr);
Fixed.

2022-01-31 13:44 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      data_trans.a_source = item.d_source;
Agreed, beside eflash_data_phase_queue, I have also removed entire process_completed_trans().

2022-01-31 13:44 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      eflash_data_phase_queue.push_back(data_trans);
Removed completely.

2022-01-31 14:04 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      process_completed_trans();
Fixed.

2022-01-31 14:57 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +    `uvm_info(`gfn, $sformatf("Comparing 2 transactions:\nt1: %0p\nt2: %0p", t1, t2), UVM_HIGH)
removed completely.

2022-01-31 16:13 UTC, sriyerg approved these changes
LGTM, one [comment](https://github.com/lowRISC/opentitan/pull/10052/files#r793895440) is yet to be addressed.

2022-01-31 16:13 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_dir_rd_vseq.sv
> +    flash_op.addr inside {[BytesPerBank * bank : BytesPerBank * (bank + 1) - BytesPerBank / 2]};
Okay.

2022-01-31 16:15 UTC, sriyerg commented
You also need to fix the code lint issues that were reported before we can merge it in.

2022-01-31 16:54 UTC, nikola-miladinovic commented
> You also need to fix the code lint issues that were reported before we can merge it in.

I think that this fails are not related to this commit files. I run all scripts for checking at it seems fine.

2022-02-01 02:32 UTC, merged