[csrng, dv] CSRNG interrupt, alert and error verification
lowRISC/opentitan pull request #10089
Opened 2022-01-14 17:55 UTC by Muqing-Liu

- Add vseqs for CSRNG interrupt, alert and error tests
  - Update the related config files to include the interrupt, alert and error tests

Signed-off-by: Muqing Liu <muqing.liu@wdc.com>

2022-01-15 18:20 UTC, matutem reviewed
Please change the PR title: per https://docs.opentitan.org/doc/project/detailed_contribution_guide/, in section "What should commit messages look like?". That suggests the title of the PR could be "Test CSRNG interrupts, alerts, and errors".

2022-01-17 22:59 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/csrng_env_cfg.sv
> +  rand bit         use_invalid_mubi;
Thanks a lot for your comments @matutem! I have checked the clkmr_base_vseq.sv, but I couldn't find where get_rand_mubi4_val is defined, I am not sure how to use this function. Could you please also point me to where get_rand_mubi4_val is defined? Thanks!

2022-01-17 22:59 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/seq_lib/csrng_alert_vseq.sv
> +    } invalid_mubi_e;
sure, I will move it to csrng_env_pkg

2022-01-17 23:00 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/seq_lib/csrng_alert_vseq.sv
> +      case (invalid_mubi_case)
Okay, I will update the check.

2022-01-17 23:07 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/seq_lib/csrng_alert_vseq.sv
> +
This section is to test the cs_bus_cmp_alert, this is to check whether the software application genbits bus value is equal to the previous valid value. I set the flag0 = 1, clen = 0 in the cmd, so that seed of zero is used to ensure the genbits value is constant to induce this cs_bus_cmp_alert. The cmd sequence is instantiate-generate-instantiate-generate, so the genbits bus is compared after two generate cmds to generate the cs_bus_cmp_alert. Randomization is not involved here.

2022-01-17 23:08 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
> +      `uvm_fatal(`gfn, $sformatf("\n\t ----| PATH NOT FOUND"))
Thank you for spotting this. $sformatf is not necessary here. I will remove it.

2022-01-17 23:08 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
> +  task automatic force_fifo_err(string path1, string path2, bit value1, bit value2,
Sure, I will create a local task for the common part.

2022-01-25 04:42 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/csrng_env_cfg.sv
> +  rand bit         use_invalid_mubi;
I have found the definition and replaced the invalid_mubi_c with the "get_rand_mubi4_val" function.

2022-01-25 04:43 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/csrng_env_cfg.sv
> +}
Nice catch! Thank you!

2022-01-25 04:45 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/seq_lib/csrng_alert_vseq.sv
> +    } invalid_mubi_e;
This enum is also declared in the csrng_env_cfg.sv, I have moved the enum declaration to csrng_env_pkg.sv.

2022-02-11 16:04 UTC, mwbranstad commented
@Muqing-Liu is the PR close to being resolved?

2022-02-11 18:08 UTC, Muqing-Liu commented
> @Muqing-Liu is the PR close to being resolved?

Hopefully yes, I am working on solving the last comments of moving the full paths reference to an interface from the EDN PR, since there are also many full paths reference in the sequence in this PR.

2022-02-11 18:41 UTC, mwbranstad commented
ah thanks. Was just wondering if this PR was active or just growing stale.

2022-02-16 22:30 UTC, martin-lueker commented
Hi Reviewers,
   Anka has scheduled a V2 review for this block on Friday.   Are there any substantial blocking issues here?  We would like to move the remaining formatting issues to follow-up/cleanup issues so that the review can proceed.

2022-02-16 23:15 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
> +      `uvm_fatal(`gfn, $sformatf("\n\t ----| PATH NOT FOUND"))
Done.

2022-02-16 23:15 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/seq_lib/csrng_alert_vseq.sv
> +    } invalid_mubi_e;
Done.

2022-02-16 23:53 UTC, martin-lueker commented on hw/ip/csrng/dv/env/seq_lib/csrng_alert_vseq.sv
> +
Hi @Muqing-Liu, 
  For the benefit of future Maintainers, could you please add a one-line comment to this effect.
  "Here we force CSRNG to generate two-identical outputs to trigger a cs_bus_cmp_alert"
  @matutem, would this be satisfactory?

2022-02-17 00:58 UTC, msfschaffner commented
@matutem can you take a look at this PR and see whether your requested changes are addressed appropriately?

2022-02-17 17:30 UTC, martin-lueker commented on hw/ip/csrng/dv/env/seq_lib/csrng_alert_vseq.sv
> +
Great Thanks Muqing.

2022-02-17 17:32 UTC, martin-lueker commented on hw/ip/csrng/dv/env/csrng_env_cfg.sv
> +  rand bit         use_invalid_mubi;
Hi @matutem, BTW thanks for pointing this out.  I was unware that this function existed!

2022-02-18 07:57 UTC, matutem requested changes
Could you make the suggested changes?

2022-02-18 07:57 UTC, matutem commented on hw/ip/csrng/dv/env/csrng_env_cfg.sv
> +      invalid_mubi_case = which_invalid_mubi;
If which_invalid_mubi is of type invalid_mubi_e then this assignment would be redundant... Otherwise it probably needs a type cast.

2022-02-18 07:57 UTC, matutem commented on hw/ip/csrng/dv/env/csrng_path_if.sv
> +    return $sformatf("tb.dut.u_csrng_core.cmd_stage_ack[%0d]", which_hw_inst_exc);
Please use core_path here and in line 19 for consistency.

2022-02-18 07:57 UTC, matutem commented on hw/ip/csrng/dv/env/seq_lib/csrng_err_vseq.sv
> +      sfifo_cmd_err_test: begin // ERR_CODE_TEST: SFIFO_CMD_ERR
Same suggestion as in https://github.com/lowRISC/opentitan/pull/9896, regarding use of the err_code_test value as the bit position of the corresponding bit position in the err_code CSR for all err_code tests.

2022-02-18 07:57 UTC, matutem commented on hw/ip/csrng/dv/env/seq_lib/csrng_err_vseq.sv
> +    // Clear intr_state register
You mean "Disable interrupts."?

2022-02-18 07:57 UTC, matutem commented on hw/ip/csrng/dv/env/csrng_env_cfg.sv
> +  constraint which_fatal_err_c { which_fatal_err inside {[0:25]};}
It seems which_fatal_err is unused?

2022-02-18 07:57 UTC, matutem commented on hw/ip/csrng/dv/env/csrng_env_pkg.sv
> +  } fatal_err_e;
Is this also unused?

2022-02-18 13:39 UTC, martin-lueker commented on hw/ip/csrng/dv/env/csrng_env_cfg.sv
> +  rand uint  which_invalid_mubi;
Ah Thanks for pointing that out!

2022-02-18 22:54 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/csrng_env_cfg.sv
> +  rand uint  which_invalid_mubi;
Yes, sure, I have directly randomized the enum type.

2022-02-18 22:55 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/csrng_env_cfg.sv
> +      invalid_mubi_case = which_invalid_mubi;
Yes, sure, I have removed this assignment

2022-02-18 22:55 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/csrng_path_if.sv
> +    return $sformatf("tb.dut.u_csrng_core.cmd_stage_ack[%0d]", which_hw_inst_exc);
Sure, I have updated all the functions using the core_path

2022-02-18 22:59 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/seq_lib/csrng_err_vseq.sv
> +    // Clear intr_state register
Yes, comment updated

2022-02-25 01:33 UTC, martin-lueker approved these changes
Hi @Muqing-Liu, this is also looking good.   Just a few more points about condensing the very long cases statements to highlight the differences between the cases.

2022-02-25 01:33 UTC, martin-lueker commented on hw/ip/csrng/dv/env/csrng_path_if.sv
> +  function automatic string cs_hw_inst_exc_path1(int which_hw_inst_exc);
As in the entropy_src review, please consider condensing these functions into a small handful.  You can use arrays to make from enums to sublocks or paths  

Presumably if these are used in large case statements you can look at the enumerations you are branching over to inform the interface for your reduced function.

2022-02-25 01:33 UTC, martin-lueker commented on hw/ip/csrng/dv/env/seq_lib/csrng_err_vseq.sv
> +        path_full      = cfg.csrng_path_vif.sfifo_cmdreq_err_path_full();
Another place with lots of repeated code.  Try and see if you can reduce this to just 2 or 3 different _classes_ of errrors.

2022-02-25 01:33 UTC, martin-lueker commented on hw/ip/csrng/dv/env/seq_lib/csrng_err_vseq.sv
> +      cmd_stage_sm_err_test: begin // ERR_CODE_TEST: CMD_STAGE_SM_ERR
Yes, this really needs to be condensed so that the reader can see which cases are similar and which ones are different.

2022-02-25 01:33 UTC, martin-lueker commented on hw/ip/csrng/dv/sva/csrng_assert_if.sv
> +`define PATH1 \
As in entropy_src, you can make these into an array and loop over them in the functions below.

2022-02-25 01:33 UTC, martin-lueker commented on hw/ip/csrng/dv/env/seq_lib/csrng_intr_vseq.sv
> +      end
MOre very long case statements.  See what you can do to boil this down, and capture similar sections into fewer cases.

2022-02-25 19:03 UTC, matutem reviewed
It seems Martin and you are working towards adding more abstraction and condensing the code. Please strive for that in all subsequent PRs: lack of abstraction leads to very long streams of code which are very counter-productive, hard to maintain, difficult to review, etc.

I will leave Martin and you to take this to completion. Let me know if you need any additional feedback. Thanks Muqing.

2022-02-28 19:01 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/csrng_path_if.sv
> +  function automatic string cs_hw_inst_exc_path1(int which_hw_inst_exc);
Done.

2022-02-28 19:02 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/seq_lib/csrng_intr_vseq.sv
> +      end
Done.

2022-02-28 19:03 UTC, Muqing-Liu commented on hw/ip/csrng/dv/env/seq_lib/csrng_err_vseq.sv
> +        path_full      = cfg.csrng_path_vif.sfifo_cmdreq_err_path_full();
Done.

2022-03-01 13:40 UTC, martin-lueker approved these changes
Looking better each time!  Keep it up Muqing!

2022-03-01 13:40 UTC, martin-lueker commented on hw/ip/csrng/dv/env/seq_lib/csrng_intr_vseq.sv
> +                                                          "push");
You have a literal 7 here and below.  This one is really not good for maintainability. If this path name changes, this code will break in very hard to find ways.  It would be better to perform a search to find the last '.' in the path and remove everything afterwards.

2022-03-01 13:40 UTC, martin-lueker commented on hw/ip/csrng/dv/env/seq_lib/csrng_intr_vseq.sv
> +                                                          "push");
More opportunity for condensing here. Here's a pseudo-code-ish example:
```
// see previous comment about the literal "7", though I leave it here for now.
string fifo_base_path = path_name.substr(0, path_name.len()-7);
string paths_exts[4] = {"push", "full", "pop", "not_empty"};
string fifo_forced_paths[4];
bit forced_values[4] = {1'b1, 1'b1, 1'b1, 1'b0};
// This is the pseudo-code part
foreach (path_exts[i]) begin
   fifo_forced_paths[i] = cfg.csrng_path_vif.fifo_err_path(cfg.NHwApps, fifo_base_path, path_exts[i]);
end
// Note if the function below is anything like the one of the same name from entropy_src, there is no reason that force all fifo errors can't take arrays as opposed to literally 4 arguments.
force_all_fifo_errs(fifo_forced_paths, forced_values, ral.intr_state.cs_fatal_err, 1'b1, cfg.which_fifo_err);
```

2022-03-01 13:40 UTC, martin-lueker commented on hw/ip/csrng/dv/env/seq_lib/csrng_intr_vseq.sv
> +        path_push      = cfg.csrng_path_vif.fifo_err_path(cfg.NHwApps,
Since so much of this code is repeated from the previous case, you can pull the definitions of `fifo_forced _paths` (See comment above) out of the case statement to reuse the code in both of these cases.

2022-03-16 15:33 UTC, martin-lueker commented on hw/dv/sv/dv_lib/dv_base_test.sv
> +  virtual function void configure_env();
FYI: @matutem, this point has been reverted.

2022-03-16 15:34 UTC, martin-lueker commented
Hi @matutem, Can we merge this?

2022-03-16 20:38 UTC, matutem approved these changes
With a minor suggestion, LGTM.

2022-03-18 17:12 UTC, martin-lueker commented on hw/ip/csrng/dv/env/csrng_env_cfg.sv
> +  virtual csrng_assert_if csrng_assert_if; // handle to csrng assert interface
It looks like this was applied offline.  Thanks @Muqing-Liu!

2022-03-18 17:15 UTC, martin-lueker commented
Thanks for the review @matutem

2022-03-18 17:16 UTC, merged