Flash ctrl fifo evict
lowRISC/opentitan pull request #10254
Opened 2022-01-21 17:43 UTC by nikola-miladinovic

First pull request #10052 should be merged since it has environment changes for fifo evicition test.

2022-01-21 17:50 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_fifo_evict_vseq.sv
> +// Copyright lowRISC contributors.
this just occurred to me, assuming the flash buffer never turned on, this test would not be able to reveal that.
Should we add an expectation check of some kind of the DV side to make the flash buffers are actually on?

2022-01-21 17:50 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_fifo_evict_vseq.sv
> +// Copyright lowRISC contributors.
also note, if you see the latest documentation, the flash buffers do not turn on until AFTER init has been called, so we need to make sure init is called here.

2022-01-21 17:54 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_fifo_evict_vseq.sv
> +    foreach (flash_op_data[k]) begin
should we do something more direct here? If the `flash_op_data` is just randomized, doesn't it mean with enough seeds it could accidentally match the currently read data (even if highly unlikely).

2022-01-21 17:55 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_fifo_evict_vseq.sv
> +    foreach (flash_op_data[k]) begin
@sriyerg 
@weicaiyang

2022-01-21 17:56 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_fifo_evict_vseq.sv
> +    // 2. SW read, program and SW read
i get really confused by the terminology.

When you say `direct`, you mean coming from the tlul bus externally right?
When you say `sw`, you referring to the register initiated read? 

The usage of sw here i think is a little problematic.

2022-01-21 17:56 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_fifo_evict_vseq.sv
> +    foreach (flash_op_data[k]) begin
this routine seems to show up over and over, probably should break it out into a separate task so things are a bit more compact and readable (not to mention better for future maintenance)

2022-01-21 17:57 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_fifo_evict_vseq.sv
> +    flash_op.op = flash_ctrl_pkg::FlashOpProgram;
same with this one on routine reuse

2022-01-21 17:59 UTC, tjaychen commented
a few things:
1. i should have caught this earlier. But we really shouldn't call this `FIFO`.  That implies the behavior is first in first out, where it's really just more of a memory. 
2. there is a lot of code re-use that i think could do with some cleaning-up
3. it would be good to stress different timing delays within the scenarios.  Ie, read + program + read are really closely packed together or farther apart.  This will help create some variation when run with different seeds beyond just changing the data.

2022-01-21 21:14 UTC, matutem requested changes
Please consider reducing code size by more abstraction.

2022-01-21 21:14 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_fifo_evict_vseq.sv
> +    // program data
Please create and call functions, and by all means try to reduce the amount of code here. There really seems to be lots of replication, which is the enemy of maintainability. Some of the other files here could also take some abstraction.

2022-01-24 16:32 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_fifo_evict_vseq.sv
> +    // 2. SW read, program and SW read
changed to host read instead direct read. Changed to controller read instead sw read.

2022-01-24 16:33 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_fifo_evict_vseq.sv
> +// Copyright lowRISC contributors.
added initialization task apply_reset().

2022-01-24 16:33 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_fifo_evict_vseq.sv
> +    flash_op.op = flash_ctrl_pkg::FlashOpProgram;
Ok, tasks are created.

2022-01-24 16:34 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_fifo_evict_vseq.sv
> +    // program data
Ok, tasks are created.

2022-01-24 19:20 UTC, nikola-miladinovic commented
> a few things:
> 
> 1. i should have caught this earlier. But we really shouldn't call this `FIFO`.  That implies the behavior is first in first out, where it's really just more of a memory.
> 2. there is a lot of code re-use that i think could do with some cleaning-up
> 3. it would be good to stress different timing delays within the scenarios.  Ie, read + program + read are really closely packed together or farther apart.  This will help create some variation when run with different seeds beyond just changing the data.

1. changed from fifo_eviction to rd_buff_eviction
2. code is cleaned up
3. spec is clear. since one operation needs to be completed before another starts, I do not think that it makes sense to have closed packed data. @sriyerg : I have implemented all scenarios what we were talking on V1 review. Please make comment is some modification need to be made. Thanks in advance.

2022-01-24 22:40 UTC, tjaychen commented
> > a few things:
> > 
> > 1. i should have caught this earlier. But we really shouldn't call this `FIFO`.  That implies the behavior is first in first out, where it's really just more of a memory.
> > 2. there is a lot of code re-use that i think could do with some cleaning-up
> > 3. it would be good to stress different timing delays within the scenarios.  Ie, read + program + read are really closely packed together or farther apart.  This will help create some variation when run with different seeds beyond just changing the data.
> 
> 1. changed from fifo_eviction to rd_buff_eviction
> 2. code is cleaned up
> 3. spec is clear. since one operation needs to be completed before another starts, I do not think that it makes sense to have closed packed data. @sriyerg : I have implemented all scenarios what we were talking on V1 review. Please make comment is some modification need to be made. Thanks in advance.

I should say I am more concerned that that by ONLY testing packed together scenarios we may hide bugs in the flash read pipeline. For example let's say I have a bug where a lingering stage does the incorrect thing during clean-up, but is always masked by an incoming new transaction. It is always good to vary the timing a little to ensure we are not missing unexpected cases.

2022-01-26 17:38 UTC, nikola-miladinovic commented
> > > a few things:
> > > 
> > > 1. i should have caught this earlier. But we really shouldn't call this `FIFO`.  That implies the behavior is first in first out, where it's really just more of a memory.
> > > 2. there is a lot of code re-use that i think could do with some cleaning-up
> > > 3. it would be good to stress different timing delays within the scenarios.  Ie, read + program + read are really closely packed together or farther apart.  This will help create some variation when run with different seeds beyond just changing the data.
> > 
> > 
> > 
> > 1. changed from fifo_eviction to rd_buff_eviction
> > 2. code is cleaned up
> > 3. spec is clear. since one operation needs to be completed before another starts, I do not think that it makes sense to have closed packed data. @sriyerg : I have implemented all scenarios what we were talking on V1 review. Please make comment is some modification need to be made. Thanks in advance.
> 
> I should say I am more concerned that that by ONLY testing packed together scenarios we may hide bugs in the flash read pipeline. For example let's say I have a bug where a lingering stage does the incorrect thing during clean-up, but is always masked by an incoming new transaction. It is always good to vary the timing a little to ensure we are not missing unexpected cases.

Ok, now random number between 0 and 10 is implemented between host reads, program and erase while controller reads are still tight.

2022-01-26 20:35 UTC, weicaiyang commented
private CI is failing with this error.
```
                Error-[SVBENM] End name does not match the begin name
                ../src/lowrisc_dv_flash_ctrl_env_0.1/seq_lib/flash_ctrl_rd_buff_evict_vseq.sv, 456
                  endtask name is 'check_all_ones', while the task name is
                  'check_all_ones_host'.
                  Please make the begin and end names same.
```

2022-01-26 20:46 UTC, matutem requested changes
Also, it seems this PR redoes the changes to flash_ctrl_host_dir_rd_vseq.sv in https://github.com/lowRISC/opentitan/pull/10052?

And please re-request a review when you think you are ready with this suggestions. Otherwise I won't see this as a pending review.

2022-01-26 20:46 UTC, matutem commented on hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson
> +            order to test read buffereviction properly. Read should be executed by both Software
```suggestion
            order to test read buffer eviction works properly. Read should be executed by both Software
```

2022-01-26 20:46 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +    if (exp_data[0] != rd_trans.data) begin
Please use `DV_CHECK_EQ.

2022-01-26 20:46 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      void'(addr_phase_mbox.try_get(t));
Could you check the response value? I think you would expect a positive value, thus `DV_CHECK_GT(...try_get(t), 0). Same below.

2022-01-26 20:46 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +  flash_bank_mp_info_page_cfg_t defualt_info_page_cfg = '{default:1, scramble_en:0, ecc_en:0,
```suggestion
  flash_bank_mp_info_page_cfg_t default_info_page_cfg = '{default:1, scramble_en:0, ecc_en:0,
```
Also fix the use of this value.

2022-01-27 10:48 UTC, nikola-miladinovic commented
> private CI is failing with this error.
> 
> ```
>                 Error-[SVBENM] End name does not match the begin name
>                 ../src/lowrisc_dv_flash_ctrl_env_0.1/seq_lib/flash_ctrl_rd_buff_evict_vseq.sv, 456
>                   endtask name is 'check_all_ones', while the task name is
>                   'check_all_ones_host'.
>                   Please make the begin and end names same.
> ```

Fixed, thanks for info since i do not have access to private CI messages.

2022-01-27 10:58 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson
> +            order to test read buffereviction properly. Read should be executed by both Software
Ok, fixed.

2022-01-27 11:02 UTC, nikola-miladinovic commented
> Also, it seems this PR redoes the changes to flash_ctrl_host_dir_rd_vseq.sv in #10052?
> 
> And please re-request a review when you think you are ready with this suggestions. Otherwise I won't see this as a pending review.

@matutem : Since i needed changes from #10052, i created branch from there. So first that PR needs to be merged and afterwards this one. That means that files flash_ctrl_scoreboard.sv and flash_ctrl_base_vseq.sv will be fixed there, not here since this files will come on top of that merged PR.

2022-01-27 11:36 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      void'(addr_phase_mbox.try_get(t));
this is fixed already. please check #10052.

2022-01-27 11:41 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +    if (exp_data[0] != rd_trans.data) begin
fixed in #10052 with `DV_CHECK_EQ(exp_data[0], trans.d_data).

2022-01-27 11:42 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +  flash_bank_mp_info_page_cfg_t defualt_info_page_cfg = '{default:1, scramble_en:0, ecc_en:0,
Fixed in #10052.

2022-02-01 16:52 UTC, nikola-miladinovic commented
> Also, it seems this PR redoes the changes to flash_ctrl_host_dir_rd_vseq.sv in #10052?
> 
> And please re-request a review when you think you are ready with this suggestions. Otherwise I won't see this as a pending review.

@matutem : Please check this PR, since button re-request review does not show up. perhaps it will once checks are done.

2022-02-01 18:18 UTC, nikola-miladinovic commented
> Also, it seems this PR redoes the changes to flash_ctrl_host_dir_rd_vseq.sv in #10052?
> 
> And please re-request a review when you think you are ready with this suggestions. Otherwise I won't see this as a pending review.

Now this PR has only data relevant for read buffer eviction test.

2022-02-01 21:06 UTC, matutem approved these changes
After changing to `DV_CHECK_RANDOMIZE_FATAL, LGTM.

Notice your test explicitly schedules controller or host operations. If it is possible it would be better to randomize the sequence of host and controller operations. I hope you will try this in subsequent test sequences.

2022-02-02 13:47 UTC, eshapira approved these changes
LGTM with 2 questions

2022-02-02 13:58 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rd_buff_evict_vseq.sv
> +
@eshapira : main tasks like flash_ctrl_write, do_direct_read,flash_ctrl_read are located into flash_ctrl_base_vseq. Due to various usage (like adding random time between transactions), separate tasks are needed within the test.

2022-02-02 13:58 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rd_buff_evict_vseq.sv
> +    apply_reset();
I just checked and you are correct. It will be removed.

2022-02-02 14:01 UTC, nikola-miladinovic commented
> 



> After changing to `DV_CHECK_RANDOMIZE_FATAL, LGTM.
> 
> Notice your test explicitly schedules controller or host operations. If it is possible it would be better to randomize the sequence of host and controller operations. I hope you will try this in subsequent test sequences.

Since coverage is still not involved, lets keep it as it is now. Later on, I will repair it, with covergroup that everything was hit.

2022-02-02 21:46 UTC, tjaychen approved these changes

2022-02-03 03:34 UTC, merged