[dv/hmac] Add wipe secret checking
lowRISC/opentitan pull request #10363
Opened 2022-01-26 06:25 UTC by cindychip

This PR adds a sequence to check the wipe secret functionality.
The sequence will randomly issue wipe secret in the following four
conditions:
1). Before hmac key was input.
2). Before hmac start command.
3). Before hmac process command.
4). Before hmac process is done.

Signed-off-by: Cindy Chen <chencindy@opentitan.org>

2022-01-27 02:00 UTC, matutem requested changes
A few comments and a change request...

2022-01-27 02:44 UTC, cindychip commented on hw/ip/hmac/dv/env/hmac_scoreboard.sv
> +  bit [TL_DW-1:0] exp_digest[8];
Sounds good, thanks for pointing it out.

2022-01-27 02:44 UTC, cindychip commented on hw/ip/hmac/dv/env/hmac_scoreboard.sv
> +          // If wipe_secret is triggered, ensure the predicted value does not match with the
Thanks for catching that. Updated

2022-01-27 02:44 UTC, cindychip commented on hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
> +    intr_hmac_err_en dist {1'b1 := 8, 1'b0 := 2};
This is very old testbench (2 years old haha). Maybe verible was not set up back then?

2022-01-27 02:44 UTC, cindychip commented on hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
> +        if (!hmac_en) rd_digest();
Here it will corrupt the secret_keys and existing digest.
If hmac is not enabled - only the existing digest will be affected (because the hashing won't use secret_key), so we immediately read out the corrupted digests.
If hmac is enabled - hmac hashing will use the corrupted secret key, so the digest will be checked at the end of the loop (line 184).

2022-01-27 02:44 UTC, cindychip commented on hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
> +              wipe_secrets();
yes it will be checked at the end of the loop, because we want to make sure the hashing is finished, and the final digest is corrupted.

2022-01-27 18:43 UTC, matutem commented on hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
> +    intr_hmac_err_en dist {1'b1 := 8, 1'b0 := 2};
Would you mind formatting it?

2022-01-27 18:48 UTC, cindychip commented on hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
> +    intr_hmac_err_en dist {1'b1 := 8, 1'b0 := 2};
My bad! Totally misunderstand your comment! Sure! I think this is the correct format right?

2022-01-28 00:52 UTC, matutem approved these changes
LGTM

2022-01-28 02:31 UTC, merged