Flash ctrl hw sec otp2
lowRISC/opentitan pull request #10513
Opened 2022-02-01 15:44 UTC by TimEwins

2022-02-01 15:58 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +  // Body Task
Fixed

2022-02-01 15:59 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +      // Read back Creator and Owner seeds via Host, and compare with the data presented to the Key Manager Interface.
Fixed

2022-02-01 16:04 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +        0: do_flash_op_secret_part(FlashCreatorPart, flash_ctrl_pkg::FlashOpProgram, dummy_data);
Added default, which will never be hit

2022-02-01 16:04 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +      // READ CREATOR AND OWNER SEEDS
Fixed

2022-02-01 16:10 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +           get_csr_val_with_updated_field(ral.bank0_info0_page_cfg_shadowed[page].prog_en, data, program_en) |
Fixed

2022-02-01 16:11 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +           get_csr_val_with_updated_field(ral.bank0_info0_page_cfg_shadowed[page].erase_en, data, erase_en) |
Fixed

2022-02-01 16:11 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +           get_csr_val_with_updated_field(ral.bank0_info0_page_cfg_shadowed[page].scramble_en, data, scramble_en) |
Fixed

2022-02-01 16:11 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +           get_csr_val_with_updated_field(ral.bank0_info0_page_cfg_shadowed[page].ecc_en, data, ecc_en) |
Fixed

2022-02-01 16:11 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +           get_csr_val_with_updated_field(ral.bank0_info0_page_cfg_shadowed[page].ecc_en, data, ecc_en) |
Fixed

2022-02-01 16:12 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +           get_csr_val_with_updated_field(ral.bank0_info0_page_cfg_shadowed[page].he_en, data, he_en);
Fixed

2022-02-02 00:50 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    if (cfg.seq_cfg.en_init_keys_seeds == 1) begin
is there any reason to not always init seeds?

2022-02-02 00:52 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +        flash_op.addr = 32'h00000800; // Start Address Page 1
@TimEwins maybe it's better to make this a parameter in the `env_pkg`? That way other tests might be able to re-use this as well.

2022-02-02 00:52 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    cfg.flash_ctrl_vif.lc_seed_hw_rd_en = lc_ctrl_pkg::On;  // Enable Secret Partition
could we leave this as `off`? Technically when front door reading / programming / erasing, you shouldn't need this to be on. If you DO, then we probably have another bug somewhere in the design.

2022-02-02 00:54 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    case (flash_op.op)
the dv folks can comment better, but shouldn't the below code belong somewhere outside of this task? It seems like general program / read / erase is something a lot of different tasks / tests will re-use. 

maybe @nikola-miladinovic already has them elsewhere too.

2022-02-02 00:55 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    cfg.flash_ctrl_vif.lc_owner_seed_sw_rw_en   = lc_ctrl_pkg::On;
is there any reason these aren't all OFF by default and just selectively turned on?
I'm worried by having some as ON by reset we may miss hardware bugs.

2022-02-02 01:05 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +  virtual task init_data_part();
can't help but think this should be a common task with some inputs :)

2022-02-02 01:09 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +      csr_wr(.ptr(ral.init), .value(1));  // Enable Secret Seed Output
I think we should randomly issue some transactions before the init is called.
It is technically a possible way of using the flash_ctrl.

2022-02-02 09:24 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    if (cfg.seq_cfg.en_init_keys_seeds == 1) begin
There is no specific reason not to init seeds, but by default this bit is reset to zero (disabled) in the default register map, so has to be done with a CSR write after reset (in the System there may be some other mechanism doin this).  I have added the option to set this bit through the cfg  (function configure_vseq).  This can be changed if required.   

// Enable Initial Secret Seed Readout
cfg.seq_cfg.en_init_keys_seeds = 1;

2022-02-02 09:32 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +        flash_op.addr = 32'h00000800; // Start Address Page 1
I assume you are referring to the 'magic' numbers here, yes I think you are probably correct, they should be stated in a package, or calculated.  I will look into this.

2022-02-02 09:44 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    cfg.flash_ctrl_vif.lc_seed_hw_rd_en = lc_ctrl_pkg::On;  // Enable Secret Partition
I have tried this suggestion, and I get a scoreboard error from the TB, relating to a recoverable error.
I have reinstated the original code.  This perhaps needs further investigation ?

* `UVM_ERROR (cip_base_scoreboard.sv:209) [scoreboard] Check failed exp_alert[alert_name] == * (* [*] vs * [*]) alert recov_err triggered unexpectedly` has 1 failures:
    * Test flash_ctrl_hw_sec_otp has 1 failures.
        * 0.flash_ctrl_hw_sec_otp.1\
          Line 198, in log /scratch/google/goo_opentitan/tim/flash_ctrl_hw_sec_otp2/flash_ctrl_wrapper-sim-xcelium/0.flash_ctrl_hw_sec_otp/out/run.log

                UVM_ERROR @   7789443 ps: (cip_base_scoreboard.sv:209) [uvm_test_top.env.scoreboard] Check failed exp_alert[alert_name] == 1 (0 [0x0] vs 1 [0x1]) alert recov_err triggered unexpectedly
                UVM_INFO @   7789443 ps: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]

2022-02-02 09:48 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    cfg.flash_ctrl_vif.lc_owner_seed_sw_rw_en   = lc_ctrl_pkg::On;
These are the default values that are applied by the TB at Reset (not my code).  But yes, it does seem odd that some of these are deafault on.  I will investigate.

2022-02-02 09:51 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +  virtual task init_data_part();
I can do this .. subject to what the solution regarding secret seeds on/off by default question

Further comments invited

2022-02-02 09:53 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +      csr_wr(.ptr(ral.init), .value(1));  // Enable Secret Seed Output
What sort of transactions are you thinking here? Flash Read, and/or Flash configuration?

2022-02-02 12:41 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    case (flash_op.op)
@tjaychen : This is only for secret partitions. There is some similar tasks in flash_ctrl_rand_ops_base_vseq but this is not related to this test. I would keep this as it is.

2022-02-02 12:44 UTC, eshapira commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +      flash_ctrl_info_bank0_cfg(
There is a method in **flash_ctrl_base_vseq** which can do this, so I don't think this new method is required.
See the method here: https://github.com/lowRISC/opentitan/blob/c0b2ef5041e8d34f264b2ddaccc8d5cfdb97b413/hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv#L126-L152
```suggestion
      flash_ctrl_mp_info_page_cfg(
        .bank(0), .info_part(0), .page(i), .page_cfg(info_regions[i])
      );
```

2022-02-02 12:44 UTC, eshapira commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +  virtual task flash_ctrl_info_bank0_cfg(input uint page,
There is a method in **flash_ctrl_base_vseq** which can do this, so I don't think this new method is required.
See the method here: https://github.com/lowRISC/opentitan/blob/c0b2ef5041e8d34f264b2ddaccc8d5cfdb97b413/hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv#L126-L152

2022-02-02 13:57 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    case (flash_op.op)
@eshapira : main tasks like flash_ctrl_write, do_direct_read,flash_ctrl_read are located into flash_ctrl_base_vseq. Due to various usage (like adding random time between transactions) need separate task within test.

2022-02-02 15:40 UTC, TimEwins commented
We have had some issues regarding GIT rebase and commits, the current PR upload is being currently being modified and is not yet check in ready.  I still need to address people's questions and then push again.

Apologies

2022-02-02 15:49 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +  virtual task do_flash_op_secret_part(input flash_info_part_e secret_part,
Fixed

2022-02-02 15:50 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +
Fixed

2022-02-02 15:50 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +  virtual task compare_secret_seed(input flash_info_part_e secret_part,
Fixed

2022-02-02 15:50 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    logic [KeyWidth-1:0] otp_addr_key               [0:flash_ctrl_pkg::NumBanks-1];
Fixed

2022-02-02 15:50 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    logic [KeyWidth-1:0] otp_data_key               [0:flash_ctrl_pkg::NumBanks-1];
Fixed

2022-02-02 15:50 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    logic [KeyWidth-1:0] otp_addr_rand_key          [0:flash_ctrl_pkg::NumBanks-1];
Fixed

2022-02-02 15:51 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    logic [KeyWidth-1:0] otp_data_rand_key          [0:flash_ctrl_pkg::NumBanks-1];
Fixed

2022-02-02 15:51 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    logic [0:KeyWidth-1] otp_expected_addr_key;
Fixed

2022-02-02 15:51 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    logic [0:KeyWidth-1] otp_expected_addr_rand_key;
Fixed

2022-02-02 15:51 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    logic [0:KeyWidth-1] otp_expected_data_rand_key;
Fixed

2022-02-02 15:52 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    logic [0:KeyWidth-1] otp_addr_key               [0:flash_ctrl_pkg::NumBanks-1];
Fixed

2022-02-02 15:53 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    logic [0:KeyWidth-1] otp_data_key               [0:flash_ctrl_pkg::NumBanks-1];
Fixed

2022-02-02 15:53 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    logic [0:KeyWidth-1] otp_addr_rand_key          [0:flash_ctrl_pkg::NumBanks-1];
Fixed

2022-02-02 15:53 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    logic [0:KeyWidth-1] otp_addr_rand_key          [0:flash_ctrl_pkg::NumBanks-1];
Fixed

2022-02-02 15:53 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    logic [0:KeyWidth-1] otp_data_rand_key          [0:flash_ctrl_pkg::NumBanks-1];
Fixed

2022-02-02 15:55 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    logic [0:KeyWidth-1] otp_data_rand_key          [0:flash_ctrl_pkg::NumBanks-1];
Fixed

2022-02-02 15:58 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    cfg.flash_ctrl_vif.lc_owner_seed_sw_rw_en   = lc_ctrl_pkg::On;
I am currently investigating this ... but it does look like the rd_en needs to be on at power up for the seeds to come out at all.  Please could the desired functionality be investigated?

2022-02-02 16:38 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv
> +  } flash_info_part_e;
Agreed and Changed

2022-02-02 16:40 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +        flash_op.op = flash_ctrl_pkg::FlashOpProgram;  // Select Program Operation
Agreed ... will correct this

2022-02-02 16:42 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +
Fixed

2022-02-02 18:10 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    cfg.flash_ctrl_vif.lc_seed_hw_rd_en = lc_ctrl_pkg::On;  // Enable Secret Partition
I have now turned this off when performing the front door access as suggested.  The test still passes.

2022-02-02 18:11 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    cfg.flash_ctrl_vif.lc_owner_seed_sw_rw_en   = lc_ctrl_pkg::On;
I have now changed the TB code to ensure these are off by default, and only turned on when required.

2022-02-02 18:14 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    cfg.flash_ctrl_vif.lc_seed_hw_rd_en = lc_ctrl_pkg::On;  // Enable Secret Partition
o sounds good. Wait, I thought I saw somewhere making this OFF was causing issues?

2022-02-02 18:23 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +      flash_ctrl_info_bank0_cfg(
Agreed, and Changed.

2022-02-02 18:25 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +  virtual task flash_ctrl_info_bank0_cfg(input uint page,
Agreed and Changed.

2022-02-02 18:32 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    logic [0:KeyWidth-1] otp_addr_key               [0:flash_ctrl_pkg::NumBanks-1];
Fixed

2022-02-02 18:33 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    logic [0:KeyWidth-1] otp_data_key               [0:flash_ctrl_pkg::NumBanks-1];
Fixed

2022-02-02 18:37 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    cfg.flash_ctrl_vif.lc_seed_hw_rd_en = lc_ctrl_pkg::On;  // Enable Secret Partition
I was mistaken ... it is working

2022-02-02 19:21 UTC, TimEwins commented
New Candidate uploaded for Review

2022-02-03 08:41 UTC, matutem requested changes
Many suggestions and questions...

2022-02-03 08:41 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    case (flash_op.op)
If there are minor differences between the tasks they can be controlled by additional arguments. It is "highly desirable" to avoid replication by the creation of proper abstractions. Highly replicated code can become a maintenance nightmare.

Please make a good effort to consolidate.

2022-02-03 08:41 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    //    cfg.flash_ctrl_vif.lc_seed_hw_rd_en = lc_ctrl_pkg::Off;  // Enable Secret Partition
Is there any reason why you won't remove these comments? They seem obsolete.

2022-02-03 08:41 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +      if (cfg.flash_ctrl_vif.keymgr.seeds[bit'(secret_part)][i] === 'x) begin
`DV_CHECK(!$isunknown(<data>))

2022-02-03 08:41 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    if (key_data === flash_op_data)
You could just `DV_CHECK_EQ...

2022-02-03 08:41 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    // Loop
These comments don't add value: the code in line 58 makes line 60 redundant, and the for loop in line 63 makes line 62 unnecessary. Please add comments only when things need clarification.

Another example: the comments in lines 67, 68, and 69 are not informative either.

2022-02-03 08:41 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +      #100ns;
Prefer to use some clock's vif wait_clks function.

2022-02-03 08:41 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +  // Task : init_info_part
An unnecessary and incorrect comment. Please remove it.

2022-02-03 08:41 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +  // Task : init_info_part
Not incorrect, but unnecessary.

2022-02-03 08:41 UTC, matutem commented on hw/ip/flash_ctrl/dv/tb/tb.sv
> +  logic [KeyWidth-1:0] otp_addr_key;
Could you add otp_req and otp_rsp to some interface (like flash_ctrl_if.sv?) so this code can be moved somewhere like a task in the base_vseq? It can access otp_req and otp_rsp via cfg.<interface>_vif.otp_req.
A task in sequences is a more obvious location for it.

2022-02-03 10:47 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
>      data =
Fixed, as in I have removed the Verible format flags.  I did this in a slightly different way to that suggested, but the code is cleaner, and the test still passes.  I also took the liberty of fixing up other large 'OR' chains in a similar manner

2022-02-03 10:55 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    cfg.flash_ctrl_vif.lc_seed_hw_rd_en = lc_ctrl_pkg::Off;  // Enable Secret Partition HW Access
The poll_fifo_status flag controls whether the fifo is polled (of course) for fifo flow control reasons.  In these particular tests, the number of words written/read from the FIFOs are less than 16 words (i.e less than a full FIFO), so technically, the pooling is not required.  However I have enabled it (poll_fifo_status = 1) and the test continues to pass as expected

2022-02-03 10:57 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    //    cfg.flash_ctrl_vif.lc_seed_hw_rd_en = lc_ctrl_pkg::Off;  // Enable Secret Partition
Yes, these wll be removed, they were missed.

2022-02-03 11:04 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +      if (cfg.flash_ctrl_vif.keymgr.seeds[bit'(secret_part)][i] === 'x) begin
Code amended

2022-02-03 11:16 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    if (key_data === flash_op_data)
Suggestion endorsed.  Code modified.

2022-02-03 12:00 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +    // Loop
Corrected and noted for the future

2022-02-03 12:00 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +      #100ns;
Changed

2022-02-03 12:00 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +  // Task : init_info_part
Done

2022-02-03 12:01 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +  // Task : init_info_part
Removed

2022-02-07 11:55 UTC, TimEwins commented
PR UPDATED

I have made the suggested ammendments, and improved the test (whilst doing this).

This is the latest PR Candidate.

2022-02-07 16:46 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/tb/tb.sv
> +  logic [KeyWidth-1:0] otp_addr_key;
Implemented

2022-02-07 16:48 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +        flash_op.addr = 32'h00000800; // Start Address Page 1
Magic Numbers moved into env_pkg

2022-02-07 16:50 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +        flash_op.addr = 32'h00000800;  // Start Address Page 1
Done

2022-02-07 16:51 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +      flash_ctrl_pkg::FlashOpErase: begin
Fixed

2022-02-07 16:51 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +        flash_ctrl_start_op(flash_op);  // Start Controller
Fixed

2022-02-07 16:51 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +//                    Additionally check Partitions with the previous data programmed
Fixed

2022-02-07 16:51 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
> +      cfg.seq_cfg.disable_flash_init = 1;  // Disable Flash Random Initialisation
Fixed

2022-02-09 06:33 UTC, matutem approved these changes
LGTM

2022-02-09 07:25 UTC, eshapira approved these changes
LGTM, thanks!

2022-02-09 09:58 UTC, TimEwins commented
I was asked this question ... but I could nt find it in the history, but to elaborate, for the record ....

In [hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv](https://github.com/lowRISC/opentitan/pull/10513#discussion_r801287236):
> -    data = get_csr_val_with_updated_field(ral.default_region_shadowed.rd_en, data, read_en) |
-        get_csr_val_with_updated_field(ral.default_region_shadowed.prog_en, data, program_en) |
-        get_csr_val_with_updated_field(ral.default_region_shadowed.erase_en, data, erase_en) |
-        get_csr_val_with_updated_field(ral.default_region_shadowed.scramble_en, data,
-                                       scramble_en) |
-        get_csr_val_with_updated_field(ral.default_region_shadowed.ecc_en, data, ecc_en) |
-        get_csr_val_with_updated_field(ral.default_region_shadowed.he_en, data, he_en);
+    data = get_csr_val_with_updated_field(ral.default_region_shadowed.rd_en, data, read_en);
+    data = data |
+        get_csr_val_with_updated_field(ral.default_region_shadowed.prog_en, data, program_en);
+    data = data |
+        get_csr_val_with_updated_field(ral.default_region_shadowed.erase_en, data, erase_en);
+    data = data |
+        get_csr_val_with_updated_field(ral.default_region_shadowed.scramble_en, data, scramble_en);
+    data = data | get_csr_val_with_updated_field(ral.default_region_shadowed.ecc_en, data, ecc_en);
+    data = data | get_csr_val_with_updated_field(ral.default_region_shadowed.he_en, data, he_en);
Can you please elaborate about this change?
Doesn't it better to do it in a single assignment rather then multiple?
If it's only aesthetics, in my perspective, the former looked a bit clearer.
Same question for the changes in the flash_ctrl_mp_info_page_cfg & flash_ctrl_start_op tasks.

This was originally expressed as a multiple item OR, but the Verible linter was unhappy with the width of the OR.   One solution was to do this, or add pragmas to turn the linter off.

2022-02-10 17:03 UTC, tjaychen commented
thanks all, if no objections we'll merge after CI passes.

2022-02-10 20:37 UTC, merged