[kmac] Fix Fatal Alert connection
lowRISC/opentitan pull request #10517
Opened 2022-02-01 17:52 UTC by eunchan

@m-temp reported incorrect connection for the fatal alert in #10516.
The alert_sender modules are instantiated in opposit way.

2022-02-02 02:57 UTC, msfschaffner commented on hw/ip/kmac/rtl/kmac.sv
> +      .IsFatal((i==0?1:0))
Since most other IPs actually solve this the other way round (i.e. as `.IsFatal(i)`), can we maybe fix this by changing the assignments further above (lines 1196-1207)?

2022-02-02 08:34 UTC, m-temp requested changes
I agree  with @msfschaffner The alert handling should be similar in all IPs

2022-02-03 16:37 UTC, eunchan commented
OK let me revise :)

2022-02-03 17:41 UTC, msfschaffner approved these changes

2022-02-03 17:42 UTC, msfschaffner commented
Thanks for changing it!

2022-02-03 19:04 UTC, eunchan commented
Looks like there's timing slack.

2022-02-03 19:42 UTC, msfschaffner commented
Oh no. I don't think it is directly related to this change, since the RTL change does not introduce longer combo paths. Rather, we may just have gotten a suboptimal placement (based on the seed being used).

Maybe rebase on master and push again?

If this starts to happen more often we probably have to either do some FPGA timing/placement optimizations, or lower the system clock frequency,

2022-02-03 19:43 UTC, msfschaffner commented
FYI @tjaychen

2022-02-03 19:48 UTC, msfschaffner commented
@eunchan we just merged an FPGA timing fix in https://github.com/lowRISC/opentitan/pull/10572. 
So maybe this works after rebasing onto master now.

2022-02-03 23:23 UTC, eunchan commented
![image](https://user-images.githubusercontent.com/1192814/152445899-263fa749-ef6d-407f-98bc-b54f0289d723.png)
Merging Now.

2022-02-03 23:23 UTC, merged