[pwm] FIX SMOKE TEST
lowRISC/opentitan pull request #10745
Opened 2022-02-10 13:10 UTC by suehnel

fix configuration of pwm_monitor from smoke_vseq wrt polarity/invert bit

Signed-off-by: Christoph Suehnel <christoph.suehnel@ensilica.com>

2022-02-10 17:39 UTC, sriyerg requested changes
Please remove the large swathes of commented out code - it makes the review slightly difficult. In general, we prefer avoiding commented out code because in the long run, it creates more confusion than be of help.

2022-02-10 17:39 UTC, sriyerg commented on hw/ip/pwm/dv/env/seq_lib/pwm_base_vseq.sv
> +    bit          BlinkEn;
Please refrain from keeping commented out code. 
Below as well.

2022-02-10 17:39 UTC, sriyerg commented on hw/ip/pwm/dv/env/seq_lib/pwm_base_vseq.sv
> +    cfg.pwm_cfg.CntrEn       = cntren;
Our style guide mandates the use of lower_snake_case for all variables. This data structure in `pwm_cfg` needs to be updated.

2022-02-17 05:17 UTC, matutem reviewed
Chrostoph I'd be glad to review this code once the verible lint checks and Srirkishna's suggestions are implemented and pushed.

2025-06-12 14:30 UTC, alees24 commented
PWM RTL and DV were extensively revised at the end of last year.

2025-06-12 14:30 UTC, closed without merging