[flash_ctrl] Fixes for erase suspend
lowRISC/opentitan pull request #10759
Opened 2022-02-10 19:25 UTC by tjaychen

- correctly generate eraes_done
- update model to correctly absorb erase_suspend input
- fixes #10748

Signed-off-by: Timothy Chen <timothytim@google.com>

2022-02-10 21:14 UTC, tjaychen commented
@nikola-miladinovic as far as i can tell in the waves, the erase suspend is behaving correctly now.  However the test still fail, it might have something to do with updating expected value on the bit.

2022-02-11 13:01 UTC, nikola-miladinovic requested changes
@tjaychen : Still bit Erase Suspend Req is stucked at 1 when there is not erase in progress. it should be immediately cleared.

2022-02-11 16:39 UTC, tjaychen commented
> @tjaychen : Still bit Erase Suspend Req is stucked at 1 when there is not erase in progress. it should be immediately cleared.

let me check again, i thought it was cleared when i looked at it yesterday.

2022-02-11 19:43 UTC, tjaychen commented
@nikola-miladinovic can you let me konw where it's stuck?

The first image is one where erase_suspend is called when there's no ongoing erase. You can see the reg value clearing very quickly.
![image](https://user-images.githubusercontent.com/1026250/153658620-931ff0ec-6664-4425-87c4-9218bf17890f.png)

The second image is one where erase_suspend is called when there's an ongoing erase.

![image](https://user-images.githubusercontent.com/1026250/153658780-d2b42d69-54d8-4936-9d39-526fe9168f1f.png)

So I'm not sure which case you're talking about is stuck. If you have a way to reproduce it (i don't see it when I grab your branch), let me know.

2022-02-14 10:54 UTC, nikola-miladinovic commented
So I am able to write erase suspend request but it is just stucked without self returning to 0. Here is what I see in Xcelium:
![erase_suspend_not_active](https://user-images.githubusercontent.com/93394800/153850763-ef1baa38-74fc-46eb-bd5b-efb94e50f9fd.JPG)

2022-02-14 12:56 UTC, nikola-miladinovic commented
After updating flash_ctrl_mp.sv I am also seeing good behaviour for 1. Scenario (without erase requests).

2022-02-14 19:13 UTC, nikola-miladinovic commented
@tjaychen : When erase suspend request is issued when there is no erase ongoing and when bank erase is ongoing, RTL works as expected. However there are two main problems with suspend of page erase:
1) Since page erase is only 2 clk wide, it seems impossible that erase suspend can happen with controller write - in attachement there are two pictures with waiting time 2 clk and 3 clk, line 247 cfg.clk_rst_vif.wait_clks(2); One error suspend request is too early while the other is too late with arrival.
2) When 3clk is waiting for triggering erase suspend request, some strange MP error is happening which might be source of RTL bug since all regions are enabled. This case is commited and seed is fixed 1. If you want to change and see erase suspend request before start of page erase, please replace "3" with "2" in line 247 of the test.
![2clk_wait](https://user-images.githubusercontent.com/93394800/153930528-814772fb-4d34-4fe5-b963-4a87cae12623.JPG)
![3clk_wait](https://user-images.githubusercontent.com/93394800/153930534-cd53d179-2aba-4abf-bd76-623602fa4a29.JPG)

2022-02-14 23:09 UTC, tjaychen commented
> 

hi Nikola,
I am still out today and may be for a few more days due to some personal issues. As you pointed out, the erase is cut short because there is a memory protection error. Can you triage that a bit to find out exactly what's wrong and perhaps file a memory protection error if that is the cause? 

All regions enabled doesn't mean anything necessarily. As mentioned previously, it depends on whether every region enables erase and which one has precedence.

2022-02-15 16:03 UTC, nikola-miladinovic approved these changes
All good now. DUT has described behaviour.

2022-02-15 20:07 UTC, tjaychen commented
@nikola-miladinovic just to confirm, are there still additional issues? Or does this fix everything on your end?

2022-02-15 21:27 UTC, eunchan approved these changes

2022-02-15 21:27 UTC, nikola-miladinovic commented
> @nikola-miladinovic just to confirm, are there still additional issues? Or does this fix everything on your end?

@tjaychen This fix everything.I can see clearly on waves erase bank and page suspend. I also fixed some address constraints in my test and soon PR will be raised. Thanks for support.

2022-02-16 00:13 UTC, merged