[flash_ctrl] Add Test For The RMA Feature
lowRISC/opentitan pull request #10854
Opened 2022-02-15 16:35 UTC by TimEwins

Test the Flash RMA Functionality

Fash Partitions are Erased, Programmed and then Wiped by the RMA.  After the RMA has completed,
The test checks that SW Access to the FLASH is denied, and after a subsequent Reset, the Flash
is confirmed to be set to data other than that previously programmed.
Each run of the test performs 4 RMA cycles, seperated by a Reset.

Signed-off-by: TIM EWINS <tim.ewins@ensilica.com>

2022-02-15 16:51 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
> +    // Randomize the 'Keys and Seeds' Setting to prove
Done

2022-02-15 16:51 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
> +  virtual task set_rand_data_page(input flash_sec_part_e part, output uint addr, output uint num_words);
Done

2022-02-17 00:07 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
> +//   Read Partitions#() Compare Data (MISMATCH Expected)
sounds good. We still need to rely on the assertion (i need to fix) to ensure program data matches read data right?

2022-02-17 09:18 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
> +//   Read Partitions#() Compare Data (MISMATCH Expected)
The assertion would help with checking the internal functionality.  Otherwise the TB would need to probe inside the DUT to do the program-readback check

So yes, if we can fix the assertion that would be great.

2022-02-17 15:51 UTC, TimEwins commented
https://github.com/lowRISC/opentitan/issues/10855 Is now resolved, awaiting merge of [flash_ctrl] Fix assertion for read verify check #10903

2022-02-21 09:38 UTC, nikola-miladinovic approved these changes

2022-02-22 18:12 UTC, matutem requested changes
Could you look into the suggestions?

2022-02-22 18:12 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
> +      // Additionally check that the Flash has not just been Erased, but has been overwritten
```suggestion
      // After Reset and DUT Initialisation, Check the FLASH is written randomly and its contents
      // mismatch against its contents before the RMA took place.
      // This May get an occasional Hit ~ 1 in 32^2-1, per location
      // Additionally check that the Flash has not just been Erased, but has been overwritten.
```

2022-02-22 18:12 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
> +      foreach (order_q[i]) begin
This loop looks like the one above, could you make it a task to reduce lines of code?

2022-02-23 11:23 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
> +//   Read Partitions#() Compare Data (MISMATCH Expected)
Assertion fixed, awaiting merge

2022-02-23 13:02 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
> +    num_trans = 4;  // Fixed Number of Iterations as Test time is VERY LONG
Accepted ... I have reduced the number of iterations from 4 to 2 (2 being the minimum I think), this reduces the Xcelium simulation time (real time) from 47min to 30mins.  The main time factor here is the RMA Req->Ack cycle, which can vary greatly depending on simulaion seed.  Multiple runs in parallel are fine.

2022-02-23 15:40 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    join
Hi @matutem join_any was not used, because it causes problems for the driver/scoreboard checking.  I have added some more comments to explain what is going on here, and modified the code slightly, for example the belt-braces fork-join.

This task is called when we are expecting a timeout to occur, so if we get a status = 1 that is fail in itself.
A fork-join is used so that both threads terminate together (Clean Exit).

The first thread loops reading status until either status = 1, or timeout (thread 2) occurs.  If status does return 1, then the first thread will die, and the timeout (thread 2) will continue.

If status does not return 1 within the timeout period, then when timeout does occur, if thread 1 is still running, it allows any outstanding csr_rd to finish(cleanly).

So the task is used to expect a timeout, and give an error if status returns within the timeout.

If thread 1 is killed in the middle of the csr_rd, by the timeout, there are left over outstanding transactions in the TB queues and the sim Fails.

The code does work, in that the timeout does occur, and status is not returned 1.

Checking the reverse of this has not been explicitly tested, as the RTL functions as it should

I hope this explanation is of help.

I have also changed the task name to "wait_flash_op_done_expect_timeout()" to be more descriptive.

Example TB Output (excerpt)

.flash_ctrl_hw_rma_vseq] RMA REQUEST
.flash_ctrl_hw_rma_vseq] RMA Seed : 0x11c1288a
.flash_ctrl_hw_rma_vseq] Waiting for RMA to complete ... 
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Starting RMA Timeout Check ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] Polling RMA ACK ...
.flash_ctrl_hw_rma_vseq] RMA complete
.flash_ctrl_hw_rma_vseq] RMA Duration : 220000146000 ps
.flash_ctrl_hw_rma_vseq] Attempting to READ from Flash
.flash_ctrl_hw_rma_vseq] Polling Flash Status ...
.flash_ctrl_hw_rma_vseq] Exiting Timeout Check ... Timeout Occured, Expected
.flash_ctrl_hw_rma_vseq] RMA Read Check Clean Exit
.flash_ctrl_hw_rma_vseq] Timeout Seen - Flash Not Accessible By Software, Expected, PASS
.flash_ctrl_hw_rma_vseq] RESET
.flash_ctrl_hw_rma_vseq] READ

2022-02-23 17:10 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
> +      cfg.clk_rst_vif.wait_clks($urandom_range(100, 1000));
Removed, as not really needed, and just adds to test run time.

2022-02-23 17:13 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
> +      // Additionally check that the Flash has not just been Erased, but has been overwritten
Comment amended

2022-02-23 18:03 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
> +      foreach (order_q[i]) begin
I have done ths

2022-02-23 18:24 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
> +
Fixed

2022-02-23 18:24 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +  virtual task wait_flash_op_done_expect_timeout(input time timeout_ns = 10_000_000, output bit result);
Fixed

2022-02-23 20:03 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +  virtual task wait_flash_op_done_expect_timeout(input time timeout_ns = 10_000_000, output bit result);
Fixed

2022-02-23 20:03 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
> +
Fixed

2022-02-23 21:10 UTC, TimEwins commented
@tjaychen @weicaiyang @cindychip @matutem Please could someone with Azure access tell me what the CI (private) error is ?  I have no access to this?

Thanks

2022-02-23 21:17 UTC, tjaychen commented
> @tjaychen @weicaiyang @cindychip @matutem Please could someone with Azure access tell me what the CI (private) error is ? I have no access to this?
> 
> Thanks

here you go

```*  Error-[SVBENM] End name does not match the begin name has 1 failures:
    * Test default has 1 failures.
        * default\
          Line 1212, in log /azp/agent/_work/1/s/scratch/HEAD/flash_ctrl_wrapper-sim-vcs/default/build.log

                Error-[SVBENM] End name does not match the begin name
                ../src/lowrisc_dv_flash_ctrl_env_0.1/seq_lib/flash_ctrl_hw_rma_vseq.sv, 240
                  endtask name is 'do_flash_op', while the task name is 'do_flash_ops'.
                  Please make the begin and end names same.
```

2022-02-24 09:08 UTC, TimEwins commented
Thanks @tjaychen

2022-02-24 11:59 UTC, TimEwins commented
Ready for Review and Merge

2022-02-25 16:38 UTC, matutem approved these changes
LGTM

2022-02-25 21:09 UTC, merged