[spi_host/dv] Sw Reset Test
lowRISC/opentitan pull request #10913
Opened 2022-02-17 12:44 UTC by visbaz

- Added Speed Test
- Added Constraints to Segment Item
- Added Quad And Dual To Device Resp Seq
- Added Tag For Cover Points To Speed Test
- Added Sw Reset Test

Signed-off-by: Viswanadha Bazawada <viswanadha.bazawada@ensilica.com>

2022-02-23 13:10 UTC, rasmus-madsen approved these changes
LGTM with some nit comments

2022-02-23 13:10 UTC, rasmus-madsen commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_smoke_vseq.sv
> +          cfg.clk_rst_vif.wait_clks(100);
do we want to make this wait for a random amount of time?

2022-02-23 13:10 UTC, rasmus-madsen commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_speed_vseq.sv
> +  int num_transactions = 2;
didn't you move this to the config?

2022-02-23 13:20 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_smoke_vseq.sv
> +          cfg.clk_rst_vif.wait_clks(100);
we can do that . am checking for active to be 0 and rxqd as well so either all TX and RX has finished or only TX happened and RX never happened. 
100 wait clocks is just a drain time ...may be that should be removed and tried :)

2022-02-23 13:23 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_speed_vseq.sv
> +  int num_transactions = 2;
not yet .....its done only for smoke test ....for speed as soon as dual and quad works num trans will be random from config .
a todo can be placed

2022-02-26 01:04 UTC, weicaiyang requested changes
please add me to review all the spi_host PRs
If you update spi_agent, please add @kosta-kojdic as well, since he is also using this agent (both device and host) in spi_device TB.

2022-02-26 01:04 UTC, weicaiyang commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +                 end
alignment is off again, are we using tab?

2022-02-26 01:05 UTC, weicaiyang commented
I will be nice if @kosta-kojdic can take a look at the update of tl_monitor

2022-02-27 20:15 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
> +  int num_resets = 1;
TODO is placed as of now. Debug is ongoing for designer.

2022-02-27 20:15 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
> +// sw_reset test vseq
agreed and added

2022-02-27 20:37 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
> +            start_spi_host_trans(2);
TODO is placed . transactions will be updated to random as in smoke test.

2022-02-27 22:16 UTC, visbaz commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +              CmdOnly,ReadStd,WriteStd: begin
Done

2022-02-27 22:37 UTC, visbaz commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +              CmdOnly,ReadStd,WriteStd: begin
done

2022-02-27 22:38 UTC, visbaz commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +                 end
Tab is never used only single spaces . a typo only.

2022-02-28 07:19 UTC, weicaiyang approved these changes
LGTM with a few nits

2022-02-28 07:19 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
> +  int num_resets = 1; //TODO increase number of Iterations.
nit: use num_trans which is defined in base_vseq, so that it's more aligned with other blocks.

2022-02-28 07:19 UTC, weicaiyang commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +              CmdOnly,ReadStd,WriteStd: begin
hmm, looks like these haven't been updated.

2022-02-28 07:19 UTC, weicaiyang commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +              CmdOnly, ReadStd, WriteStd: begin
nit: add 2 spaces indent for each case branch.

2022-02-28 17:29 UTC, kosta-kojdic approved these changes

2022-03-01 08:39 UTC, visbaz commented
@weicaiyang please merge this PR

2022-03-01 18:19 UTC, weicaiyang approved these changes
there are a few very small nits. I will merge this and let you address them in a future PR

2022-03-01 18:19 UTC, merged