Command filtering passthrough and start of scb for it
lowRISC/opentitan pull request #10997
Opened 2022-02-21 13:55 UTC by kosta-kojdic

Command filtering according to testplan description. Start of scoreboard implementation for passthrough mode.

Signed-off-by: Kosta Kojdic <kosta.kojdic@ensilica.com>

2022-02-22 19:31 UTC, matutem approved these changes
Just a request for clarification, which can probably be part of the comment above the corresponding code.

LGTM

2022-02-22 19:31 UTC, matutem commented on hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_cmd_filtering_vseq.sv
> +      pass_cmd = {<<1{pass_cmd}};
Could you explain the bit swapping performed?

2022-02-22 20:10 UTC, kosta-kojdic commented on hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_cmd_filtering_vseq.sv
> +      pass_cmd = {<<1{pass_cmd}};
Bit swapping is for the previously configured host bit order (basically if we use MSB or LSB first on the host bus) to reflect command opcode written to CMD_INFO register. We configure command opcode here:
ral.cmd_info[11].opcode.set(pass_cmd);
In order for it to be recognized by device as configured opcode we need to swap bits for bit order configured in this test. Without swapping of bits it would be recognized as reverse-bit order and command received would not match opcode configured in cmd_info register.

2022-02-22 21:30 UTC, weicaiyang requested changes

2022-02-22 21:30 UTC, weicaiyang commented on hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_cmd_filtering_vseq.sv
> +      csr_update(.csr(ral.cmd_filter[cmd_position]));
maybe create a task `cfg_cmd_filter(bit enable, bit[7:0] cmd)` for this
also include the following
```      
      cmd_position = pass_cmd / 32;
      cmd_offset = pass_cmd % 32;
```

2022-02-22 21:30 UTC, weicaiyang commented on hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_cmd_filtering_vseq.sv
> +      pass_cmd = {<<1{pass_cmd}};
swap or not should depend on `tx/rx_order`, right?

2022-02-23 08:43 UTC, kosta-kojdic commented on hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_cmd_filtering_vseq.sv
> +      cfg.m_spi_agent_cfg.passthrough = 1;
I thought to use Passthrough config in the scoreboard, but we can use configured mode in the scoreboard instead.

2022-02-23 18:20 UTC, weicaiyang approved these changes
LGTM

2022-02-23 18:22 UTC, merged