[spi_host/dv] coverage branch
lowRISC/opentitan pull request #11082
Opened 2022-02-24 20:21 UTC by visbaz

- Added Speed Test
- Added Constraints to Segment Item
- Added Quad And Dual To Device Resp Seq
- Added Tag For Cover Points To Speed Test
- Added Sw Reset Test
- Added Performance Test
- Added Spi Monitor Update Dual And Quad Mode

Signed-off-by: Viswanadha Bazawada <viswanadha.bazawada@ensilica.com>

2022-03-09 00:14 UTC, weicaiyang reviewed
a few general suggestions
1. don't make a very huge PR. if possible, split into several small PRs in the future
2. update the PR title to reflect the change
3. please add @rasmus-madsen and me to review spi_host PRs

2022-03-09 00:14 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
> +          end
nit:
```suggestion
          begin
            start_reactive_seq();
          end
          begin
            check_error_cmdbusy_cmdinval();
          end
```

2022-03-09 00:14 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
> +        disable fork;
we should not kill `check_error_cmdbusy_cmdinval();` while it's calling `csr_rd/wr`. Otherwise, the RAL may get into deadlock.
Perhaps set a flag and let it finish gracefully.

2022-03-09 00:14 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    end
```suggestion
    if(intr_state.error) begin
      csr_rd_check(.ptr(ral.error_status.underflow), .compare_value(1)); // check underflow error
      csr_wr(.ptr(ral.error_status), .value(0)); // clear underflow error
      csr_wr(.ptr(ral.intr_state), .value(0)); // clear interrupt error
    end
    else begin
      `uvm_fatal(`gfn, $sformatf("Expected Underflow Error Not Found"))
    end
```

2022-03-09 00:14 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
> +// smoke test vseq
can you elaborate what we do in the vseq? same for the vseq below

2022-03-09 00:14 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +      cpol_cp : coverpoint spi_configopts.cpol[SPI_HOST_NUM_CS];
nit: add 2 spaces indent

2022-03-09 05:31 UTC, visbaz commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +                cmd_byte++;
accepted and changed

2022-03-09 05:33 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
> +          end
accepted and changed

2022-03-09 05:34 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    end
accepted and changed

2022-03-09 05:38 UTC, visbaz commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +      cpol_cp : coverpoint spi_configopts.cpol[SPI_HOST_NUM_CS];
accepted and changed

2022-03-09 21:27 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    csr_wr(.ptr(ral.intr_enable), .value(2'b11)); // interrupt enable for err and event
ditto, we can randomize it

2022-03-09 21:27 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    if(intr_state.error) begin
we can use csr_rd_check and remove the `if` condition.

2022-03-09 21:27 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    generate_transaction();
nit: alignment

2022-03-09 21:27 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    segment = new();
new seems not needed as we get it from `transaction.segments.pop_back()`

2022-03-09 21:27 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    if (error_status.overflow) begin
nit:
```
`DV_CHECK_EQ(error_status.overflow, 1)
```

2022-03-09 21:27 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv
> +// event test vseq
please provide some more details of this vseq

2022-03-09 21:27 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_stress_all_vseq.sv
> +// sw_reset test vseq
please elaborate on this vseq

2022-03-11 10:00 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
> +// smoke test vseq
done

2022-03-11 10:01 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
> + spi_host_error_status_t error_status;
accepted and changed

2022-03-11 10:02 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
> +    bit [7:0] read_q[$];
accepted and changed

2022-03-11 10:05 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
> +          start_spi_host_trans(2,1'b0);
implemented and done

2022-03-14 08:42 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    generate_transaction();
accepted and changed

2022-03-14 08:44 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    segment = new();
accepted and changed

2022-03-14 08:45 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    if (error_status.overflow) begin
accepted and changed

2022-03-14 08:50 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv
> +// event test vseq
accepted and changed

2022-03-14 09:32 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    if(intr_state.error) begin
accepted and changed

2022-03-29 04:46 UTC, weicaiyang reviewed
can you rename this PR? This is much more than just coverage update

2022-03-29 04:46 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
> +    join
nit: use 2 spaces indent

2022-03-29 04:46 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +        if(intr_state.error) begin
same here, we shouldn't rely on the design output to check other things

2022-03-29 04:46 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +    begin
nit: no need to have this begin... end

2022-03-29 04:46 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +  `DV_CHECK_EQ(passthrough_o_s, cio_sd_i)
fix the indent and below in other files.

2022-03-29 04:46 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +      covergroup interrupt_cg with function sample(spi_host_intr_state_t spi_intr_state_reg,
you can reuse https://github.com/lowRISC/opentitan/blob/88dee60904a8872febccc967f914f6b59e190a4f/hw/dv/sv/cip_lib/cip_base_env_cov.sv#L8

2022-03-29 04:46 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +      endgroup
we should cross the error_en with error_status, same for the event_enable.

2022-03-29 04:46 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +      //endgroup
clean up these codes

2022-03-29 04:46 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +        cpol_cp : coverpoint spi_configopts.cpol[SPI_HOST_NUM_CS]{ bins cpol = {[0:1]}; }
is `SPI_HOST_NUM_CS-1` the right index? if SPI_HOST_NUM_CS is more than 1, how do we sample value for the other index?
```suggestion
        cpol_cp : coverpoint spi_configopts.cpol[SPI_HOST_NUM_CS-1]{ bins cpol = {[0:1]}; }
```

2022-03-29 04:46 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +        duplex_cp : coverpoint direction{ bins dir = {[1:3]}; }
it's already an enum, we can just cover all the defined enum values except the unsupported values
```suggestion
        duplex_cp : coverpoint direction{ ignore_bins unsupported_dir = {None}; }
```

2022-03-29 04:46 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +        bins csntrail = {[0:15]};
nit: 2 spaces indent

2022-03-29 04:47 UTC, weicaiyang commented
@rasmus-madsen can you also take a look? You must understand this better than me.

2022-03-29 07:13 UTC, visbaz commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +        bins csntrail = {[0:15]};
accepted and changed

2022-03-29 07:13 UTC, visbaz commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +        duplex_cp : coverpoint direction{ bins dir = {[1:3]}; }
accepted and changed

2022-03-29 07:15 UTC, visbaz commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +      //endgroup
accepted and changed

2022-03-29 08:10 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +    begin
accepted and changed

2022-03-29 08:13 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
> +    join
accepted and changed

2022-03-29 08:15 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv
> +          end
accepted and changed

2022-03-29 08:19 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv
> +        end
accepted and changed

2022-03-29 11:07 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv
> +        if(event_enable.txempty && status.txempty) begin
This sequence expects all the events to be captured.
we enable all events and when an event occurs enable for that event is disabled.
At the end of the sequence we check event enable register if all events have occurred.

2022-03-29 12:57 UTC, visbaz commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +      endgroup
accepted and changed

2022-03-29 22:21 UTC, visbaz commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +      covergroup interrupt_cg with function sample(spi_host_intr_state_t spi_intr_state_reg,
accepted and changed

2022-03-30 08:15 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
> +    csr_wr(.ptr(ral.intr_enable), .value(2'b11)); // interrupt enable for err and event
implemented and done

2022-03-30 08:46 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    csr_wr(.ptr(ral.intr_enable), .value(2'b11)); // interrupt enable for err and event
implemented and done

2022-03-30 09:01 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
> +       if (error) begin
implemented

2022-03-30 09:01 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    csr_wr(.ptr(ral.intr_enable), .value(2'b11)); // interrupt enable for err and event
implemented

2022-03-30 09:02 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +        if(intr_state.error) begin
implemented

2022-03-30 09:03 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +// SPI_HOST HWIP Technical Specification Block Diagram
Sure no more sequence additions

2022-03-30 09:25 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +    uvm_hdl_force("tb.passthrough_i.csb", 1'b1);
I agree but all the infrastructure will be put in to verify and MUX functionality.  I rather chose it to verify from a sequence only in my implementation.

If this is the methodology i can surely implement.

2022-03-30 17:47 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +    uvm_hdl_force("tb.passthrough_i.csb", 1'b1);
yeah, we still drive it in the sequence, but we should drive it through a virtual interface rather than force it.

For checking, SVA may be easier, since it's just a few MUX

2022-04-01 08:34 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +    uvm_hdl_force("tb.passthrough_i.csb", 1'b1);
Test drives a vif than forces now . Sequence checks both the paths from passthrough to cio_sd

2022-04-01 08:42 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +    uvm_hdl_force("tb.passthrough_i.csb", 1'b1);
> it's a port, no need to force it. We could put it in a virtual interface and drive it
> 
> It may be better to write some assertions to check the passthrough behavior, since it's just some simple combination logic. We can put the SVAs in the RTL.

Will Designer place these assertions in RTL ?

2022-04-04 05:06 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +    uvm_hdl_force("tb.passthrough_i.csb", 1'b1);
Designer usually writes some assertions for internal logic. DV engineer writes most of port-level assertions, so you may need to write them.

2022-04-04 06:10 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +  bit [3:0]   cio_sd_i;
are these still needed?

2022-04-04 06:10 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +    `DV_CHECK_EQ(cfg.spi_passthrough_vif.os, cfg.spi_passthrough_vif.cio_sd_i)
looks like we only drive `is`, we should also drive `cio_sd_i` to ensure device to host data passes through correctly.

2022-04-04 07:27 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
> +   join
fixed

2022-04-04 07:28 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
> +        error_status.cmdbusy = 0;
accepted and changed

2022-04-04 09:23 UTC, visbaz commented on hw/ip/spi_host/dv/env/spi_host_scoreboard.sv
> +          spi_error_status_reg.accessinval   = bit'(get_field_val(ral.error_status.accessinval,
accepted and changed

2022-04-04 09:25 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +  bit [3:0]   cio_sd_i;
accepted and changed

2022-04-04 10:13 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
> +       if(error_status.cmdbusy) begin
fixed

2022-04-04 19:32 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv
> +        if(event_enable.txempty && status.txempty) begin
seeing all the events are triggered can't prove they are triggered correctly. For example, if txwm and txfull are wired together, we can't find out this issue.

2022-04-04 19:49 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv
> +        if(event_enable.ready && status.ready) begin
nit: please also fix other `if` statement
```suggestion
        if (event_enable.ready && status.ready) begin
```

2022-04-04 19:49 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +      @(posedge cfg.clk_rst_vif.clk);
nit: indent

2022-04-04 19:49 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +      cfg.spi_passthrough_vif.is <= i;
we should at least toggle all the bits of `is`. perhaps just use random value. `num_trans` is probably too small

2022-04-04 19:49 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +      cfg.spi_passthrough_vif.is <= i;
perhaps move `for (int i = 0; i < num_trans; i++) begin` to the top of this sequence to loop the whole sequence for a few times.
We can use another loop for driving `is`.

2022-04-04 19:49 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    end // end for
can we test this overflow more precisely.
1. configure spi to run at a very slow frequency.
2. send TX_FIFO_SIZE+1 items, so the fifo will be full, as one item is processing, and TX_FIFO_SIZE items make the fifo full. Check no overflow
3. send another item, check overflow occurs.

The current approach doesn't know if the overflow occurs at the right time.

2022-04-04 19:49 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
> +      end
indent

2022-04-04 19:49 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv
> +      if(wait_ready) wait_ready_for_command();
```suggestion
      if (wait_ready) wait_ready_for_command();
```

2022-04-04 19:49 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +      endgroup
add a TODO if you plan to implement this later.

2022-04-04 19:49 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +        }
can we sample all the mode? If not, use ignored_bin with the mode name (enum name). I think mode is an enum. 
```suggestion
        mode_cp : coverpoint spi_cmd_reg.mode;
```

2022-04-04 19:49 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/spi_host_env_pkg.sv
> +  } spi_host_error_enable_t;
```suggestion
  typedef struct packed{
    bit csidinval;
    bit cmdinval;
    bit underflow;
    bit overflow;
    bit cmdbusy;
  } spi_host_error_enable_t;
```

2022-04-04 19:49 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/spi_host_scoreboard.sv
> +      end
```suggestion
      if (cfg.en_cov) begin
        cov.unaligned_data_cg.sample(item.a_mask);
      end
```

2022-04-04 19:49 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/spi_host_scoreboard.sv
> +          cov.control_cg.sample(spi_ctrl_reg,spien,output_en,sw_rst);
ditto

2022-04-04 20:36 UTC, rasmus-madsen requested changes
@visbaz I started the review of this - but this is simply too big.
please move individual tests/vseq to their own PR
this will make the reivew process much much easier for all parts (you also) because they can be merged as the changes are fixed

2022-04-04 20:36 UTC, rasmus-madsen commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    csr_wr(.ptr(ral.error_status), .value(0)); // clear underflow error
I think you are clearing the overflow - not the underflow

2022-04-04 20:36 UTC, rasmus-madsen commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv
> +        if(event_enable.txempty && status.txempty) begin
@visbaz I think I agree that this function seems a little odd.
Ideally you would enable each events individually and check them individually so you know exactly what caused that event!

with this sequence it seems you have no real vision into if the event was caused by an expected scenario or by a bug in the code! 

as an example I don't believe you ever see rx_full as you set drain_rx  = 1
this will immediate trigger the event of turning of this interrupt!

2022-04-04 20:36 UTC, rasmus-madsen commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv
> +          end
this code will disable the rxfull alert without the full ever happening

2022-04-04 20:36 UTC, rasmus-madsen commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +    join
something is wrong with the indentation here

2022-04-04 20:36 UTC, rasmus-madsen commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +    join
same here

2022-04-04 21:05 UTC, weicaiyang commented
> @visbaz I started the review of this - but this is simply too big. please move individual tests/vseq to their own PR this will make the reivew process much much easier for all parts (you also) because they can be merged as the changes are fixed

Agree. If they're in small PRs, some of them can be landed much faster.

2022-04-05 10:28 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +      cfg.spi_passthrough_vif.is <= i;
accepted and implemented

2022-04-05 10:28 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_passthrough_mode_vseq.sv
> +      @(posedge cfg.clk_rst_vif.clk);
accepted and implemented

2022-04-05 10:28 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv
> +        if(event_enable.ready && status.ready) begin
accepted and implemented

2022-04-07 07:22 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    end // end for
The current test does the same . each transaction has a segment with spi data of min 4 bytes .....so with 50 iterations and randomization with in it will reach txqd >72 which is the max depth and triggers the error of overflow.
else if this scenario doesn't happen in 50 iterations then test is expected to fail. 

I have changed this test as per description above.

2022-04-07 17:44 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_error_txrx_vseq.sv
> +    end // end for
It's better to check the overflow happens when it's just one item over the depth..
if the depth is 72, we just need to send 74 to trigger the overflow error. 50 iterations will send 200+ bytes, which is too much.

2022-04-08 11:58 UTC, rasmus-madsen requested changes
small change request other than that LGTM

2022-04-08 11:58 UTC, rasmus-madsen commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
> +          cfg.clk_rst_vif.wait_clks(100);
WHy Do we need to wait 100 clocks here?

2022-04-08 11:58 UTC, rasmus-madsen commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv
> +    if(wait_ready) wait_ready_for_command();
```suggestion
    if (wait_ready) wait_ready_for_command();
```

2022-04-08 11:58 UTC, rasmus-madsen commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv
> +      if(wait_ready) wait_ready_for_command();
```suggestion
      if (wait_ready) wait_ready_for_command();
```

2022-04-08 11:58 UTC, rasmus-madsen commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +    num_segment_cg = new();
we have an instantiation macro for this
`DV_FCOV_INSTANTIATE_CG

2022-04-08 11:58 UTC, rasmus-madsen commented on hw/ip/spi_host/dv/env/spi_host_scoreboard.sv
> +    if((rx_data_q.size() != 0))
```suggestion
    if ((rx_data_q.size() != 0))
```

2022-04-08 12:13 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
> +          cfg.clk_rst_vif.wait_clks(100);
i updated this to be random between 100 to 200 ...reset to be applied while ongoing tranfers.

2022-04-08 12:47 UTC, visbaz commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +    num_segment_cg = new();
modified using this macro

2022-04-08 19:39 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
> +      end
nit: 
```suggestion
    cfg.clk_rst_vif.wait_clks($urandom_range(100, 200));
    spi_host_init();
    cfg.clk_rst_vif.wait_clks($urandom_range(100, 200));
```

2022-04-08 19:39 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
> +
nit: remove extra lines

2022-04-08 19:39 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +  endgroup
Add a TODO, if you plan to implement this later

2022-04-08 19:39 UTC, weicaiyang commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +    num_segment_cg = new();
looks like you haven't updated this

2022-04-08 22:50 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv
> +    if(wait_ready) wait_ready_for_command();
changed

2022-04-08 22:50 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv
> +      if(wait_ready) wait_ready_for_command();
changed

2022-04-08 22:51 UTC, visbaz commented on hw/ip/spi_host/dv/env/spi_host_env_cov.sv
> +    num_segment_cg = new();
using new function instead of macro

2022-04-08 22:52 UTC, visbaz commented on hw/ip/spi_host/dv/env/spi_host_scoreboard.sv
> +    if((rx_data_q.size() != 0))
changed

2022-04-08 22:53 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
> +      end
changed

2022-04-08 22:54 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
> +
changed

2022-04-08 23:14 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
> +
removed

2022-04-08 23:14 UTC, visbaz commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
> +      end
changed

2022-04-11 09:39 UTC, rasmus-madsen approved these changes
LGTM - but there are still some cleanup to do before this can be merged

2022-04-11 18:36 UTC, weicaiyang approved these changes
LGTM

2022-04-11 18:36 UTC, merged