[flash_ctrl] ADD SCOREBOARD MEMORY MODEL
lowRISC/opentitan pull request #11193
Opened 2022-03-02 17:51 UTC by nikola-miladinovic

Add Scoreboard memory model and checking of data. All four
partitions (data,info,info1,redundandy0 are supported.
Erase and erase suspension is not supported.

Signed-off-by: Nikola Miladinovic <nikola.miladinovic@ensilica.com>

2022-03-07 23:47 UTC, matutem reviewed
Please keep an eye out for avoiding repetitive code for better readability and maintainability.

2022-03-07 23:47 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +        end
Remove repetitive code: this could be a void function that takes the actual memory as a ref, and each of the three cases would just call it.

2022-03-07 23:47 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +        end
Same about remove repetitive code: create a function for this code, and just call it for the three parts.

2022-03-07 23:47 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +        end
Same about repetitive code.

2022-03-08 09:46 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +        end
Ok, it will be fixed.

2022-03-08 14:39 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +        end
Ok, will be fixed.

2022-03-09 00:05 UTC, matutem approved these changes
Please deal with csr_name (and other class members you find could be avoided).
LGTM

2022-03-09 00:05 UTC, matutem commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +  virtual task read_access_info(string name);
Is this used? You seem to use csr_name instead. And in write_access_info above you use name instead. Please choose... I would delete the class scope csr_name... and generally avoid declaring class members if possible.

2022-03-09 09:07 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +  virtual task write_access_info(string name);
Ok, agreed and fixed.

2022-03-09 09:11 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +  virtual task read_access_info(string name);
Correct. There is no need for defining "string name". Removed from both tasks.

2022-03-09 15:50 UTC, eshapira requested changes
Sorry for the late review, thanks for doing this model.
I have some additional notes/questions:
1. **Erase:** You mention in the message that this model doesn't support erase and erase suspend.
I think it can't ignore the erase because if an erase will happen on the modeled addresses, it will fail the simulation.
It can be done by monitoring the writings to the control & erase_suspend registers.
If the erase_suspend is too complicated to model maybe it can be ignored, but the erase itself is too important to my opinion and almost every test requests erases.
2. **Back-door writes:** Another factor needs to be considered is the back-door writes. It has to be monitored and affect the model because as it's affecting the actual flash.
3. **Method to do back-door of the model:** Maybe it will be good to add a method to do full back-door check of the model.

2022-03-09 15:50 UTC, eshapira commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      default:        exp_flash_redund[addr] = data;
In flash memories bits that programmed to 0 can't be programmed back to 1 and trying to do so will not change the bit value.
I think this has to be taken into account here as well.
@sha-ron @sriyerg What do you think?

```suggestion
      FlashPartData:  exp_flash_data[addr]   = data | exp_flash_data[addr];
      FlashPartInfo:  exp_flash_info[addr]   = data | exp_flash_info[addr];
      FlashPartInfo1: exp_flash_info1[addr]  = data | exp_flash_info1[addr];
      //FlashPartRedundancy
      default:        exp_flash_redund[addr] = data | exp_flash_redund[addr];
```

2022-03-09 15:50 UTC, eshapira commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +          if (cfg.scb_check && rd_access) begin
See the **cfg.scb_checks** note about this one.

```suggestion
          if (rd_access) begin
```

2022-03-09 15:50 UTC, eshapira commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +        end else if (is_mem_addr(item, ral_name)) begin  // rd fifo
See the **cfg.scb_checks** note about this one.

```suggestion
        end else if (is_mem_addr(item, ral_name) && cfg.scb_checks) begin  // rd fifo
```

2022-03-09 15:50 UTC, eshapira commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +          if (cfg.scb_check && wr_access) begin
Few notes about **cfg.scb_checks**:
1. I think that it needs to be clear that this field's value should be changed only in the beginning of the test, because otherwise the model won't be accurate.
2. If it's 0, there no need for all of the model, so I think that the `if (cfg.scb_checks)` should encompass all of the model (mybe in line 147, do `if (is_mem_addr(item, ral_name) && cfg.scb_checks)`). Same with the read part below.

```suggestion
          if (wr_access) begin
```

2022-03-09 15:50 UTC, eshapira commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +        if (is_mem_addr(item, ral_name)) begin  // prog fifo
See the cfg.scb_checks note about this one.

```suggestion
        if (is_mem_addr(item, ral_name) && cfg.scb_checks) begin  // prog fifo
```

2022-03-09 15:52 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
> +  bit scb_check = 0;
It needs to be disabled by default since other tests are developed already and we want to control when we are doing automatic checking in scoreboard.

2022-03-09 15:55 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +          if (cfg.scb_check && rd_access) begin
Please see comment above. Thanks.

2022-03-09 15:55 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +        end else if (is_mem_addr(item, ral_name)) begin  // rd fifo
Same comment.

2022-03-09 16:04 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +          if (cfg.scb_check && wr_access) begin
1. Agree - it is meant to be at the beginning on each test which has automatically checking in scoreboard, this field should be set to 1.
2. Agree, it will be fixed.

2022-03-09 16:16 UTC, nikola-miladinovic commented
> Sorry for the late review, thanks for doing this model. I have some additional notes/questions:
> 
> 1. **Erase:** You mention in the message that this model doesn't support erase and erase suspend.
>    I think it can't ignore the erase because if an erase will happen on the modeled addresses, it will fail the simulation.
>    It can be done by monitoring the writings to the control & erase_suspend registers.
>    If the erase_suspend is too complicated to model maybe it can be ignored, but the erase itself is too important to my opinion and almost every test requests erases.
> 2. **Back-door writes:** Another factor needs to be considered is the back-door writes. It has to be monitored and affect the model as it's affecting the actual flash.
> 3. **Method to back-door check the model:** Maybe it will be good to add a method to do full back-door check of the model.

1. Erase is just being implemented and it will be second PR since this has near 400 lines of code. Agree that erase_suspend will be not part of the model.
2.  & 3. Backdoor is something which is not visible by monitors and therefore it cannot be caught in Scoreboard. Point is that we model functionality of DUT, not of DV.

2022-03-09 16:41 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +        if (is_mem_addr(item, ral_name)) begin  // prog fifo
Fixed according to comment.

2022-03-09 17:43 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +      default:        exp_flash_redund[addr] = data;
Currently regression of the test for MP regions is failing with this change, so I advice to leave it for now. One of the next test is modification of rand ops test and there we could introduce this behaviour of model.

2022-03-09 18:23 UTC, nikola-miladinovic commented
@eshapira : This is only first part of Scoreboard. There will be chances for enhancement (i.e. once I create second PR to add support erase of pages and banks).

2022-03-10 18:14 UTC, tjaychen commented
merging, thanks @nikola-miladinovic

2022-03-10 18:15 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
> +        2'b10: return FlashPartRedundancy;
hmmm.... i can merge now but we can look at this later.. i'm not sure we should be naming this so explicitly in the open...

2022-03-10 18:16 UTC, merged

2022-03-14 20:02 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
> +  flash_ctrl_scoreboard scoreboard;
Please refrain from adding handles to testbench compoments in the cfg class. It needs to be the other way around - the cfg class handle is used by test bench components to provide them access to common verif settings.

2022-03-17 04:45 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
> +  bit scb_check = 0;
I agree with @eshapira - please enable scb by default and disable it in the sequences that do not need it.

2022-03-17 19:36 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
> +  bit scb_check = 0;
@sriyerg : Please create an issue and assign to me.