[dv,top,pwm] sleep pwm pulses test
lowRISC/opentitan pull request #11288
Opened 2022-03-07 16:43 UTC by jdonjdon

This is top level 'chip_sw_sleep_pwm_pulses' test

2022-03-08 00:12 UTC, timothytrippel reviewed
Thanks @jdonjdon! I added a few comments on the SW side.

2022-03-08 00:12 UTC, timothytrippel commented on sw/device/tests/pwm_test.c
> +    CHECK_DIF_OK(dif_pwm_phase_cntr_set_enabled(&pwm, kDifToggleDisabled));
just an FYI, the `dif_pwm_configure()` DIF will [disable the phase counter temporarily before updating it to its previous value before setting other configuration registers](https://github.com/lowRISC/opentitan/blob/c3dc1fa938d1889e806ff531be305afcaeb52ad8/sw/device/lib/dif/dif_pwm.c#L49-L51).

2022-03-08 07:12 UTC, timothytrippel approved these changes
Thanks for the fixes @jdonjdon ! LGTM from a SW perspective.

2022-03-08 09:19 UTC, sriyerg requested changes
I left quite a few comments, but in general, this is pretty good work @jdonjdon. 

One thing to note here is for the SV sequence to actually detect that the chip has indeed entered the deep sleep state, and then count that packets while in deep sleep state. during deep sleep, the packet count should be non-zero. There should be a `pwrmgr` FSM state that you can probe, to know that the chip is indeed in deep sleep.

2022-03-08 09:19 UTC, sriyerg commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwm_pulses_vseq.sv
> +    `uvm_info(`gfn, $sformatf("PWMCH%0d: got pkt %0d", ch,pkt_cnt[ch]), UVM_LOW)
```suggestion
    `uvm_info(`gfn, $sformatf("PWMCH%0d: got pkt %0d", ch, pkt_cnt[ch]), UVM_LOW)
```

nit: style violation - leave a single space between args and operators

2022-03-08 09:19 UTC, sriyerg commented on hw/top_earlgrey/dv/tb/tb.sv
> +    void'($value$plusargs("pwm_chk_enable=%0d", pwm_chk_en));
I suggest removing this - `pwm_monitor_cfg` already has a control knob to enable / disable the monitor. Adding second level of control may increase confusion.

2022-03-08 16:47 UTC, jdonjdon commented on hw/top_earlgrey/dv/env/chip_env.sv
> +      m_pwm_monitor[i] = pwm_monitor::type_id::create($sformatf("m_pwm_monitor%0d", i), this);
Agreed. But I prefer the name without bracket o avoid
extra escape character I have to put when I control the verbosity
of this agent.
I saw uart_agent has the same convention too. (agent name+%0d).+
>>    m_uart_agents[i] = uart_agent::type_id::create($sformatf("m_uart_agent%0d", i), this);
Can I keep this?

2022-03-08 17:14 UTC, jdonjdon commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwm_pulses_vseq.sv
> +  localparam uint DUTY_CYCLE[NUM_PWM_CHANNELS] = '{6, 11, 27, 8, 17, 7};
Yes it is just random value with some overlap.

2022-03-08 18:18 UTC, jdonjdon commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwm_pulses_vseq.sv
> +          p_sequencer.pwm_rx_fifo[j].get(item[j]);
Not sure I understand your comment.
I want to call process_pwm_data only when packet is received.
pwm_rx_fifo.get blocking calls until it gets data.

After I get the packet, how do I make this available to process_pwm_data?

2022-03-08 18:26 UTC, jdonjdon commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwm_pulses_vseq.sv
> +    `uvm_info(`gfn, "+----+------+------+-------+", UVM_LOW)
I remove post_start task. But I will keep this function for test debug.
Is that ok?

2022-03-08 18:30 UTC, jdonjdon commented on hw/top_earlgrey/dv/tb/tb.sv
> +    void'($value$plusargs("pwm_chk_enable=%0d", pwm_chk_en));
This is for dut output to pwm_monitor connection.
Until pinmux assignment to pwmout is finalized, can I keep this temporary?
After assignment is fixed, I can remove this

2022-03-08 20:51 UTC, sriyerg commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwm_pulses_vseq.sv
> +          p_sequencer.pwm_rx_fifo[j].get(item[j]);
You can move the fifo get into `process_pwm_data()`. I don't think passing the item externally instead to `pwm_process_data()` is advantageous. You can simply pass the channel index and let it get from the fifo.

```systemverilog
  virtual task collect_and_process_pwm_data(int channel);
    pwm_item item;
    p_sequencer.pwm_rx_fifo[channel].get(item);
```

2022-03-08 20:52 UTC, sriyerg commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwm_pulses_vseq.sv
> +    join_any
Ohh, is there something else that is accessing those chip IOs in that 100us time? That seems unexpected.

2022-03-08 21:08 UTC, sriyerg commented on sw/device/tests/sleep_pwm_pulses_test.c
> +};
Add a comment stating that these are arbitrarily chosen and why.

2022-03-08 21:16 UTC, sriyerg commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwm_pulses_vseq.sv
> +  localparam uint DUTY_CYCLE[NUM_PWM_CHANNELS] = '{6, 11, 27, 8, 17, 7};
Declare this as `rand uint duty_cycles[PWM_NUM_CHANNELS];` Add some meaningful constraints. You can overwrite the SW symbol with these settings so that SW is not fixed, but randomized as well. 
```systemverilog
  virtual task cpu_init();
    super.cpu_init();
    sw_symbol_backdoor_overwrite("kPwmDutycycle", {8{<<duty_cycles}});
  endtask
```

2022-03-08 21:21 UTC, sriyerg commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwm_pulses_vseq.sv
> +    end
// Move this to post_start:
```systemverilog 
  virtual task post_start();
    super.post_start();  // waits for SW test to finish
    // Disable the PWM monitor here
  endtask
```

2022-03-08 21:27 UTC, sriyerg commented on hw/top_earlgrey/dv/env/chip_env_pkg.sv
> +  parameter uint NUM_PWM_CHANNELS = 6;
Assign this parameter to `pwm_reg_pkg::NOutputs` instead.

2022-03-08 21:31 UTC, sriyerg commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwm_pulses_vseq.sv
> +    join_any
Discussed offline - agree that we need to wait on pinmux init to be done instead.

2022-03-08 21:36 UTC, sriyerg commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwm_pulses_vseq.sv
> +    if (pkt_cnt[ch] > 2) begin
`if pkt_cnt[ch] <= 2) return;` for early return and reduced indentation.

2022-03-08 21:39 UTC, sriyerg commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwm_pulses_vseq.sv
> +      if (item.active_cnt == duty_cycle_in_clk[ch]) begin
No need to maintain separate class variable clock period values - you could directly get it from a function. 
```suggestion
      if (item.active_cnt == get_duty_cycle_clk(duty_cycle[ch])) begin
```

2022-03-09 08:53 UTC, sriyerg approved these changes
THanks @jdonjdon for making the changes! This PR looks great and is almost ready to go in. I left a few more comments, but I am fine with them address later if you prefer.

2022-03-09 08:53 UTC, sriyerg commented on hw/dv/sv/pwm_monitor/pwm_monitor.sv
> +    `uvm_info(`gfn, $sformatf("getting delay %d", cfg.ok_to_end_delay_ns), UVM_HIGH)
Isn't this already printed by `super.run_phase()`?

2022-03-09 08:53 UTC, sriyerg commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwm_pulses_vseq.sv
> +    else begin
The `else begin` is not needed because the control flow returns on line 85 (if the `if` condition succeeds). 
The point of early return was to reduce the indentation level for lines 87-103. Having the `else begin` defeats that purpose.

2022-03-09 08:53 UTC, sriyerg commented on sw/device/tests/sleep_pwm_pulses_test.c
> +static volatile const uint16_t kPwmDutycycle[PWM_PARAM_N_OUTPUTS] = {
Add a comment here stating that the DV test sequence `<path-to-vseq>` may overwrite these values via backdoor.

2022-03-09 08:53 UTC, sriyerg commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwm_pulses_vseq.sv
> +                   $sformatf("PWMCH%0d : lowpower counter is zero",i))
```suggestion
                   $sformatf("PWMCH%0d : lowpower counter is zero", i))
```

2022-03-09 14:45 UTC, jdonjdon commented on hw/dv/sv/pwm_monitor/pwm_monitor.sv
> +    `uvm_info(`gfn, $sformatf("getting delay %d", cfg.ok_to_end_delay_ns), UVM_HIGH)
Yes, I double checked. dv_phase_monitor only has
   virtual task run_phase(uvm_phase phase);
    fork
      collect_trans(phase);
    join
  endtask
and collect_trans is almost virtual task.

2022-03-09 19:28 UTC, sriyerg approved these changes

2022-03-09 19:29 UTC, sriyerg commented
Sorry, one last thing - please map the test to the testplan at `hw/top_earlgrey/data/chip_testplan.hjson`.

2022-03-09 19:30 UTC, sriyerg commented
> Sorry, one last thing - please map the test to the testplan at `hw/top_earlgrey/data/chip_testplan.hjson`.

Looks this this is already done.

2022-03-09 19:30 UTC, merged