chip dv] Fix AST initialization routine
lowRISC/opentitan pull request #11376
Opened 2022-03-10 17:35 UTC by sriyerg

Use absolute address range of AST rather than reference the AST CSRs via
RAL, because those structures do not exist in the closed source.

Signed-off-by: Srikrishna Iyer <sriyer@google.com>

2022-03-10 17:50 UTC, sriyerg commented on hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
> +    uvm_reg_addr_t ast_addr = ral.ast.default_map.get_base_addr();
@sha-ron, I hope your internal RAL has an entity called `ast` so this line should not cause a breakage for you, correct?

2022-03-10 17:51 UTC, sriyerg commented
![image](https://user-images.githubusercontent.com/46467186/157724576-c8694cee-3bad-489c-8588-edce103d9d3c.png)

Waveform from non-SW CSR test showing AST initialization using the same mechanism as the SW tests.

2022-03-10 18:43 UTC, tjaychen commented on hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
> +    uvm_reg_addr_t ast_addr = ral.ast.default_map.get_base_addr();
@sriyerg does this assume this block of register has to be at the base of the ast space?
If they ever move it around, this could get out of sync right?

2022-03-10 19:23 UTC, sha-ron approved these changes

2022-03-10 19:23 UTC, sha-ron commented on hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
> +    uvm_reg_addr_t ast_addr = ral.ast.default_map.get_base_addr();
Yes, we have an ast entity so it is ok.

2022-03-10 19:44 UTC, sriyerg commented on hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
> +    uvm_reg_addr_t ast_addr = ral.ast.default_map.get_base_addr();
Yes that is correct @tjaychen. I modeled the handling of AST initialization for non-SW tests exactly the same way as the mask ROM. Note that the same assumption is also made by mask / test ROM as well:
https://github.com/lowRISC/opentitan/blob/de5926469c2d14a6427896a6e7b9040eeb4e65ce/sw/device/lib/testing/test_rom/test_rom_start.S#L157 

The ROM makes references to "REGA" and "REGAL" address offsets from constants derived from open source `as.hjson` (REGA in open source happens to start at the base of AST cfg space), but these may not exist in the closed source NTIL repo, which means those offsets will go out of sync if the assumptions across open and closed source are not correct.

2022-03-10 19:49 UTC, tjaychen commented on hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
> +    uvm_reg_addr_t ast_addr = ral.ast.default_map.get_base_addr();
yeah personally i think it makes sense to stick what needs to be common between open/closed at a very obvious place (like base address here). But would be good for Jacob / Sha-ron to confirm.

2022-03-10 20:33 UTC, Jacob-Levy commented on hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
> +    uvm_reg_addr_t ast_addr = ral.ast.default_map.get_base_addr();
AST Base Address is identical for both open and close.
The offset of the last register is also the same.
The registers names are not.
This rules will be kept when the number of registers will be changed.
At this time we have a total of 32 registers.

2022-03-10 21:23 UTC, sriyerg commented on hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
> +    uvm_reg_addr_t ast_addr = ral.ast.default_map.get_base_addr();
The question more is, whether the start address of where we initiate the AST programming will always coincide with the AST base address, and whether the "regal" register will always be immediately after it. This code and the mask ROM, both make these assumptions.

2022-03-11 06:23 UTC, sha-ron approved these changes

2022-03-11 06:23 UTC, sha-ron commented on hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
> +    uvm_reg_addr_t ast_addr = ral.ast.default_map.get_base_addr();
Yes, the start address of where we initiate the AST will always be the AST base address and unless we will find out something very big missing the offset of the "regal" register will stay as it is today.

2022-03-11 06:33 UTC, sriyerg commented
@tjaychen, need your approval to merge this :)
Thanks.

2022-03-11 10:02 UTC, rswarbrick approved these changes

2022-03-11 10:02 UTC, rswarbrick commented on hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
> +    `uvm_info(`gfn, $sformatf("Writing 0x%0h to 0x%0h", data, ast_addr), UVM_MEDIUM)
Maybe it makes sense to tweak this message to something like "Writing 0x%0h to 0x%0h (assumed to be regal register)" or similar? That way, it will be more obviously different from the messages that come out of the loop above.

2022-03-11 10:02 UTC, rswarbrick commented on hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
> +    // closed source repo.
Thinking about it, we could presumably use `get_reg_by_name` to assert that if there is a `regal` register then it's at the location we expect?

2022-03-11 11:44 UTC, Jacob-Levy commented on hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
> +    // closed source repo.
You cannot use REGAL or any register name from the OS since they are dummy registers to make the XBAR allocate the correct address space for the AST and the `ast_base_assress.`

From that point on, you need to use only the (ast_base_address + register_offset) to acccsess any AST register.
The REGAL register stand for Reg AST Last since you have access to its offset you can write the block for register init 
from OTP/ROM/CSR.  Block start at  (ast_base_address+0) to (ast_base_address+offset(REGAL)) included.

Since REGAL does not exist in the close source, I think you need to use ast_start_addrees and ast_end_address
for the routine. The ast_start_address=ast_base_address in both open and close. The ast_end_address will need to be calculated accourding to the open or close but the end result is going to be the same.

I can ease this calculation by adding the offset of the last register to the ast_pkg.sv as a parameter that you can use for
the address calculation.

2022-03-13 04:04 UTC, Jacob-Levy requested changes
Please use parameter from ast_pkg.sv that defines the last register offset for both open and close source. Parameter name is AST_REGS_LAST_OFFSET.

2022-03-14 22:23 UTC, sriyerg commented
> Please use parameter from ast_pkg.sv that defines the last register offset for both open and close source. Parameter name is AstLastRegOffset.

Done - PTAL, thanks!

2022-03-14 22:46 UTC, Jacob-Levy reviewed
The ast_pck.sv is a single file that is identical for open and close source.
The REGAL is a dummy  external register that is not exsit in the close source.
Can you remove the reference to REGAL from the ast_pkg.sv

2022-03-14 23:00 UTC, sriyerg commented
> The ast_pkg.sv is a single file that is identical for open and close source. The REGAL is a dummy external register that does not exist in the close source. Can you please remove the reference to REGAL from the ast_pkg.sv

Updated.

2022-03-15 06:07 UTC, merged