[dv] Enable C/C++ code sourcing with VCS in .core files
lowRISC/opentitan pull request #11796
Opened 2022-03-30 16:13 UTC by ctopal

Apparently fusesoc is not properly sourcing C/C++ files.
Manually adding the generated directories solves the issue.

Signed-off-by: Canberk Topal <ctopal@lowrisc.org>

2022-03-30 16:33 UTC, rswarbrick requested changes

2022-03-30 22:41 UTC, ctopal commented on hw/dv/verilator/memutil_dpi.core
> +          - '-CFLAGS -I../../src/lowrisc_dv_crypto_prince_ref_0.1'
Sorry about not doing that in the first place, now it's more sensible.

2022-03-31 06:22 UTC, sriyerg commented
Seems to be handled here also:
https://github.com/lowRISC/opentitan/blob/master/hw/ip/otbn/dv/memutil/otbn_memutil_sim_opts.hjson

2022-03-31 11:20 UTC, rswarbrick commented
You're right, @sriyerg, but this is actually for users in the Ibex repo, where you can build a VCS simulation directly from fusesoc. Everything works except for the include directories (and, of course, the hjson doesn't help in this case).

2022-03-31 11:21 UTC, rswarbrick approved these changes

2022-03-31 11:21 UTC, merged