[lint] Various fixes
lowRISC/opentitan pull request #12143
Opened 2022-04-15 00:59 UTC by msfschaffner

This takes care of most lint warnings/errors that currently show up.

2022-04-15 01:00 UTC, msfschaffner commented on hw/ip/otbn/rtl/otbn.sv
> -    .FlopOutput(0)
I am not certain why this interrupt output was not flopped in the first place.
This needs to be flopped due to CDC...

2022-04-15 01:01 UTC, msfschaffner commented on hw/ip/prim/rtl/prim_packer.sv
> +    pos_d = pos_q;
I renamed this mainly so that the assignment on line 71 can remain a one-liner (otherwise I would have to break the line, which means that we will need a begin/end block around it.

2022-04-15 01:02 UTC, msfschaffner commented on hw/ip/usbdev/rtl/usbdev.sv
> +  localparam int RcvrWakeTimeWidth = vbits(RcvrWakeTimeUs + 2);
@a-will I am not 100% certain, but it looked like this width was wrong here (we want to be able to represent `RcvrWakeTimeUs + 1`). Can you double check this is correct?

2022-04-15 03:31 UTC, a-will commented on hw/ip/usbdev/rtl/usbdev.sv
> +  localparam int RcvrWakeTimeWidth = vbits(RcvrWakeTimeUs + 2);
We do want to represent `RcvrWakeTimeUs + 1`, but I don't think the extra 1 (to get +2) is needed here. `$clog2(RcvrWakeTimeUs + 1)` ought to be enough bits.

What was harming lint was the tool's insistence that there might be a carry out, even though I had already accounted for it with `RcvrWakeTimeWidth`'s calculation. The change below should be enough on its own, right? Am I missing something?

2022-04-15 16:15 UTC, tjaychen commented on hw/ip/otbn/rtl/otbn.sv
> -    .FlopOutput(0)
there's a chance this is related to clock idle-ness? At one point, there was an issue where if the clkmgr disabled this clock, it would disable it fast enough such that the interrupt wouldn't be able to get out (related to when the block goes idle). 

But I agree with @msfschaffner it is probably better to flop and extend the idle time if needed.

2022-04-15 16:17 UTC, tjaychen commented on hw/ip/otp_ctrl/rtl/otp_ctrl_kdi.sv
> +      nonce_out_d[$clog2(NumNonceChunks)'(entropy_cnt)] = edn_data_i;
just a quick question here.. i'm assuming (could be wrong) that entropy count is wider than the number of `NumNonceChunks`? if that's true, would it be better to do a bit select?

2022-04-15 16:42 UTC, tjaychen commented on hw/ip/pinmux/rtl/pinmux.sv
> +        if (reg2hw.dio_pad_attr[kk].drive_strength.qe) begin
damn it, this reminds me that we need to eventually fix this so there is only one qe... or at least split the qe out into its own struct so that we can easily just logically OR the whole thing...

2022-04-15 16:43 UTC, tjaychen commented on hw/ip/prim/rtl/prim_packer.sv
> +    pos_d = pos_q;
ahh... line width issue?

2022-04-15 16:44 UTC, tjaychen approved these changes
most of it looks good to me, i've left a few comments.
Probably good for @eunchan to review `prim_packer`.

2022-04-15 20:05 UTC, msfschaffner commented on hw/ip/prim/rtl/prim_packer.sv
> +    pos_d = pos_q;
yes... ;)

2022-04-15 20:10 UTC, msfschaffner commented on hw/ip/usbdev/rtl/usbdev.sv
> +  localparam int RcvrWakeTimeWidth = vbits(RcvrWakeTimeUs + 2);
So in order to represent `N` inclusively, you need `$clog(N+1)` bits - otherwise you would only be able to represent numbers from `[0 ... N-1]` in certain circumstances. Hence, in order to represent `(N + 1)` inclusively you would need `$clog2(N + 2)` bits...

Does that make sense?

2022-04-15 20:10 UTC, tjaychen commented on hw/ip/otbn/rtl/otbn.sv
> -    .FlopOutput(0)
@GregAC

2022-04-15 20:11 UTC, msfschaffner commented on hw/ip/otp_ctrl/rtl/otp_ctrl_kdi.sv
> +      nonce_out_d[$clog2(NumNonceChunks)'(entropy_cnt)] = edn_data_i;
The counter is wider yes. I can change this to a bit select to make it explicit.

2022-04-15 20:12 UTC, a-will commented on hw/ip/usbdev/rtl/usbdev.sv
> +  localparam int RcvrWakeTimeWidth = vbits(RcvrWakeTimeUs + 2);
Ahh, doh, I forgot... We're not doing `RcvrWakeTimeUs` items, but the actual value. Thanks!

2022-04-15 20:12 UTC, a-will approved these changes

2022-04-15 20:14 UTC, msfschaffner commented on hw/ip/pinmux/rtl/pinmux.sv
> +        if (reg2hw.dio_pad_attr[kk].drive_strength.qe) begin
yeah the interleaving of qe and data bits is really annoying. at least rearranging them would make it easier to tie them off to unused or OR them as you say...

2022-04-15 20:14 UTC, msfschaffner commented on hw/ip/usbdev/rtl/usbdev.sv
> +  localparam int RcvrWakeTimeWidth = vbits(RcvrWakeTimeUs + 2);
Jup ;).

2022-04-15 20:15 UTC, msfschaffner commented
I'm holding off merging until @GregAC and @eunchan could give this a look also.

2022-04-15 21:14 UTC, eunchan commented
LGTM :)

> On Apr 15, 2022, at 1:15 PM, Michael Schaffner ***@***.***> wrote:
> 
> 
> I'm holding off merging until @GregAC <https://github.com/GregAC> and @eunchan <https://github.com/eunchan> could give this a look also.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/lowRISC/opentitan/pull/12143#issuecomment-1100369351>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAJDG3TVQZ4UF7SYQIMILQTVFHE7LANCNFSM5TPI4GOA>.
> You are receiving this because you were mentioned.
>

2022-04-19 18:52 UTC, GregAC requested changes
Other OTBN changes LGTM but the one I commented on needs attention.

2022-04-19 18:52 UTC, GregAC commented on hw/ip/otbn/rtl/otbn.sv
> -    .FlopOutput(0)
Ah yes, this change will break the interrupt as the idle signal will change before the interrupt is raised. I can come up with an alternate change that will allow the flop. This PR shouldn't get merged without either a fix or this particular change removed.

2022-04-19 18:54 UTC, msfschaffner commented
Thanks @GregAC! How would such a fix look like? Insert a flop on the `idle_o` output path?

2022-04-19 19:08 UTC, msfschaffner commented
I have added a mubi sender for the `idle_o` signal, which also contains a flop (this is actually good for CDC also, since the `idle_o` signal was driven combinationally before).

2022-04-19 21:52 UTC, GregAC commented
> Thanks @GregAC! How would such a fix look like? Insert a flop on the `idle_o` output path?

RTL wise yes, but there may be a DV environment impact too (as it models the timing down to the cycle).

2022-04-19 22:08 UTC, msfschaffner commented
Ok, let's take care of flopping the IRQ and `idle_o` signals here: #12215. I have removed these patches from this PR.

2022-04-20 08:51 UTC, GregAC approved these changes

2022-04-20 16:17 UTC, merged