[pwrmgr] Force clocks on when slow fsm is invalid
lowRISC/opentitan pull request #12264
Opened 2022-04-21 21:40 UTC by tjaychen

- fixes #12164

Signed-off-by: Timothy Chen <timothytim@google.com>

2022-04-21 21:41 UTC, tjaychen commented
@jeoongp FYI

2022-04-22 04:09 UTC, jdonjdon requested changes
Tim, those  *_clk_en_d  initially 0.
So this change causes all clock enables to be zero forever (except slow_clk_en)

2022-04-22 05:30 UTC, tjaychen commented
> Tim, those *_clk_en_d initially 0. So this change causes all clock enables to be zero forever (except slow_clk_en)

@jdonjdon sorry what do you mean, doesn't this force the clock enables to be 1?

2022-04-22 05:42 UTC, jdonjdon commented
> > Tim, those *_clk_en_d initially 0. So this change causes all clock enables to be zero forever (except slow_clk_en)
> 
> @jdonjdon sorry what do you mean, doesn't this force the clock enables to be 1?

My bad,  I misread your change. (fsm_invalid_q | .... makes sense).
I thought it was (fsm_invalid_q & ....). 
I rerun the failed test case from (https://github.com/lowRISC/opentitan/issues/12164)
now it passes.

2022-04-22 05:43 UTC, jdonjdon approved these changes
LGTM

2022-04-22 06:29 UTC, tjaychen commented
> LGTM

sounds great! thank you for trying it out @jdonjdon !

2022-04-22 11:50 UTC, matutem approved these changes
With a question, LGTM

2022-04-22 11:50 UTC, matutem commented on hw/ip/pwrmgr/rtl/pwrmgr_slow_fsm.sv
> +  // invalid signal forces power to turn off.
I don't understand this comment: are you referring to clearing pd_nd in any slow_fsm invalid state?

2022-04-22 15:43 UTC, tjaychen commented on hw/ip/pwrmgr/rtl/pwrmgr_slow_fsm.sv
> +  // invalid signal forces power to turn off.
yeah that's right. I guess that comment kind of has an awkward position...

2022-04-22 15:43 UTC, merged