[flash_ctrl] ADD TEST FLASH CTRL ERROR PROG TYPE
lowRISC/opentitan pull request #12310
Opened 2022-04-25 14:20 UTC by TimEwins

Perform accesses in order to provoke the 'program type' error.
Test via the Software interface

Signed-off-by: TIM EWINS <tim.ewins@ensilica.com>

2022-04-25 14:27 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
> +    localparam uint x_max = 16;
Fixed

2022-04-25 14:27 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
> +    localparam uint y_max = 32;
Fixed

2022-04-25 14:28 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    //otp_model();  // Start OTP Model TODO Currently Disabled
Fixed

2022-04-25 17:27 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
> +    for (int x=0; x<$urandom_range(8, X_MAX); x++) begin
Agreed, that would be better for random seed stability.  Changed.

2022-04-25 18:26 UTC, TimEwins commented
Please could someone with Azure Access tell me what the error in CI is ?

2022-04-25 22:10 UTC, cindychip commented
> Please could someone with Azure Access tell me what the error in CI is ?

I just reran the CI. I do not think your PR causes the failure.

2022-04-25 23:24 UTC, cindychip commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
> +            };
Do you need a bracket here? http://www.asic-world.com/systemverilog/operators4.html
Seems like ! has a higher priority than inside operator.
```suggestion
            !(mp_regions[i].start_page inside {
              [mp_regions[j].start_page:mp_regions[j].start_page + mp_regions[j].num_pages]
            });
```

2022-04-26 07:56 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +      "prog_win_err"  : csr_rd(.ptr(ral.err_code.prog_win_err),  .value(err_code_bit));
Code changed, kept backdoor read check on pass

2022-04-26 07:58 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    csr_rd(.ptr(ral.op_status.err), .value(op_status_err));
Code changed

2022-04-26 08:02 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    string         alert_msg;
Unused variables removed

2022-04-26 08:20 UTC, eshapira approved these changes
LGTM

2022-04-26 08:21 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
> +            };
Braces added to convey design intent more specifically

2022-04-26 08:22 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +      "prog_win_err"  : csr_rd(.ptr(ral.err_code.prog_win_err),  .value(err_code_bit));
Changes made.

2022-04-26 08:22 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    csr_rd(.ptr(ral.op_status.err), .value(op_status_err));
Changes made.

2022-04-26 08:23 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +    string         alert_msg;
Unused variables removed

2022-04-26 08:49 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +
Corrected

2022-04-26 12:35 UTC, eshapira reviewed
Please see my notes on the constraints on your other PR #12313, they relevant for this test as well.

2022-04-26 14:13 UTC, TimEwins commented
Please do not merge until I push new changes

2022-04-26 16:45 UTC, TimEwins commented
I have updated the following ....

Simplified the constraints, as suggested in simillar PR 12313

Ready for Review

2022-04-27 02:39 UTC, jdonjdon requested changes

2022-04-27 02:39 UTC, jdonjdon commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
> +    for (int x=0; x<x_max; x++) begin
nits
for (int x = 0; x < x_max; ++x) begin

2022-04-27 02:39 UTC, jdonjdon commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
> +      for (int y=0; y<y_max; y++) begin
same as line 186

2022-04-27 08:40 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
> +    for (int x=0; x<x_max; x++) begin
I agree this is an alternative method, but as this style is used elsewhere in the Test Bench I would like to keep it as it is, unless there is strong opposition

2022-04-27 08:41 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
> +
Agreed.  Lines Removed.

2022-04-27 08:41 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
> +      for (int y=0; y<y_max; y++) begin
As above

2022-04-27 09:21 UTC, TimEwins commented
Resubmitted

2022-04-27 11:24 UTC, TimEwins commented
Some checks are failing ... seems a common proble.  Suspect issues outside this PR.

2022-04-27 16:46 UTC, TimEwins commented
Please can someone retrigger the checkin checks to see if the errors have cleared ?

2022-04-28 17:33 UTC, weicaiyang commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
> +    for (int x=0; x<x_max; x++) begin
@TimEwins OpenTitan follows this [style guide](https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#spacing).
 either `++x` or `x++` is fine. But we should add spaces around `=` and `<`. 
```suggestion
    for (int x = 0; x < x_max; x++) begin
```

2022-04-28 17:45 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
> +    for (int x=0; x<x_max; x++) begin
I was never questioning the spaces.  I was questioning the unusual use of ++x in verilog, which is seldome used.
Changed

2022-04-28 17:48 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
> +      for (int y=0; y<y_max; y++) begin
Changed as above

2022-04-28 18:04 UTC, TimEwins commented
Updates pushed

2022-05-03 18:06 UTC, TimEwins commented
Rebased and ready for merge

This merge will conflict with #12313

Depending on which is merged first the other will need rebasing

2022-05-03 18:36 UTC, TimEwins commented
Checks need to be re-ran .. something is failing elsewhere

2022-05-04 20:42 UTC, jdonjdon approved these changes

2022-05-05 08:32 UTC, TimEwins commented
@weicaiyang Rebased and clean ... subject to further PR merges if they occur in the meantime

2022-05-05 17:50 UTC, weicaiyang approved these changes

2022-05-05 17:50 UTC, merged