[flash_ctrl] ADD TEST FLASH CTRL ERROR PROG WIN
lowRISC/opentitan pull request #12313
Opened 2022-04-25 15:48 UTC by TimEwins

Perform accesses in order to provoke the 'program resolution' error.
Test via the Software interface.

Signed-off-by: TIM EWINS <tim.ewins@ensilica.com>

2022-04-25 15:53 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv
> +
Fixed

2022-04-25 17:46 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv
> +  constraint xMax_c { xMax inside {[64:256]}; };   // Loop - Num Iterations
Changed

2022-04-26 09:30 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
> +
Fixed

2022-04-26 12:34 UTC, eshapira approved these changes
LGTM except one thing.
Please note that this thing is relevant also for your other PR #12310.

2022-04-26 12:34 UTC, eshapira commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv
> +    }
As in the other comment, this shouldn't be dependent of flash_op operation, since it's always a program:
```suggestion
    solve flash_op before flash_op_data;
    flash_op_data.size() == flash_op.num_words;
```

2022-04-26 12:34 UTC, eshapira commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv
> +    cfg.seq_cfg.op_readonly_on_info1_partition = 1;
If you do only transactions to the data partition, no need for those.
```suggestion
```

2022-04-26 12:34 UTC, eshapira commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv
> +    };
In this test you're only using program transactions and only to data partition. correct?
If so, no need for all of those constraints.
```suggestion
```

2022-04-26 13:01 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv
> +    }
Hi @eshapira I agree with everything you say, and will change the code accordingly.

The method of having a common set of random constraints and then using 'randomize with' is another way of doing it.

There is already an issue raised on us to look at putting a default set of constraints into the base class, as there is a ot of repetition of constraints as you have observed.

I have a feeling that this will eventually change again.

2022-04-26 13:02 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv
> +    cfg.seq_cfg.op_readonly_on_info1_partition = 1;
As above

2022-04-26 14:13 UTC, TimEwins commented
Please do not merge until I push new changes

2022-04-26 16:43 UTC, TimEwins commented
I have updated the following ....

1) Simplified the constraints, as suggested
2) Removed some $urandom expressions and replaced them with class constraints for better seed stability

Ready for Review

2022-04-26 16:48 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv
> +  constraint extended_num_words_c { extended_num_words
Done

2022-04-26 16:48 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv
> +
Done

2022-04-26 16:49 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv
> +        `uvm_info(`gfn, $sformatf("--> flash_op_data_prog_win : %p", flash_op_data_prog_win), UVM_HIGH)
Done

2022-04-27 03:07 UTC, jdonjdon requested changes

2022-04-27 03:07 UTC, jdonjdon commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv
> +// Copyright lowRISC contributors.
Can you add this file to https://github.com/lowRISC/opentitan/pull/12310/files ?
Unless someone ask you to create pr per vseq, I don't see why we have 2 PRs' with mostly redundant
updates.

2022-04-27 08:51 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv
> +// Copyright lowRISC contributors.
The PR submission 'process' we are using 'limits' the number of code lines that can be submitted in one PR.  Having one PR per vseq compartmenatlises the submissions which are sequential in this instance.

So it is best to stick to two PRs, especially now they are both already submitted.

2022-04-27 09:22 UTC, TimEwins commented
Resubmitted

2022-04-27 11:24 UTC, TimEwins commented
Some checks are failing ... seems a common proble.  Suspect issues outside this PR.

2022-04-27 16:46 UTC, TimEwins commented
Please can someone retrigger the checkin checks to see if the errors have cleared ?

2022-04-28 17:40 UTC, weicaiyang commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv
> +// Copyright lowRISC contributors.
One vseq one PR is probably fine. And we actually encourage people to make small PRs. the same changes on base_vseq will be merged after both PR are landed.

2022-04-28 18:06 UTC, TimEwins commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv
> +// Copyright lowRISC contributors.
Sometimes there is a need to duplicate in order to make progress.  The PR review system usually takes a while, and we need to make forward progress.

2022-05-03 18:06 UTC, TimEwins commented
Rebased and ready for merge

This merge will conflict with #12310

Depending on which is merged first the other will need rebasing

2022-05-03 18:37 UTC, TimEwins commented
Checks need to be re-ran .. something is failing elsewhere

2022-05-04 20:41 UTC, weicaiyang commented
there is a conflicting file. @TimEwins can you resolve it?

2022-05-04 20:42 UTC, jdonjdon approved these changes

2022-05-05 08:32 UTC, TimEwins commented
@weicaiyang Rebased and clean ... subject to further PR merges if they occur in the meantime

2022-05-05 17:51 UTC, weicaiyang commented
> @weicaiyang Rebased and clean ... subject to further PR merges if they occur in the meantime

yeah, need to rebase again...

2022-05-05 17:51 UTC, weicaiyang approved these changes

2022-05-05 17:52 UTC, TimEwins commented
@weicaiyang I'll do the rebase now

2022-05-09 08:58 UTC, TimEwins commented
@weicaiyang Ready for merge

2022-05-09 21:10 UTC, merged