[flash_ctrl]: ADD FUNCTIONAL COVERAGE
lowRISC/opentitan pull request #12418
Opened 2022-05-02 13:48 UTC by nikola-miladinovic

Add covergroups for functional coverage defined in Testplan.

Signed-off-by: Nikola Miladinovic <nikola.miladinovic@ensilica.com>

2022-05-02 17:24 UTC, jdonjdon requested changes

2022-05-02 17:24 UTC, jdonjdon commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cov.sv
Please remove all cover groups for MUBI CSR.
They are automatically created (https://reports.opentitan.org/hw/ip/flash_ctrl/dv/latest/cov_report/grp8.html)

2022-05-03 08:39 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson
> +            Covers data and info partitions selection.
For types of information partitions, please take a look on lines 227-240 at flash_ctrl_scoreboard.sv.
For erase suspension, please take a look on lines 241-246 at same file as above.

2022-05-03 09:34 UTC, nikola-miladinovic commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cov.sv
Fixed.

2022-05-03 13:55 UTC, jdonjdon approved these changes
LGTM

2022-05-03 21:12 UTC, weicaiyang approved these changes

2022-05-03 21:12 UTC, merged