[flash_ctrl/dv] Add full checking of scb mem model
lowRISC/opentitan pull request #12620
Opened 2022-05-12 14:21 UTC by eshapira

Hi,
This PR is adding a full check of the scoreboard memory model at the end of each test in the scoreboard check_phase.
This also required to do full updates of the model after each backdoor initialization.
This PR resolves issue #12565
Thanks!

Signed-off-by: Eitan Shapira <eitanshapira89@gmail.com>

2022-05-12 15:09 UTC, nikola-miladinovic requested changes
To keep existing tests passing,please put default value on 0. Otherwise we need to revisit each test and to check where vaule should be 0 (where non-blocking direct reads are issued).

2022-05-12 15:13 UTC, tjaychen commented
> 

@nikola-miladinovic i'm not quite following what you mean. If the scoreboard is enabled, what's the reason we should not do this backdoor check all the time?

2022-05-12 15:35 UTC, nikola-miladinovic commented
Due to parallel threads issued when non blocking reads are issued, i have distinguished checks of blocking and non-blocking reads - lines 102-104 in the scoreboard. As I remember,in the non-blocking reads,task for returning d.data was not collecting transactions correctly (i think all zeros were returned).

2022-05-12 15:36 UTC, tjaychen commented
> Due to parallel threads issued when non blocking reads are issued, i have distinguished checks of blocking and non-blocking reads - lines 102-104 in the scoreboard. As I remember,in the non-blocking reads,task for returning d.data was not collecting transactions correctly (i think all zeros were returned).

but if i understood correctly, the check from @eshapira is more about ensuring the scoreboard programmed / erase state is reflective of what's actually there right? So I don't think we have to worry about reads do we? It's more about whether all the programs / erases, backdoor or frontdoor are correctly collected in the scoreboard.

2022-05-12 16:45 UTC, eshapira commented
@tjaychen That's right. It's mainly to make sure there aren't any unexpected changes of data in the flash memory.
@nikola-miladinovic I'm not quite understand your concern, but notice that the check I added is also gated by **scb_check** and I assume that most of the tests running with **scb_check**=1 would be better have this full check.
In addition, I also ran local regression on all the tests with 2 seeds for each of the tests and they all passed (except the 2 **stress_all** tests, which I'm pretty sure didn't passed before this change as well).

2022-05-13 01:01 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
> +        if ($isunknown(read_val[i][j])) read_val[i][j] = 1'b1;
is it safe to assume unknown is just all 1's?

2022-05-13 01:03 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
> +      if ($isunknown(bkdr_rd_data)) bkdr_rd_data = ALL_ONES;
this might be a proprietary issue, but do we really have cases where it's just x? Is it because the block level doesn't do an all 1's initialization like we do at chip level?

2022-05-13 01:04 UTC, tjaychen commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
> +      if ($isunknown(bkdr_rd_data)) bkdr_rd_data = ALL_ONES;
o wait... i also just remembered there are specific backdoor routines that invalidate the flash..maybe that's why.

2022-05-13 09:44 UTC, nikola-miladinovic approved these changes
@eshapira @tjaychen LGTM since this check is at the check phase and all tests are passing. No concerns regarding non-blocking direct reads.

2022-05-13 16:08 UTC, tjaychen approved these changes

2022-05-13 16:09 UTC, tjaychen commented
thanks all, i will merge this now.

2022-05-13 16:09 UTC, merged

2022-05-15 11:45 UTC, eshapira commented
Thanks!