[otbn, dv] Fixed regression issue in otbn_illegal_mem_acc
lowRISC/opentitan pull request #12906
Opened 2022-05-27 14:56 UTC by prajwalaputtappa

This commit disables compare check that happens in the memory model
whenever an illegal access is done to the imem / dmem while the otbn is
busy executing instructions.

it also disables end address check inside run_otbn task.

Signed-off-by: Prajwala Puttappa <prajwalaputtappa@lowrisc.org>

2022-05-27 15:11 UTC, rswarbrick commented on hw/dv/sv/cip_lib/cip_base_scoreboard.sv
> +  bit disable_compare_chk = 0;
Instead of a single `bit`, could we do this by calling some hook function that says whether to do the comparison? Then we could subclass that hook, which seems a bit more flexible (and less "stateful") than this approach.

2022-05-27 15:11 UTC, rswarbrick commented on hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
> +    disable_compare_chk = !cfg.en_scb_tl_err_chk;
I don't think this is quite right: shouldn't we be disabling the check if STATUS is nonzero, and then comparing the return value with zero in this case?

2022-05-30 12:41 UTC, rswarbrick commented on hw/dv/sv/cip_lib/cip_base_scoreboard.sv
> +  virtual function bit enable_compare_chk();
Sorry, I realise you've done exactly what I suggested but I've realised that there's a much better way to do it!

Could you instead define something like `virtual function void mem_compare(string ral_name, uvm_reg_addr_t addr, tl_seq_item item)` ? The default behaviour could be the call to `exp_mem[ral_name].compare(addr, item.d_data, item.a_mask);` but then you could override it much more cleanly in `otbn_scoreboard.sv`, calling out to the superclass when we're idle but checking for zero otherwise.

2022-06-10 13:56 UTC, ctopal requested changes

2022-06-10 13:56 UTC, ctopal commented on hw/dv/sv/cip_lib/cip_base_scoreboard.sv
> +  endfunction
As Rupert suggested I think doing it this way is cleaner:

```suggestion
    if (!cfg.under_reset && get_mem_access_by_addr(cfg.ral_models[ral_name], addr) == "RW") begin
      mem_compare(ral_name, addr, item);
    end
  endtask

  virtual function void mem_compare(string ral_name, uvm_reg_addr_t addr, tl_seq_item item);
    exp_mem[ral_name].compare(addr, item.d_data, item.a_mask);
  endfunction
```

2022-06-10 13:56 UTC, ctopal commented on hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
> +  endfunction
I think if you can change it like this as mentioned above, it might be cleaner.

```suggestion
  virtual function void mem_compare(string ral_name, uvm_reg_addr_t addr, tl_seq_item item);
    // We can only compare the contents inside memories when the OTBN is not operating
    if (model_status == otbn_pkg::StatusIdle) begin
      super.mem_compare(ral_name, addr, item);
    // Otherwise the contents will read out as zeros so compare expected memory with zero. 
    end else begin
      exp_mem[ral_name].compare(addr, '0, item.a_mask);
    end
  endfunction
```

2022-06-10 13:56 UTC, ctopal commented on hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
> +  endfunction
I think if you can change it like this as mentioned above, it might be cleaner.

```suggestion
  virtual function void mem_compare(string ral_name, uvm_reg_addr_t addr, tl_seq_item item);
    // We can only compare the contents inside memories when the OTBN is not operating
    if (model_status == otbn_pkg::StatusIdle) begin
      super.mem_compare(ral_name, addr, item);
    // Otherwise the contents will read out as zeros so compare expected memory with zero. 
    end else begin
      exp_mem[ral_name].compare(addr, '0, item.a_mask);
    end
  endfunction
```

2022-06-17 11:20 UTC, ctopal approved these changes
LGTM, thanks!

2022-06-21 04:37 UTC, weicaiyang approved these changes
LGTM

2022-06-21 04:37 UTC, merged