[PWM/DV]  PWM Functional Coverage And SB Fixes
lowRISC/opentitan pull request #13517
Opened 2022-07-05 13:20 UTC by dharanendrak

Improved FC coverage
   Added OVF/UF fixes in SB

Signed-off-by: Dharanendra Kumar <dharanendra.kumar@ensilica.com>

2022-07-05 13:47 UTC, dharanendrak commented
**A. Functional coverage updates as follows:**
 1. hw/ip/pwm/dv/env/pwm_env_cov.sv

a. Corrected the bin ranges
b. removed valid range 
c. I see now single channels and all channels hitting. There was some typo in scoreboard, see item 2A.
d. Added bins for duty cycle over flow and under flow

2.hw/ip/pwm/dv/env/pwm_scoreboard.sv

a. Corrected the way the parameters passed to sample routine
b. Added coverage for Duty Cycle Over flow and Underflow

**NOTE :** To get better coverage :
  1. Allow tests to run longer ( this will ensure under flow and over flow scenarios ).
  2. It is better if the coverage database is merged from one regressions to other. 
  3. Run more tests.

**B. Fix for RTL issue ( over flow and underflow )**
  a. Checker is fixed for over flow
  b. Checker is fixed for under flow

2022-07-06 17:58 UTC, cindychip commented on hw/ip/pwm/dv/env/pwm_env_cov.sv
> +      bins channel_5 = {['h20:'h3F]};
I am not sure if I understand this coverpoint correctly, but from the [register declaration](https://docs.opentitan.org/hw/ip/pwm/doc/index.html#Reg_pwm_en), I would expect something like this:
```suggestion
      bins channel_0 = {6'b?????1};
      bins channel_1 = {6'b????1?};
      bins channel_2 = {6'b???1??};
      bins channel_3 = {6'b??1???};
      bins channel_4 = {6'b?1????};
      bins channel_5 = {6'b1?????};
```

2022-07-06 17:59 UTC, cindychip commented on hw/ip/pwm/dv/env/pwm_env_cov.sv
> +      bins high_range     = {[0:(MAX_16/3)]};
Is there any reason why we remove this low/mid/high range?

2022-07-06 17:59 UTC, cindychip commented on hw/ip/pwm/dv/env/pwm_env_cov.sv
> +      bins channel_0 = {['h1:'h3F]};
same comment as above :)

2022-07-06 18:02 UTC, cindychip commented on hw/ip/pwm/dv/env/pwm_scoreboard.sv
> +    if ((int_dc[channel][16] == 1) && ( duty_cycle[channel].B > duty_cycle[channel].A)) begin
small nit :)
```suggestion
    if ((int_dc[channel][16] == 1) && (duty_cycle[channel].B > duty_cycle[channel].A)) begin
```

2022-07-06 18:02 UTC, cindychip commented on hw/ip/pwm/dv/env/pwm_scoreboard.sv
> +  bit [16:0]                        int_dc[PWM_NUM_CHANNELS]   = '{default:0};
Could you add some comment to explain the extra one bit is for overflow check please?

2022-07-06 18:04 UTC, cindychip requested changes
Thanks Dhara for working on this.
There are some small changes requests. Please let me know if you have any questions or if I misunderstand the code ;)

2022-07-06 22:07 UTC, dharanendrak commented on hw/ip/pwm/dv/env/pwm_env_cov.sv
> +      bins high_range     = {[0:(MAX_16/3)]};
I have added in the comment section : 

// phase_delay will not go as large as MAX_16/3,
    // since it is computed  and derived from MAX_16 value
    // phase delay of the PWM rising edge, in units of 2^(-16) PWM cycles

2022-07-06 22:08 UTC, dharanendrak commented on hw/ip/pwm/dv/env/pwm_scoreboard.sv
> +  bit [16:0]                        int_dc[PWM_NUM_CHANNELS]   = '{default:0};
Yes, it is for overflow check

2022-07-06 22:54 UTC, dharanendrak commented
Cindy,

  I have updated all your comments, except on phase_delay. 
 phase_delay random variable will not have the values till MAX_16.

thanks
Dharan

2022-07-07 01:21 UTC, cindychip commented on hw/ip/pwm/dv/env/pwm_scoreboard.sv
> +    high_cycles = (int_dc[channel][15:0] >> (16 - (channel_cfg.DcResn + 1))) * (channel_cfg.ClkDiv + 1);
@dharanendrak Do you mind also addressing this comment from verible lint?

2022-07-07 02:26 UTC, dharanendrak commented on hw/ip/pwm/dv/env/pwm_scoreboard.sv
> +                   (((16'hFFFF - duty_cycle[channel].A ) / (blink[channel].B + 1'b1))) *blink[channel].B;
Done.

2022-07-07 02:27 UTC, dharanendrak commented
Cindy,
 
   I have updated the scoreboard for  line-length.

thanks
Dharan

2022-07-07 16:16 UTC, merged