[otbn, dv] Adds otbn_rf_base_glitch_detect testcase
lowRISC/opentitan pull request #13554
Opened 2022-07-08 12:15 UTC by prajwalaputtappa

This commit adds a testcase called otbn_rf_base_glitch_detect to verify OTBN.RF_BASE.DATA_REG_SW.GLITCH_DETECT countermeasure.

2022-07-08 14:04 UTC, andreaskurth requested changes
I think this is a good start for verifying an important countermeasure, thanks @prajwalaputtappa!

I have added some comments and suggestions. Even more importantly, we should also verify the case when the write enabled of the addressed register is glitched to `0`. Could you extend the current test code?

2022-07-08 14:04 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_base_glitch_detect_vseq.sv
> +    `DV_CHECK_FATAL(uvm_hdl_force(oh_p, invalid_oh_val) == 1);
```suggestion

    // Glitch the write enable by injecting an additional `1` for a different register than the one that should be written.
    uvm_hdl_read(waddr_path, wr_addr);
    `DV_CHECK_STD_RANDOMIZE_WITH_FATAL(oh_bit, oh_bit != wr_addr;)
    invalid_oh_val[wr_addr] = 1;
    invalid_oh_val[oh_bit] = 1;
    `DV_CHECK_FATAL(uvm_hdl_force(oh_p, invalid_oh_val) == 1);
```

2022-07-08 14:04 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_base_glitch_detect_vseq.sv
> +    cfg.model_agent_cfg.vif.otbn_disable_reg_checks();
Wouldn't it be better to disable register checks in the model just *before* we glitch the write enable?

2022-07-08 14:04 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_base_glitch_detect_vseq.sv
> +    @(cfg.clk_rst_vif.cb);
```suggestion

    // Tell the model that a fatal error happened.
    @(cfg.clk_rst_vif.cb);
```

2022-07-08 17:45 UTC, weicaiyang commented
@prajwalaputtappa 

we have already supported [testing one-hot countermeasure](https://github.com/lowRISC/opentitan/blob/master/hw/dv/sv/sec_cm/prim_onehot_check_if.sv) in the common sec_cm test, so in otbn_sec_cm test, it already forces the onehot primitive with these 3 types fault injection.
https://github.com/lowRISC/opentitan/blob/a4684e1331fa7f64d091e37a1a4bda140cd3d4d1/hw/dv/sv/sec_cm/prim_onehot_check_if.sv#L27-L31

perhaps you just need to check if the common sec_cm is sufficient. If you need to do any additional check, we could override the otbn_common_vseq and add it, like you did for other countermeasure, e.g. prim_count

2022-07-12 14:36 UTC, ctopal commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_base_glitch_detect_vseq.sv
> +    `DV_CHECK_STD_RANDOMIZE_WITH_FATAL(oh_bit, oh_bit != wr_addr;)
I think it was right before, with `DV_CHECK_STD_RANDOMIZE_WITH_FATAL` macro we are basically writing the constraint part as the second argument and because of that it needs to be like a legit SystemVerilog code snippet. Also, there shouldn't be a `;` after a macro.

2022-07-12 14:55 UTC, ctopal commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_base_glitch_detect_vseq.sv
> +    cfg.model_agent_cfg.vif.otbn_disable_reg_checks();
It probably does not matter since we are doing the checks towards the end of the operation (first at the start of internal wipe, secondly when it's actually wiped)

2022-07-13 06:03 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_base_glitch_detect_vseq.sv
> +    `DV_CHECK_STD_RANDOMIZE_WITH_FATAL(oh_bit, oh_bit != wr_addr;)
Thanks @ctopal, you are right! My bad, sorry for the noise.

2022-07-15 09:11 UTC, closed without merging

2022-07-15 09:11 UTC, prajwalaputtappa commented
This test is automatically taken care of by sec_cm test.