[kmac] FI protected `absorbed` signal
lowRISC/opentitan pull request #13856
Opened 2022-07-26 21:59 UTC by eunchan

This commit protects `sha3pad::absorbed_d` signal against FI attacks.
The signal is converted into `mubi4_t` and uses `mubi4_*` functions to
check the True and False values.

Reporting to SW side still remains logic to create an interrupt.

Related issue: https://github.com/lowRISC/opentitan/issues/13855

2022-07-26 22:00 UTC, tjaychen approved these changes

2022-07-26 22:08 UTC, cindychip approved these changes

2022-07-26 23:03 UTC, cindychip commented
Actually QQ @eunchan, should this be documented as a sec_cm feature for D2S?

2022-07-26 23:07 UTC, eunchan commented
> Actually QQ @eunchan, should this be documented as a sec_cm feature for D2S?
>
Good point. I should add that too.

2022-07-26 23:08 UTC, eunchan commented
Hum, `entropy_src` unit test is failing... Not sure what I touched causes the issue.

2022-07-26 23:12 UTC, cindychip commented
> Hum, `entropy_src` unit test is failing... Not sure what I touched causes the issue.

Looks like entropy_src also uses "sha3": https://github.com/lowRISC/opentitan/blob/master/hw/ip/entropy_src/rtl/entropy_src_core.sv#L2304
It looks like a common test failure. I can take a look soon.

2022-07-26 23:15 UTC, tjaychen commented
it might just be a port mismatch since we went from logic to mubi.

On Tue, Jul 26, 2022 at 4:13 PM Cindy Chen ***@***.***> wrote:

> Hum, entropy_src unit test is failing... Not sure what I touched causes
> the issue.
>
> Looks like entropy_src also uses "sha3":
> https://github.com/lowRISC/opentitan/blob/master/hw/ip/entropy_src/rtl/entropy_src_core.sv#L2304
> It looks like a common test failure. I can take a look soon.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lowRISC/opentitan/pull/13856#issuecomment-1196072414>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH2RSRM4ISEC3BTOUBL72TVWBWIDANCNFSM54XO2XOQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-07-26 23:17 UTC, cindychip commented
Hi @eunchan, looks like the issue is related to here:
https://github.com/lowRISC/opentitan/blob/master/hw/ip/entropy_src/rtl/entropy_src_core.sv#L827
https://github.com/lowRISC/opentitan/blob/master/hw/ip/entropy_src/rtl/entropy_src_core.sv#L2338
Since the absorb output become an enum, we probably cannot directly assign it.

2022-07-26 23:22 UTC, eunchan commented
Oh.. I forgot that the entropy_src uses SHA3 hehe... let me fix that too.

> On Jul 26, 2022, at 4:18 PM, Cindy Chen ***@***.***> wrote:
> 
> 
> Hi @eunchan <https://github.com/eunchan>, looks like the issue is related to here:
> https://github.com/lowRISC/opentitan/blob/master/hw/ip/entropy_src/rtl/entropy_src_core.sv#L827 <https://github.com/lowRISC/opentitan/blob/master/hw/ip/entropy_src/rtl/entropy_src_core.sv#L827>
> https://github.com/lowRISC/opentitan/blob/master/hw/ip/entropy_src/rtl/entropy_src_core.sv#L2338 <https://github.com/lowRISC/opentitan/blob/master/hw/ip/entropy_src/rtl/entropy_src_core.sv#L2338>
> Since the absorb output become an enum, we probably cannot directly assign it.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/lowRISC/opentitan/pull/13856#issuecomment-1196075021>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAJDG3SRBWR7ATXED4T7RB3VWBW2XANCNFSM54XO2XOQ>.
> You are receiving this because you were mentioned.
>

2022-07-27 07:49 UTC, m-temp requested changes
I guess there's a mubi4 => logic conversion missing in https://github.com/lowRISC/opentitan/blob/5883379ed2288fc6d5a612ddcacb7279f103d594/hw/ip/kmac/rtl/kmac_app.sv#L374-L376

2022-07-27 07:49 UTC, m-temp commented on hw/ip/kmac/rtl/sha3.sv
> +  // absorbed is a mubi4 signal that indicates sponge absorbing is done.
I think it stays a "pulse" signal, or? Although the encoding has been changed, it stays true only for one cycle, doesn't it?

2022-07-27 07:49 UTC, m-temp commented on hw/ip/kmac/rtl/kmac_app.sv
should we add a comment, why reducing the mubi4 to logic is non critical for this output?

2022-07-27 10:59 UTC, m-temp approved these changes

2022-07-27 16:07 UTC, eunchan commented on hw/ip/kmac/rtl/sha3.sv
> +  // absorbed is a mubi4 signal that indicates sponge absorbing is done.
I thought the signal no longer pulse as it becomes a multibit signal. But, conceptually, you are right. Rolled back the change :)

2022-07-27 16:08 UTC, eunchan commented on hw/ip/kmac/rtl/kmac_app.sv
I revised again to make `absorbed_o` to `mubi4_t` and convert it to logic right in front of the interrupt generation module. So, users can understand easily. Thanks!

2022-07-27 21:25 UTC, merged

2022-08-02 18:32 UTC, cdgori commented
post-merge but this all LGTM - good improvement here