[kmac] Change `done` to `mubi4_t`
lowRISC/opentitan pull request #14176
Opened 2022-08-10 00:15 UTC by eunchan

_Related Issue: https://github.com/lowRISC/opentitan/issues/13855_

`clear_i` triggers `rst_storage` in `keccak_round`. `rst_storage`
signal integrity is checked in the PR
https://github.com/lowRISC/opentitan/pull/14103

However, `clear_i` may be a victim of FI attacks. Then the consequences
are same to the FI attacks on `rst_storage`. Whenever the hashing
operation is completed and early `clear_i` signal is issued prior to SW
read, the result digest is 0. (It will be great if SW checks two shares
of the digests are not all zero)

This commit converts the `sha3_done` to `mubi4_t` and following logics
to check the signal to `prim_mubi_pkg::MuBi4True` strictly.

2022-08-10 00:38 UTC, tjaychen commented
@eunchan that's a good point on checking both shares for 0's.
@jadephilipoom FYI.

2022-08-10 01:08 UTC, msfschaffner commented
@eunchan the CI trigger seems to be stuck here. this happened to me also, and I had to re-push the PR to fix it...

2022-08-10 07:50 UTC, m-temp requested changes
It's not (only) a CI fault, but the `entropy_src` also depends on sha3 and thus needs to be adjusted. See `../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src_core.sv, 2337`

2022-08-10 07:54 UTC, m-temp commented
A general question not only related to this PR: When using mubi-signals: Should they act as a sensor and actively trigger an alert (`mubi*_test_invalid()`) or are we fine with the `_test_strict()` and `_test_loose()` function and take appropriate actions in the surrounding logic?

2022-08-10 15:11 UTC, tjaychen commented
> A general question not only related to this PR: When using mubi-signals: Should they act as a sensor and actively trigger an alert (`mubi*_test_invalid()`) or are we fine with the `_test_strict()` and `_test_loose()` function and take appropriate actions in the surrounding logic?

that's actually not something we've reached agreement across the project, so it's kind of up to each block to decide what makes the most sense. Most of the time I believe we treat anything but the "strict" as an inert value.

If you see #11400, there is a plan in the future to standardize this like shadow registers for configurable values. Inside the logic however, it will still be up to each individual design. Just due to the sheer number of mubi signals some blocks have however, it may be a bit unwieldly to do alerts for every single one.

2022-08-10 15:23 UTC, m-temp commented
> If you see #11400, there is a plan in the future to standardize this like shadow registers for configurable values. Inside the logic however, it will still be up to each individual design. Just due to the sheer number of mubi signals some blocks have however, it may be a bit unwieldly to do alerts for every single one.

@tjaychen Thanks for pointing to this issue. I'll follow the discussion there.

2022-08-10 16:03 UTC, eunchan commented
> It's not (only) a CI fault, but the `entropy_src` also depends on sha3 and thus needs to be adjusted. See `entropy_src_core.sv, 2337`
>
Yeah. That thought came up right before I sleep last night! Just updated

2022-08-10 16:04 UTC, eunchan commented
> > that's actually not something we've reached agreement across the project, so it's kind of up to each block to decide what makes the most sense. Most of the time I believe we treat anything but the "strict" as an inert value.
> 
> @eunchan I see the point in using the `_test_true_loose()` as it is the same as `not _test_strict_false()`, but perhaps one could make this statement more obvious. And/or add a comment what we do if this signal is attacked.
>
Yes. I used `test_true_loose()` to catch any FI attacks on the signal while staying in Idle(MuBi4False).

2022-08-10 23:43 UTC, msfschaffner approved these changes
LGTM

2022-08-10 23:44 UTC, msfschaffner reviewed
Ah sorry one thing I did realize is that in order for this to not be optimized away, we may have to insert a `prim_mubi4_sender` with `AsyncOn(0)` between assignment and consumers.

2022-08-11 00:46 UTC, eunchan commented
> Ah sorry one thing I did realize is that in order for this to not be optimized away, we may have to insert a `prim_mubi4_sender` with `AsyncOn(0)` between assignment and consumers.
>
Thanks. Let me add that.

2022-08-11 01:23 UTC, msfschaffner commented on hw/ip/kmac/rtl/kmac.sv
> +    .AsyncOn (0)
LGTM thanks

2022-08-11 07:42 UTC, m-temp approved these changes
LGTM

2022-08-11 15:33 UTC, merged