[otbn, dv] Adds testcase to verify OTBN.DATA.MEM.SW_NOACCESS
lowRISC/opentitan pull request #14242
Opened 2022-08-12 10:20 UTC by prajwalaputtappa

This commit adds a testcase to verify OTBN.DATA.MEM.SW_NOACCESS
countermeasure. It writes or reads from 1st Kib of address space in DMEM
whcih is inaccessible to Ibex.

Signed-off-by: Prajwala Puttappa <prajwalaputtappa@lowrisc.org>

2022-08-12 15:00 UTC, GregAC reviewed
This looks good, thanks @prajwalaputtappa 

Anything we could do to ensure the write definitely hasn't updated the memory? We could probe it directly to check the location hasn't changed. How simple would that be? It's a scrambled memory but we do already have some utilities for accessing them. If it's not super easy let's merge this now and spin that out as a new task.

2022-08-12 22:23 UTC, weicaiyang approved these changes
LGTM with a nit

2022-08-12 22:23 UTC, weicaiyang commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_sw_no_acc_vseq.sv
> +    wait (cfg.model_agent_cfg.vif.status != otbn_pkg::StatusBusyExecute);
we don't allow to use wait directly. #13402
```suggestion
   `DV_WAIT(cfg.model_agent_cfg.vif.status != otbn_pkg::StatusBusyExecute)
```

2022-08-16 06:27 UTC, GregAC commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_sw_no_acc_vseq.sv
> +    wait (cfg.model_agent_cfg.vif.status != otbn_pkg::StatusBusyExecute);
@prajwalaputtappa could you fix this up and rebase and then I can merge this.

2022-08-16 12:45 UTC, prajwalaputtappa commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_sw_no_acc_vseq.sv
> +    wait (cfg.model_agent_cfg.vif.status != otbn_pkg::StatusBusyExecute);
I've made all required changes and repushed.

2022-08-16 14:55 UTC, GregAC approved these changes
Great, thanks @prajwalaputtappa

2022-08-16 16:57 UTC, ctopal reviewed
Sorry for the delayed feedback on some parts, I just figured them out!

2022-08-16 16:57 UTC, ctopal commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_sw_no_acc_vseq.sv
> +    uvm_mem mem = ral.dmem;
This is not getting used in the test, can you remove it please?

2022-08-16 16:57 UTC, ctopal commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_sw_no_acc_vseq.sv
> +    addr = $urandom_range('h8C00, 'h8FFC);
I think you need to use `cfg.ral.get_addr_from_offset(addr)` to calculate the bus address. Something like this:

```suggestion
    bit [11:0] offset;
    offset = $urandom_range('hC00, 'hFFC);
    addr = cfg.ral.get_addr_from_offset('h8000 + offset);
```

2022-08-16 16:57 UTC, ctopal commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_sw_no_acc_vseq.sv
> +                  $sformatf("\n\t ----| Writing %d to a memory", data),
Minor nit: I think printing the data in hex makes more sense

2022-08-16 16:57 UTC, ctopal commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_sw_no_acc_vseq.sv
> +        `DV_CHECK_FATAL(data == '0)
Bus data from an erroneous request returns with '1 instead of '0. 
```suggestion
        `DV_CHECK_FATAL(data == '1)
```

2022-08-16 16:57 UTC, ctopal commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_sw_no_acc_vseq.sv
> +         rdata = cfg.read_dmem_word(addr / (4 * BaseWordsPerWLEN), key, nonce);
We cannot just give bus address to this method we need to provide an index of DMEM memory. Difficulty is calculating the index itself because we are mapping a 256b depth RAM to 32b depth register. That's where the ` / (4 * BaseWordsPerWLEN)` part comes from. But we still need to provide with the offset rather than the full address. Doing it like this should work I think:

```systemverilog
    offset = $urandom_range('hC00, 'hFFC);
    rdata = cfg.read_dmem_word(offset / (4 * BaseWordsPerWLEN), key, nonce);
```

2022-08-16 16:58 UTC, ctopal requested changes
I think some changes has to be made before merging this so I'm marking it as such

2022-08-17 14:23 UTC, prajwalaputtappa commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_sw_no_acc_vseq.sv
> +         rdata = cfg.read_dmem_word(addr / (4 * BaseWordsPerWLEN), key, nonce);
Thanks for this Canberk. I've made the required changes. I've used the same offset I randomized in the beginning of the test to pick a write address.

2022-08-17 23:30 UTC, matutem approved these changes
With a really minor nit, LGTM

2022-08-17 23:30 UTC, matutem commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_sw_no_acc_vseq.sv
> +    `DV_CHECK_STD_RANDOMIZE_FATAL(data)
Nit: constrain data so it is not all 1's... I know there is a 1 / 2^32 chance it would...

2022-08-18 09:58 UTC, andreaskurth approved these changes
LGTM, thanks @prajwalaputtappa!

2022-08-18 09:58 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_sw_no_acc_vseq.sv
> +// A sequence that writes to 1st Kib of address in DMEM which is inaccessible to ibex.
Nit:
```suggestion
// A sequence that writes to 1st Kib of address in DMEM which is inaccessible on TLUL.
```
I suggest to phrase this more generically, because even though Ibex is the only host device in current designs, the test is actually not specific to Ibex.

2022-08-22 08:58 UTC, merged