[rtl] Randomize dv_srate_value in AST RNG
lowRISC/opentitan pull request #14414
Opened 2022-08-20 17:23 UTC by sriyerg

This commit randomizes the dv_srate_value in
AST RNG model so that the randomness fetched from
AST is different for different simulation seeds.

Signed-off-by: Srikrishna Iyer <sriyer@google.com>

2022-08-21 08:59 UTC, Jacob-Levy approved these changes
LGTM,

Will update the AST source file with the change.

2022-08-22 16:32 UTC, tjaychen commented on hw/top_earlgrey/ip/ast/rtl/rng.sv
>    if ( !$value$plusargs("rng_srate_value=%0d", dv_srate_value) ) begin
could we tweak the plusargs to be the upper limit of the random? or something like that?
I originally added the `rng_srate_value` plusarg because for certain entropy tests it was taking forever to collect entropy. 

Since we are also using this to randomize the lfsr selection, it might be good to somehow combine the two ideas so that tests like `entropy_src_edn_req` can benefit from both repeated runs of different values and potentially shorter collection times. 

It may be that it would make sense to define both the lower and upper values.

2022-08-22 17:56 UTC, sriyerg commented on hw/top_earlgrey/ip/ast/rtl/rng.sv
>    if ( !$value$plusargs("rng_srate_value=%0d", dv_srate_value) ) begin
So, something like `+rng_srate_value_upper=20`, `+rnd_srate_value_lower=100`?
What would be their default values if the plusarg is not set (I arbitrarily chose {32, 128} below)?

2022-08-22 18:57 UTC, tjaychen commented on hw/top_earlgrey/ip/ast/rtl/rng.sv
>    if ( !$value$plusargs("rng_srate_value=%0d", dv_srate_value) ) begin
yeah that's right. I think for some of the heavy entropy tests, I might do something like...15 ~ 30.
I think the defaults you chose (32~128) looks good to me.

2022-08-22 19:01 UTC, tjaychen commented on hw/top_earlgrey/ip/ast/rtl/rng.sv
>    if ( !$value$plusargs("rng_srate_value=%0d", dv_srate_value) ) begin
o another suggestion, the open source ast is also based on an lfsr, so you could place `urandom` on its seed and function also.  Both are okay i think..not sure if there's a reason to prefer one over the other.

2022-08-22 21:02 UTC, sriyerg commented on hw/top_earlgrey/ip/ast/rtl/rng.sv
>    if ( !$value$plusargs("rng_srate_value=%0d", dv_srate_value) ) begin
Spoke to @tjaychen offline and concluded that modifying the prim lfsr is not needed. 

Alternatively, the prim LFSR seed needs to be exposed as a parameter at the chip level so that the seed values are set using the topgen / rand cnst tooling instead. @tjaychen, @Jacob-Levy

2022-08-22 21:02 UTC, sriyerg commented
@tjaychen, @Jacob-Levy - please re-review this PR with the new changes.

2022-08-22 21:24 UTC, tjaychen approved these changes

2022-08-22 23:37 UTC, Jacob-Levy commented
@sriyerg Your last change disable the ability to control directly the dv_srate_value which sets the 'srate_value' for OS.
In the real AST the 'srate_value' is set by a register field. 
When looking at your code the min=max=value will set the dv_srate_val to a specific value.

Any reason why the original dv_srate_val plusargs can not be set to random range outside? +dv_srate_val=<random>?
This will mimik the real register setting..

2022-08-23 00:28 UTC, Jacob-Levy requested changes
This is not a DV file... 
Please revert to the original dv_srate_value plusearge code and do all the randomization outside.
+rng_srate_value=\<rand_range\>
I need to keep this file as close as posible to the real AST.

2022-08-23 00:48 UTC, tjaychen commented
> This is not a DV file... Please revert to the original dv_srate_value plusearge code and do all the randomization outside. +rng_srate_value=<rand_range> I need to keep this file as close as posible to the real AST.

@Jacob-Levy , weren't you originally okay with the `$urandom` option? We could certainly keep that stuff under plusarg and ifdef's code.  But are you saying you would prefer this code outside in the TB that then forced a specific net instead of having it here?

2022-08-23 07:51 UTC, Jacob-Levy commented
@tjaychen I was OK with the change since it looked minor compare to the original code. 
The new change force me to review the SRATE logic in the real rng.sv and it looks that we clearly off from what it is.
The minimum SRATE is 20 and when we force it to be much less the ast_pulse_sync fired the ASSERT. I asked @zi-v that we come-up with a min/max value for the OS that reflects the real ASR rng,sv,

2022-08-23 08:48 UTC, sriyerg commented
> @sriyerg Your last change disable the ability to control directly the dv_srate_value which sets the 'srate_value' for OS. In the real AST the 'srate_value' is set by a register field. When looking at your code the min=max=value will set the dv_srate_value to a specific value.
> 
> Any reason why the original dv_srate_value plusargs can not be set to random range outside? +dv_srate_value=<random> This will mimik the real register setting..
> 
> @tjaychen It is better to randomize the seed_i of the prim_lfsr on each run to get different random values and by controling the dv_srate_value you control the rate of the random bits.
> 
> I suggest that the randomization will use the plusargs on the DV side and not in the rng.sv code. It need to stay as close as could be to the real AST.
> 
> @zi-v Can you comment about the range of the rng_srate_value? value at reset is: 12'd120.

It's a good idea to randomize `seed_i` input of `prim_lfsr`. I thought its initial seed was set via a module parameter. I will make an update for it in the next PR.

2022-08-23 19:26 UTC, Jacob-Levy requested changes
See attached rng.sv file

2022-08-23 20:16 UTC, sriyerg commented
> @sriyerg There is more to it that making changes to the rng.sv. As I mention before, the file in the OT/OS is not the source. In the OS, the RNG is using TLUL clock for the LFSR and the SRATE, Since it pulls the 4-bit random from the LFSR, the SRATE minimum must be > 4 else you will sample the same bits. For the real AST, the RANDOM generator works much slower and in order not to get the same data, the SRATE minimum must be >= 100. The bottom line, SRATE for the OS can range between 5 to 500 and for the real AST will range between 100 to 500. We need to go back to the original 'rng_srate_value' plusargs and override the value from outside per run. Also, I suggest we add a new plusargs, rng_seed_value, to set the prim_lfsr seed_i port. I attached the modified rng.sv file that you can incorporate in the PR. Also, following is the code I've changed:
> 
> ```
> ///////////////////////////////////////
> // RNG Bus using LFSR
> ///////////////////////////////////////
> logic rst_n;
> logic[EntropyStreams-1:0] lfsr_val;
> 
> assign rst_n = scan_mode_i ? rst_ni : rst_ni && rng_en_i;
> 
> // These LFSR parameters have been generated with
> // $ ./util/design/gen-lfsr-seed.py --width 64 --seed 15513 --prefix "Rng"
> localparam int RngLfsrWidth = 64;
> typedef logic [RngLfsrWidth-1:0] rng_lfsr_seed_t;
> typedef logic [RngLfsrWidth-1:0][$clog2(RngLfsrWidth)-1:0] rng_lfsr_perm_t;
> localparam rng_lfsr_seed_t RndCnstRngLfsrSeedDefault = 64'h1d033d20eed3b14;
> localparam rng_lfsr_perm_t RndCnstRngLfsrPermDefault = {
>   128'h98c2c94ab5e40420ed73f6c7396cd9e1,
>   256'h58c6d7435ddb2ed1f22400c53a5aaa796ef7785e120628fbabc87f0b3928550f
> };
> 
> rng_lfsr_seed_t rng_lfsr_seed;
> 
> prim_lfsr #(
>   .LfsrDw ( RngLfsrWidth ),
>   .EntropyDw ( 1 ),
>   .StateOutDw ( EntropyStreams ),
>   .DefaultSeed ( RndCnstRngLfsrSeedDefault ),
>   .StatePermEn ( 1'b1 ),
>   .StatePerm ( RndCnstRngLfsrPermDefault ),
>   .ExtSeedSVA ( 1'b1 )  // ext seed is used
> ) u_rng_lfsr (
>   .clk_i ( clk_i ),
>   .rst_ni ( rst_n ),
>   .lfsr_en_i ( rng_en_i ),
>   .seed_en_i ( 1'b1 ),
>   .seed_i ( rng_lfsr_seed ),
>   .entropy_i ( 1'b0 ),
>   .state_o ( lfsr_val )
> );
> 
> logic srate_rng_val;
> logic [12-1:0] srate_cnt, srate_value;
> logic [EntropyStreams-1:0] rng_b;
> 
> `ifndef SYNTHESIS
> logic [RngLfsrWidth-1:0] dv_seed_value;
> logic [12-1:0] dv_srate_value;
> int srate_init;
> 
> initial begin
>   if ( !$value$plusargs("rng_seed_value=%0h", dv_seed_value) ) begin
>     dv_seed_value = {$urandom(), $urandom()};
>   end
>   if ( !$value$plusargs("rng_srate_value=%0d", dv_srate_value) ) begin
>     srate_init = $urandom_range(12'd5, 12'd500);  // 4-bit rng_b requier minimum 5 LFSR clock to randomize 
>     dv_srate_value = srate_init[12-1:0];
>   end
> end
> 
> assign rng_lfsr_seed = dv_seed_value;
> assign srate_value   = dv_srate_value;
> `else
> assign rng_lfsr_seed = RndCnstRngLfsrSeedDefault;
> assign srate_value   = 12'd120;
> `endif
> ```
> 
> [rng.sv.gz](https://github.com/lowRISC/opentitan/files/9401815/rng.sv.gz)


Thanks @Jacob-Levy. IMO for testing, it is useful to have a tighter range within which the `dv_srate_value` is randomized in the open source. I can add the following checks to ensure the plusarg is not set incorrectly. 
```systemverilog
  `ASSERT_I(RngSrateMinCheck, rng_srate_value_min >= 5)
  `ASSERT_I(RngSrateMaxCheck, rng_srate_value_max <= 500)
  `ASSERT_I(RngSrateBoundsCheck, rng_srate_value_max >= rng_srate_value_min)
  dv_srate_value = $urandom_range(rng_srate_value_min, rng_srate_value_max);
```

Does this satisfy your concern?

2022-08-23 20:26 UTC, sriyerg commented
> This is not a DV file... Please revert to the original dv_srate_value plusearge code and do all the randomization outside. +rng_srate_value=<rand_range> I need to keep this file as close as posible to the real AST.

Don't worry @Jacob-Levy :) I will not merge this PR until everyone is happy.

2022-08-23 21:10 UTC, Jacob-Levy commented
You don't need two pluseatgs for min and max. The value I wrote are the spec for the OS rng.sv. 
Adding a check for the rng_srate_value is OK to make sure if it done externally, the value is within the range. I will add the check to the file.

2022-08-24 09:31 UTC, Jacob-Levy commented
@tjaychen @sriyerg 
I've added the pluseargs 'dv_srate_value' back, cleaned VCS compatibility issues, and also resolved the VCS Lint warnings.
Sending the file on email and also attaching it to the PR.

The real RNG SRATE can not be randomized since its a register field. I need that some of the test will be dirtected by using the 'dv_srate_value' that way on the real RNG it will be replaced with register writes. The real RNG has much more options that need to be programed.

2022-08-24 14:38 UTC, matutem reviewed
It seems you have a good pair of reviewers already. Things look okay on the surface for me, but I'll let you, @tjaychen, and @Jacob-Levy deal with this.

2022-08-26 06:31 UTC, sriyerg commented
@Jacob-Levy, re-pushed to only have the `srate` randomization changes. Please review, thanks!

2022-08-26 18:43 UTC, Jacob-Levy approved these changes
LGTM

2022-08-26 18:50 UTC, merged

2022-08-26 18:50 UTC, sriyerg commented
> LGTM

Thanks!

2022-08-26 19:07 UTC, Jacob-Levy commented
Will rebase & update my PR to address only the USB calibrate test.