[otbn, dv] Added a testcase to verify *_STACK.ADDR.INTEGRITY
lowRISC/opentitan pull request #14656
Opened 2022-08-30 15:37 UTC by prajwalaputtappa

This commit adds a new testcase called otbn_stack_addr_integ_chk to
verify OTBN.CALL_STACK.ADDR.INTEGRITY and OTBN.LOOP_STACK.ADDR.INTEGRITY
countermeasures.

Signed-off-by: Prajwala Puttappa <prajwalaputtappa@lowrisc.org>

2022-08-31 12:59 UTC, andreaskurth requested changes
Overall LGTM, thanks @prajwalaputtappa!

I have two change requests concerning number formatting plus a couple of suggestions to comply with our coding style guide, but neither requires much extra work

2022-08-31 12:59 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
> +        $sformat(err_path, "tb.dut.u_otbn_core.u_otbn_rf_base.u_call_stack.stack_storage[%d]",
```suggestion
        $sformat(err_path, "tb.dut.u_otbn_core.u_otbn_rf_base.u_call_stack.stack_storage[%0d]",
```
LRM specifies that values formatted with `%d` have leading spaces, which will not work as path in many simulators. To get rid of the leading spaces, use `%0d`

2022-08-31 12:59 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
> +    "tb.dut.u_otbn_core.u_otbn_controller.u_otbn_loop_controller.loop_info_stack.stack_storage[%d]",
```suggestion
    "tb.dut.u_otbn_core.u_otbn_controller.u_otbn_loop_controller.loop_info_stack.stack_storage[%0d]",
```

2022-08-31 12:59 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
> +    begin
```suggestion
    if (err_type) begin // err_type = 1 -> call stack error injection
```
As mandated by our [SystemVerilog Coding Style Guide](https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#begin--end)

2022-08-31 12:59 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
> +    else begin //  err_type = 0 -> loop stack error injection
```suggestion
    end else begin //  err_type = 0 -> loop stack error injection
```

2022-08-31 12:59 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
> +      end while(!top_valid);
```suggestion
      end while (!top_valid);
```

2022-08-31 12:59 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
> +    if(top_valid) begin
```suggestion
    if (top_valid) begin
```

2022-08-31 12:59 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
> +              if(err_type) begin
```suggestion
              if (err_type) begin
```

2022-08-31 12:59 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
> +                  end while(!stack_read);
```suggestion
                  end while (!stack_read);
```

2022-08-31 12:59 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
> +              else begin
```suggestion
              end else begin
```

2022-08-31 12:59 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
> +                  end while(!stack_write);
```suggestion
                  end while (!stack_write);
```

2022-08-31 12:59 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
> +    if(stack_wr_idx != 0) begin
```suggestion
    if (stack_wr_idx != 0) begin
```

2022-08-31 12:59 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
> +      else begin
```suggestion
      end else begin
```

2022-08-31 12:59 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
> +      if(!err_type) begin
```suggestion
      if (!err_type) begin
```

2022-09-01 07:11 UTC, andreaskurth approved these changes

2022-09-05 13:58 UTC, ctopal reviewed
I got a little confused about some specific part, otherwise it looks alright, thanks!

2022-09-05 13:58 UTC, ctopal commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
> +              end
I am not sure if I understand this part, do you mind adding a comment explaining why we are doing this?

2022-09-06 11:24 UTC, prajwalaputtappa commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
> +              end
Explanation added in comment.

2022-09-13 08:20 UTC, ctopal approved these changes

2022-09-13 08:21 UTC, merged