[otbn,dv] Fix-up `lc_tx_t` modelling in DV
lowRISC/opentitan pull request #14999
Opened 2022-09-19 17:39 UTC by ctopal

2022-10-23 17:48 UTC, GregAC approved these changes
LGTM, thanks for this @ctopal 

Though I did a quick run to gather some coverage and we're still not hitting the missing transitions. In particular we're not seeing the transition to locked out of the secure wipe states or the initial state.

To hit the transition out of initial we need a corrupt MUBI very early on before it transitions out of the initial state. Potentially we can waive this transition for V2. We're not hitting the secure wipe cases because if we hit the `go_during` case whatever randomisation about timing `start_otbn_running` adds clearly isn't enough to hit the secure wipe after execution. The `go_after` case waits for secure wipe to finish before doing anything (via `run_otbn`).

So I think this does what we need other some tweaks to hit the secure wipe states. Hitting the initial state would be nice as well but can certainly consider a waiver if that's trickier (might takes us above the 90% V2 coverage threshold anyway).

2022-10-24 08:46 UTC, ctopal commented
I think we have some seeds passing with `go_before` configuration, with that we inject the faulty signals at the initial state. Although the chances are 33% for getting invalid MuBi value and 30% for injecting it at the initial state. And pass rate for `go_before` configuration is 40% which means we at least need to run approx 25-30 tests to hit the scenario that is currently shows up as a FSM transition hole (`OtbnStartStopStateInitial->OtbnStartStopStateLocked`). I believe you are right about `go_after` waiting until secure wipe finishes, so I think making that less likely shouldn't be a problem. I'm thinking about doing a 30/65/5 split + 30 iterations for this test. Does that makes sense to you?

I've just ran a 30 iteration regression with VCS T-2022.06 with 30/65/5 split. It shows current 3/4 holes getting covered (`OtbnStartStopSecureWipeAllZero->OtbnStartStopStateLocked` which needs direct tests because it's a state that lasts single cycle).

2022-10-24 09:23 UTC, GregAC commented
> I'm thinking about doing a 30/65/5 split + 30 iterations for this test. Does that makes sense to you?
> I've just ran a 30 iteration regression with VCS T-2022.06 with 30/65/5 split. It shows current 3/4 holes getting covered (Missing one is OtbnStartStopSecureWipeAllZero->OtbnStartStopStateLocked which needs direct tests because it's a state that lasts single cycle).

Sounds good, I think we'll hit the coverage goal without the OtbnStartStopSecureWipeAllZero->OtbnStartStopStateLocked transition.

2022-10-24 12:55 UTC, vogelpi reviewed
Thanks for the PR @ctopal . I did review the RTL part. I think the `done_o` signal of `otbn_start_stop_control` should just be high for one clock cycle. The rest looks good.

2022-10-24 12:55 UTC, vogelpi commented on hw/ip/otbn/rtl/otbn_controller.sv
> +                                                     urnd_reseed_err_i | mubi_err_d);
I think initially not including the `mubi_err_d` here was intentional. We wanted the invalid MuBi value to still trigger a secure wipe. However, in the meantime things changed. Even if `otbn_start_stop_control` wouldn't lock up immediately, it would detect a `dropped_secure_wipe_req` (because the controller sets the req and then locks up where the req is dropped again).

Since after reset, we always perform a secure wipe now and OTBN doesn't become available before this secure wipe has finished, locking up directly upon a MuBi error sounds reasonable. It would be great if also @andreaskurth could share his opinion as he did a lot of work around the secure wipe.

2022-10-24 12:55 UTC, vogelpi commented on hw/ip/otbn/rtl/otbn_start_stop_control.sv
> +                    init_sec_wipe_done_q) || mubi_err_d);
This doesn't look right because `mubi_err_d` keeps being asserted. This means inside `otbn.sv` we keep writing the error bits and alerts, but luckily not the interrupt because that's triggered from another signal.

2022-10-24 12:55 UTC, vogelpi commented on hw/ip/otbn/rtl/otbn_start_stop_control.sv
> +                    init_sec_wipe_done_q) || mubi_err_d);
I think this signal is usually just high for 1 clock cycle.

2022-10-24 13:23 UTC, ctopal commented on hw/ip/otbn/rtl/otbn_start_stop_control.sv
> +                    init_sec_wipe_done_q) || mubi_err_d);
What would you suggest using for this instead? Would `mubi_err_d && !mubi_err_q` work?

2022-10-24 13:34 UTC, vogelpi commented on hw/ip/otbn/rtl/otbn_start_stop_control.sv
> +                    init_sec_wipe_done_q) || mubi_err_d);
Yes, that would be an option.

2022-10-24 19:24 UTC, GregAC commented
@ctopal see the final two commits on my https://github.com/GregAC/opentitan/commits/otbn_escalate_cov branch. With those we're now hitting all of the FSM transitions (other than the OtbnStartStopSecureWipeAllZero->OtbnStartStopStateLocked transition and we make the coverage goal with it).

Could you take a look at cherry pick the commits in to this PR (though actually one only increases the test iterations so can probably just get merged in with the iteration change you've already made)? Haven't done it myself as I don't want to mess up your branch for dealing with Pirmin's feedback.

2022-10-25 05:51 UTC, andreaskurth requested changes
Thanks for this PR, @ctopal. Overall LGTM, but I suggest a few changes

2022-10-25 05:51 UTC, andreaskurth commented on hw/ip/otbn/dv/model/otbn_core_model.sv
> +  assign invalid_lc_esc_en = !(lc_escalate_en_i inside {lc_ctrl_pkg::On, lc_ctrl_pkg::Off});
Suggest to use the `lc_ctrl_pkg::lc_tx_test_invalid()` function here instead of manual `inside` expressions

2022-10-25 05:51 UTC, andreaskurth commented on hw/ip/otbn/dv/model/otbn_core_model.sv
> +  assign valid_lc_esc_req = lc_escalate_en_i != lc_ctrl_pkg::Off;
Suggest to use `lc_ctrl_pkg::lc_tx_test_true_strict()` (first line) and `lc_ctrl_pkg::lc_tx_test_true_loose()` (second line) to clearly express the intent

2022-10-25 05:51 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_escalate_vseq.sv
> +    select_rma_req = $urandom_range(0, 1);
This looks wrong because `$urandom_range` is defined (18.13.2 in IEEE 1800-2012) as
```sv
function int unsigned $urandom_range(int unsigned maxval, int unsigned minval = 0);
```
So the prior version should be correct and the changed version has maximum and minimum value reversed

2022-10-25 05:51 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_escalate_vseq.sv
>      go_after = 95 <= bda_idx;
With this code, `go_during` would have a chance of 65% and `go_after` one of 5%, no? If that is the intention, please update the comment.

2022-10-25 05:51 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/tb.sv
> +  // TODO: Fix modelling of URND in the locked state.
Suggest to create an issue for tracking this and reference the issue number here with the `TODO`

2022-10-25 05:51 UTC, andreaskurth commented on hw/ip/otbn/rtl/otbn.sv
> +      clk_i, !rst_ni || u_otbn_core.urnd_reseed_err || err_bits.bad_internal_state)
Suggest updating the comment on lines 1213 and 1238 to become
```text
2. bad_internal_state disables the internal secure wipe related assertion because a 
```
and adding a similar comment between lines 1264 and 1265

2022-10-25 05:51 UTC, andreaskurth commented on hw/ip/otbn/rtl/otbn.sv
> +      clk_i, !rst_ni || u_otbn_core.urnd_reseed_err || err_bits.bad_internal_state)
Doesn't this relax the assertions too much, though?

For example, if pre-decode and decode mismatch, a bad internal state error will be raised. In that case, an internal secure wipe can take place, should take place, and we want those assertions to check that it does.

2022-10-25 05:51 UTC, andreaskurth commented on hw/ip/otbn/rtl/otbn_controller.sv
> +                                                     urnd_reseed_err_i | mubi_err_d);
I agree

2022-10-25 07:53 UTC, ctopal commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_escalate_vseq.sv
> +    select_rma_req = $urandom_range(0, 1);
I think the order does not matter since it gets reversed in the case where `maxval<minval` but I agree it could also stay as it is.

2022-10-25 08:34 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_escalate_vseq.sv
> +    select_rma_req = $urandom_range(0, 1);
> I think the order does not matter since it gets reversed in the case where `maxval<minval`

Ah you're right, 18.13.2 also states that.

> but I agree it could also stay as it is.

Yeah, let's keep the existing code if there's no need to change it.

2022-10-25 08:54 UTC, ctopal commented on hw/ip/otbn/rtl/otbn.sv
> +      clk_i, !rst_ni || u_otbn_core.urnd_reseed_err || err_bits.bad_internal_state)
Yes you're right, I thought we couldn't get the reset using the hierarchical reference but it looks like it's working so I changed it to just reset when we see mubi error from start_stop_controller. Thanks for noticing this!

2022-10-25 13:21 UTC, merged