[otbn,dv] Add test for RF integrity error FIs
lowRISC/opentitan pull request #15479
Opened 2022-10-13 17:09 UTC by ctopal

This commit introduces two tests that are used for injecting integrity errors by making bit flips on base register file (rf_intg_err) or bignum register file (rf_bignum_intg_err). Relevant V2S countermeasures are mapped as well. This would more directly check the error response of OTBN in the case of integrity faults rather than having more implicit checking throughout our other tests.

Signed-off-by: Canberk Topal <ctopal@lowrisc.org>

2022-10-14 07:23 UTC, andreaskurth requested changes
Thanks for prioritizing the addition of these tests, @ctopal!

I think this is on track but have a few questions and suggestions.

What is the current pass rate of these new tests?

2022-10-14 07:23 UTC, andreaskurth commented on hw/ip/otbn/data/otbn_sec_cm_testplan.hjson
> +      tests: ["otbn_rf_intg_err"]
For the sake of consistency, I'd call this test `otbn_rf_base_intg_err` (and also update the name of the vseq)
```suggestion
      tests: ["otbn_rf_base_intg_err"]
```

2022-10-14 07:23 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_intg_err_vseq.sv
> +
This reduces coverage before OTBN starts executing. Is this really necessary? That is, is the existing `await_use` mechanism (maybe with increased timeout?) not sufficient to ensure we inject an error when it has an effect?

2022-10-14 07:23 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_intg_err_vseq.sv
> +class otbn_rf_intg_err_vseq extends otbn_base_vseq;
Why doesn't this vseq extend `otbn_intg_err_vseq`? Wouldn't that reduce the amount of code and/or make it simpler? Or is `otbn_intg_err_vseq` missing something?

2022-10-14 11:14 UTC, ctopal commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_intg_err_vseq.sv
> +class otbn_rf_intg_err_vseq extends otbn_base_vseq;
It's because the arguments for the some tasks and functions are written for bignum lengths in `otbn_intg_err_vseq` base class. I'm happy to consider alternatives if you have suggestions about it.

2022-10-14 11:36 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_intg_err_vseq.sv
> +class otbn_rf_intg_err_vseq extends otbn_base_vseq;
Ah, I see. Could a type parameter on the class help?

2022-10-14 13:06 UTC, ctopal commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_intg_err_vseq.sv
> +class otbn_rf_intg_err_vseq extends otbn_base_vseq;
Do you mind if I do this as a cleanup task after declaring V2S?

2022-10-14 13:12 UTC, ctopal commented
Thanks for the quick review @andreaskurth! I've implemented most of the suggestions you gave except extending `otbn_intg_err_vseq` for base RF. I think that can be better suited as an enhancement task.

Pass rate is >95% for bignum, 80% for base with 50 seeds each.

2022-10-14 15:16 UTC, andreaskurth commented on hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_intg_err_vseq.sv
> +class otbn_rf_intg_err_vseq extends otbn_base_vseq;
Yes, I agree :+1: Could you please open an issue referencing this discussion?

2022-10-17 16:00 UTC, GregAC approved these changes

2022-10-17 16:00 UTC, merged