[sw/sca/sha3] Edited and added necessary files for SHA3 TVLA on cw310 (issue #15470)
lowRISC/opentitan pull request #15929
Opened 2022-11-02 16:59 UTC by wettermo

- Added new handler function whith which sha3 masking can be disabled/enabled throught capture.py in ot-sca/cw repository
- Added simpleserial acknowledge messages for synchronization with host software in batch mode
- Edited sha3_serial file for sha3 mode only
- Added sha3_serial target (copied kmac_serial and renamed it)

Signed-off-by: Moritz Wettermann <moritz.wettermann@gi-de.com>

2022-11-02 17:16 UTC, wettermo commented
The corresponding pull request in the ot-sca repository is: 
https://github.com/lowRISC/ot-sca/pull/104

2022-11-03 09:11 UTC, vogelpi reviewed
Thanks @wettermo and @m-temp for working on this! This looks mostly good.

I recommend to:
1. Instead of just renaming the `kmac_serial.c` file. I would try to use `git move` then the diff will be much smaller.
2.  Align the commit message with our standard, see here https://docs.opentitan.org/doc/project/detailed_contribution_guide/#what-should-commit-messages-look-like

2022-11-03 09:11 UTC, vogelpi commented on sw/device/sca/sha3_serial.c
> +      .msg_mask = false,
Nit: I wouldn't change these safe defaults...

2022-11-03 09:11 UTC, vogelpi commented on sw/device/sca/sha3_serial.c
> + */
The function name and description might be counter intuitive. IIRC, the entropy seed can only be set once after reset. After this point, you can just change the values for `entropy_mode`, `entropy_fast_process` and `msg_mask`. But I might be wrong. It's worth to check the spec and determine whether this function should be changed.

2022-11-03 09:11 UTC, vogelpi commented on sw/device/sca/sha3_serial.c
> +                         0x70410fef},
These two values can be set outside of the if/else when defining `config`.

2022-11-03 09:20 UTC, m-temp commented
> 1. Instead of just renaming the `kmac_serial.c` file. I would try to use `git move` then the diff will be much smaller.

We did this at first. I guess the problem is that everything was squashed into one commit.

2022-11-03 09:24 UTC, m-temp requested changes

2022-11-03 09:24 UTC, m-temp commented on sw/device/sca/sha3_serial.c
> +  simple_serial_register_handler('m', sha3_set_masks);
We should also add this function to the comment at line 22 of the file "Set mode/mask_off ('m')"

2022-11-03 09:24 UTC, m-temp commented on sw/device/sca/sha3_serial.c
> +  // Set key strength and calculate rate (r) and digest length (d) in 32-bit
We already talked about this, but perhaps s.o has also a comment on this:
set key strength might be misleading, as there is no key in sha3. I guess this is a problem with the dif. Is there a better wording for "kstrength"? Does k stand for key or kmac?

2022-11-03 09:24 UTC, m-temp commented on sw/device/sca/sha3_serial.c
> +    };
We should delete these comments here and below from my first draft.

2022-11-04 16:46 UTC, wettermo commented
I did some fine tuning of my commit and further applied the comments above from @vogelpi and @m-temp.

The commit adds the SCA device software for SHA3 TVLA:
- It separates the sha3 and kmac into two serial files / targets for better distinctiveness
- Further, the sha3 target implements a handler function to enable/disable masks via a simpleserial command

The sha3_serial binary can now be build from this PR to include it in the ot-sca PR https://github.com/lowRISC/ot-sca/pull/104 .

2022-11-07 09:26 UTC, m-temp approved these changes
LGTM

2022-11-07 11:12 UTC, vogelpi reviewed
Thanks @wettermo , I've left some comments on the `set_masking` function. The rest looks good!

2022-11-07 11:12 UTC, vogelpi commented on sw/device/sca/sha3_serial.c
> +  // host
Nit: This is not a batch command. I would just change this to "Acknowledge the command."

2022-11-07 11:12 UTC, vogelpi commented on sw/device/sca/sha3_serial.c
> +  // host
Actually, do we really need to acknowledge this command?

2022-11-07 11:21 UTC, wettermo commented on sw/device/sca/sha3_serial.c
> +  }
Ups, you're completely right!! Somehow I mixed that up, sorry! I'll change that.

2022-11-07 11:34 UTC, wettermo commented on sw/device/sca/sha3_serial.c
> +  // host
Okay, I'll edit the comment. 
Probably it's not absolutely necessary to acknowledge this command, but without doing it we somehow always got timing/out-of-sync issues with the capture file (a reason could be the call of `kmac_block_until_idle()` at the end of the function). You most likely could solve this using delays in the capture file as well, but we thought it might be a good idea to add an acknowledge.

2022-11-07 13:26 UTC, vogelpi commented on sw/device/sca/sha3_serial.c
> +  }
Thanks @wettermo , it seems you forgot to remove the `!` in front of `en_mask[0]`. Now the log output matches what is happening in the design but it doesn't match what the simpleserial command requests...

2022-11-07 15:49 UTC, vogelpi commented on sw/device/sca/sha3_serial.c
> +  }
Okay, now I understand. Thanks for explaining. I don't have a strong opinion, going with `kmac_disable_masking(const uint8_t *masks_off, size_t off_len)` sounds reasonable to me.

2022-11-07 15:49 UTC, vogelpi commented on sw/device/sca/sha3_serial.c
> +  // host
SG, thanks for the explanation.

2022-11-08 10:42 UTC, vogelpi approved these changes
LGTM, thanks @wettermo !

2022-11-09 08:50 UTC, m-temp commented
can s.o. merge this PR to merge https://github.com/lowRISC/ot-sca/pull/104 and to close https://github.com/lowRISC/opentitan/issues/15470?

2022-11-10 10:06 UTC, vogelpi commented
I am merging this, the kokoro step failed with a flow error. But this step is RTL-related only anyway and this PR doesn't touch RTL. Thanks again @wettermo and @m-temp !

2022-11-10 10:06 UTC, merged