[spi_host] Bug fix for spi_host_speed
lowRISC/opentitan pull request #16015
Opened 2022-11-04 11:01 UTC by abdullahvarici

spi_host_speed regression tests are failing for a long time with a zero pass rate. This PR includes 3 commits / fixes and increases pass rate to 100%.

In spi_monitor.sv, cmd value gets updated after first byte transmitted during command segment. But it should be updated at the end of the segment. First commit fixes that.

spi_host_speed test fails when a weak pull-up and an assign to zero concur, the signal becomes `x`. Second commit fixes that.

sck_polarity and sck_phase in vif do not have the correct value and this leads to sampling data on wrong edge of sck. Third commit fixes this error.

Fourth commit fixes drive conflict when spi_agent responsing read requests.

Signed-off-by: Abdullah Varici <abdullah.varici@lowrisc.org>

2022-11-04 13:06 UTC, andreaskurth reviewed
Thanks for these fixes, @abdullahvarici. The main changes LGTM, but I have two suggestions on the other changes that are currently included in this PR

2022-11-04 13:06 UTC, andreaskurth commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv
> +    `uvm_info(`gfn, $sformatf("DEBUG: Transaction=%s", trans.convert2string()), UVM_LOW)
I'd prefer not adding a debug print in a bug fix commit. If you think this print should be in the code base (and not just in your local copy, where you throw it away after you're done working on the test), I suggest you put it into a separate commit.

2022-11-04 13:06 UTC, andreaskurth commented on hw/ip/spi_host/dv/env/spi_host_env_cfg.sv
> +    // m_spi_agent_cfg.spi_cmd_width = num_cmd_bytes;
```suggestion
```
Completely remove this code (and the comment above?) rather than commenting it out

2022-11-04 14:46 UTC, andreaskurth approved these changes

2022-11-04 17:21 UTC, abdullahvarici commented
With the last commit, pass rate:
![image](https://user-images.githubusercontent.com/18007634/200037330-ba5302fa-3b70-4ae9-be60-9642577c7a98.png)

2022-11-04 17:30 UTC, sriyerg commented
Added @weicaiyang for review and approval.

2022-11-04 19:13 UTC, weicaiyang commented on hw/ip/spi_host/dv/tb.sv
> +    assign (highz0, pull1) spi_if.sio[i] = !cio_sd_en_o[i];
do we need to have a default pull? I thought we leave it highz if no one drives it.

2022-11-04 19:13 UTC, weicaiyang commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +    bit [1:0] sck_mode = {sck_polarity[csid], sck_phase[csid]};
I changed that the CS can be set by cfg.csid or controlled from a transaction item, as I have transactions that drive different CSBs . This is the [knob](https://cs.opensource.google/opentitan/opentitan/+/master:hw/dv/sv/spi_agent/spi_agent_cfg.sv;l=30).

The vif.sck_* are updated based on the actual CSB. Not sure if it doesn't work as expected?
https://cs.opensource.google/opentitan/opentitan/+/master:hw/dv/sv/spi_agent/spi_host_driver.sv;l=60?q=vif.sck_polarity&ss=opentitan%2Fopentitan:hw%2F

2022-11-05 04:57 UTC, a-will commented on hw/ip/spi_host/dv/tb.sv
> +    assign (highz0, pull1) spi_if.sio[i] = !cio_sd_en_o[i];
I think a default pull shouldn't be necessary at the block level, no ...assuming I'm not missing some overzealous assertion. I'm less familiar with the block level, though.

(Side note: For the chip level, `z` hits logic in the pad wrapper and becomes `x`, triggering SVAs. We enable the DIO pads' pulls there.)

2022-11-07 06:56 UTC, andreaskurth commented on hw/ip/spi_host/dv/tb.sv
> +    assign (highz0, pull1) spi_if.sio[i] = !cio_sd_en_o[i];
Just to make the context explicit, the pull-up (though it's named pulldown) was already in the code. This PR merely fixes the code so that the simulation now behaves like what seems to be the intention of the code. Prior to this change, an assignment to zero by the device would have led to an `x`.

The consensus now seems to be that this pull-up is not required. Given time pressure, I suggest we only make changes that are necessary _now_. Thus, is block-level DV more solid without this pull-up and should we therefore remove it now?

2022-11-07 19:04 UTC, andreaskurth commented
Thanks for your feedback, @weicaiyang. We've noticed another drive conflict where the assignment on L103 seems to conflict with https://github.com/lowRISC/opentitan/blob/20e9432fe6eb2805766358cb67e971db693424a8/hw/dv/sv/spi_agent/spi_if.sv#L20. Simply removing the pull-up is not an option, though. We'll continue investigating tomorrow, unless this rings a bell for you?

We'll check removing the change related to `sck_mode` directly after that

2022-11-07 19:18 UTC, weicaiyang commented
> Thanks for your feedback, @weicaiyang. We've noticed another drive conflict where the assignment on L103 seems to conflict with
> 
> https://github.com/lowRISC/opentitan/blob/20e9432fe6eb2805766358cb67e971db693424a8/hw/dv/sv/spi_agent/spi_if.sv#L20
> 
> . Simply removing the pull-up is not an option, though. We'll continue investigating tomorrow, unless this rings a bell for you?
> We'll check removing the change related to `sck_mode` directly after that

SG, thanks @andreaskurth 
FYI, I connected the spi_if as follows in spi_device TB. I don't see any driving conflict. Also LMK if you find a better approach for this in-out connection. I was struggled on this before and still don't know what the best practice is.

https://cs.opensource.google/opentitan/opentitan/+/master:hw/ip/spi_device/dv/tb/tb.sv;l=116?q=tb.sv&ss=opentitan%2Fopentitan:hw%2Fip%2Fspi_device%2F

2022-11-09 21:15 UTC, abdullahvarici commented
I pushed another commit that fixes another drive conflict.

2022-11-09 23:21 UTC, weicaiyang reviewed
Left 2 more comments. Can you also take a look at my earlier comments?

BTW, perhaps let's address the comments first and avoid adding more unrelated update to the PR.

2022-11-09 23:21 UTC, weicaiyang commented on hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv
> +              endcase
It doesn't seem necessary to convert this to num_lanes and then convert it back to cmd (spi_cmd_e) in driver..
`num_lanes` is introduced for flash model. spi_host only uses generic mode for now.
We can stick to ReadStd/ReadDual/ReadQuad and no need to use num_lanes at all.

2022-11-09 23:21 UTC, weicaiyang commented on hw/dv/sv/spi_agent/spi_device_driver.sv
> +    drive_bus_for_reset();
why we need these? we already call them at line 64-65

2022-11-10 11:57 UTC, andreaskurth commented on hw/ip/spi_host/dv/tb.sv
> +    assign (highz0, pull1) spi_if.sio[i] = !cio_sd_en_o[i];
Currently this pull-up is necessary, otherwise the test fails. I've created #16205 to track this and suggest we use the fix developed in this PR for now.

2022-11-10 17:25 UTC, weicaiyang requested changes

2022-11-10 17:25 UTC, weicaiyang commented on hw/dv/sv/spi_agent/spi_device_driver.sv
> +    drive_bus_for_reset();
I see. Looks like we always return fixed length data. Ideally device should just keep responding data until host drops CSB. So thjs task sends fixed amount data, then finishes. I think we need to enhance TB to test random length data (no need to address in this PR).

For this, how about using a forever wait like `wait (0);`, so that we let line 57-58 handle them. It may be easier to debug if we have only one place drive high z.

2022-11-10 18:31 UTC, abdullahvarici commented on hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv
> +              endcase
Sorry @weicaiyang. I don't understand what you are suggesting here.

2022-11-10 18:32 UTC, abdullahvarici commented on hw/dv/sv/spi_agent/spi_device_driver.sv
> +    drive_bus_for_reset();
Thanks, I changed it as you suggested.

2022-11-10 18:51 UTC, abdullahvarici commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +    bit [1:0] sck_mode = {sck_polarity[csid], sck_phase[csid]};
OK, I'll try to fix it.

2022-11-10 19:13 UTC, weicaiyang commented on hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv
> +              endcase
Sorry, let me clarify.
in line 60, we got the 1st byte data and convert it to `cmd` (type is spi_cmd_e), then we translate it to rsp.num_lanes, and send to driver. In the driver (line 85-88), we convert num_lanes back to `cmd` (type is spi_cmd_e). The `cmd` is very redundant.

I suggest to completely remove `spi_cmd_e` in spi_agent. If so, we could know `num_lanes` from the 1st byte data and send this info to driver. Driver can use `num_lanes` directly.

LMK if it's still not clear to you.

2022-11-10 19:29 UTC, abdullahvarici commented on hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv
> +              endcase
Actually in driver we are not converting num_lanes to spi_cmd_e but spi_mode_e as it is used in send_data_to_sio() function. I don't think we can use num_lanes directly without making any change to send_data_to_sio() function.

2022-11-10 20:13 UTC, weicaiyang commented on hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv
> +              endcase
Sorry, I made a typo in my last comment. I just fixed it. Please read it again.
I mean to remove `spi_mode_e`, including to change `send_data_to_sio` to take `num_lanes` as an input.

When I added the flash mode, I only use `num_lanes`. If general mode also uses `num_lanes`, `spi_mode_e` is probably not needed any more. 

But we need to clean up vseq that uses it in spi_host/dv as well. I'm fine to keep it as is and address this in another PR.

2022-11-11 06:34 UTC, abdullahvarici commented on hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv
> +              endcase
Ah OK. We can create a seperate PR for that then.

2022-11-11 08:48 UTC, abdullahvarici commented
Instead of making following change: `vif.sck_polarity -> sck_polarity[csid]` I have initialized that value in `spi_host_base_vseq.sv`.

2022-11-11 18:51 UTC, abdullahvarici commented
I reverted some of the changes in the last commit and applied other work arounds since the `chip_sw_spi_host_tx_rx` test was failing.

2022-11-11 19:41 UTC, weicaiyang approved these changes
LGTM
Regarding the `vif.sck_*`, I should set its value in the spi_monitor, instead of spi_host_driver. That's why you saw it didn't work for the device side.
Instead of having device_vseq to set its value, I will make a PR to set it in monitor.

2022-11-11 20:00 UTC, andreaskurth commented
Thanks for your feedback and support, @weicaiyang! I think this is ready to be merged.

2022-11-11 20:18 UTC, merged