[spi_host/dv] Fix spi_host_stress_all test
lowRISC/opentitan pull request #16314
Opened 2022-11-14 13:22 UTC by abdullahvarici

Before starting sequences running back to back in spi_host_stress_all test, the req fifos were not empty and this was causing misbehaviours. Stop previously started reactive-sequences and flush fifos. Increase test time-out.

Signed-off-by: Abdullah Varici <abdullah.varici@lowrisc.org>

2022-11-14 16:20 UTC, andreaskurth reviewed
Good catch and fix, thanks @abdullahvarici!

Running a full regression, I got `spi_host_stress_all` passing 44/50 (`spi_host_sw_reset` 48/50, rest 100%), and all non-passes of that test were timeouts after 60 mins. Should we decrease `num_trans` for this test, like we [have done for `spi_host_sw_reset`](https://github.com/lowRISC/opentitan/pull/16253/files)? (Note that the existing `constraint num_trans_c` would have to be removed so the constraint in `spi_host_base_vseq` can do its job.)

2022-11-14 19:02 UTC, weicaiyang approved these changes
LGTM with a question

2022-11-14 19:43 UTC, hcallahan-lowrisc approved these changes
I think @weicaiyang 's suggestion is a good idea, if you just call the `cleanup_reactive_seq` function from `post_start` in the base_vseq then it will happen automatically, and we can remove the call from every vseq. Otherwise, LGTM!

2022-11-15 11:22 UTC, andreaskurth requested changes

2022-11-15 11:22 UTC, andreaskurth commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_stress_all_vseq.sv
>    }
Suggest to replace lines 10 to 16 with
```sv
  task pre_randomize();
    super.pre_randomize();
    cfg.seq_cfg.host_spi_min_trans = 2;
    cfg.seq_cfg.host_spi_max_trans = 3;
    cfg.seq_cfg.host_spi_min_runs = 2;
    cfg.seq_cfg.host_spi_max_runs = 5;
  endtask
```
because that reuses the existing constraints defined in `spi_host_base_vseq`.

2022-11-15 18:50 UTC, abdullahvarici commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_stress_all_vseq.sv
>    }
Thanks Andreas. I changed it.

2022-11-15 19:29 UTC, andreaskurth approved these changes
Thanks @abdullahvarici, I think this is ready for merging :+1:

2022-11-15 20:01 UTC, merged