[csrng,dv] Add CG to check FIFOs in cmd_stage
lowRISC/opentitan pull request #16390
Opened 2022-11-16 15:35 UTC by ctopal

This commit introduces `csrng_sfifo_cg` which checks FIFOs in csrng_cmd_stage instantiations.

This should help verifying the stall behaviour described in https://github.com/lowRISC/opentitan/issues/15744

Signed-off-by: Canberk Topal <ctopal@lowrisc.org>

2022-11-16 17:54 UTC, marnovandermaas approved these changes
LGTM, just one question.

2022-11-16 17:54 UTC, marnovandermaas commented on hw/ip/csrng/dv/cov/csrng_cov_if.sv
> +      illegal_bins more_than_depth = {[3:$]};
Isn't it impossible for this command depth to be 3 or higher since it is defined as a 2 bit value?

2022-11-16 17:58 UTC, andreaskurth requested changes
Thanks @ctopal, the coverpoints LGTM, but please define `illegal_bins` for the crosses (e.g., valid for empty output FIFO and ready for full input FIFO).

2022-11-16 17:59 UTC, andreaskurth commented
This PR is designed to resolve #15744.

2022-11-17 09:39 UTC, ctopal commented on hw/ip/csrng/dv/cov/csrng_cov_if.sv
> +      illegal_bins more_than_depth = {[3:$]};
Thanks for pointing it out, this one was from a previous version of the code!

2022-11-17 11:05 UTC, ctopal commented
Rebased and updated according to feedback, thanks @andreaskurth and @marnovandermaas for the reviews!

2022-11-17 13:40 UTC, andreaskurth commented on hw/ip/csrng/dv/cov/csrng_cov_if.sv
> +      illegal_bins empty_ready = !binsof(cp_hw0_cmd_depth) intersect {2}
I would rename those illegal bins
```suggestion
      illegal_bins not_full_and_not_ready = !binsof(cp_hw0_cmd_depth) intersect {2}
```
because the condition is the FIFO not being full and the command stage not being ready.

If you agree, please change the other `*_cmd_cross`es as well

2022-11-17 13:40 UTC, andreaskurth commented on hw/ip/csrng/dv/cov/csrng_cov_if.sv
> +    }
The other combination I think we're not observing (though I haven't run a full regression on it) is full and ready. I quickly checked the `prim_fifo_sync` implementation, and I think because the read and write pointer are both registered, there is no combinational path that allows a write to a full FIFO to happen if that FIFO is read in the same cycle. Thus:
```suggestion
    illegal_bins full_and_ready = binsof(cp_hw0_cmd_depth) intersect {2} with (hw0_cmd_rdy);
    }
```

2022-11-17 13:40 UTC, andreaskurth commented on hw/ip/csrng/dv/cov/csrng_cov_if.sv
> +    hw0_genbits_cross: cross cp_hw0_genbits_depth, hw0_genbits_vld, hw0_genbits_rdy;
The behavior of `csrng_cmd_stage` strikes me as odd. According to the current bin counts, we are observing cases where `hw0_genbits_vld == 1'b1 && cp_hw0_genbits_depth == '0`. That is, the genbit output is valid even though the FIFO is empty?

The RTL, though, says genbits is valid if the FIFO is not empty
https://github.com/lowRISC/opentitan/blob/b6b962ac5ab60d69ba26a692403eee54d0100644/hw/ip/csrng/rtl/csrng_cmd_stage.sv#L436

where
https://github.com/lowRISC/opentitan/blob/b6b962ac5ab60d69ba26a692403eee54d0100644/hw/ip/csrng/rtl/csrng_cmd_stage.sv#L422

and due to
https://github.com/lowRISC/opentitan/blob/b6b962ac5ab60d69ba26a692403eee54d0100644/hw/ip/csrng/rtl/csrng_cmd_stage.sv#L412

`rvalid_o` is only true if the FIFO is not empty
https://github.com/lowRISC/opentitan/blob/b6b962ac5ab60d69ba26a692403eee54d0100644/hw/ip/prim/rtl/prim_fifo_sync.sv#L100

Whereas I would have expected this combination to form
```sv
illegal_bins empty_and_valid = binsof(cp_hw0_genbits_depth) intersect {0} with (hw0_genbits_vld);
```

What am I missing?

2022-11-17 16:16 UTC, vogelpi reviewed
Thanks for the PR @ctopal ! This looks good modulo the comments of @andreaskurth.

2022-11-17 16:16 UTC, vogelpi commented on hw/ip/csrng/dv/cov/csrng_cov_if.sv
> +    hw0_genbits_cross: cross cp_hw0_genbits_depth, hw0_genbits_vld, hw0_genbits_rdy;
Thanks for flagging this @andreaskurth . I believe there is a typo in the definition of `cp_hw0_genbits_depth` above. It's using the the `hw1_genpits_depth` signal. See comment above.

2022-11-17 21:09 UTC, ctopal commented
@andreaskurth, @vogelpi Thanks for the great feedback and sorry for the silly typo! I've added the illegal bins you suggested as they're quite sensible.

2022-11-17 23:02 UTC, ctopal commented
In the case of `csrng_err` test we are injecting some illegal states into command stage FIFOs. So, implementing assertions is better for dynamically turning them on/off dependent on the test. Removing the illegal bins from `*_cmd_cross` in the next push.

2022-11-17 23:06 UTC, ctopal commented
Added 2 new commits, one for the assertion the other is a minor fix for regwen coverage.

2022-11-17 23:38 UTC, vogelpi approved these changes
Thanks @ctopal , this looks good to me!

Nice that you switched to assertions instead of illegal bins. We can disable these.

2022-11-17 23:39 UTC, vogelpi commented on hw/ip/csrng/dv/tb.sv
> +      (tb.dut.u_csrng_core.gen_cmd_stage[i].u_csrng_cmd_stage.sfifo_cmd_depth != 2'h2) |->
Here you could theoretically avoid the hardcoded `2'h2` and instead look up the parameter value of the instantiation of interest. This would make the assertion more robust.

2022-11-17 23:40 UTC, ctopal commented on hw/ip/csrng/dv/tb.sv
> +      (tb.dut.u_csrng_core.gen_cmd_stage[i].u_csrng_cmd_stage.sfifo_cmd_depth != 2'h2) |->
I think as an improvement we can also use some other signal in the hierarchy instead of diving that deep, is it okay to do that after this one though?

2022-11-17 23:53 UTC, vogelpi commented on hw/ip/csrng/dv/tb.sv
> +      (tb.dut.u_csrng_core.gen_cmd_stage[i].u_csrng_cmd_stage.sfifo_cmd_depth != 2'h2) |->
Yes sure but it's also not so important. Don't worry, we still have more important things to do ;-)

2022-11-18 07:11 UTC, andreaskurth approved these changes
LGTM, thanks @ctopal!

2022-11-18 11:11 UTC, merged