[csrng/rtl] In state machines consolidate transitions to error and idle states
lowRISC/opentitan pull request #16397
Opened 2022-11-16 17:43 UTC by marnovandermaas

To avoid code replication and simplify FSM coverage, this consolidation puts the global transitions to the error and idle states outside of the case block.

This was suggested as part of the CSRNG V2S meeting and contributes to this issue: https://github.com/lowRISC/opentitan/issues/16388

2022-11-16 17:53 UTC, andreaskurth requested changes

2022-11-16 17:53 UTC, andreaskurth commented on hw/ip/csrng/rtl/csrng_cmd_stage.sv
> +      state_d = Idle;
Please write the code the same way as for EDN: Keep the existing `unique case` statement at the scope it has, remove the `local_escalate` and `!cs_enable_i` conditions from each state, and add one `if`-`else` code block *after* the `unique case` block.

2022-11-16 17:57 UTC, marnovandermaas commented on hw/ip/csrng/rtl/csrng_cmd_stage.sv
> +      state_d = Idle;
This way I keep the original behavior. Otherwise I need to make sure that setting values like `cmd_arb_req_o`, `command_gen_1st_req`, etc. before going into the error/idle state does not change the behavior of the block

2022-11-16 19:15 UTC, msfschaffner commented on hw/ip/csrng/rtl/csrng_cmd_stage.sv
> +      state_d = Idle;
@marnovandermaas has a point. Both variations are legal, but if we put it after the case statement, we would have to tie off any signals that have been set as part of the case statement. I am fine with either.

2022-11-16 20:02 UTC, andreaskurth commented on hw/ip/csrng/rtl/csrng_cmd_stage.sv
> +      state_d = Idle;
Oh, I see. Thanks for enlightening me, I agree with your approach :+1:

2022-11-16 20:02 UTC, andreaskurth approved these changes

2022-11-17 08:54 UTC, marnovandermaas commented
I found a problem with the way I handled the error state. I want to do a bit more testing to gain confidence in this design so I have converted the PR to draft for now.

2022-11-17 08:55 UTC, marnovandermaas commented on hw/ip/csrng/rtl/csrng_cmd_stage.sv
> +      state_d = Idle;
Thanks, I will keep it like this then.

2022-11-17 08:59 UTC, marnovandermaas commented
There is one difference I can see between the original state machine and the new proposal. If state_q is illegal, then the original state machine would go to the error state regardless of the value of enable. Does anyone think it is a problem that if we are in an illegal state with enable low that we go to the idle state instead of the error state?

2022-11-17 09:04 UTC, andreaskurth commented
> Does anyone think it is a problem that if we are in an illegal state with enable low that we go to the idle state instead of the error state?

Yes, the error state is terminal and there must be no transition out of it -- except a negative edge of `rst_ni`.

2022-11-17 09:13 UTC, vogelpi approved these changes
Thanks @marnovandermaas for doing this! The changes look good to me. You'll have to rebase this PR.

2022-11-17 09:13 UTC, vogelpi commented on hw/ip/csrng/rtl/csrng_cmd_stage.sv
> +          if (cs_enable_i) begin
I think this `if (cs_enable_i) begin` could be dropped because if `cs_enable_i` is low, we anyway don't end up in the `unique case` right?

2022-11-17 09:13 UTC, vogelpi commented on hw/ip/csrng/rtl/csrng_main_sm.sv
> -        end else
It's quite unexpected to see that we did have an `end else` without a `begin` followed by a multi-line statement and that this worked correctly.

2022-11-17 09:16 UTC, vogelpi commented
> > Does anyone think it is a problem that if we are in an illegal state with enable low that we go to the idle state instead of the error state?
> 
> Yes, the error state is terminal and there must be no transition out of it -- except a negative edge of `rst_ni` -- and any illegal state must transition to the error state.

Yes, this would be a major issue. Illegal states are always a very strong sign of an FI attack going on. We need to enter a terminal error state when this happens.

2022-11-17 09:19 UTC, vogelpi commented on hw/ip/csrng/rtl/csrng_cmd_stage.sv
> +      state_d = Idle;
After reading your question on entering idle in case of illegal state if `cs_enable_i` is low I think one probably needs to check the state here as well. Basically do something like:
```sv
end else if (!cs_enable_i && state_q inside {Idle, ...})
  ...
```

2022-11-17 11:18 UTC, marnovandermaas commented on hw/ip/csrng/rtl/csrng_cmd_stage.sv
> +          if (cs_enable_i) begin
Yes, better to not have the duplication.

2022-11-17 11:31 UTC, marnovandermaas commented on hw/ip/csrng/rtl/csrng_cmd_stage.sv
> +      state_d = Idle;
This should be done now.

2022-11-17 11:32 UTC, marnovandermaas commented on hw/ip/csrng/rtl/csrng_cmd_stage.sv
> +          if (cs_enable_i) begin
Thanks for finding this, I have also removed the same statement in the main FSM.

2022-11-17 11:34 UTC, marnovandermaas commented on hw/ip/csrng/rtl/csrng_main_sm.sv
> -        end else
I think the if block is considered a single block, similar to if you write without the enter between else and if:
```
if (...) begin
  ...
end else if (...) begin
  ...
end
```

2022-11-17 11:38 UTC, marnovandermaas commented
Rebase

2022-11-17 13:35 UTC, marnovandermaas commented
I've tested this commit and have not seen any failures. These changes do mean that the coverage no longer detects that the command stage and main are state machines, but the code coverage looks good to me.

2022-11-17 14:24 UTC, vogelpi commented
> I've tested this PR and have not seen any failures. These changes do mean that the xcelium coverage tool no longer detects that the command stage and main are state machines, but the code coverage looks good to me.

Thanks @marnovandermaas . Regarding "These changes do mean that the xcelium coverage tool no longer detects that the command stage and main are state machines" is this something we are expecting @andreaskurth or does it complicate your work in any way?

2022-11-17 16:29 UTC, vogelpi commented
Alright, thanks @andreaskurth for the feedback and again @marnovandermaas for the work, let's merge this!

2022-11-17 16:29 UTC, merged

2022-11-17 21:02 UTC, msfschaffner commented
> > Regarding "These changes do mean that the xcelium coverage tool no longer detects that the command stage and main are state machines" is this something we are expecting @andreaskurth or does it complicate your work in any way?
> 
> I think we would prefer if the coverage tool kept recognizing those FSMs, but we don't have a strict requirement for it. If we need to know in which state the block is in when an event (such as disabling) happens, we can still add explicit coverpoints to track this.

Is this maybe due to the fact that we now embed the case statement in an if/else block? I.e., would the tool recognize the FSM again if we did it the other way round (place the override statements after the case statement)?

2022-11-18 09:10 UTC, marnovandermaas commented
> > > Regarding "These changes do mean that the xcelium coverage tool no longer detects that the command stage and main are state machines" is this something we are expecting @andreaskurth or does it complicate your work in any way?
> > 
> > 
> > I think we would prefer if the coverage tool kept recognizing those FSMs, but we don't have a strict requirement for it. If we need to know in which state the block is in when an event (such as disabling) happens, we can still add explicit coverpoints to track this.
> 
> Is this maybe due to the fact that we now embed the case statement in an if/else block? I.e., would the tool recognize the FSM again if we did it the other way round (place the override statements after the case statement)?

Yes, I think so. Although I am not sure about whether it would recognize the state transitions if you put an if/else block after the case statement.

2022-11-18 16:08 UTC, msfschaffner commented
You can probably check this by running another modules that does it this way in Xcelium.
EDN for instance does it the other way in `edn_main_sm.sv`.