[entropy_src] Latch rng_enable
lowRISC/opentitan pull request #16732
Opened 2022-12-08 18:55 UTC by eunchan

rng_enable is being used in other clock domains. The logic did not latch the signal in the previous design.

This commit latches the signal to make it a glitch-free signal.

In the entropy_src top, the RTL seems to have a mux. However, `Stub` is a parameter so the mux will be optimized out.

2022-12-08 19:10 UTC, martin-lueker requested changes

2022-12-08 19:10 UTC, martin-lueker commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +      rng_enable_q <= '0;
I know there is no OT style for this, but all other flops are managed in always block in line 488, would you be okay with putting this there?

2022-12-08 19:12 UTC, martin-lueker requested changes

2022-12-08 19:12 UTC, martin-lueker commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +  assign entropy_src_rng_o.rng_enable = rng_enable_q;
THis is problematic, as the delay will cause a lot of problems in DV

- Dropped samples in DV
- Shift in enable timing will cause mismatch in anticipated statistics.

These are the real issues with this commit. (Not the placement of the flops... I hit "Review" too soon)

2022-12-08 19:14 UTC, martin-lueker commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +  assign entropy_src_rng_o.rng_enable = rng_enable_q;
Is this really an async clock domain? If so with have lots of other issues to deal with.    Is there no other way to resolve the issues you are having?

2022-12-08 19:16 UTC, martin-lueker commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +      rng_enable_q <= '0;
For the record: this is purely a nit.  My bigger issue is in my other comment.

2022-12-08 19:23 UTC, eunchan commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +      rng_enable_q <= '0;
No problem. FYI, there's [another `always_ff`](https://cs.opensource.google/opentitan/opentitan/+/master:hw/ip/entropy_src/rtl/entropy_src_core.sv;l=2338) in the design.

2022-12-08 19:26 UTC, tjaychen commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +  assign entropy_src_rng_o.rng_enable = rng_enable_q;
@arnonsha can speak more to this, but i think @jeoongp also discovered that rng enable is consumed asynchronously. (however the data interface should be on the entropy_src clock..i think).

2022-12-08 19:26 UTC, eunchan commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +  assign entropy_src_rng_o.rng_enable = rng_enable_q;
I also worried when I revise the design as the change introduces one cycle delay to `rng_enable`. However, as far as I check, the signal is again synchronized in other modules (AST). @arnonsha can comment here.

I am currently running all top level test cases including `entropy_src` modules. So far the results are good. 3 remaining tests are still running though.

2022-12-08 19:26 UTC, tjaychen commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +  assign entropy_src_rng_o.rng_enable = rng_enable_q;
@martin-lueker in terms of the issues you're pointing out, is this related to how the DV expects the transactions to be timed? Because I would think the data interface is more important to you, not the `rng_en`

2022-12-08 19:27 UTC, martin-lueker commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +  assign entropy_src_rng_o.rng_enable = rng_enable_q;
Thinking more about this... it might be okay, but it will take some attention.

The dropped samples aren't a problem in the real devices, as that is the expected behavior, DV just needs to know clearly which ones are dropped.  DV can just ensure that it never sends data in back-to-back cycles.

The shift in enable timing, I'm trying to think, but it may not be that bad.

2022-12-08 19:27 UTC, eunchan commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +  assign entropy_src_rng_o.rng_enable = rng_enable_q;
> @arnonsha can speak more to this, but i think @jeoongp also discovered that rng enable is consumed asynchronously. (however the data interface should be on the entropy_src clock..i think).
>
Ah.. if it is clocked in entropy_src clock, then, it makes sense this is only visible in RDC (as a warning)

2022-12-08 19:30 UTC, martin-lueker commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +  assign entropy_src_rng_o.rng_enable = rng_enable_q;
> @arnonsha can speak more to this, but i think @jeoongp also discovered that rng enable is consumed asynchronously. (however the data interface should be on the entropy_src clock..i think).

Well frankly, AST doesn't give a hoot about the enable signal.  It's only used by DV. @arnonsha or @zi-v can probably confirm.

2022-12-08 19:32 UTC, eunchan commented
```log
### Test Results
|  Stage  |                  Name                  | Tests                                    |  Max Job Runtime  |  Simulated Time  |  Passing  |  Total  |  Pass Rate  |
|:-------:|:--------------------------------------:|:-----------------------------------------|:-----------------:|:----------------:|:---------:|:-------:|:-----------:|
|   V2    |         chip_sw_clkmgr_jitter          | chip_sw_edn_entropy_reqs_jitter          |      23.242m      |     5.745ms      |     3     |    3    |  100.00 %   |
|   V2    |     chip_sw_alert_handler_entropy      | chip_sw_alert_handler_entropy            |      3.084m       |     2.537ms      |     3     |    3    |  100.00 %   |
|   V2    |          chip_sw_aes_entropy           | chip_sw_aes_entropy                      |      2.881m       |     3.528ms      |     3     |    3    |  100.00 %   |
|   V2    |          chip_sw_kmac_entropy          | chip_sw_kmac_entropy                     |      2.821m       |     3.077ms      |     3     |    3    |  100.00 %   |
|   V2    |    chip_sw_entropy_src_ast_rng_req     | chip_sw_entropy_src_ast_rng_req          |      3.087m       |     2.871ms      |     3     |    3    |  100.00 %   |
|   V2    |       chip_sw_entropy_src_csrng        | chip_sw_entropy_src_csrng                |      13.077m      |     7.441ms      |     3     |    3    |  100.00 %   |
|   V2    |  chip_sw_entropy_src_fuse_en_fw_read   | chip_sw_entropy_src_fuse_en_fw_read_test |      5.352m       |     4.843ms      |     3     |    3    |  100.00 %   |
|   V2    | chip_sw_entropy_src_known_answer_tests | chip_sw_entropy_src_kat_test             |      2.744m       |     3.222ms      |     3     |    3    |  100.00 %   |
|   V2    |         chip_sw_csrng_edn_cmd          | chip_sw_entropy_src_csrng                |      13.077m      |     7.441ms      |     3     |    3    |  100.00 %   |
|   V2    |        chip_sw_edn_entropy_reqs        | chip_sw_edn_entropy_reqs                 |      23.384m      |     5.120ms      |     3     |    3    |  100.00 %   |
|   V2    |       chip_sw_ast_sys_clk_jitter       | chip_sw_edn_entropy_reqs_jitter          |      23.242m      |     5.745ms      |     3     |    3    |  100.00 %   |
|   V2    |           chip_sw_smoketest            | chip_sw_entropy_src_smoketest            |      5.173m       |     3.848ms      |     3     |    3    |  100.00 %   |
|   V2    |                                        | **TOTAL**                                |                   |                  |    30     |   30    |  100.00 %   |
|         |                                        | **TOTAL**                                |                   |                  |    30     |   30    |  100.00 %   |


INFO: [FlowCfg] [scratch_path]: [chip] [/workspaces/repo/scratch/entropy_src_rng_enable/chip_earlgrey_asic-sim-vcs]

          [   legend    ]: [Q: queued, D: dispatched, P: passed, F: failed, K: killed, T: total]
00:02:59  [    build    ]: [Q: 00, D: 00, P: 01, F: 00, K: 00, T: 01] 100%
00:31:54  [     run     ]: [Q: 00, D: 00, P: 30, F: 00, K: 00, T: 30] 100%
```

Tests passed.

2022-12-08 19:36 UTC, martin-lueker commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +  assign entropy_src_rng_o.rng_enable = rng_enable_q;
> ```
> ### Test Results
> |  Stage  |                  Name                  | Tests                                    |  Max Job Runtime  |  Simulated Time  |  Passing  |  Total  |  Pass Rate  |
> |:-------:|:--------------------------------------:|:-----------------------------------------|:-----------------:|:----------------:|:---------:|:-------:|:-----------:|
> |   V2    |         chip_sw_clkmgr_jitter          | chip_sw_edn_entropy_reqs_jitter          |      23.242m      |     5.745ms      |     3     |    3    |  100.00 %   |
> |   V2    |     chip_sw_alert_handler_entropy      | chip_sw_alert_handler_entropy            |      3.084m       |     2.537ms      |     3     |    3    |  100.00 %   |
> |   V2    |          chip_sw_aes_entropy           | chip_sw_aes_entropy                      |      2.881m       |     3.528ms      |     3     |    3    |  100.00 %   |
> |   V2    |          chip_sw_kmac_entropy          | chip_sw_kmac_entropy                     |      2.821m       |     3.077ms      |     3     |    3    |  100.00 %   |
> |   V2    |    chip_sw_entropy_src_ast_rng_req     | chip_sw_entropy_src_ast_rng_req          |      3.087m       |     2.871ms      |     3     |    3    |  100.00 %   |
> |   V2    |       chip_sw_entropy_src_csrng        | chip_sw_entropy_src_csrng                |      13.077m      |     7.441ms      |     3     |    3    |  100.00 %   |
> |   V2    |  chip_sw_entropy_src_fuse_en_fw_read   | chip_sw_entropy_src_fuse_en_fw_read_test |      5.352m       |     4.843ms      |     3     |    3    |  100.00 %   |
> |   V2    | chip_sw_entropy_src_known_answer_tests | chip_sw_entropy_src_kat_test             |      2.744m       |     3.222ms      |     3     |    3    |  100.00 %   |
> |   V2    |         chip_sw_csrng_edn_cmd          | chip_sw_entropy_src_csrng                |      13.077m      |     7.441ms      |     3     |    3    |  100.00 %   |
> |   V2    |        chip_sw_edn_entropy_reqs        | chip_sw_edn_entropy_reqs                 |      23.384m      |     5.120ms      |     3     |    3    |  100.00 %   |
> |   V2    |       chip_sw_ast_sys_clk_jitter       | chip_sw_edn_entropy_reqs_jitter          |      23.242m      |     5.745ms      |     3     |    3    |  100.00 %   |
> |   V2    |           chip_sw_smoketest            | chip_sw_entropy_src_smoketest            |      5.173m       |     3.848ms      |     3     |    3    |  100.00 %   |
> |   V2    |                                        | **TOTAL**                                |                   |                  |    30     |   30    |  100.00 %   |
> |         |                                        | **TOTAL**                                |                   |                  |    30     |   30    |  100.00 %   |
> 
> 
> INFO: [FlowCfg] [scratch_path]: [chip] [/workspaces/repo/scratch/entropy_src_rng_enable/chip_earlgrey_asic-sim-vcs]
> 
>           [   legend    ]: [Q: queued, D: dispatched, P: passed, F: failed, K: killed, T: total]
> 00:02:59  [    build    ]: [Q: 00, D: 00, P: 01, F: 00, K: 00, T: 01] 100%
> 00:31:54  [     run     ]: [Q: 00, D: 00, P: 30, F: 00, K: 00, T: 30] 100%
> ```
> 
> Tests passed.
> 
> But this does not mean that the generated entropy satisfy the criteria. I do not know we have that kind of tests.

Thanks @eunchan.   I suspect any issues (if they existed) would be very rare.

2022-12-08 19:40 UTC, martin-lueker commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +  assign entropy_src_rng_o.rng_enable = rng_enable_q;
As far as the quality is concerned, checks are done to compare accepted samples the processing done in the NIST recommendations.  From that point of view I'm confident this is okay.   

I may be overly picky here, I've just spent so many hours cleaning up single-cycle DV deltas in this block (none of which are extremely important... the tests on the register statistics --not required by NIST, diagnostics only-- are far more stringent than is practically required)

2022-12-08 19:43 UTC, eunchan commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +  assign entropy_src_rng_o.rng_enable = rng_enable_q;
>  I've just spent so many hours cleaning up single-cycle DV deltas
>
I feel your pain. I also worry that and suffered that in other blocks. At least we should have a good coverage with this change.

2022-12-08 19:57 UTC, arnonsha commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +  assign entropy_src_rng_o.rng_enable = rng_enable_q;
> Well frankly, AST doesn't give a hoot about the enable signal. It's only used by DV. @arnonsha or @zi-v can probably confirm.

AST does care about this signal. it enables/disables RNG (surprise :-) )

2022-12-08 20:23 UTC, martin-lueker commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +  assign entropy_src_rng_o.rng_enable = rng_enable_q;
Oh goodness. Well I'm always delighted to learn new things.  ;)  Except in this case there may be a bigger issue here.  The IP (and DV) are treating this like a "ready" signal, one that we have been currently assuming is ignored.   For a literal enable signal, are there documented guidelines for when this should be used?

2022-12-08 20:26 UTC, martin-lueker commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +  assign entropy_src_rng_o.rng_enable = rng_enable_q;
FYI @mwbranstad.  Furthermore required behavior for this line is not clear in the documentation.

2022-12-08 20:27 UTC, martin-lueker commented on hw/ip/entropy_src/rtl/entropy_src_core.sv
> +  assign entropy_src_rng_o.rng_enable = rng_enable_q;
All: Should we make an issue to discuss this more?

2022-12-08 21:21 UTC, zi-v commented
Indeed, we only output random bits when rng_enable is asserted. This is hinted by  https://docs.opentitan.org/hw/ip/entropy_src/doc/#ptrng-hardware-interface although I must admit we could have made this drawing more explicit.
BTW, the reason we have asynchronous clock domain crossing inside the RNG is that entropy_src module clock was not known at the time we designed it and in addition, we wanted to time the bits with non-jittery clocks so we can better optimize the bit rate.

2022-12-09 15:54 UTC, martin-lueker commented
Thanks @Zi-v,
So my question to all is is: are there hard requirements (outside unit-level DV) on the behavior of this line?  When should it be enabled or disabled?  Is it purely a power saving measure for AST?  (The entropy_src IP makes no assumptions about the quality of entropy coming in).

I think we can approve this PR (it seems I'm the only holdout), but I'm really curious what the "right" way to use this line is from a top-level perspective.

2022-12-09 17:21 UTC, tjaychen commented
> Thanks @zi-v, So my question to all is is: are there hard requirements (outside unit-level DV) on the behavior of this line? When should it be enabled or disabled? Is it purely a power saving measure for AST? (The entropy_src IP makes no assumptions about the previous status when enabled, it always does its start up checks).
> 
> I think we can approve this PR (it seems I'm the only holdout), but I'm really curious what the "right" way to use this line is from a top-level perspective.

This is all part of the entropy complex enable / disable. ROM enables everything, but when we get to ROM_ext (or later), we will disable everything again as we get ready for the FIPS mode setup.  We will re-enable everything (entropy_src, csrng, edn) at that time.  This is part of the reason we've been harping on enable / disable testing, since there were a few observed corner cases.

2022-12-10 17:45 UTC, martin-lueker commented
> This is all part of the entropy complex enable / disable. ROM enables everything, but when we get to ROM_ext (or later), we will disable everything again as we get ready for the FIPS mode setup. We will re-enable everything (entropy_src, csrng, edn) at that time. This is part of the reason we've been harping on enable / disable testing, since there were a few observed corner cases.

Thanks @tjaychen.  Though with that said would be make sense to have a separate enable for AST? Or is that overkill?

2022-12-10 17:45 UTC, martin-lueker commented
> > This is all part of the entropy complex enable / disable. ROM enables everything, but when we get to ROM_ext (or later), we will disable everything again as we get ready for the FIPS mode setup. We will re-enable everything (entropy_src, csrng, edn) at that time. This is part of the reason we've been harping on enable / disable testing, since there were a few observed corner cases.
> 
> Thanks @tjaychen. Though with that said would be make sense to have a separate enable for AST? Or is that overkill?

To clarify: Something where one can disable the module, and reset it, without disabling AST.

2023-01-13 17:00 UTC, eunchan commented
@zi-v @arnonsha could you give us your opinions on this? Disconnecting the enable from entropy_src and adding a CSR field inside AST to control the RNG.

2023-01-13 21:17 UTC, tjaychen commented
@martin-lueker / @vogelpi between what @eunchan has proposed here vs a separate register, does either one have a big impact on `entropy_src` from your perspective?  I think the ast interface is probably not going to change at this point, so I feel like we can go with what @eunchan has suggested and see if there is a dv fallout (doesn't seem like there should be).

2023-01-15 06:24 UTC, zi-v commented
Having a register inside AST to control the AST enable is not a good idea mainly because the AST register interface is not meant to be controlled during runtime. It is only meant to be used for power-up configuration. In addition, as @tjaychen mentioned, changing the AST interface at this stage is a lot of pain, we need to have a very good reason to do so.

I think it is OK keep AST RNG enable and ENTROPY_SRC enable tied together because ...
If there's an entropy failure which require restart we'll anyway need to restart both.
If there's a bug in one of AST RNG or ENTROPY_SRC which require a restart, the inhibit restart of the other module will not cost so much in time delay.
Spliting the AST and ENTROPY RNG enable control bits at the open source will probably be OK for Nuvoton (need to confirm with @sha-ron if we want to choose this path), but will add DV load at the open source side which I am not sure is justified at this stage.

2023-01-16 15:01 UTC, vogelpi commented
I understand the concerns of @martin-lueker and @zi-v and I think this PR can be extended just a little bit to reduce additional DV churn considerably.

As far as I understand, the main issue with this PR is that it creates one additional delay cycle on the `entropy_src_rng_o.rng_enable` signal which AST and the entropy_src block-level DV framework uses to decide when to push data. Now, this signal depends on three signals:
- `es_enable_fo` and `es_delayed_enable` probably both change rarely. Seeing the enable going high one clock cycle later upon enabling shouldn't be an issue. Also, seeing the enable go low one cycle later shouldn't be a big issue for DV. It means entropy_src might drop 1 data beat from AST around enabling/disabling.
- `sfifo_esrng_not_full` is the most critical signal because this one will frequently change between 0 and 1. However, this is very easy to fix. We can just take `depth_o` and `wvalid_i` of this FIFO to know 1 cycle ahead when the FIFO is going to be full. This is the change I suggest to include in this PR.

If we think also the delay on the enable going low is a problem (handled by `es_delayed_enable`) and we don't want to handle this in DV only, also this can be fixed in the RTL I believe. It will mainly require us to pre-compute some `_fifo_not_empty` signals to make `extend_enable` inside `entropy_src_delay_enable.sv` go low one clock cycle earlier. WDYT?

2023-01-17 17:40 UTC, sha-ron commented
For AST DV the delay is not an issue.

2023-01-18 16:33 UTC, martin-lueker approved these changes
As per my last comment: I'm no longer concerned about DV issue.

2023-01-18 16:34 UTC, tjaychen approved these changes

2023-01-18 18:56 UTC, merged