[ci] Disable the Verilator weak straps tests in CI
lowRISC/opentitan pull request #16829
Opened 2022-12-14 19:05 UTC by milesdai

The `sw_strap_value_sim_verilator` test appears to be timing out in CI periodically but passes fine locally. We will disable this test for now in CI.

2022-12-14 19:10 UTC, alphan approved these changes
LGTM, thanks @milesdai! Can we add this to the nightly runs when we have them as we discussed offline?

2022-12-14 19:11 UTC, drewmacrae requested changes
Can you open and link an issue that describes the problem

2022-12-14 19:22 UTC, milesdai commented
I've opened #16831 to address both comments.

2022-12-14 20:05 UTC, drewmacrae reviewed
I'd be inclined to keep the test and keep observing it to see if we can better understand what's happening, reproduce it locally and fix it.

2022-12-15 16:50 UTC, cfrantz approved these changes

2022-12-15 16:51 UTC, merged