[ibex] Change ichache scramble key assertion
lowRISC/opentitan pull request #17019
Opened 2023-01-10 16:25 UTC by sha-ron

Signed-off-by: Sharon Topaz <sharon.topaz@nuvoton.com>

Changing the assertion not to check individual bank ports, but the key register connected to all these banks.
This due to the issues some DFT tools have with generate loops.

2023-01-10 16:27 UTC, tjaychen commented on hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
> +    )
@GregAC @vogelpi 
just to elaborate a bit, @msfschaffner and others pointed out that after dft insertion, the tools can sometimes change the path of the memories.  So the generate loop's path reference make this a bit unfriendly,

2023-01-10 20:37 UTC, sha-ron commented on hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
> +
Sorry, done.

2023-01-10 20:38 UTC, sha-ron commented on hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
> +
Done.

2023-01-19 14:32 UTC, andreaskurth commented on hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
> +    )
Hmm, I knew that DFT tools could make changes related to macros (and FFs), but the paths currently used in the assertions point to the `key_i` input of the `prim_ram_1p_scr` RTL module. Is that already problematic? Or is the problem related to the generate statements?

The reason I'm asking is that the proposed change makes this assertion much less useful for ensuring that the received scramble key correctly propagates to the module that implements the scrambling.

2023-01-19 14:37 UTC, andreaskurth requested changes
Thanks for flagging this. I think we should resolve this without reducing the checks that the assertions bring -- if possible -- as described [in this comment](https://github.com/lowRISC/opentitan/pull/17019#discussion_r1081347733).

2023-01-19 18:30 UTC, msfschaffner commented on hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
> +    )
The problem is that the tools unroll the generate loops and change the block label names, which causes the path in the assertion to not be correct anymore after mbist insertion.

Hence, just checking the 0-th way would not work either. But, your second suggestion to put the assertion into the loop body should work. 

We could basically split this assertion into two and still retain the same coverage: the assertion that @sha-ron  is proposing here, and an assertion inside the loop body that checks whether the module inputs are correctly connected to the input of the  `prim_ram_1p_scr` module.

2023-02-01 16:52 UTC, andreaskurth commented
Closing this because the alternative implementation in #17155 has been merged.

2023-02-01 16:52 UTC, closed without merging