[site] Added a styled 404 page
lowRISC/opentitan pull request #17705
Opened 2023-03-27 07:29 UTC by HU90m

A slightly prettier and more informative 404 page:

![Screenshot from 2023-03-27 08-19-43](https://user-images.githubusercontent.com/45573837/227870639-3b0736ce-4131-44ff-8401-28bc05c2c4bf.png)

Parts of the index that would be common to both it and the 404 page were separated out into Hugo partials.

2023-03-28 10:17 UTC, jwnrt commented
Thanks for working on this! The old `404` message wasn't very helpful

I've tried testing this locally unsuccessfully:

* `hugo serve` from `site/landing` shows me `404 page not found` at `http://localhost:1313/foo`
* `./util/site/build-docs.sh serve` shows me a longer message, maybe from the python server? See below.

```
Error response

Error code: 404

Message: File not found.

Error code explanation: HTTPStatus.NOT_FOUND - Nothing matches the given URI.
```

Am I doing something wrong here?

2023-03-28 10:22 UTC, jwnrt requested changes
Code looks fine, but I haven't tested it locally yet

Just some comments on the preamble/postamble stuff

2023-03-28 10:22 UTC, jwnrt commented on site/landing/layouts/partials/preamble.html
Is this the rainbow background?

I wonder why it's defined inline, maybe we should move this out to an `.svg` and use `background-image`?

2023-03-28 20:42 UTC, HU90m commented on site/landing/layouts/partials/preamble.html
Yeah, I thought this was strange as well.

Now that I am leaving `index.html` untouched (and not moving this into `preamble.html`), I think I will leave this be for now.

2023-03-28 20:49 UTC, HU90m commented on site/landing/layouts/partials/postamble.html
This is a great suggestion. After closer inspection, turns out very little from index is needed to keep the header and footer working, so I've left `index.html` untouched and removed the preamble & postamble partials.

2023-03-29 08:57 UTC, jwnrt approved these changes
Good work, looks nice.

`localhost:1313/404.html` works, so I'll trust that our server redirects to that page for 404s

2023-03-29 10:08 UTC, hcallahan-lowrisc approved these changes
@jwnrt Yes the hosting system will just serve a page called 404.html at the root by default. So this should work when deployed. 
LGTM!

2023-03-29 10:13 UTC, jwnrt commented on site/landing/layouts/partials/preamble.html
Update: this was actually the icons for the "transparent... high quality... flexible..." section, they're just defined at the top for some reason.

2023-03-29 10:50 UTC, HU90m commented
> Good work, looks nice.
> 
> `localhost:1313/404.html` works, so I'll trust that our server redirects to that page for 404s

Ah sorry, I never replied to https://github.com/lowRISC/opentitan/pull/17705#issuecomment-1486591531 . As Harry has said, you are spot on.

2023-03-29 12:21 UTC, andreaskurth approved these changes
LGTM, thanks @HU90m!

2023-03-29 12:21 UTC, merged