[spit_host,dv,cleanup] Cleanup and add comments to dv code.
lowRISC/opentitan pull request #18851
Opened 2023-06-08 07:32 UTC by hcallahan-lowrisc

[IGNORE FIRST 4 COMMITS, WILL BE REBASED AWAY WHEN #18850 IS MERGED]

2023-06-12 11:21 UTC, rswarbrick approved these changes
Some nitty questions, but this looks very sensible to me.

2023-06-12 11:21 UTC, rswarbrick commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
> +      `uvm_info(`gfn, $sformatf("Starting num_runs %0d/%0d now!", i, num_runs), UVM_LOW)
Total nit, but do you really want "num_runs" here? (I would have thought that you want something like "Starting run 2/3" ?

2023-06-12 11:21 UTC, rswarbrick commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv
> +          send_tl_access(.addr(align_addr), .data(data), .write(write),
As a follow-up, I wonder whether we should refactor the argument name to something like "enable_write" or something. I think the two "write" words on this line mean something slightly different! :-)

2023-06-13 09:49 UTC, crteja requested changes
LGTM with a minor nit

2023-06-13 09:49 UTC, crteja commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv
> +    typedef enum bit {write = 1'b1, read = 1'b0} rdwr_e;
The literal (`write` and `read`) can be confused with variable names. Please change enum values to either camelcase or all caps ([enumerations](https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#enumerations))

2023-06-13 13:11 UTC, hcallahan-lowrisc commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv
> +    typedef enum bit {write = 1'b1, read = 1'b0} rdwr_e;
Changed to use all caps enumerations, thanks @crteja

2023-06-13 13:11 UTC, hcallahan-lowrisc commented on hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
> +      `uvm_info(`gfn, $sformatf("Starting num_runs %0d/%0d now!", i, num_runs), UVM_LOW)
Done! (will get merged as part of https://github.com/lowRISC/opentitan/pull/18850)

2023-06-14 13:43 UTC, hcallahan-lowrisc commented
Rebased to remove commits from https://github.com/lowRISC/opentitan/pull/18850

2023-06-15 07:10 UTC, merged