WIP: [i2c,dv] Various timing fixes for the agent and CDC
lowRISC/opentitan pull request #19030
Opened 2023-06-23 05:22 UTC by a-will

This is kind of a grab bag of timing and other fixes, where each individual commit addresses something different.

There are a couple other changes I haven't yet pushed up, but this set should eliminate errors for target mode tests (except I haven't done the target_stress_all* tests yet).

### Test Results
|  Stage  |         Name         | Tests                     |  Max Job Runtime  |  Simulated Time  |  Passing  |  Total  |  Pass Rate  |
|:-------:|:--------------------:|:--------------------------|:-----------------:|:----------------:|:---------:|:-------:|:-----------:|
|   V1    |     target_smoke     | i2c_target_smoke          |      19.100s      |     9.073ms      |    50     |   50    |  100.00 %   |
|   V1    |                      | **TOTAL**                 |                   |                  |    50     |   50    |  100.00 %   |
|   V2    |  target_fifo_empty   | i2c_target_stress_rd      |      33.710s      |     3.805ms      |    50     |   50    |  100.00 %   |
|         |                      | i2c_target_intr_smoke     |      2.710s       |     2.285ms      |    50     |   50    |  100.00 %   |
|   V2    |   target_fifo_full   | i2c_target_stress_rd      |      33.710s      |     3.805ms      |    50     |   50    |  100.00 %   |
|         |                      | i2c_target_intr_stress_wr |      35.400s      |     64.277ms     |    50     |   50    |  100.00 %   |
|         |                      | i2c_target_stress_wr      |      47.100s      |     66.840ms     |    50     |   50    |  100.00 %   |
|   V2    |    target_timeout    | i2c_target_timeout        |      2.740s       |     11.990ms     |    49     |   50    |   98.00 %   |
|   V2    | target_clock_stretch | i2c_target_stretch        |      9.745m       |     46.677ms     |    50     |   50    |  100.00 %   |
|   V2    |                      | **TOTAL**                 |                   |                  |    299    |   300   |   99.67 %   |
|         |                      | **TOTAL**                 |                   |                  |    349    |   350   |   99.71 %   |

### Test Results
|  Stage  |         Name         | Tests                     |  Max Job Runtime  |  Simulated Time  |  Passing  |  Total  |  Pass Rate  |
|:-------:|:--------------------:|:--------------------------|:-----------------:|:----------------:|:---------:|:-------:|:-----------:|
|   V2    |  target_error_intr   | i2c_target_unexp_stop     |      3.070s       |     18.028ms     |    50     |   50    |  100.00 %   |
|   V2    |    target_glitch     | i2c_target_glitch         |      1.460s       |     5.721ms      |     2     |    2    |  100.00 %   |
|   V2    |     target_perf      | i2c_target_perf           |      1.910s       |    914.762us     |    50     |   50    |  100.00 %   |
|   V2    | target_fifo_overflow | i2c_target_tx_ovf         |      13.880s      |     9.357ms      |    50     |   50    |  100.00 %   |
|   V2    |  target_fifo_reset   | i2c_target_fifo_reset_acq |      12.460s      |     10.105ms     |    50     |   50    |  100.00 %   |
|         |                      | i2c_target_fifo_reset_tx  |      12.010s      |     10.069ms     |    50     |   50    |  100.00 %   |
|   V2    |     bad_address      | i2c_target_bad_addr       |      2.200s       |     7.752ms      |    50     |   50    |  100.00 %   |
|   V2    |  target_mode_glitch  | i2c_target_hrst           |      1.070s       |     3.139ms      |    50     |   50    |  100.00 %   |
|   V2    |                      | **TOTAL**                 |                   |                  |    352    |   352   |  100.00 %   |
|         |                      | **TOTAL**                 |                   |                  |    352    |   352   |  100.00 %   |

The commit that fixes up HostStop's relationship with the SCL drive thread finished off i2c_target_timeout, but I haven't done the full run of all tests with that commit in yet.

On the host side, I'm still tweaking the constraints solver for i2c_host_perf. The two failure modes are unsolvable constraints and "DUT not working as expected" because the measured SCL period is significantly longer than expected (likely fixable by including the extra 3 cycles for thigh + double-counted t_f). The current commit is held back, but this is where it stands with that WIP commit:

### Test Results
|  Stage  |        Name         | Tests                    |  Max Job Runtime  |  Simulated Time  |  Passing  |  Total  |  Pass Rate  |
|:-------:|:-------------------:|:-------------------------|:-----------------:|:----------------:|:---------:|:-------:|:-----------:|
|   V1    |     host_smoke      | i2c_host_smoke           |      58.920s      |     12.812ms     |    50     |   50    |  100.00 %   |
|   V1    |                     | **TOTAL**                |                   |                  |    50     |   50    |  100.00 %   |
|   V2    |   host_error_intr   | i2c_host_error_intr      |      0.810s       |     46.466us     |    50     |   50    |  100.00 %   |
|   V2    |      host_perf      | i2c_host_perf            |      15.904m      |    143.365ms     |    32     |   50    |   64.00 %   |
|   V2    |    host_override    | i2c_host_override        |      0.280s       |     14.757us     |    50     |   50    |  100.00 %   |
|   V2    | host_fifo_watermark | i2c_host_fifo_watermark  |      2.056m       |     13.564ms     |    50     |   50    |  100.00 %   |
|   V2    | host_fifo_overflow  | i2c_host_fifo_overflow   |      2.506m       |     6.824ms      |    50     |   50    |  100.00 %   |
|   V2    |   host_fifo_reset   | i2c_host_fifo_fmt_empty  |      14.060s      |    741.621us     |    50     |   50    |  100.00 %   |
|         |                     | i2c_host_fifo_reset_rx   |      5.320s       |    267.579us     |    50     |   50    |  100.00 %   |
|         |                     | i2c_host_fifo_reset_fmt  |      0.430s       |     1.086ms      |    50     |   50    |  100.00 %   |
|   V2    |   host_fifo_full    | i2c_host_fifo_full       |      1.271m       |     47.803ms     |    50     |   50    |  100.00 %   |
|   V2    |    host_timeout     | i2c_host_stretch_timeout |      20.450s      |     3.163ms      |    50     |   50    |  100.00 %   |
|   V2    | host_rx_oversample  | i2c_host_rx_oversample   |      56.250s      |     5.548ms      |    50     |   50    |  100.00 %   |
|   V2    |                     | **TOTAL**                |                   |                  |    532    |   550   |   96.73 %   |
|         |                     | **TOTAL**                |                   |                  |    582    |   600   |   97.00 %   |

2023-06-23 05:23 UTC, a-will commented
CC @crteja @jdonjdon

2023-06-23 05:28 UTC, a-will commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_i2c_device_tx_rx_vseq.sv
> +    cfg.m_i2c_agent_cfgs[i2c_idx].timing_cfg.tSetupStop = tSetupBit;
Oops, this is too fast. I mistakenly applied the change here (before fixing up HostStop on the driver side)

2023-06-23 09:23 UTC, crteja commented on hw/dv/sv/i2c_agent/i2c_if.sv
> +    wait(!scl_i);
This is much better than waiting for time and accidentally toggling SDA.

2023-06-23 09:23 UTC, crteja commented on hw/dv/sv/i2c_agent/i2c_if.sv
> +    wait(!scl_i);
@a-will  Thanks for the changes. Overall these look good. Does this PR also address https://github.com/lowRISC/opentitan/issues/18985 ?

2023-06-23 15:11 UTC, a-will commented on hw/dv/sv/i2c_agent/i2c_if.sv
> +    wait(!scl_i);
> @a-will Thanks for the changes. Overall these look good. Does this PR also address #18985 and #19010 ?

Yes. For #19010, it really just applies your changes on top of my refactoring, with me explaining the original timing a bit better than
```
tClockLow needs to be "slightly" shorter than the actual clock low period
```

2023-06-23 23:35 UTC, a-will commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_i2c_device_tx_rx_vseq.sv
> +    cfg.m_i2c_agent_cfgs[i2c_idx].timing_cfg.tSetupStop = tSetupBit;
This belonged on tClockStop. Fixed.

2023-06-24 04:40 UTC, a-will commented on hw/ip/i2c/dv/env/seq_lib/i2c_host_perf_vseq.sv
> +    tlow < 2*scl_period - t_r - t_f - thigh;
I added this line to try to capture the prior code's speed additions, but I feel like we're deviating from the test plan here. The host_perf testpoint claims we should be targeting max throughput.

Shall I adjust this to pick the minimums and target max throughput again? Right now, the tendency is to be much closer to the half frequency value.

2023-06-24 04:42 UTC, a-will commented
Updated the constraints and period tracking for i2c_host_perf to match how the IP tracks time, with a TODO to fix those alongside #18492 .

In a regression, all 50 seeds of i2c_host_perf now pass.

2023-06-24 04:44 UTC, a-will commented
@jdonjdon @crteja : This is a bunch of things in one PR. Feel free to tell me you'd like commits split off, dropped, changed, etc. Thanks! :smile:

2023-06-24 04:46 UTC, a-will commented on hw/dv/sv/i2c_agent/i2c_agent_cfg.sv
> +  bit stretch_after_ack = 0;
FYI: This feature isn't actually exercised yet.

2023-06-24 18:21 UTC, jdonjdon approved these changes
LGTM

2023-06-26 05:44 UTC, a-will commented on hw/dv/sv/i2c_agent/i2c_if.sv
> +    wait(scl_i === 1'b1);
Until this latest push, I had forgotten to _always_ have the host agent wait for SCL to actually rise after turning off its driver. With this, I am getting a 100% pass rate for i2c_target_stress_all as well.

2023-06-26 05:47 UTC, a-will commented
I've been doing tests piecemeal and still need to do a full regression. If the merged progressive results reflect the full regression, we should be back to 100% for V2, now with CDC instrumented. (notwithstanding any runtime timeout adjustments needed -- i2c_host_stress_all had at least one case for my simulation environment)

2023-06-26 08:28 UTC, crteja commented on hw/ip/i2c/dv/env/seq_lib/i2c_host_perf_vseq.sv
> +    tlow < 2*scl_period - t_r - t_f - thigh;
> Shall I adjust this to pick the minimums and target max throughput again? Right now, the tendency is to be much closer to the half frequency value.

Yes, the intent of perf test case is to check if the the programmed timing registers yield the desired throughput on the I2C bus.

2023-06-26 09:14 UTC, crteja requested changes

2023-06-26 18:46 UTC, a-will commented on hw/top_earlgrey/dv/env/seq_lib/chip_sw_i2c_device_tx_rx_vseq.sv
> +
Done

2023-06-26 18:51 UTC, crteja commented
@a-will , changes look good to me. Were you able to run a full regression?

2023-06-26 19:03 UTC, a-will commented on hw/ip/i2c/dv/env/seq_lib/i2c_host_perf_vseq.sv
> +    tlow < 2*scl_period - t_r - t_f - thigh;
Done, with some qualifications. There's still a little wiggle room, since we allow `t_r` and `t_f` to randomly choose values that are _less_ than the requirements in the spec.

I'd quibble a little with the term `desired throughput`, since there are a number of structural reasons that we won't hit the nominal max frequency for each mode. With a 9 MHz peripheral clock, for example, targeting FastPlus would only yield 643 kHz (all critical values would round up to the next cycle: tlow=5, thigh=3, t_r=2, t_f=2), and that's without accounting for synchronizers in the round-trip path. But I think I get what you mean. ;)

2023-06-26 19:08 UTC, a-will commented
> @a-will , changes look good to me. Were you able to run a full regression?

Only just started. It'll be awhile...

2023-06-26 19:09 UTC, crteja commented
> > @a-will , changes look good to me. Were you able to run a full regression?
> 
> Only just started. It'll be awhile...

Ok. I'm approving this change. Please merge after the regression run.

2023-06-26 19:09 UTC, crteja approved these changes

2023-06-26 23:15 UTC, a-will commented
## I2C Simulation Results
### Monday June 26 2023 19:05:36 UTC
### GitHub Revision: [`ded2c9e07`](https://github.com/lowrisc/opentitan/tree/ded2c9e07bb64fffa2554b78d81bfc050df9e416)
### Branch: i2c-dv-timing-fixes
### [Testplan](https://docs.opentitan.org/hw/ip/i2c/doc/dv/#testplan)
### Simulator: VCS

### Test Results
|  Stage  |                   Name                    | Tests                                 |  Max Job Runtime  |  Simulated Time  |  Passing  |  Total  |  Pass Rate  |
|:-------:|:-----------------------------------------:|:--------------------------------------|:-----------------:|:----------------:|:---------:|:-------:|:-----------:|
|   V1    |                host_smoke                 | i2c_host_smoke                        |      59.810s      |     5.746ms      |    50     |   50    |  100.00 %   |
|   V1    |               target_smoke                | i2c_target_smoke                      |      20.460s      |     2.226ms      |    50     |   50    |  100.00 %   |
|   V1    |               csr_hw_reset                | i2c_csr_hw_reset                      |      0.260s       |     70.339us     |     5     |    5    |  100.00 %   |
|   V1    |                  csr_rw                   | i2c_csr_rw                            |      0.280s       |     30.526us     |    20     |   20    |  100.00 %   |
|   V1    |               csr_bit_bash                | i2c_csr_bit_bash                      |      1.760s       |    418.270us     |     5     |    5    |  100.00 %   |
|   V1    |               csr_aliasing                | i2c_csr_aliasing                      |      0.520s       |     59.830us     |     5     |    5    |  100.00 %   |
|   V1    |        csr_mem_rw_with_rand_reset         | i2c_csr_mem_rw_with_rand_reset        |      0.700s       |     64.705us     |    20     |   20    |  100.00 %   |
|   V1    | regwen_csr_and_corresponding_lockable_csr | i2c_csr_rw                            |      0.280s       |     30.526us     |    20     |   20    |  100.00 %   |
|         |                                           | i2c_csr_aliasing                      |      0.520s       |     59.830us     |     5     |    5    |  100.00 %   |
|   V1    |                                           | **TOTAL**                             |                   |                  |    155    |   155   |  100.00 %   |
|   V2    |              host_error_intr              | i2c_host_error_intr                   |      0.780s       |    163.197us     |    50     |   50    |  100.00 %   |
|   V2    |              host_stress_all              | i2c_host_stress_all                   |      11.929m      |     35.497ms     |    50     |   50    |  100.00 %   |
|   V2    |                 host_perf                 | i2c_host_perf                         |      15.182m      |     51.311ms     |    50     |   50    |  100.00 %   |
|   V2    |               host_override               | i2c_host_override                     |      0.270s       |     19.454us     |    50     |   50    |  100.00 %   |
|   V2    |            host_fifo_watermark            | i2c_host_fifo_watermark               |      2.136m       |     6.433ms      |    50     |   50    |  100.00 %   |
|   V2    |            host_fifo_overflow             | i2c_host_fifo_overflow                |      2.354m       |     27.521ms     |    50     |   50    |  100.00 %   |
|   V2    |              host_fifo_reset              | i2c_host_fifo_reset_fmt               |      0.450s       |    970.383us     |    50     |   50    |  100.00 %   |
|         |                                           | i2c_host_fifo_fmt_empty               |      15.010s      |    842.681us     |    50     |   50    |  100.00 %   |
|         |                                           | i2c_host_fifo_reset_rx                |      5.610s       |     1.150ms      |    50     |   50    |  100.00 %   |
|   V2    |              host_fifo_full               | i2c_host_fifo_full                    |      1.095m       |     3.458ms      |    50     |   50    |  100.00 %   |
|   V2    |               host_timeout                | i2c_host_stretch_timeout              |      18.570s      |     7.898ms      |    50     |   50    |  100.00 %   |
|   V2    |            host_rx_oversample             | i2c_host_rx_oversample                |      1.027m       |     5.951ms      |    50     |   50    |  100.00 %   |
|   V2    |           i2c_host_mode_toggle            | i2c_host_mode_toggle                  |      54.190s      |     10.197ms     |    50     |   50    |  100.00 %   |
|   V2    |             target_error_intr             | i2c_target_unexp_stop                 |      3.070s       |     2.717ms      |    50     |   50    |  100.00 %   |
|   V2    |               target_glitch               | i2c_target_glitch                     |      1.320s       |     4.389ms      |     2     |    2    |  100.00 %   |
|   V2    |             target_stress_all             | i2c_target_stress_all                 |      56.450s      |     83.258ms     |    50     |   50    |  100.00 %   |
|   V2    |                target_perf                | i2c_target_perf                       |      1.810s       |     5.021ms      |    50     |   50    |  100.00 %   |
|   V2    |           target_fifo_overflow            | i2c_target_tx_ovf                     |      13.550s      |     5.236ms      |    50     |   50    |  100.00 %   |
|   V2    |             target_fifo_empty             | i2c_target_stress_rd                  |      34.780s      |     2.272ms      |    50     |   50    |  100.00 %   |
|         |                                           | i2c_target_intr_smoke                 |      2.600s       |     2.384ms      |    50     |   50    |  100.00 %   |
|   V2    |             target_fifo_reset             | i2c_target_fifo_reset_acq             |      11.170s      |     10.073ms     |    50     |   50    |  100.00 %   |
|         |                                           | i2c_target_fifo_reset_tx              |      11.440s      |     10.080ms     |    50     |   50    |  100.00 %   |
|   V2    |             target_fifo_full              | i2c_target_stress_wr                  |      54.970s      |     79.928ms     |    50     |   50    |  100.00 %   |
|         |                                           | i2c_target_stress_rd                  |      34.780s      |     2.272ms      |    50     |   50    |  100.00 %   |
|         |                                           | i2c_target_intr_stress_wr             |      29.010s      |     53.353ms     |    50     |   50    |  100.00 %   |
|   V2    |              target_timeout               | i2c_target_timeout                    |      2.460s       |     4.416ms      |    50     |   50    |  100.00 %   |
|   V2    |           target_clock_stretch            | i2c_target_stretch                    |      7.005m       |     35.943ms     |    50     |   50    |  100.00 %   |
|   V2    |                bad_address                | i2c_target_bad_addr                   |      2.340s       |     2.059ms      |    49     |   50    |   98.00 %   |
|   V2    |            target_mode_glitch             | i2c_target_hrst                       |      1.110s       |    770.065us     |    50     |   50    |  100.00 %   |
|   V2    |                alert_test                 | i2c_alert_test                        |      0.240s       |     91.502us     |    50     |   50    |  100.00 %   |
|   V2    |                 intr_test                 | i2c_intr_test                         |      0.250s       |     45.142us     |    50     |   50    |  100.00 %   |
|   V2    |           tl_d_oob_addr_access            | i2c_tl_errors                         |      1.000s       |     89.924us     |    20     |   20    |  100.00 %   |
|   V2    |            tl_d_illegal_access            | i2c_tl_errors                         |      1.000s       |     89.924us     |    20     |   20     [...]

2023-06-26 23:56 UTC, a-will commented
For the one i2c_target_bad_addr failure above, the run time was much longer than the timeout (currently, 20_000_000 ns). After extending, it passes:

### Test Results
|  Stage  |    Name     | Tests               |  Max Job Runtime  |  Simulated Time  |  Passing  |  Total  |  Pass Rate  |
|:-------:|:-----------:|:--------------------|:-----------------:|:----------------:|:---------:|:-------:|:-----------:|
|   V2    | bad_address | i2c_target_bad_addr |      2.130s       |     38.444ms     |     1     |    1    |  100.00 %   |
|   V2    |             | **TOTAL**           |                   |                  |     1     |    1    |  100.00 %   |
|         |             | **TOTAL**           |                   |                  |     1     |    1    |  100.00 %   |

2023-06-27 00:20 UTC, a-will commented
In the one failure of its kind, `i2c_same_csr_outstanding` appears to be playing with the pin overrides, which causes the IP to violate the SCL glitch timing assertion. When the OVRD CSR is excluded from write checks, the test passes.

I'm going to balk on including yet another change here, but we should fix up the CSR exclusions in a subsequent PR.

That covers the failures from this regression run. Overall, we see significant improvement. Merging now :)

2023-06-27 00:20 UTC, merged