[alert_handler] Convert theory of operation to template
lowRISC/opentitan pull request #19157
Opened 2023-07-10 18:28 UTC by a-will

The theory of operation document referenced a particular instance's parameters in a table. Change the table header to not explicitly refer to Earl Grey and populate some of the values from template parameters.

Note: The conversion to Mako template caused lines beginning with `#` to become comments, so I have changed the syntax to use the HTML variant.

2023-07-10 23:46 UTC, a-will commented
This was mostly motivated by a multi-top annoyance, where the new top still had Earl Grey references.

2023-07-11 08:41 UTC, hcallahan-lowrisc requested changes
Table changes LGTM.

For the headings, you can use the trick in https://github.com/lowRISC/opentitan/pull/3458

2023-07-11 12:37 UTC, msfschaffner commented
We may have to pull in the top-name into IPgen in the future to uniquify generated IPs via a pre- or suffix (e.g. `top_earlgrey_alert_handler`, and that would allow us to create top-specific documentation in a somewhat more convenient way.

For now however I think this is perfectly fine.

2023-07-11 12:38 UTC, msfschaffner approved these changes
LGTM (modulo @hcallahan-lowrisc's suggestion)!

2023-07-11 17:26 UTC, a-will commented
> Table changes LGTM.
> 
> For the headings, you can use the trick in #3458
> 
> Thanks!

I don't see how wrapping the Markdown header shorthand in a <%text> Mako tag is any better than the unadulterated HTML / Markdown header tag, haha. But if that's the preference, it's no problem!

2023-07-11 17:31 UTC, a-will commented
> > Table changes LGTM.
> > For the headings, you can use the trick in #3458
> > Thanks!
> 
> I don't see how wrapping the Markdown header shorthand in a <%text> Mako tag is any better than the unadulterated HTML / Markdown header tag, haha. But if that's the preference, it's no problem!

Ah, it does minimize the diff for the generated core doc, though. :)

2023-07-11 20:46 UTC, merged