[util,doc] Add codeblock support to CMDGEN
lowRISC/opentitan pull request #19301
Opened 2023-07-27 12:44 UTC by hcallahan-lowrisc

Since CMDGEN currently uses HTML-comments, if you wrap these comments inside a markdown codeblock to gain formatting for the result of your command, the HTML comments will also be rendered in the codeblock.

This PR adds an optional argument mode to CMDGEN to insert the codeblocks for you, only this time inside the HTML braces.
Currently, if you malform the optional arguments, the errors aren't very nice. This could be improved with this implementation.

As a demonstrator, replace the hardcoded content of the ipgen.py tool in its README with the CMDGEN-generated content. Use the 'console' formatter to clearly show that we are printing CLI output here.

2023-07-28 09:07 UTC, HU90m requested changes

2023-07-28 09:07 UTC, HU90m commented on util/cmdgen.py
> +        res = subprocess.run(" ".join(cmd_args.cmd), shell=True, capture_output=True)
```suggestion
        res = subprocess.run(" ".join(cmd_args.cmd), shell=True, capture_output=True , env={"COLUMNS": "80"})
```

Makes slightly more deterministic

2023-08-29 09:51 UTC, hcallahan-lowrisc commented
As part of this PR, I noticed that the output from python's argparse changes at some point between 3.8 and 3.12, with the string "optional arguments" changing to "options". This is a non-functional change, but if you run `./util/cmdgen.py --update` with a newer version of python than is used in CI, it will change the content, and if you commit it will then fail the CI check.

2023-08-29 16:01 UTC, hcallahan-lowrisc commented
@jwnrt

2023-08-29 16:12 UTC, nbdd0121 commented
Since CMDGEN runs shell, can we do things more akin to Unix tool philosophy and create a script (`codewrap.py` or `codewrap.sh`) and then pipe the output to it? E.g.

```markdown
<!-- BEGIN CMDGEN util/ipgen.py generate --help | util/codewrap.py --type console -->
```

2023-08-29 16:16 UTC, hcallahan-lowrisc commented
> 

Yeah I like this more. Thanks for the idea. We should definitely document the cmdgen tools with some examples of solving common problems (such as this), so a contributor can just copy-paste a solution without too much thought.

2023-08-29 16:19 UTC, hcallahan-lowrisc commented
We should also consider if stdout/stderr handling if we are using pipes in a CMDGEN invocation

2023-08-29 16:20 UTC, nbdd0121 commented
Or we could just do
```markdown
<!-- BEGIN CMDGEN echo '```console`' && util/ipgen.py generate --help && echo '```' -->
```

2023-08-29 16:26 UTC, hcallahan-lowrisc commented
> Or we could just do
> 
> ```
> <!-- BEGIN CMDGEN echo '```console' && util/ipgen.py generate --help && echo '```' -->
> ```

IMO this is ugly, but will hear arguments

2023-08-31 10:45 UTC, jwnrt commented
> IMO this is ugly, but will hear arguments

My view is this isn't very pretty, but I don't think it's worth adding the shorthand flag to cmdgen to avoid

2026-04-20 19:04 UTC, rswarbrick commented
Hi @hcallahan-lowrisc! Is this PR something that should be resurrected? If not, should it be closed?

2026-04-20 21:37 UTC, hcallahan-lowrisc commented
Closing as it's not really that important, but could be brought back in the future as a cleanup.

2026-04-20 21:37 UTC, closed without merging