[opentitantool] Avoid required --help argument
lowRISC/opentitan pull request #19400
Opened 2023-08-09 20:48 UTC by jesultra

A few subcommands used a `--hexdata` option with the short form `-h`, conflicting with standard `-h` for `--help`.  The tpm.rs file used `-d` as the short form of `--hexdata` in some places.

This PR standardizes on `-d` as the short form of `--hexdata`, eliminating the conflict with build in help.  The immediate need for this CL is that somehow, the explicit declarations of long-form only `--help` cases errors about "Required argument: help".  And rather than figuring our how to properly declare `--help` as optional, I think it makes sense to standardize on a short form that does not conflict with `-h`.

2023-08-09 23:16 UTC, nbdd0121 commented
I digged into clap's expansion, and it seems that in the code generated by the derive macro, when trying to get value from matches, it does not care about whether `required` is true or not (it's indeed false in this case, because `bool` implies takes_value = false).

The fix without changing the command name is actually to use `help: ()` instead of `help: bool`:
```diff
     // `disable_help_flag` disable both short and long help flags. Add long help back.
     #[arg(long, action = clap::ArgAction::Help, help = "Print help")]
-    help: bool,
+    help: (),
```

That said, if we are allowed to change the CLI, then I'd be more than happy to get rid of the horrible `disable_help_flag` hacks!

2023-08-09 23:18 UTC, nbdd0121 requested changes
In `spi.rs`, there is also a `SpiRead` which has a `--hexdump (-h)` that conflicts with help.

2023-08-10 22:53 UTC, jesultra commented
Thanks for pointing out `SpiRead`.  I tried that as well and found that currently, it too fails with `error: The following required argument was not provided: help`.

I have removed the short form of `--hexdata` on `spi read`, to avoid the conflict with `-h` for `--help`.

I do not think it is a problem to change the short forms of the flags.  I will let Chris chime in.

2023-08-10 23:37 UTC, nbdd0121 approved these changes
LGTM if command line change approved

2023-08-11 17:28 UTC, cfrantz approved these changes

2023-08-11 17:28 UTC, merged