Rv dm cmderr
lowRISC/opentitan pull request #19458
Opened 2023-08-16 05:59 UTC by Musawir745

I have added a new test sequence of RV_DM please review it.

2023-08-16 15:19 UTC, jdonjdon reviewed
Review is in progress, please wait for #19391 is merged

2023-08-17 14:59 UTC, jdonjdon requested changes
Please see the comment

2023-08-17 14:59 UTC, jdonjdon commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_exception_vseq.sv
> +  task body();
After rebase, you can reuse write_chk (from #19391) like
write_chk(.ptr(tl_mem_ral.exception), .cmderr(3), .command(32'h00231000));

2023-08-23 13:21 UTC, jdonjdon commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_exception_vseq.sv
> +    repeat ($urandom_range(1, 10)) begin
`write_chk` itself has repeat ($random_range(1, 10))
Do you need an extra repeat?

2023-08-24 04:16 UTC, Musawir745 commented
I inadvertently included an additional test sequence in this pull request, which hasn't undergone review yet. I intend to generate a new pull request specifically for this test case from a separate branch.

2023-08-24 04:16 UTC, closed without merging