[usbdev/doc] Documentation updates
lowRISC/opentitan pull request #19528
Opened 2023-08-25 17:50 UTC by alees24

Software advisories regarding responsivenes to SETUP packets and handling of notification interrupts.
Cabling requirements for USRUSB on CW310/CW340.
Clarify causes of link_in_err.
Minor corrections.

2023-08-28 14:27 UTC, hcallahan-lowrisc requested changes
Overall the content of these updates seems clear and reasonable to me. Thanks for clarifying the potential issues.

Nit. Our Markdown style is one sentence per line.

2023-08-29 10:19 UTC, rswarbrick commented on hw/ip/usbdev/doc/programmers_guide.md
> +It is important for software to collect received packets promptly so that there is always space available for the receipt of subsequent SETUP packets. The USB protocol specification does not provide
Nit: Line breaks here please :-)

2023-08-29 15:27 UTC, hcallahan-lowrisc approved these changes
LGTM, just needs a rebase now.

2023-08-29 15:28 UTC, HU90m approved these changes

2023-08-31 16:27 UTC, merged