[USB]
lowRISC/opentitan pull request #19824
Opened 2023-10-03 10:41 UTC by MubashirSaleem775

USBDEV block level verification updated tb file and added new interface for usbdev block verification.

@alees24  please review this PR
@jdonjdon

2023-10-03 14:57 UTC, jdonjdon commented
From CI you have following failures
2023-10-03T12:43:43.3733329Z ## Failure Buckets
2023-10-03T12:43:43.3733506Z 
2023-10-03T12:43:43.3733916Z * `Offending '(!$isunknown(usb_ref_pulse_o))'` has 2 failures:
2023-10-03T12:43:43.3734295Z     * Test usbdev_csr_hw_reset has 1 failures.
2023-10-03T12:43:43.3734583Z         * 0.usbdev_csr_hw_reset.1\
2023-10-03T12:43:43.3735072Z           Line 62, in log /azp/agent/_work/1/s/scratch/HEAD/usbdev-sim-vcs/0.usbdev_csr_hw_reset/latest/run.log
2023-10-03T12:43:43.3735547Z 
2023-10-03T12:43:43.3735879Z                 	Offending '(!$isunknown(usb_ref_pulse_o))'
2023-10-03T12:43:43.3736264Z                 UVM_ERROR @   1316284 ps: (usbdev.sv:1089) [ASSERT FAILED] USBRefPulseKnown_A
2023-10-03T12:43:43.3736630Z                 UVM_INFO @   1316284 ps: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
2023-10-03T12:43:43.3737054Z                 --- UVM Report catcher Summary ---
2023-10-03T12:43:43.3737315Z                 
2023-10-03T12:43:43.3737490Z 
2023-10-03T12:43:43.3737662Z     * Test usbdev_csr_rw has 1 failures.
2023-10-03T12:43:43.3737928Z         * 0.usbdev_csr_rw.1\
2023-10-03T12:43:43.3738384Z           Line 62, in log /azp/agent/_work/1/s/scratch/HEAD/usbdev-sim-vcs/0.usbdev_csr_rw/latest/run.log
2023-10-03T12:43:43.3738628Z 
2023-10-03T12:43:43.3738915Z                 	Offending '(!$isunknown(usb_ref_pulse_o))'
2023-10-03T12:43:43.3739273Z                 UVM_ERROR @   1316284 ps: (usbdev.sv:1089) [ASSERT FAILED] USBRefPulseKnown_A
2023-10-03T12:43:43.3739624Z                 UVM_INFO @   1316284 ps: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
2023-10-03T12:43:43.3740034Z                 --- UVM Report catcher Summary ---
2023-10-03T12:43:43.3740293Z

2023-10-05 14:25 UTC, alees24 requested changes
Thanks for separating the block-level interface from the `usb20_if` that we currently use in chip simulations.

Could you please format the commit message as described [here](https://opentitan.org/book/doc/contributing/github_notes.html?highlight=github#working-in-your-local-repo)?
You can look at some of the other PR titles/descriptions and their commits as examples.

Because this change introduces an interface rather than directly tying the port inputs, there are no longer any drivers on the following pins:
- cio_usb_dp_i
- cio_usb_dn_i
- usb_rx_d_i
- cio_sense_i

In particular, it's the absence of drivers/valid state on the `cio_usb_dp_i` and `cio_usb_dn_i` pins which leads to the assertion that is seen in CI about the `usb_ref_pulse_o` output not having a known state (USBRefPulseKnown_A).

As a basic sanity check of the connectivity and interface changes, running the `usbdev_smoke` test ought (presently) to run as far as the uvm_error `FIXME` occurring. I don't know how this translate into your simulation environment, but with the standard OT repo/tooling, this can be run using:
```
cd $REPO_TOP
util/dvsim/dvsim.py hw/ip/usbdev/dv/usbdev_sim_cfg.hjson -i usbdev_smoke --fixed-seed=1 [ --tool xcelium ]
```

2023-10-11 06:54 UTC, MubashirSaleem775 commented
Thanks @alees24  for your Review 

What you're saying is correct; we can expect an assert failure error because there's currently no driver that sets vsense to high, which the device needs to sense and enter a known state. I'm currently working on implementing these features in the driver class. Initially, I had sent the pull request only for the purpose of reviewing the interface. I will submit the pull request again with the driver to handle these signals, and I hope it will pass the CI test next time.

@jdonjdon  can we merge this change without driver class as it will take some time to complete.

2023-10-11 15:23 UTC, jdonjdon commented
> Thanks @alees24 for your Review
> 
> What you're saying is correct; we can expect an assert failure error because there's currently no driver that sets vsense to high, which the device needs to sense and enter a known state. I'm currently working on implementing these features in the driver class. Initially, I had sent the pull request only for the purpose of reviewing the interface. I will submit the pull request again with the driver to handle these signals, and I hope it will pass the CI test next time.
> 
> @jdonjdon can we merge this change without driver class as it will take some time to complete.
@MubashirSaleem775 
I am afraid you have to re submit what you want to merge. I can't slice your PR.

2023-10-17 04:16 UTC, MubashirSaleem775 commented
> @MubashirSaleem775 I am afraid you have to re submit what you want to merge. I can't slice your PR.

Thanks @jdonjdon .  I am working on driver when it complete i will re-submit this with driver class.

2023-10-17 04:16 UTC, closed without merging