[utils] Create a python scrip to digest the tesplan and output a csv
lowRISC/opentitan pull request #20251
Opened 2023-11-01 16:06 UTC by engdoreis

This PR creates a script to digest a testplan and produce a csv or/and update a google sheet.

## Usage
To generate a csv from all sival testplans:
```sh
./util/py/scripts/testplan_decoder.py --dir hw/top_earlgrey/data/ip --csv /tmp/sival.csv
``` 
To update a google sheet from all sival testplans:
```sh
./util/py/scripts/testplan_decoder.py --dir hw/top_earlgrey/data/ip --url <url/of/the/sheet> --credentials <path/to/google/credentials>
```
In order to get the credentials.json follow the [guide](https://docs.gspread.org/en/latest/oauth2.html).

2023-11-01 16:13 UTC, johngt commented
Investigating the service account route now

2023-11-01 22:29 UTC, moidx commented
Service accounts are prone to open attack vectors. If possible, consider any of the other alternatives listed here: https://cloud.google.com/iam/docs/best-practices-service-accounts#choose-when-to-use

2024-01-29 11:07 UTC, HU90m requested changes
It would be nice to have a `py_binary` rule to allow us to run these in the bazel environment with all the requirements.

2024-02-15 12:17 UTC, johngt commented
Have tested the create new issues in a private repo and then have this against the live repo.
Apart from an issue with lc_ctrl being reported as hmac (due to erroneous testplan) - seems to have been successful.

2025-08-08 10:25 UTC, closed without merging