[opentitantool] Avoid orphaned OpenOCD processes
lowRISC/opentitan pull request #20298
Opened 2023-11-08 23:35 UTC by jesultra

If a opentitantool or other process invokes `Jtag.connect()` but terminates for any reason before invoking `Jtag.disconnect()`, the current code may leave an orphaned openocd process, which may hold on to USB resources.

The stock OpenOCD code does not seem to have provisions to terminate when stdin closes.  This CL insteads patches OpenOCD to have it request a signal from the Linux kernel, whenever its parent terminates for any reason.

2023-11-08 23:53 UTC, timothytrippel approved these changes
Thanks @jesultra !

2023-11-09 10:45 UTC, nbdd0121 approved these changes

2023-11-09 19:50 UTC, nbdd0121 requested changes
Indentation in the patch should be tab to match upstream OpenOCD

2023-11-09 22:38 UTC, timothytrippel commented
> Indentation in the patch should be tab to match upstream OpenOCD

I don't think that is worth stalling this patch. Merging.

2023-11-09 22:38 UTC, merged