[usbdev] Added Usb block level DV Environment
lowRISC/opentitan pull request #20369
Opened 2023-11-16 08:46 UTC by MubashirSaleem775

Add usb20 block level interface.
Modify usb tb.sv to hook up dut using usb20_block_interface. Add clock divider module to drive K/J symbols for multiple clock cycles. Add usb20 driver to drive token packet.
Add usb20 block interface in usb20_agent.

@alees24 
@jdonjdon 
@a-will

2023-11-16 22:13 UTC, jdonjdon approved these changes
Looks good.
You have a compile error due to Clock_Divider.sv
Please add this to [here](https://github.com/lowRISC/opentitan/blob/927176403871e9504681b0dd080ae8c525411428/hw/ip/usbdev/dv/usbdev_sim.core#L17)
Then smoke test will pass.

2023-11-17 05:04 UTC, MubashirSaleem775 commented
> Looks good. You have a compile error due to Clock_Divider.sv Please add this to [here](https://github.com/lowRISC/opentitan/blob/927176403871e9504681b0dd080ae8c525411428/hw/ip/usbdev/dv/usbdev_sim.core#L17) Then smoke test will pass.


Thank you, @jdonjdon, for your quick reply. I've addressed the issue and committed the fix once more.

2023-11-17 17:05 UTC, jdonjdon requested changes
Please see the comment.

2023-11-17 17:05 UTC, jdonjdon commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +  virtual task run_phase(uvm_phase phase);
Since this is same as [parent's task](https://cs.opensource.google/opentitan/opentitan/+/master:hw/dv/sv/dv_lib/dv_base_driver.sv;drc=7d38bf9095e6e911259b9e6831bebf0a073839af;l=19)
You don't need this.
Instead, please add 
virtual task reset_signals();
   // add driver reset here.
endtask

2023-11-18 04:36 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +  virtual task run_phase(uvm_phase phase);
@jdonjdon  Ok i will remove run_phase from driver and define tasks inside driver that are virtual task reset_signals() and get_and_drive().

2023-11-18 05:09 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +  virtual task run_phase(uvm_phase phase);
@jdonjdon, I attempted to eliminate the run_phase, but encountered an issue. The parent task utilizes fork join to concurrently execute the reset and get_and_drive tasks. I must execute the reset_signals() first before get_and_drive(). Consequently, I included this approach within usb20_driver.sv, similar to what was done in uart_driver.sv. If run_phase is removed, I would have to integrate the bus reset task within the get_and_drive task. What are your thoughts on this?

2023-11-18 05:23 UTC, jdonjdon commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +  virtual task run_phase(uvm_phase phase);
@MubashirSaleem775 oh you are right. I think you can keep run_phase as is if you want.
Add dummy `reset_signals` is more important to avoid compile error.

2023-11-18 06:04 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +  endtask
@jdonjdon, since the reset_signals() task is already included in the driver class, I'm puzzled about the necessity of adding dummy reset signals. I'm having difficulty understanding why you're encountering a compilation error, as it's functioning correctly in my tests. Could you please provide additional details about the compilation error?

2023-11-18 06:08 UTC, jdonjdon commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +  endtask
> @jdonjdon, since the reset_signals() task is already included in the driver class, I'm puzzled about the necessity of adding dummy reset signals. I'm having difficulty understanding why you're encountering a compilation error, as it's functioning correctly in my tests. Could you please provide additional details about the compilation error?

To be precise, it will cause runtime error not compile error.
In my original reply, you can see [dv_base_driver.sv](https://cs.opensource.google/opentitan/opentitan/+/master:hw/dv/sv/dv_lib/dv_base_driver.sv;drc=7d38bf9095e6e911259b9e6831bebf0a073839af;l=19)
which is parent class of usb20_driver.
From the line 28 and 33, dv_base_driver force to override `reset_signals()` and  `get_and_drive()`.
Otherwise, it will fire `uvm_fatal.

2023-11-18 06:21 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +  endtask
Alright, I comprehend that it will trigger `uvm_fatal if I don't extend the reset_signals() and get_and_drive() tasks. However, I want to emphasize that I've already extended both tasks in the usb20_driver class. 
At line 169 i have defined reset_siganls() task and at line 36 i have defined get_and_drive() task.

2023-11-18 06:23 UTC, jdonjdon commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +  endtask
@MubashirSaleem775 you are right. Sorry I missed those.

2023-11-18 06:23 UTC, jdonjdon approved these changes

2023-11-18 06:30 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +  endtask
@jdonjdon No problem. Please inform me if any modifications are necessary to pass the CI tests. Thanks.

2023-11-18 07:51 UTC, jdonjdon commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +  endtask
@MubashirSaleem775 it is weird. I still can see 
23-11-18T07:04:52.3396339Z * `UVM_FATAL (dv_base_driver.sv:28) driver [driver] this is implemented as pure virtual task - please extend` has 2 failures:
2023-11-18T07:04:52.3396862Z     * Test usbdev_csr_rw has 1 failures.
2023-11-18T07:04:52.3397115Z         * 0.usbdev_csr_rw.1\
2023-11-18T07:04:52.3397596Z           Line 61, in log /azp/agent/_work/1/s/scratch/HEAD/usbdev-sim-vcs/0.usbdev_csr_rw/latest/run.log
2023-11-18T07:04:52.3397973Z 
2023-11-18T07:04:52.3398615Z                 UVM_FATAL @         0 ps: (dv_base_driver.sv:28) uvm_test_top.env.m_usb20_agent.driver [uvm_test_top.env.m_usb20_agent.driver] this is implemented as pure virtual task - please extend
2023-11-18T07:04:52.3399358Z                 UVM_INFO @         0 ps: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
2023-11-18T07:04:52.3400008Z                 --- UVM Report catcher Summary ---
2023-11-18T07:04:52.3400330Z                 
2023-11-18T07:04:52.3400512Z                 
2023-11-18T07:04:52.3400636Z 
2023-11-18T07:04:52.3400771Z     * Test usbdev_csr_hw_reset has 1 failures.
2023-11-18T07:04:52.3401042Z         * 0.usbdev_csr_hw_reset.1\
2023-11-18T07:04:52.3401616Z           Line 61, in log /azp/agent/_work/1/s/scratch/HEAD/usbdev-sim-vcs/0.usbdev_csr_hw_reset/latest/run.log
2023-11-18T07:04:52.3402233Z 
2023-11-18T07:04:52.3402910Z                 UVM_FATAL @         0 ps: (dv_base_driver.sv:28) uvm_test_top.env.m_usb20_agent.driver [uvm_test_top.env.m_usb20_agent.driver] this is implemented as pure virtual task - please extend
2023-11-18T07:04:52.3403687Z                 UVM_INFO @         0 ps: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
2023-11-18T07:04:52.3404127Z                 --- UVM Report catcher Summary ---


Can you rebase and push again?

2023-11-21 19:17 UTC, a-will commented on hw/dv/sv/usb20_agent/usb20_block_if.sv
> +  assign usb_n = usb_dn_en_o ? usb_dn_o : drive_n;
Also want an assignment if 0 to weak0

2023-11-22 15:58 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_block_if.sv
> +  assign usb_n = usb_dn_en_o ? usb_dn_o : drive_n;
@a-will  the weak0 assignment in this way will be okay ? or do you want some other way.

  // Weak0 assignments
  assign (weak0, weak1) usb_p = (usb_dp_en_o ? 1'b0 : 1'bz);
  assign (weak0, weak1) usb_n = (usb_dn_en_o ? 1'b0 : 1'bz);
  assign (weak0, weak1) drive_p = (usb_dp_en_o ? 1'bz : 1'b0);
  assign (weak0, weak1) drive_n = (usb_dn_en_o ? 1'bz : 1'b0);

2023-11-22 17:30 UTC, MubashirSaleem775 commented
I have added a new PR of this work. new PR is :
[Add usb20 block level DV Environment #20404](https://github.com/lowRISC/opentitan/pull/20404)

2023-11-22 17:30 UTC, closed without merging