[hw,dma,rtl] Use cached opcode instead of unlocked register value
lowRISC/opentitan pull request #20455
Opened 2023-11-23 17:50 UTC by Razer6

This is a remainder of the locking PR from before.

2023-11-27 14:38 UTC, alees24 requested changes
The first change, within the DmaAddrSetup state is sound, but the second breaks function because the captured opcode has not yet been assigned.

If `control_q.opcode` is to be used everywhere else, then the use of  `reg2hw.control.opcode.q` in the 'unique case' expression could definitely benefit from explanation, please.

Also, I think the comment associated with 'clear_sha_status' could benefit from being updated, since it still makes reference to the 'busy' bit which previously governed its behavior.

2023-11-27 15:31 UTC, Razer6 commented on hw/ip/dma/rtl/dma.sv
> +      unique case (control_q.opcode)
I think its a mixture of both. The SHA digest gets written with `sha2_digest_set` being set in `DmaFinalize`, where we need to use `control_q.opcode` while initially, we would need to use `reg2hw.control.opcode.q`. I think we can remove the per-line-muxes, gate the logic with `sha2_digest_set`,  and use the default assignment of `hw2reg = '0;` to cover for the clear case. Like the following code:

```systemverilog
if (sha2_digest_set) begin
  for (int unsigned i = 0; i < NR_SHA_DIGEST_ELEMENTS / 2; i++) begin
    unique case (control_q.opcode)
      OpcSha256: begin
        hw2reg.sha2_digest[i].d = sha2_digest[i][0 +: 32];
      end
      OpcSha384: begin
        if (i < 6) begin
          hw2reg.sha2_digest[i*2].d     = sha2_digest[i][32 +: 32];
          hw2reg.sha2_digest[(i*2)+1].d = sha2_digest[i][0  +: 32];
        end
      end
      default: begin // SHA2-512
        hw2reg.sha2_digest[i*2].d     = sha2_digest[i][32 +: 32];
        hw2reg.sha2_digest[(i*2)+1].d = sha2_digest[i][0  +: 32];
      end
    endcase
  end
end
```

WDYT?

2023-11-27 17:11 UTC, alees24 commented on hw/ip/dma/rtl/dma.sv
> +      unique case (control_q.opcode)
Yes, okay, I hadn't fully considered the effect of that case statement on the updating of the SHA digest. What you propose sounds fine.
It would definitely be worth explaining how 'clear_sha_status' operates, where it's assigned to `hw2reg.sha2_digest[i].de`, because the default hw2reg assignment is not readily visible.

2023-11-27 17:32 UTC, Razer6 commented on hw/ip/dma/rtl/dma.sv
> +      unique case (control_q.opcode)
I updated the logic and added a comment before to explain the usage. Can you please review the changes and approve if its ok?

2023-11-27 18:04 UTC, alees24 approved these changes
Thanks for including the explanations.
LGTM, just minor formatting to be addressed.

2023-11-28 19:30 UTC, msfschaffner approved these changes

2023-11-28 19:30 UTC, merged