[ci] Add the sival exec_env to the CI nigthly BoB tests
lowRISC/opentitan pull request #20451
Opened 2023-11-23 11:35 UTC by engdoreis

Add the sival exec_env to the CI nigthly BoB tests.

I broke the tests into two steps to optimize the bitstream load.

2023-11-23 12:09 UTC, jwnrt requested changes

2023-11-23 12:09 UTC, jwnrt commented on sw/device/tests/pmod/BUILD
> +>>>>>>> 45428dd033 ([ci] Add the sival exec_env to the CI nigthly BoB tests)
Merge conflict here

2023-11-23 13:50 UTC, engdoreis commented on sw/device/tests/pmod/BUILD
> +>>>>>>> 45428dd033 ([ci] Add the sival exec_env to the CI nigthly BoB tests)
Sorry, fixed

2023-11-23 14:01 UTC, jwnrt approved these changes
This LGTM, I'll check back on how the CI run goes when it's done.

I see you've removed the `BoB` tags - are all the tests using the BoB in the `//sw/device/tests/pmod` directory so we can still filter them out if we don't have a BoB?

2023-11-23 14:40 UTC, engdoreis commented
> This LGTM, I'll check back on how the CI run goes when it's done.
> 
> I see you've removed the `BoB` tags - are all the tests using the BoB in the `//sw/device/tests/pmod` directory so we can still filter them out if we don't have a BoB?

We can filter them by the folder they are in. Previously they were under //sw/device/tests, so the tag was the only way to filter.

2023-11-23 17:12 UTC, engdoreis commented
I had to put the `manual` tag back, otherwise the pmod test would appear in the CI job for every PR.

2023-11-27 09:58 UTC, pamaury commented on ci/azure-pipelines-nightly.yml
> +    displayName: "Run the PMOD tests with ROM"
maybe change the name to "Run the PMOD test for Sival"?

2023-12-01 08:49 UTC, engdoreis commented
> I think it would be a good idea to keep the `bob` tag as it gives a uniform way to filter tests, _not_ based on folder location. What do you think?

I think you're right, I put the tag back, but called pmod to be consistent with the folder name.

2023-12-01 14:56 UTC, pamaury approved these changes

2023-12-01 14:57 UTC, merged