[prim_sha2,rtl] Add prim_sha2 RTL
lowRISC/opentitan pull request #20675
Opened 2023-12-18 13:36 UTC by gdessouky

This PR is a reduced PR spun off from the PR #20472 (see discussion in PR) which commits only the RTL for the SHA-2 multi-mode primitive that can be compile-time configured as 256-bit or multi-mode. This also includes fixes for RTL code styling in the HMAC IP that were not complying with the Verilog style guidelines, and RTL fixes and linting waiver updates to pass AscentLint linting. 

After discussions in the Silicon WG meeting Dec 12 2023, it was agreed that we would get the SHA-2 prim changes and testbenches first merged, and follow up with the instantiation in HMAC and DMA in a later PR to not impact RTL freeze and coverage metrics (even if DV regression testing passes). We will also discuss if it is required/useful to extend HMAC to support the extended digest modes for Earlgrey PROD and Darjeeling later.

The first commit is the multi-mode RTL implementation as baseline, and second is the actual prim_sha2 RTL and linting waivers.

2023-12-19 08:31 UTC, Razer6 requested changes
Thank you for the changes. I left a few comments to the organization of the multimode code.

2023-12-19 08:31 UTC, Razer6 commented on hw/ip/prim/rtl/prim_sha2_32.sv
> +  generate
No need for a `generate` statement anymore: https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#generate-constructs

2023-12-19 08:31 UTC, Razer6 commented on hw/ip/prim/rtl/prim_sha2_32.sv
> +  always_comb begin : accumulate_word
I wonder if this always block should be wrapped int the `MultimodeEn` flag rather than the other way around:

```systemverilog
if (MultimodeEn) begin : gen_multimode_logic
   always_comb begin
      ...
   end
end
```

This should include the signal definitions and then avoids the tie off.

2023-12-19 08:31 UTC, Razer6 commented on hw/ip/prim/rtl/prim_sha2_32.sv
> +  always_comb begin
Same as above.

2023-12-19 08:31 UTC, Razer6 commented on hw/ip/prim/rtl/prim_sha2_32.sv
> +  always_ff @(posedge clk_i or negedge rst_ni) begin
I wonder if we should do:

```systemverilog
if (MultimodeEn) begin : gen_ff_multimode
  
end
```

and then instantiate the flops inside the generate. This removes the "enable" on the flop, which gets removed anyway. Can we also use prim_ff instances then for the flops?

2023-12-19 08:31 UTC, Razer6 commented on hw/ip/prim/rtl/prim_sha2_pad.sv
> +    if (!rst_ni)         digest_mode_flag <= None;
Nit: whitespace

2023-12-19 10:46 UTC, msfschaffner commented on hw/ip/prim/rtl/prim_sha2_32.sv
> +  always_comb begin : accumulate_word
Yes that would be the preferred way also from my end.

2023-12-19 10:47 UTC, msfschaffner commented on hw/ip/prim/rtl/prim_sha2_32.sv
> +  always_ff @(posedge clk_i or negedge rst_ni) begin
@Razer6 is there a specific reason you would like to use prim_flop here? If there no synthesis constraints are needed for these flops (e.g. keeping in place and do not optimize), using always_ff is just fine.

2023-12-21 15:02 UTC, gdessouky commented on hw/ip/prim/rtl/prim_sha2_32.sv
> +  always_comb begin : accumulate_word
Thanks @Razer6 and @msfschaffner! Will change the wrapping of the code in all instances that way, but am not sure about the signal definitions, they are then only visible in this scope, can't connect them to ports or update them in `always_ff` blocks later.

2023-12-21 15:02 UTC, gdessouky commented on hw/ip/prim/rtl/prim_sha2_32.sv
> +  generate
thanks for catching, had fixed others and missed that one.

2023-12-21 18:04 UTC, vogelpi reviewed
Thanks @gdessouky for refactoring your work. I've just did an initial review of the package file and noted some code style fixes + unused parameter removal. 

I think the commit message probably also should be aligned, IIUC this PR contains most code style fixes already.

2023-12-22 09:27 UTC, gdessouky commented on hw/ip/prim/rtl/prim_sha2_pkg.sv
> +    SwPushMsgWhenShaDisabled   = 32'h 0000_0001,
That makes sense, will evaluate how coverage changes after pushing again now, and then clean this up.

2023-12-22 09:29 UTC, gdessouky commented
> Thanks @gdessouky for refactoring your work. I've just did an initial review of the package file and noted some code style fixes + unused parameter removal.
> 
> I think the commit message probably also should be aligned, IIUC this PR contains most code style fixes already.

Thanks @vogelpi for your review! I've taken care of your suggestions, and reorged the code further for the sake of coverage in my push now.

2023-12-22 09:32 UTC, gdessouky commented on hw/ip/prim/rtl/prim_sha2_32.sv
> +  always_ff @(posedge clk_i or negedge rst_ni) begin
I stick to `always_ff` blocks in my last push and reorged the code to avoid checking the `MultimodeEn` parameter at runtime where possible  - thanks @Razer6 and @msfschaffner for your comments!

2024-01-26 06:04 UTC, gdessouky commented
> Is this PR still relevant or can it be closed?

Yes, we can close this one. The other PR with more commits, including these, has been merged. I'll go ahead and close!

2024-01-26 06:04 UTC, closed without merging