[usbdev] Predictor of usbdev
lowRISC/opentitan pull request #20703
Opened 2023-12-21 10:28 UTC by sarahmazhar-impare

This request contains the usbdev_TransactionManager class of the usbdev predictor (reference model). Some amendments are done to make it compatible with the scoreboard.

2023-12-22 00:02 UTC, jdonjdon approved these changes

2023-12-22 00:26 UTC, jdonjdon reviewed
See in line

2023-12-22 00:26 UTC, jdonjdon commented on hw/ip/usbdev/dv/env/usbdev_TransactionManager.sv
> +         pid = 8'b0010_1101;
@sarahmazhar-impare Is this pid is the same pid as in usb20_item.sv ?

2023-12-22 06:35 UTC, sarahmazhar-impare commented on hw/ip/usbdev/dv/env/usbdev_TransactionManager.sv
> +         pid = 8'b0010_1101;
Yes it is same as the usb20_item.sv pid for Ack type handshake

2023-12-23 14:32 UTC, jdonjdon requested changes
Please wait for #20709 merged and use the same enum defined 
in usb20_agent_pkg in the PR.

2024-03-04 15:13 UTC, rswarbrick commented
Hi @sarahmazhar-impare! Is this PR still current? If so, please could you rebase it and we'll try to review it. If not, please could you close it?

2024-03-05 21:42 UTC, closed without merging