[RV_DM] rv_dm_sba_debug_disabled_vseq
lowRISC/opentitan pull request #20739
Opened 2023-12-28 07:33 UTC by Shahid-Mehmood-S

The test ensures that the SBA interface is disabled when 'lc_hw_debug_en' is not set to true, ensuring no SBA TL accesses occur.

2023-12-28 09:47 UTC, Shahid-Mehmood-S commented
@jdonjdon I have rebased and resolved all the conflicts as requested.
Kindly review it. Thanks

2023-12-29 16:25 UTC, jdonjdon commented on hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
> +       `uvm_info(`gfn, $sformatf("Does not receive SBA access item:\n%0s",
Line 190: use 2 space indentations.

2023-12-29 16:29 UTC, jdonjdon commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_sba_debug_disabled_vseq.sv
> +      cfg.rv_dm_vif.lc_hw_debug_en<=lc_ctrl_pkg::Off;
Test plan says non-true. So use following syntax to assign random non-true value. 

cfg.rv_dm_vif.lc_hw_debug_en = get_rand_lc_tx_val([.t_weight(0), .f_weight(1), .other_weight(4));

2023-12-29 16:30 UTC, jdonjdon reviewed
@Shahid-Mehmood-S , please see in lines

2024-01-18 15:20 UTC, jdonjdon commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_sba_debug_disabled_vseq.sv
> +      cfg.rv_dm_vif.lc_hw_debug_en = get_rand_lc_tx_val([.t_weight(0), .f_weight(1), .other_weight(4));
you have a typo in line 24. remove '['.

2024-01-18 16:35 UTC, rswarbrick commented
If I understand correctly, this change is intended to fix issue #15668. Is that correct? If so, it's probably worth marking it in GitHub as such.

2024-01-18 16:44 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
> +                                item.sprint(uvm_default_line_printer)), UVM_HIGH)
Nit: Indentation is off here.

2024-01-18 16:44 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
> +                                item.sprint(uvm_default_line_printer)), UVM_HIGH)
Can we rephrase this? If I understand correctly, line 185 means that the proposed code will sometimes spit out something that looks like:
```
Received SBA access item:
blahblah
Does not receive SBA access item:
blahblah
```

That seems rather confusing! (And hopefully easy to rephrase to fix)

2024-01-18 16:44 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
> +
Please drop these two lines of change. One changes the indentation to be wrong. The second adds an unnecessary blank line.

2024-01-18 16:44 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_sba_debug_disabled_vseq.sv
> +      cfg.debugger.sba_access(req);
These three lines are repeated below. Could you factor them out into a task?

2024-01-22 11:34 UTC, rswarbrick requested changes
The proposed change to `rv_dm_scoreboard` is something we'd need to be a bit careful about. If it needs to happen, it definitely needs to be in a different commit from the change that adds the vseq.

2024-01-22 11:34 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
> +      end else if (cfg.rv_dm_vif.lc_hw_debug_en==lc_ctrl_pkg::Off) begin
I'm not completely sure I understand this. I think the previous code was dying with an error if we saw an SBA access that wasn't expected. Your patch demotes this to uvm_info / UVM_HIGH and makes it happen less often (checking `lc_hw_debug_en`).

We definitely should *not* make this change without some careful thought and explanatory comments.

2024-01-22 11:36 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
> +                                item.sprint(uvm_default_line_printer)), UVM_HIGH)
The re-indented version is still incorrect (with one extra space). Once you've got the code correct, please can you indent it correctly? (Most editors can do this for you on a given line)

2024-01-24 13:00 UTC, closed without merging