[hw,mbx,rtl] Clear interrupts when acknowledging an abort
lowRISC/opentitan pull request #20895
Opened 2024-01-19 11:08 UTC by Razer6

Previously, acknowledging an abort left all interrupts to the host side being active, as well as the interrupt to the SOC.

This PR utilizes the `hostif_control_abort_clear` signal to clear all pending interrupts to Ibex and clears the interrupt register to the SOC.

Since there is currently no proper DV environment in place, I verified that manually using the existing smoke sequence with the following flow:
1. Start a transfer from the SOC (Generates ready IRQ)
2. Let Host write an error
3. Soc Writes Abort (Generates Abort IRQ)
4. Ibex acknowledges the abort

![Screenshot 2024-01-19 at 11 56 01](https://github.com/lowRISC/opentitan/assets/278301/30d4a9a9-f43e-440d-95c8-f9eeb368153f)

2024-01-23 17:34 UTC, hcallahan-lowrisc reviewed
Took a look at the waveforms and can confirm I see the interrupts clearing on abort acknowledgement after this change.

Is there a risk that if the responder FW acknowledges the abort before the requester has claimed/handled the irq, the requester FW could get into a strange state? I can't really anticipate how the soc firmware would handle an abort triggered from the RoT-side, but maybe it would be safer if the doe_intr_o could not be cleared from the other side?

2024-01-23 18:05 UTC, andreaskurth approved these changes
Code LGTM, though I haven't tested it

2024-01-23 21:10 UTC, Razer6 commented
> Is there a risk that if the responder FW acknowledges the abort before the requester has claimed/handled the irq, the requester FW could get into a strange state? I can't really anticipate how the soc firmware would handle an abort triggered from the RoT-side, but maybe it would be safer if the doe_intr_o could not be cleared from the other side?

I have to think a little bit about that. I think in the normal case, the abort is initiated from the SOC, there is no reason that there is an issue. For the second case, there might be a problem but I am not yet fully sure.  The feature is used as a soft-reset from the responder side in case something bad happens. It's not used as a general operation. A hang operation is usually not detected in a short sequence, where an IRQ might not be claimed yet but at a larger timeout. i.e, 1 second.

2024-01-31 12:41 UTC, alees24 requested changes
Please see comments.

2024-01-31 12:41 UTC, alees24 commented on hw/ip/mbx/rtl/mbx_hostif.sv
> +  assign hw2reg.intr_state.mbx_error.de = intr_error_de | hostif_control_abort_clear_o;
Whilst this change is harmless, I'm inclined to argue that it is a case of complicating the hardware where FW could just as easily perform this task, since it knows that it is using the 'Firmware Reset/Abort Clear' mechanism. FW could simply write to the INTR_STATE register immediately after writing to the CONTROL register to clear the abort.

In fact neither approach is guaranteed to prevent the FW interrupt handler being entered after the CONTROL register has been written, because of the latencies in register writers and the fact that the interrupt assertion may have been retained outside of the MBX IP, within the PLIC and/or CPU, for example.

2024-01-31 12:41 UTC, alees24 commented on hw/ip/mbx/rtl/mbx_sysif.sv
>                                                   sysif_status_error_set_i          |
Presumably the intent here is that 'sysif_status_doe_intr_ready_clear_i' should reset the 'doe_intr_status' bit and thus deassert the interrupt line to the SoC? If so, the necessary logic is missing from the assignments to 'intr_status.de' and 'intr_status.d'.

The waveforms shown in this PR do not include the signal `doe_intr_o`, but rather `doe_intr_en_o` which appears to have been cleared because the SoC has disabled the interrupt at the point of trying to set the Abort bit.  The SoC-side software will need to be careful not to clear the 'intr_en' and 'async_msg_en' bits inadvertently when raising an Abort.

2024-02-01 16:18 UTC, Razer6 commented on hw/ip/mbx/rtl/mbx_hostif.sv
> +  assign hw2reg.intr_state.mbx_error.de = intr_error_de | hostif_control_abort_clear_o;
I agree that SW could do that as well. But as said, in both cases the IRQ might be stored somewhere else. I think that in that case the FW would need to sample the STATUS.busy bit. If during an interrupt, the busy bit is not set, then a FW-initiated abort happened before and a flaky IRQ is received - WDYT?

2024-02-01 16:37 UTC, Razer6 commented on hw/ip/mbx/rtl/mbx_sysif.sv
>                                                   sysif_status_error_set_i          |
I think the same thing can be done during on the SOC side. It can query the IRQ state to ensure its not a flaky one. I think the the right logic is the following one, which also avoids the lint. It seems that somehow got lost:

```
  assign hw2reg.soc_status.doe_intr_status.de = DoeIrqSupport &
                                                (sysif_status_doe_intr_ready_set_i   |
                                                 sysif_status_doe_intr_ready_clear_i |
                                                 sysif_status_error_set_i            |
                                                 async_msg_set_gated);
  assign hw2reg.soc_status.doe_intr_status.d  = (sysif_status_doe_intr_ready_set_i |
                                                 sysif_status_error_set_i          |
                                                 async_msg_set_gated)              & 
                                                 ~sysif_status_doe_intr_ready_clear_i;
```

2024-02-01 16:59 UTC, Razer6 commented on hw/ip/mbx/rtl/mbx_sysif.sv
>                                                   sysif_status_error_set_i          |
So the Linux driver does not use IRQ yet instead they only poll for SOC_STATUS.error and SOC_STATUS.ready. With acking the abort (or a FW-initiated abort), the ready gets already cleared.

2024-02-02 15:13 UTC, alees24 requested changes
I'm okay with clearing the interrupt status bits on both sides, but it's more important that the SoC-side interrupt state be cleared, so please do reintroduce that.

Having done a bit more investigation, unless I'm mistaken, we should also address the following:

- the flop 'abort_q' in mbx_hostif.sv should prioritize being cleared by 'hostif_control_abort_clear_o' over being set by 'sysif_control_abort_set_i' (ie. reorder the assignments) since abort clearing now serves as a software reset.
- abort clearing should reset the 'SOC_STATUS.doe_async_msg_status' bit which I think it does not presently.
- abort clearing should reset the 'SOC_STATUS.error' bit too.

2024-02-02 15:45 UTC, alees24 commented on hw/ip/mbx/rtl/mbx_hostif.sv
> +  assign hw2reg.intr_state.mbx_error.de = intr_error_de | hostif_control_abort_clear_o;
FW should respond to the INTR_STATE register and trust its indication of pending conditions, so it need not consult the 'STATUS.busy' when receiving a request; it just observes that INTR_STATE.mbx_ready is set and then consults INBOUND_WRITE_PTR to ascertain the size of the message.

I think the only real advantage of having the 'hostif_control_abort_clear_o' signal clear the INTR_STATE bits itself is that the FW which clears the abort can be a little simpler, whereas if it performed an explicit write to the INTR_STATE register it would have to disable interrupts or indicate to the interrupt handler via software state that it was midway through its reset operation (between the CONTROL.abort write and the INTR_STATE write), but it's a small point.

Please see the subsequent review comment about some other issues.

2024-02-02 22:38 UTC, Razer6 commented on hw/ip/mbx/rtl/mbx_hostif.sv
> +  assign hw2reg.intr_state.mbx_error.de = intr_error_de | hostif_control_abort_clear_o;
> FW should respond to the INTR_STATE register and trust its indication of pending conditions, so it need not consult the 'STATUS.busy' when receiving a request; it just observes that INTR_STATE.mbx_ready is set and then consults INBOUND_WRITE_PTR to ascertain the size of the message.

Fair enough. If the size is 0, it might be a bogus message or a pending IRQ after the abort ack.

2024-02-05 12:29 UTC, alees24 approved these changes
Thanks for making the changes to reset the other state. Just a comment that needs correcting, please.

2024-02-05 12:29 UTC, alees24 commented on hw/ip/mbx/rtl/mbx.sv
> +    // Abort from the the host
Suggestion: Abort clearing from the host

2024-02-05 18:21 UTC, merged