[RV_DM]rv_dm_scoreboard
lowRISC/opentitan pull request #20926
Opened 2024-01-23 06:20 UTC by Shahid-Mehmood-S

This commit contains a change in line of code that is passing criteria for our 'rv_dm_sba_debug_disabled_vseq'. Our test condition is that no transaction was seen on TL SBA interface when 'lc_hw_debug_en' is Off.So that's why we add this line in scoreboard.

2024-01-23 07:12 UTC, Shahid-Mehmood-S commented
@jdonjdon

2024-01-23 14:37 UTC, rswarbrick requested changes
Some nitty comments, but I don't think this should go in at all. The proposed change turns check that causes an error into something that spits out a UVM_HIGH message. That sort of message will be ignored, so we're essentially removing the check.

That might be the right thing to do! But then we need to:
- Explain it properly in the commit message
- Remove the uninformative uvm_info call

A full fix would be to figure out why anything appeared on `sba_access_fifo` at all. Is there a sync problem, or could we have noticed that `lc_hw_debug_en` was not true and avoided pushing the element to the FIFO in the first place.

And how long does the FIFO take to run through? At what point should we be checking `lc_hw_debug_en`? This logic *might* be correct, but I'd be surprised! And it would definitely need a comment explaining why it's correct.

2024-01-23 14:37 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
> +                                    item.sprint(uvm_default_line_printer)))
Please fix the indentation here (by dropping the change to this line)

2024-01-23 14:37 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
> +      end else if (cfg.rv_dm_vif.lc_hw_debug_en==lc_ctrl_pkg::Off) begin
I think this should be `!= lc_ctrl_pkg::On`, right?

Missing space around `==`

2024-01-24 12:12 UTC, Shahid-Mehmood-S commented
> Some nitty comments, but I don't think this should go in at all. The proposed change turns a check that causes an error into something that spits out a UVM_HIGH message. That sort of message will be ignored, so we're essentially removing the check.
> 
> That might be the right thing to do! But then we need to:
> 
> * Explain it properly in the commit message
> * Remove the uninformative uvm_info call
> 
> A full fix would be to figure out why anything appeared on `sba_access_fifo` at all. Is there a sync problem, or could we have noticed that `lc_hw_debug_en` was not true and avoided pushing the element to the FIFO in the first place?
> 
> And how long does the FIFO take to run through? At what point should we be checking `lc_hw_debug_en`? This logic _might_ be correct, but I'd be surprised! And it would definitely need a comment explaining why it's correct.

Okay thanks, we will figure it out.

2024-01-24 13:00 UTC, closed without merging