[dv,chip_level] Clean up apply_reset
lowRISC/opentitan pull request #21098
Opened 2024-01-29 21:17 UTC by matutem

Change apply_reset to just do a POR, plus some jtag resets that have independent pins. Remove the apply_resets_concurrently, and rely on POR only, since the chip should internally create the derived resets.

Addresses #19445

2024-02-01 18:12 UTC, sha-ron commented on hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv
> -    callback_vseq.pre_apply_reset();
Yes, it is used for closed source, please don't remove.

2024-02-01 18:17 UTC, sha-ron commented on hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv
> -    void'($value$plusargs("skip_por_n_during_first_pwrup=%0b", skip_por_n_during_first_pwrup));
@jdonjdon @matutem This is also used by the closed source. 
Also please note that toggling POR_N is not the only way (and actually not even the main way) to power up/down. VCC power supply toggle is another way to reset the chip.  Using only POR_N pad is reducing some coverage.

2024-02-01 20:36 UTC, matutem commented on hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
> -    wait_rom_check_done();
Notice I replaced waiting for rom check done by waiting for the fast fsm to be active, which happens after the ROM check passes, or we disable checking for "goodness" as in RAW lc_state for example. Waiting for active state seems safer since the chip is really ready to run CSR or memory transactions. Keep in mind this only applies to stub cpu.

2024-02-01 21:15 UTC, matutem commented on hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv
> -    void'($value$plusargs("skip_por_n_during_first_pwrup=%0b", skip_por_n_during_first_pwrup));
The problem I am trying to solve is that the standard cip_lib flow is not necessarily suitable for the full chip, and rather than hacking it to fit, I'd rather reduce our dependencies on it.

Let me explain the simplest ones first:
- This only affects apply_reset, and VCC-related resets still remain viable. See the sequence chip_sw_main_power_glitch_vseq for example; apply_reset is typically used to make the chip pretend it got a POR_N, as you can see in line 50.
- As for not calling apply_reset on the very first power-on, I agree with you we don't need it. In fact, I think we don't need the `skip_por_n_during_first_pwrup` plusarg, and we should never issue an assert_reset in that case.
- The important change here is to remove the call to super.apply_reset, since it will gratuitously manipulate the clk_rst_if's clk and rst signals, which is confusing and possibly wrong, since that is orchestrated by pwrmgr.
- The call to post_apply_reset is also troubling since in cip_base_vseq it will wait for all alerts to be done, while in the real chip there should be no need for that. Where do you use post_apply_reset, and is it not possible to just put that in the test body?

2024-02-01 21:53 UTC, matutem commented on hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv
> +    apply_reset("HARD");
By the way, this also avoids the cip_base_vseq apply_resets_concurrently, which does even more unnatural things.

2024-02-02 09:16 UTC, rswarbrick commented on hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv
> -    callback_vseq.pre_apply_reset();
I guess this should be easy to keep working. @matutem, I think we can just reinstate the lines that call `pre_apply_reset` and `post_apply_reset`, right?

2024-02-02 09:18 UTC, rswarbrick reviewed
This looks like it makes things much easier to reason about! I guess we still need to keep the "closed source hooks" around apply_reset, but otherwise I can't see why this would break anything.

2024-02-02 19:44 UTC, matutem commented on hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv
> -    callback_vseq.pre_apply_reset();
We could, but the pre and post mechanism is where we have been hacking around the underlying problem, so if we could dispense with it we will all be much better off. This is why I'd like to know what do we use it for.

2024-02-03 19:57 UTC, sha-ron commented on hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv
> -    void'($value$plusargs("skip_por_n_during_first_pwrup=%0b", skip_por_n_during_first_pwrup));
We use pre_apply_reset but the problem is that changing something so basic (like removing super.apply_reset()) might involve a lot of effort so we need to think if this is the right time. As for removing skip_por_n_during_first_pwrup plusarg and never issue assert_reset, we use it for a lot of tests but for some tests  it is very problematic because of the way the infrastructure is built.  Specifically for chip_sw_main_power_glitch_vseq, can you please let me know what is the purpose of those tests? As I understand it is not a functional scenario.

2024-02-05 09:57 UTC, rswarbrick commented on hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv
> -    callback_vseq.pre_apply_reset();
I think I agree! But the changes here seem like a good idea either way. Maybe it makes sense to reinstate the calls to those two functions in this PR and get the cleanups in either way. We can then separate out the "and stop doing something we don't need" change so that it can be discussed in detail. (And applied, I hope!)

2024-02-05 23:31 UTC, msfschaffner commented on hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
> -    wait_rom_check_done();
Ok this sounds reasonable!

2024-02-06 04:58 UTC, matutem commented on hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv
> -    void'($value$plusargs("skip_por_n_during_first_pwrup=%0b", skip_por_n_during_first_pwrup));
I am just removing this from master, not the es branch, so it has more time to settle. I appreciate your careful review since the change will be more reliable.

If you look at what super.apply_reset does you may be glad we removed it, since it sends a reset on clk_rst_vif and it waits for alerts to settle. None of this should be needed for full chip.

I am afraid I made a mistake regarding the skip_por_n_during_first_pwrup: apply_reset is certainly not needed since the first powerup is triggered by the AST. What I intended was to get rid of the plusargs, but leave the exception on first power up. I fixed my mistake in chip_base_vseq.sv line 44 and updated the PR.

Regarding other resets, and specifically this comment above:

>Also please note that toggling POR_N is not the only way (and actually not even the main way) to power up/down. VCC power supply toggle is another way to reset the chip. Using only POR_N pad is reducing some coverage.

This change has no impact on resets due to power supply glitches, only on POR. There are a number of tests that cause resets in response to a power glitch manipulating ast's vcmain_pok, and chip_sw_pwrmgr_random_sleep_power_glitch_reset is one of them. We also have the test chip_sw_pwrmgr_full_aon_reset that triggers a glitch on vcaon_pok.

As for this comment

>Specifically for chip_sw_main_power_glitch_vseq, can you please let me know what is the purpose of those tests? As I understand it is not a functional scenario.

As I mentioned, it tests that the chip will issue a reset due to a power glitch. I guess we disagree this is not a functional scenario: it is a requirement for power manager to issue a reset for power glitches, and it causes a visible change in a CSR. It may not be easy to stimulate in silicon, but luckily we can trigger it in simulation and make sure a reset is issued. I'd characterize this as an indispensable test.

Back to the real issue with this PR, I would really like to understand how and why do you need to use pre and post apply_reset, and if there is no simple way to handle them differently I am willing to put them back, but not without examining them first.

We cannot stop making improvements to our environment unless we know of concrete problems due to the changes and we cannot address these problems in different and perhaps better ways, so let's try to find the specific problems :)

Thanks for your understanding.

2024-04-30 20:17 UTC, matutem commented
I put back in the pre and post_apply_rese callbacks. PTAL.

2024-05-01 09:48 UTC, rswarbrick approved these changes
This looks sensible to me, thanks.

2024-05-01 10:16 UTC, sha-ron commented on hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
> +    `DV_WAIT(cfg.chip_vif.pwrmgr_fast_pwr_state_active)
In some cases you might want to check things during the time from the reset until the CPU starts to run, maybe it worth adding a plusarg or something that allows to skip it.

2024-05-01 10:18 UTC, sha-ron requested changes
skip_por_n_during_first_pwrup is used in the closed source so please don't remove it.

2024-08-15 06:01 UTC, matutem commented on hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
> +    `DV_WAIT(cfg.chip_vif.pwrmgr_fast_pwr_state_active)
We used to wait till the ROM check what done. In the reset sequence that is the state exactly prior to when we enable CPU fetching, meaning a few clock ticks. I would be surprised if any test should depend on this change.

2026-04-20 19:17 UTC, rswarbrick commented
This PR seems to be stale, so closing.

2026-04-20 19:17 UTC, closed without merging