[sival,uart] Add test for UART baud rates
lowRISC/opentitan pull request #21194
Opened 2024-02-05 15:42 UTC by jwnrt

This test runs each UART with the system loopback enabled at various Baud rates and checks that the data is written and read correctly.

Resolves #19868.

Is it okay to use the system loopback here? If needed, I can add a host side to check the data but that will complicate the test.

Two of the Baud rates specified in the test plan cannot be checked on the FPGA because it doesn't clock high enough, but they should work fine on fully clocked silicon.

2024-02-05 17:07 UTC, engdoreis requested changes
By using the internal loopback we are not really validating the silicon, there are other parts that can impact the baud which are not exercised by the loopback (i.e pinmux).

2024-02-05 17:07 UTC, engdoreis commented on sw/device/tests/uart_baud_rate_test.c
> +      test_uart_baud(baud_rate);
I would use the macro `EXECUTE_TEST` here.

2024-02-06 10:54 UTC, jwnrt commented
Do you think I could somehow use the pinmux to create a loopback that would exercise the test better? I'd like to avoid having to use an opentitanlib test harness if possible because of how fiddly it is.

2024-02-06 17:25 UTC, jwnrt commented
I've changed the test to use a host side harness, but it's dependent on #21072 so will be failing for now. It passes when all the baud rates being tested are `115200` so can still be reviewed.

2024-02-07 09:50 UTC, rswarbrick approved these changes

2024-02-07 10:12 UTC, pamaury commented on sw/device/tests/uart_baud_rate_test.c
> +  for (size_t i = 0; i < sizeof(data); ++i) {
I think the loop is redundant?

2024-02-07 10:14 UTC, jwnrt commented on sw/device/tests/uart_baud_rate_test.c
> +  for (size_t i = 0; i < sizeof(data); ++i) {
Oops, yes it is

2024-02-07 10:14 UTC, jwnrt commented on sw/device/tests/uart_baud_rate_test.c
> +  OTTF_WAIT_FOR(baud_rate == 0, kTestTimeoutMillis);
This is a bad way of synchronising with the host and I want to replace it with something nicer

2024-02-07 10:20 UTC, pamaury approved these changes
It looks good to me modulo a small nit. I am no expert but the flow makes sense to me. I wonder if the `kSendData` should be a bit longer and/or contains specific bit patterns (like a lot of 0->1->0 transitions))? Feel free to ignore.

2024-02-11 00:34 UTC, jesultra commented
> I've changed the test to use a host side harness, but it's dependent on #21072 so will be failing for now. It passes when all the baud rates being tested are `115200` so can still be reviewed.

I apologize for the delay.  PR #21072 has merged now, meaning that opentitanlib should be able to control baud rate and parity on HyperDebug UART ports.

2024-02-12 10:32 UTC, jwnrt commented
> I apologize for the delay.

No problem, I hope I didn't rush you. Thanks for implementing that!

2024-02-14 14:31 UTC, jwnrt commented
I cannot work out what's wrong with `_fpga_cw310_test_rom` or `_rom_with_fake_keys`. It's like no data is going over the lines at all. I had a logic analyzer hooked up to the pins on the HyperDebug but didn't see the data moving across.

Anyway, I've just removed those two targets from the list of tests. I hope that's acceptible.

2024-02-15 11:04 UTC, engdoreis approved these changes

2024-02-15 11:04 UTC, merged

2024-02-16 16:03 UTC, jwnrt commented
Reopening until https://github.com/lowRISC/opentitan/pull/21513 updates the test plan