[usbdev] rx_fifo_sequence
lowRISC/opentitan pull request #21326
Opened 2024-02-13 09:46 UTC by Nadia-Hanif

This is the draft PR for rx_fifo sequence. It is just for code review.
@jdonjdon kindly review it. Thanks

2024-02-13 15:49 UTC, Nadia-Hanif commented
@jdonjdon Kindly review this. Thanks.

2024-02-15 15:30 UTC, jdonjdon reviewed
Are you going to update 
`usbdev_env.core`  `seq_lib/usbdev_vseq_list.sv` for these new sequences?

2024-02-15 15:37 UTC, Nadia-Hanif commented
> Are you going to update 
> 
> `usbdev_env.core`  `seq_lib/usbdev_vseq_list.sv` for these new sequences?

Yes i will update all those files once you approved the sequence.

2024-03-04 00:43 UTC, alees24 requested changes
Having deleted the lines mentioned in my comment, and added the changes described in PR #21805 the test 'usbdev_out_trans_nak' runs successfully.
For eg. 'usbdev_rx_fifo' it would really be helpful if you could please include the additions to 'dv/env/usbdev_env.core', 'dv/usbdev_sim_cfg.hjson' and 'dv/env/seq_lib/usbdev_vseq_list.sv' in the PR itself, please, so that tests may be simulated before reviewers approve them, rather than other way around.

2024-03-04 00:43 UTC, alees24 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_rx_fifo_vseq.sv
> +    csr_update(ral.avoutbuffer);
These lines appear to have been copied from earlier sequences, but they are not required and they conflict with recent changes to introduce separate FIFOs for SETUP and OUT buffers. Please remove them.

2024-03-04 00:43 UTC, alees24 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_out_trans_nak_vseq.sv
> +    csr_wr(.ptr(ral.intr_state), .value(32'h0001_ffff));  // clear interrupts
This write to intr_state is not required; that's what 'clear_all_interrupts()' is doing in a cleaner, more future proof manner, because it does not assume the number of interrupts defined.

2024-03-04 00:43 UTC, alees24 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_out_trans_nak_vseq.sv
> +    csr_update(ral.avbuffer);
These lines are not required either; they appear to have been copied to a lot of sequences, and purely to ensure that the 'rx_fifo_empty' is deasserted at the point of the 'body' task terminating.
They are no longer required in this sequence, or in the others. Please only present another buffer in the FIFO if it is going to be used within the test.

2024-03-04 04:53 UTC, Nadia-Hanif commented
> Having deleted the lines mentioned in my comment, and added the changes described in PR #21805 the test 'usbdev_out_trans_nak' runs successfully. For eg. 'usbdev_rx_fifo' it would really be helpful if you could please include the additions to 'dv/env/usbdev_env.core', 'dv/usbdev_sim_cfg.hjson' and 'dv/env/seq_lib/usbdev_vseq_list.sv' in the PR itself, please, so that tests may be simulated before reviewers approve them, rather than other way around.

Okay, i will update the necessary changes and include all other files.

2024-03-04 15:20 UTC, rswarbrick reviewed
As a general point about this PR: I suggest splitting it up into 4 separate PRs, with a vseq in each.

That way, they can be reviewed in parallel and are likely to be merged much more quickly. I've reviewed the first commit so far and will look at the later ones next.

2024-03-04 15:20 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_in_status_stage_vseq.sv
> +    cfg.clk_rst_vif.wait_clks(20);
What does this 20 clock wait do? It seems a little magic! Is there something specific that we're waiting for? (Or can we skip the wait entirely?)

2024-03-04 15:20 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_in_status_stage_vseq.sv
> +    cfg.clk_rst_vif.wait_clks(20);
Same question again: what does the 20 cycles do here? Is it needed?

2024-03-04 15:20 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_in_status_stage_vseq.sv
> +  task check_out_trans_accuracy();
I'd be tempted to rename this to something more descriptive. Something like `check_rxfifo_empty`?

2024-03-04 15:32 UTC, Nadia-Hanif commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_in_status_stage_vseq.sv
> +  task check_out_trans_accuracy();
> I'd be tempted to rename this to something more descriptive. Something like `check_rxfifo_empty`?

okay i will change this.

2024-03-04 18:02 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +      cfg.clk_rst_vif.wait_clks(20);
As on other commits, I think we need to think a bit about these waits. Why do we have 20 cycles here?

2024-03-04 18:02 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +      cfg.clk_rst_vif.wait_clks(20);
Another wait that I'm not sure about. Why 20 cycles here?

2024-03-04 18:27 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +      get_out_response_from_device(m_usb20_item, PidTypeAck);
This is a general question: why do we need to get a response in this vseq? I know that we're doing it in several different vseqs in the usbdev code, but it's only done in this block. What the extra sequence item that is created in `get_out_response_from_device` is doing? (Is there a simpler approach?)

2024-03-04 18:28 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +    csr_rd(.ptr(ral.rxfifo), .value(read_rxfifo));
Does reading `rxfifo` actually do anything here?

2024-03-04 18:28 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +  task check_trans_accuracy();
I'd probably suggest improving the name here. Maybe `check_av_out_empty`?

2024-03-05 04:42 UTC, Nadia-Hanif commented
> As a general point about this PR: I suggest splitting it up into 4 separate PRs, with a vseq in each.
> 
> That way, they can be reviewed in parallel and are likely to be merged much more quickly. I've reviewed the first commit so far and will look at the later ones next.

All these sequences are in different draft PRs.

2024-03-05 04:42 UTC, Nadia-Hanif commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +  task check_trans_accuracy();
okay i will change this.

2024-03-05 04:45 UTC, Nadia-Hanif commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_in_status_stage_vseq.sv
> +    cfg.clk_rst_vif.wait_clks(20);
The minimum inter-packet gap is supposed to be 2 bit times, so we need to include a delay between two packets. We could try reducing it, but unfortunately, we can't get rid of it completely.

2024-03-05 04:45 UTC, Nadia-Hanif commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +      endcase
okay i will try this.

2024-03-05 04:47 UTC, Nadia-Hanif commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +    endp = 4'd1;
As we need to send packets back-to-back to a specific endpoint, I've set the endp value to 1.

2024-03-05 04:47 UTC, Nadia-Hanif commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +   // Configure out transaction
okay i will fix this

2024-03-05 05:14 UTC, Nadia-Hanif commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +    super.dut_init("HARD");
> Why do we have to call `dut_init` explicitly here? I think it gets done by the base class in `pre_start`?

Yes, it is functioning without this. Thanks for bringing it to my attention.

2024-03-05 05:14 UTC, Nadia-Hanif commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +    csr_rd(.ptr(ral.rxfifo), .value(read_rxfifo));
Yes, it is working without this. Thanks for bringing it to my attention.

2024-03-05 06:13 UTC, Nadia-Hanif commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +    csr_rd(.ptr(ral.rxfifo), .value(read_rxfifo));
> Yes, it is working without this after the changes done on RTL side.

2024-03-05 11:08 UTC, rswarbrick commented
> All these sequences are in different draft PRs.

Ah, I see. In which case, the simplest thing might be to close this PR and promote the drafts to "non-drafts" :-) Thanks for the explanation.

2024-03-05 17:10 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_in_status_stage_vseq.sv
> +    cfg.clk_rst_vif.wait_clks(20);
That makes sense. What goes wrong if we try to send the data packet immediately after the token packet? Isn't there something which the vseq can see that tells it "it's ok to send the data packet now" ?

2024-03-06 05:51 UTC, Nadia-Hanif commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_in_status_stage_vseq.sv
> +    cfg.clk_rst_vif.wait_clks(20);
> That makes sense. What goes wrong if we try to send the data packet immediately after the token packet? Isn't there something which the vseq can see that tells it "it's ok to send the data packet now" ?

As I mentioned earlier, a minimum of 2 bit times is required between two packets. If we neglect this, it may result in skipping the initial bits of the PID. Consequently, the DUT (Design Under Test) won't respond correctly as it would receive an incorrect PID.

2024-03-08 11:27 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_in_status_stage_vseq.sv
> +    cfg.clk_rst_vif.wait_clks(20);
(I'm moving this discussion to #21852, which is a more recent PR doing the same thing). This is now at: https://github.com/lowRISC/opentitan/pull/21852#discussion_r1517596814

2024-03-08 12:02 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +      endcase
Tracked as https://github.com/lowRISC/opentitan/pull/21730#discussion_r1517624037.

2024-03-08 12:02 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +    endp = 4'd1;
Tracked as https://github.com/lowRISC/opentitan/pull/21730#discussion_r1517624865.

2024-03-08 12:03 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +    super.dut_init("HARD");
Tracked as https://github.com/lowRISC/opentitan/pull/21730#discussion_r1517625663.

2024-03-08 12:03 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_test_vseq.sv
> +    csr_rd(.ptr(ral.rxfifo), .value(read_rxfifo));
Tracked as https://github.com/lowRISC/opentitan/pull/21730#discussion_r1517629024.

2025-08-21 16:56 UTC, elliotb-lowrisc commented
Closing as no longer relevant

2025-08-21 16:56 UTC, closed without merging