[usbdev] Sequence_ISO_IN_STALL
lowRISC/opentitan pull request #21377
Opened 2024-02-15 07:56 UTC by MubashirSaleem775

Adds sequence usbdev_in_stall_vseq to verify the endpoint stall functionality.
Adds usbdev_in_iso_vseq to test the isochronous transaction functionality.
Adds usbdev_out_iso_vseq.

2024-02-15 12:16 UTC, MubashirSaleem775 commented
@jdonjdon please review this PR. Thanks

2024-02-15 15:26 UTC, jdonjdon approved these changes

2024-02-15 18:14 UTC, jdonjdon approved these changes
Let wait for Adrian's review since he is working on M2 RTL change as well.

2024-02-20 06:06 UTC, MubashirSaleem775 commented
@jdonjdon can you please share CI test failure log.

2024-03-05 17:21 UTC, rswarbrick requested changes
Please could you split this into three commits, which each add a vseq? I think there's some proper review needed for each of the sequences: it will probably be quicker if they can be reviewed in parallel.

The best thing is probably to open two new PRs (with a vseq each) and then force-push to this one with just one vseq.

2024-03-08 04:22 UTC, MubashirSaleem775 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_in_stall_vseq.sv
> +    csr_update(ral.avoutbuffer);
Okay i will remove this.

2024-03-08 04:23 UTC, MubashirSaleem775 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_in_iso_vseq.sv
> +    get_data_pid_from_device(m_usb20_item, PidTypeData0);
Okay.

2024-03-08 04:24 UTC, MubashirSaleem775 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_out_iso_vseq.sv
> +    csr_wr(.ptr(ral.intr_state), .value(32'h0001_ffff));
Okay

2024-03-08 06:49 UTC, MubashirSaleem775 commented
Thanks for you review comments.

I will add delay tasks in base_seq.

At present, the usb20_driver lacks the capability to gather IN transactions. However, I plan to address this in future pull requests (PRs).

2024-03-08 18:34 UTC, MubashirSaleem775 commented
I am goin to close this PR. i have added three separate PRs for each of three sequences with the changes you mentioned . The updated PR number is this : #21928

2024-03-08 18:34 UTC, closed without merging