[RV_DM]rv_dm_abstractcmd_status_vseq
lowRISC/opentitan pull request #21543
Opened 2024-02-18 14:40 UTC by BasitMehmood

This commit contains test sequence and other related files of #21381 testplan entry.

2024-02-19 08:42 UTC, BasitMehmood commented
@jdonjdon

2024-02-19 11:27 UTC, rswarbrick requested changes

2024-02-19 11:27 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
> +            do_read_check = 0;
Why are we disabling this check? Doing so might be right! But we need a comment that explains why we expect our RAL model to be wrong.

2024-02-19 11:27 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
> +      // The value in 'command' is access register command to send valid abstract command.
The fixed command register argument seems a little silly :-) Please move the literal into the body of `abstract_cmd` and get rid of the argument here.

2024-02-19 11:27 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
> +    repeat ($urandom_range(1, 10)) begin
Why do we need to do this several times? I can't see anything that gets randomised.

2024-02-19 11:27 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
> +      abstract_cmd(.ptr(tl_mem_ral.abstractcmd[0]),.command('h00AB0000),.cmd_val('h7b351073));
Does the value of `cmd_val` actually matter here? If not, I suggest you use a random 32-bit number (we don't have a processor to care about what command we're sending!)

2024-02-19 11:27 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
> +      csr_wr(.ptr(jtag_dmi_ral.dmcontrol.haltreq), .value(1));
Please fix the indentation here.

2024-02-19 11:27 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
> +      csr_wr(.ptr(tl_mem_ral.halted), .value(0));
Why are we writing to the `halted` register here? This is intended to be a read-only register that gets set by `rv_dm`.

2024-02-19 11:27 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
> +  task abstract_cmd (input uvm_object ptr, input int command, input int cmd_val);
For the first argument, it's probably easier to understand if you just pass the index. Then all the `tl_mem_ral.abstract_cmd` stuff doesn't need repeating.

2024-02-19 11:27 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
> +      abstract_cmd(.ptr(tl_mem_ral.abstractcmd[0]),.command('h00AB0000),.cmd_val('h7b351073));
Please also add spaces between arguments.

2024-02-19 11:27 UTC, rswarbrick commented on hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
> +      reseed: 10
Why 10 here? I can't see much being randomised in this vseq! Surely 1 or 2 would give the same confidence?

2024-02-19 12:20 UTC, BasitMehmood commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
> +      abstract_cmd(.ptr(tl_mem_ral.abstractcmd[0]),.command('h00AB0000),.cmd_val('h7b351073));
value in cmd_val is access register command with postexec bit unset and write and trasfer bit set.

2024-02-19 12:34 UTC, BasitMehmood commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
> +    repeat ($urandom_range(1, 10)) begin
ok i can remove it.

2024-02-19 15:07 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
> +      abstract_cmd(.ptr(tl_mem_ral.abstractcmd[0]),.command('h00AB0000),.cmd_val('h7b351073));
Oh! I mis-read this. So the point is that we're asking the debug module what is in `abstractcmd[0]`, and we happen to know that it should be `h7b351073`.

I've just glanced at `debug_rom.sv` and I can see this sequence. How do the abstract command indices map on to the locations in the boot rom? For example, I think that `abstractcmd[0]` is supposed to be correspond to memory address 15. How does that work?

Is there a way that we can do the ROM look-up on the DV side as well? That way, we could avoid encoding a magic value in the vseq.

2024-02-19 17:17 UTC, BasitMehmood commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
> +      abstract_cmd(.ptr(tl_mem_ral.abstractcmd[0]),.command('h00AB0000),.cmd_val('h7b351073));
There is address calculation mechanism in dm_mem.sv file on how after executing specific abstract command, hart jumps to abstractcmd region to execute these instructions and i was asked to look at it from rtl perspective. i think this is ok as well. we wanted to improve code coverage by adding tl_mem_ral.abstractcmd registers.

2024-02-21 15:33 UTC, rswarbrick commented
As a meta-point, this is going to need rebasing because it changes a couple of lists that have been updated by another PR in the meantime.

2024-02-21 15:38 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
> +      abstract_cmd(.ptr(tl_mem_ral.abstractcmd[0]),.command('h00AB0000),.cmd_val('h7b351073));
If I understand correctly, this test is supposed to be saying: "When I read the abstract command with index 0, by looking at `tl_mem_ral.abstractcmd[0]`, I should get the 32-bit number `h7b351073`".

Can you explain why this is the correct 32 bit number?

2024-02-21 15:41 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
> +            do_read_check = 0;
Thanks for adding a comment. If we happen to know what the registers should contain (I don't! But hopefully you do...), would it make much more sense to leave this check enabled and drop the explicit checks in the vseq. Yes, we'll have to ensure the RAL model correctly reflects the values we expect. But they are read-only! This should be reasonably easy!

2024-02-22 07:59 UTC, BasitMehmood commented on hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
> +            do_read_check = 0;
I have checked as you suggested but in scoreboard on line 362 csr.get_mirrored_value() check failed. do_read_check also disabled in whereto and flags registers and they are RO as well. i think hw can update value so we have to check manually.

2024-02-22 12:56 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
> +            do_read_check = 0;
Oof. I've just looked more carefully at the design. (For future me...) the "ROM" that backs `abstractcmd` can be found in `dm_mem.sv`. In particular, reads are handled in the `p_abstract_cmd_rom` block.

Anyway, I'm convinced. Maybe add a comment that says something like "Disable the read check. We don't model the contents of the abstractcmd registers." ?

2024-02-22 13:01 UTC, rswarbrick commented
Ah, this isn't quite the right way to handle merges/conflicts. We use rebasing, and keep a linear history.

I've just tidied things up with:
```
rjs@sole:~/work/opentitan$ git reset --hard f72acb
HEAD is now at f72acb7c18 [RV_DM]rv_dm_abstractcmd_status_vseq
rjs@sole:~/work/opentitan$ git rebase origin/master
Auto-merging hw/ip/rv_dm/dv/env/rv_dm_env.core
CONFLICT (content): Merge conflict in hw/ip/rv_dm/dv/env/rv_dm_env.core
Auto-merging hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
CONFLICT (content): Merge conflict in hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
Auto-merging hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
CONFLICT (content): Merge conflict in hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
error: could not apply f72acb7c18... [RV_DM]rv_dm_abstractcmd_status_vseq
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply f72acb7c18... [RV_DM]rv_dm_abstractcmd_status_vseq

rjs@sole:~/work/opentitan$ # Manually fix the merge conflicts...

rjs@sole:~/work/opentitan$ git push -f basit HEAD:abstractcmd_status_vseq 
Enumerating objects: 24, done.
Counting objects: 100% (24/24), done.
Delta compression using up to 8 threads
Compressing objects: 100% (13/13), done.
Writing objects: 100% (13/13), 1.84 KiB | 628.00 KiB/s, done.
Total 13 (delta 11), reused 1 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (11/11), completed with 11 local objects.
To github.com:BasitMehmood/opentitan.git
 + 5d628ff351...3b1fc87b26 HEAD -> abstractcmd_status_vseq (forced update)
```

2024-02-22 13:32 UTC, rswarbrick commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
> +      abstract_cmd(.ptr(tl_mem_ral.abstractcmd[0]),.command('h00AB0000),.cmd_val('h7b351073));
Right, I've done a bit more reading and I understand a bit more. (For future me: This comes from `dm_mem.sv`, line 444.)

Probably all we need is a comment, but I'd probably suggest pulling the ROM out into something explicit. Maybe something like this?

(I tidied up the code slightly, and pulled the unnecessary repeated haltreq and command writes out of the loop)

```systemverilog
  // The expected contents of the debug ROM that we will read through the abstract command
  // interface.
  bit [31:0] exp_debug_rom[10] = { 'h7b351073, 'h00000517, 'h00c55513, 'h00c51513,
                                   'h7b241073, 'h38052403, 'h00041073, 'h7b202473,
                                   'h7b302573, 'h00100073 };

  task body();
    uvm_reg_data_t r_data;

    csr_wr(.ptr(jtag_dmi_ral.dmcontrol.haltreq), .value(1));
    csr_wr(.ptr(tl_mem_ral.halted), .value(0));

    csr_wr(.ptr(jtag_dmi_ral.command), .value('h00AB0000));
    csr_rd(.ptr(jtag_dmi_ral.abstractcs), .value(r_data));
    `DV_CHECK_EQ(1, get_field_val(jtag_dmi_ral.abstractcs.busy, r_data));

    for (int i = 0; i < 10; i++) begin
      // The value in 'command' is access register command to send valid abstract command.
      csr_rd(.ptr(tl_mem_ral.abstractcmd[i]), .value(r_data));
      `DV_CHECK_EQ(exp_debug_rom[i], r_data)
    end
  endtask
```

2024-02-23 05:13 UTC, BasitMehmood commented
> Ah, this isn't quite the right way to handle merges/conflicts. We use rebasing, and keep a linear history.
> 
> I've just tidied things up with:
> 
> ```
> rjs@sole:~/work/opentitan$ git reset --hard f72acb
> HEAD is now at f72acb7c18 [RV_DM]rv_dm_abstractcmd_status_vseq
> rjs@sole:~/work/opentitan$ git rebase origin/master
> Auto-merging hw/ip/rv_dm/dv/env/rv_dm_env.core
> CONFLICT (content): Merge conflict in hw/ip/rv_dm/dv/env/rv_dm_env.core
> Auto-merging hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
> CONFLICT (content): Merge conflict in hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
> Auto-merging hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
> CONFLICT (content): Merge conflict in hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
> error: could not apply f72acb7c18... [RV_DM]rv_dm_abstractcmd_status_vseq
> hint: Resolve all conflicts manually, mark them as resolved with
> hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
> hint: You can instead skip this commit: run "git rebase --skip".
> hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
> Could not apply f72acb7c18... [RV_DM]rv_dm_abstractcmd_status_vseq
> 
> rjs@sole:~/work/opentitan$ # Manually fix the merge conflicts...
> 
> rjs@sole:~/work/opentitan$ git push -f basit HEAD:abstractcmd_status_vseq 
> Enumerating objects: 24, done.
> Counting objects: 100% (24/24), done.
> Delta compression using up to 8 threads
> Compressing objects: 100% (13/13), done.
> Writing objects: 100% (13/13), 1.84 KiB | 628.00 KiB/s, done.
> Total 13 (delta 11), reused 1 (delta 0), pack-reused 0
> remote: Resolving deltas: 100% (11/11), completed with 11 local objects.
> To github.com:BasitMehmood/opentitan.git
>  + 5d628ff351...3b1fc87b26 HEAD -> abstractcmd_status_vseq (forced update)
> ```

Thankyou so much for guiding me. I was doing the same thing. When there are conflicts I first update my local repository with lowRISC repository. Then I rebase the changes and manually resolve the conflicts and  add those conflicted files by git add... command.  When i do "git commit --amend"  I got some other person commit message. For example there was a commit message signed off by alex williams" TMP port name change". I got this issue. when I do force push, there were changes done by me but with alex-williams commit message. After that i commit with "git commit -s" command.

2024-02-23 05:29 UTC, BasitMehmood commented on hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
> +      abstract_cmd(.ptr(tl_mem_ral.abstractcmd[0]),.command('h00AB0000),.cmd_val('h7b351073));
Thankyou.

2024-02-23 10:10 UTC, rswarbrick approved these changes
The changes look good, thanks. Unfortunately, the commits are still a bit wonky: there are now 3 commits and the change that you are trying to make is what you get after merging each of them.

I've just squashed the three together and will force-push with the squashed result.

Thanks for the work!

2024-02-23 10:12 UTC, merged

2024-02-23 10:19 UTC, BasitMehmood commented
> The changes look good, thanks. Unfortunately, the commits are still a bit wonky: there are now 3 commits and the change that you are trying to make is what you get after merging each of them.
> 
> I've just squashed the three together and will force-push with the squashed result.
> 
> Thanks for the work!

CI(quality lint) check is failing. it says signed-off issue in commit message.