[hw,dma,rtl] Enable TL-UL integrity checks on response
lowRISC/opentitan pull request #21618
Opened 2024-02-22 09:34 UTC by Razer6

It was discovered that integrity checks on the TL-UL response were not enabled. This PR adds a new parameter to enable integrity checks for both TL-UL ports

2024-02-22 10:16 UTC, andreaskurth reviewed
Implementation-wise this LGTM.

Architecturally, I'd like to flag that this means that incorrect data integrity bits on the CTN response port will lead to a fatal alert. So a misbehavior / malfunction on the CTN side could DoS Darjeeling. Did you take that into account when deciding to enable integrity checks on data responses in the DMA? Alternatively, integrity checks could be enabled on the OT-internal port only.

2024-02-22 10:26 UTC, Razer6 commented
> Architecturally, I'd like to flag that this means that incorrect data integrity bits on the CTN response port will lead to a fatal alert. So a misbehavior / malfunction on the CTN side could DoS Darjeeling. Did you take that into account when deciding to enable integrity checks on data responses in the DMA? Alternatively, integrity checks could be enabled on the OT-internal port only.

Thanks for the review. Let me double check internally.

2024-02-22 10:56 UTC, andreaskurth commented
> Thanks for the review. Let me double check internally. I guess a different solution would be a recoverable alert on CTN integrity errors?

Indeed, for which FW can [define escalation criteria and mechansims](https://opentitan.org/book/hw/top_earlgrey/ip_autogen/alert_handler/doc/theory_of_operation.html#escalation-mechanisms)

2024-02-22 11:27 UTC, Razer6 commented
I proactively implemented a recoverable alert for CTN integrity errors. Can you take a look into this but wait for merging it?

2024-02-22 13:05 UTC, alees24 requested changes
I guess you've seen this:
```
sw/lib/sw/device/silicon_creator/shutdown.c:42:1: error: static assertion failed due to requirement '100 <= 396 / 4': More alerts than alert classification OTP words!
static_assert(ALERT_HANDLER_ALERT_CLASS_SHADOWED_MULTIREG_COUNT <=
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/lowrisc_rv32imcb_files/riscv32-unknown-elf/include/assert.h:45:24: note: expanded from macro 'static_assert'
```
Otherwise LGTM.

2024-02-22 19:31 UTC, Razer6 commented
We decided to accept the fatal alert for integrity errors coming from the CTN. Thus I dropped the last commit and stays with the one that @andreaskurth has reviewed first.

2024-02-23 20:16 UTC, andreaskurth approved these changes
Thanks for double-checking that these fatal errors are architecturally desired -- LGTM.

(And, as discussed out-of-band, FW such as ROM can classify alerts differently if needed, though a fatal alert will keep getting sent until reset.)

2024-02-23 20:17 UTC, andreaskurth commented
CHANGE AUTHORIZED: hw/ip/dma/data/dma.hjson
CHANGE AUTHORIZED: hw/ip/dma/rtl/dma.sv
CHANGE AUTHORIZED: hw/top_darjeeling/rtl/autogen/top_darjeeling.sv

2024-02-23 20:59 UTC, alees24 approved these changes
Thanks.

2024-02-23 21:10 UTC, msfschaffner commented
CHANGE AUTHORIZED: hw/ip/dma/data/dma.hjson
CHANGE AUTHORIZED: hw/ip/dma/rtl/dma.sv
CHANGE AUTHORIZED: hw/top_darjeeling/rtl/autogen/top_darjeeling.sv

2024-02-23 21:20 UTC, merged