Update lowrisc_ibex to lowRISC/ibex@5a8a1a99
lowRISC/opentitan pull request #21768
Opened 2024-02-29 17:40 UTC by GregAC

Update code from upstream repository
https://github.com/lowRISC/ibex.git to revision
5a8a1a99930afbb9efe107ff2c80d482239d7a5f

* [tracer] Fix reporting of load/store data (Adrian Lees)
* Update old `cpuctrl` CSR name in `cs_registers.rst` (Luís Marques)
* [doc] Require sphinx version >= 7.0 (Greg Chadwick)
* [rtl] Harden lockstep enable against FI (Pascal Nasahl)

2024-02-29 17:47 UTC, marnovandermaas submitted a review, later dismissed
These changes look reasonable to me and have already been reviewed in the ibex repo.

2024-02-29 17:48 UTC, marnovandermaas commented
There does seem to be a lint error in the lockstep:
```
ERR  [#59730] : on line 144 in file ../src/lowrisc_ibex_ibex_top_0.1/rtl/ibex_lockstep.sv
```

2024-02-29 17:58 UTC, marnovandermaas commented
This error is because the `cnt_next_o` output has been renamed to `cnt_after_commit_o` in the OpenTitan repo, but this has not been vendored into Ibex yet. Shall we fix this in Ibex before pulling this across to OpenTitan?

2024-02-29 18:04 UTC, marnovandermaas requested changes
We need to change the way that `prim_count` is used. At the very least the `commit_i` must be set to 1.

2024-02-29 18:13 UTC, GregAC commented
Opened a PR against Ibex to make the required changes: https://github.com/lowRISC/ibex/pull/2145

2024-03-01 10:34 UTC, marnovandermaas commented
Cool once you bump Ibex to https://github.com/lowRISC/ibex/commit/27dd6b2e06f3110904dda9db1abc4e1d466db30a we should be good to merge this PR.

2024-03-01 11:22 UTC, marnovandermaas commented
Another few complaints by Kokoro:
```
E   RESET_DRIVER:   ibex_lockstep.sv:165   'rst_shadow_set_q[0]' is driven by instance 'u_prim_rst_shadow_set_flop' of module 'prim_flop', and used as an asynchronous reset 'rst_ni' at ibex_if_stage.sv:449   ibex_if_stage.sv:449      New                            
E   RESET_DRIVER:   ibex_lockstep.sv:165   'q_o[0]' driven in module 'prim_flop' by port 'gen_generic.u_impl_generic.q_o[0]' at prim_flop.sv:47                                                                 prim_flop.sv:47           New                            
E   RESET_DRIVER:   ibex_lockstep.sv:165   'q_o[0]' driven in module 'prim_generic_flop' at prim_generic_flop.sv:21                                                                                             prim_generic_flop.sv:21   New                            
E   RESET_USE:   ibex_lockstep.sv:181           'enable_cmp_d[0]' is connected to 'prim_flop' port 'd_i[0]', and used as an asynchronous reset or set 'rst_ni' at ibex_if_stage.sv:449   ibex_if_stage.sv:449          New     
```
Let me know if you want me to investigate these.

2024-03-01 12:46 UTC, GregAC commented
As the way the lockstep reset had been reworked some waivers needed adjusting. I've done that now it will hopefully pass lint.

2024-03-01 17:06 UTC, GregAC commented
Adding @nasahlpa as a reviewer to check he agrees with my tweaks to the lint waivers.

2024-03-01 17:16 UTC, nasahlpa commented
Thanks for the update! The waivers LGTM!

2024-03-01 17:16 UTC, nasahlpa approved these changes

2024-03-01 18:38 UTC, msfschaffner approved these changes

2024-03-02 18:43 UTC, GregAC commented
@marnovandermaas are you happy to approve this now?

2024-03-04 09:43 UTC, marnovandermaas approved these changes
Thanks for fixing all the lints.

2024-03-04 09:54 UTC, merged