[usbdev,dv] usbdev_dv_env_changes
lowRISC/opentitan pull request #21837
Opened 2024-03-05 13:02 UTC by MubashirSaleem775

Adds changes in DV env to support error cases like timeout, PID error, CrC error and bitstuff error.

2024-03-05 14:59 UTC, rswarbrick requested changes

2024-03-05 14:59 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +  endtask
Looking a bit more carefully at your code, I think the `time_out` task can complete without killing `get_response_pid`. Would this be correct?
```systemverilog
    bit timed_out = 1'b0;

    fork begin : isolation_fork
      fork
        begin
          repeat (18) begin
            @(posedge cfg.bif.usb_clk);
            if (cfg.bif.usb_dp_en_o) break;
          end
          if (!cfg.bif.usb_dp_en_o) timed_out = 1'b1;
        end
        get_response_pid(rsp_item);
      join_any
      disable fork;

      if (timed_out) begin
        rsp_item.m_pid_type = pid_type_e'(PidTypeTimeOut);
      end
    end join
```

2024-03-05 14:59 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_driver.sv
>      end
Is this just the same as:
```systemverilog
received_pid = decoded_received_pid[15:8];
```

If so, maybe that would be simpler?

2024-03-05 14:59 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +      while (cfg.bif.usb_dp_en_o) begin
I think you can get rid of the `if` here: the `while` loop won't do anything if `cfg.bif.usb_dp_en_o` is already false.

2024-03-05 14:59 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +        received_pkt = new[received_pkt.size() + 1](received_pkt);
Why aren't we just using a queue for `received_pkt`? I think it would be rather simpler.

2024-03-05 14:59 UTC, rswarbrick commented on hw/ip/usbdev/dv/tb/tb.sv
> +    uvm_config_db#(virtual usb20_block_if)::set(null, "*.env*","bif",usb20_block_if);
I know they were missing before, but... missing spaces between the arguments here.

2024-03-05 14:59 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/usbdev_env_cfg.sv
> +  virtual usb20_block_if bif;
I see that the `tb.sv` change is setting this virtual interface instead of one in the agent. Don't we also have to delete a handle from the agent class?

2024-03-05 16:00 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
> +      PidTypeStall = 8'b1110_0001, PidTypeNyet = 8'b0110_1001, PidTypeTimeOut = 8'b1100_1100} pid_type_e;
okay i will do .

2024-03-05 16:00 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
>      end
okay, l will try this way.

2024-03-05 16:01 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
>      end
Okay

2024-03-06 05:38 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +    end else begin
sure

2024-03-06 07:29 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
>      end
we can't do this because The type of the target is 'bit[7:0]', while the type of the 
  source is 'bit$[]

2024-03-06 07:44 UTC, MubashirSaleem775 commented on hw/ip/usbdev/dv/env/usbdev_env_cfg.sv
> +  virtual usb20_block_if bif;
Yes, however, this virtual is utilized in the agent, which is why we require this handle within the agent.

2024-03-06 08:08 UTC, MubashirSaleem775 commented on hw/ip/usbdev/dv/tb/tb.sv
> +    uvm_config_db#(virtual usb20_block_if)::set(null, "*.env*","bif",usb20_block_if);
okay

2024-03-06 08:10 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +  endtask
I attempted this, but it didn't work for both scenarios, namely timeout and get_response_pid. That's why I made some modifications in the updated commit.

2024-03-06 10:15 UTC, MubashirSaleem775 commented
@rswarbrick can you please log of DV_smoke failue.

2024-03-11 16:03 UTC, rswarbrick commented
As a general comment, please could you rebase over recent changes to the code? There are currently merge conflicts with some tidyups that @alees24 merged last week.

2024-03-11 16:05 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_driver.sv
>      end
Oh, how annoying! :-) Thanks for the explanation.

2024-03-11 16:06 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +      while (cfg.bif.usb_dp_en_o) begin
Thanks for tidying this up. Something seems to have got a little unstuck with the indentation though. Would you mind re-aligning?

2024-03-11 16:10 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/usbdev_env_cfg.sv
> +  virtual usb20_block_if bif;
Ahah, I see. Thanks for the explanation.

2024-03-11 16:11 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +  endtask
Thanks for tidying this up: I think it looks much better.

2024-03-19 15:55 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +      while (cfg.bif.usb_dp_en_o) begin
okay

2024-03-19 17:29 UTC, rswarbrick requested changes

2024-03-19 17:29 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
> -  // TODO: these are presently nibble-swapped relative to the specification.
This is not mergeable yet: you are dropping a TODO comment which is still true. Please could you put it back?

2024-03-19 17:29 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
> +  typedef enum byte {bRequestGET_STATUS = 8'h00,
Nit: Missing newline after the `{`

2024-03-19 17:29 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +  task single_se0_end_of_packet();
Isn't this equivalent to `end_of_packet` but with just one iteration around the loop? Probably better to encode this with an optional argument in the existing task?
```
task end_of_packet(bit single_se0 = 1'b0);
```

2024-03-19 17:29 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_agent_cfg.sv
> +  bit single_bit_SE0 =1'b0;
These fields need comments that explain what they do.

2024-03-19 17:29 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +   bit timed_out = 1'b0;
Nit: indentation is off here.

2024-03-19 17:29 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_driver.sv
>    task get_dut_response(ref usb20_item rsp_item);
This task needs a comment that explains what it does. (I know that this is true about other tasks in the same file, but we're touching this one!)

Can you describe the behaviour in a sentence or two and put it into a comment above the task?

2024-03-19 17:29 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +          end
Can't this be written slightly more simply with something like this? (untested)
```systemverilog
    fork begin : isolation_fork
      fork
        get_response_pid();
        begin
          repeat (18) begin
            @(posedge cfg.bif.usb_clk);
            if (cfg.bif.usb_dp_en_o) break;
          end
          timed_out = 1'b1;
        end
      join_any
      disable fork;
      if (timed_out) begin
        rsp_item.m_pid_type = pid_type_e'(PidTypeTimeOut);
      end
    end join
```

Note that we no longer have to give a process to the `disable` call, which seems a bit simpler to understand.

2024-03-19 17:29 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +        received_pkt.push_back(cfg.bif.usb_p);
Nit: Indentation.

2024-03-19 17:29 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/usbdev_env.sv
> +        `uvm_fatal(`gfn, "failed to get usb20_block_if handle from uvm_config_db")
Nit: Two spaces too many here.

(But thanks for fixing the indentation a couple of lines further up)

2024-03-20 10:42 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_agent_cfg.sv
> +  bit single_bit_SE0 =1'b0;
ok

2024-03-20 10:43 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
> +  typedef enum byte {bRequestGET_STATUS = 8'h00,
okay

2024-03-20 10:43 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +  task single_se0_end_of_packet();
sure

2024-03-20 10:44 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
>    task get_dut_response(ref usb20_item rsp_item);
okay

2024-03-20 10:47 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +   bit timed_out = 1'b0;
ok

2024-03-20 10:49 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +        received_pkt.push_back(cfg.bif.usb_p);
ok

2024-03-20 10:55 UTC, MubashirSaleem775 commented on hw/ip/usbdev/dv/env/usbdev_env.sv
> +        `uvm_fatal(`gfn, "failed to get usb20_block_if handle from uvm_config_db")
ok

2024-03-21 05:50 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +          end
i tested but it works only when there is a time out case for device response it not works.

2024-03-26 17:11 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +        end
Wouldn't it be simpler to put the 18 clock wait into the top of `get_device_response`? That would also allow us to get rid of the complicated fork/join stuff. Something like this maybe? (untested!)
```systemverilog
...
    bit bitstuff_err;
    bit use_negedge;
    int time_before_response = 0;

    // Wait up to 18 clock cycles for the start of a response from the device, matching section
    // 7.1.19.1 of the USB specification.
    //
    // TODO: We currently spot this by looking at the driver enable of the DUT. We shouldn't really
    //       be stealing access to that signal and should be inferring that the device is responding
    //       by just looking at the USB_P/USB_N signals.
    for (time_before_response = 0; time_before_response < 18; time_before_response++) begin
      if (cfg.bif.usb_dp_en_o) break;
      @(posedge cfg.bif.usb_clk);
    end
    if (time_before_response >= 18) begin
      rsp_item.m_pid_type = pid_type_e'(PidTypeTimeOut);
      return;
    end

    // TODO: Operating on a div 4 clock is inherently fraught and runs into sampling problems;
    // a simple solution would be to use the 4x oversampling and detect the initial transition away
    // from Idle state, then choose an appropriate sampling phase [0,3] on the 4x clock.
    //
    // Here, for now, we just choose the clock edge to sidestep sampling errors.
...
```

@alees24: Have I understood the spec correctly here? I'm definitely not an expert... In particular, I *think* I've understood your TODO comment, but I had to think quite hard about it! Is my expansion right?

2024-03-27 08:08 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_agent_cfg.sv
> +  // its respective test sequence, followed by the transmission of a single-bit SE0 as EOP.
okay

2024-03-27 10:33 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +    end
sure, i will do that way. Thanks

2024-03-27 10:34 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
> +    PidTypeOutToken   = 8'b0001_1110,
yes its doable and its done in other PR by @alees24

2024-03-29 11:28 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +        end
This not works properly i have tested this. its works well for timeout case. for other scenario it didn't works.

2024-04-02 08:58 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +        end
Ok, thanks. Could you explain what doesn't work?

2024-04-02 12:53 UTC, rswarbrick requested changes
I've spent a vast amount of time reviewing this code and I'm *still* finding silly indentation problems.

And your practice of hiding conversations means that I have to wade through all the (MANY!) reviews that I have already written on this PR to figure out what is going on.

Reviewing this code is taking a significant chunk of my time and it's very unclear that it's worth the effort. Please tidy things up and respond in sentences to the reviews that I'm leaving.

2024-04-02 12:53 UTC, rswarbrick commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +    end
Please fix the indentation here. (I think you need two spaces more on each line)

2024-04-02 16:04 UTC, alees24 requested changes

2024-04-02 16:04 UTC, alees24 commented on hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
> +    PidTypeTimeOut = 8'b1100_1100
I'm not happy with introducing invented PID values because there is nothing that stops the invented value being transmitted/received over the USB in the presence of communication errors, device malfunction etc.

The PID is specified in terms of its 4 LSBs, which are then complemented to provide the full 8 bits that are transmitted/received over the wire.

By introducing additional values, for DV convenience, we compromise the error detection as well as increasing the risk of the DV code misbehaving, not least because we presently do not even perform a validity check on the received/decoded PID.

Please use an additional variable/state information to indicate exceptional conditions such as timeout, since there shall be additional error condition over time. The additional information probably needs to be stored in the 'usb20_item' object.

2024-04-02 16:07 UTC, alees24 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +    end
A few observation here:

    this approach may stop the packet being decoded by the USB device, leading to spurious test failures, because the randomized range overlaps the device address and endpoint number too.
    the code here is choosing a 7-bit region not the 6 bits annotated in the comment.
    the final bit (a '1') of the SYNC pattern is included in the bit stuffed sequence, although a valid PID cannot induce bit stuffing until the affected 6-bit sequence involves the final 3 bits (the MSBs) of the PID and the first 3 bits (LSBs) of the device address.
    a more robust approach, if the test is expected to guarantee a bit stuffing violation would be to have it control the device address, endpoint number and/or contents of the data packet, and then deactivate the bit stuffing functionality of the usb20_driver when driving that packet onto the USB.

2024-04-05 05:11 UTC, MubashirSaleem775 commented on hw/dv/sv/usb20_agent/usb20_driver.sv
> +        end
The suggested code isn't functioning properly. In a fork-join scenario, there are two possibilities: either the device responds with a packet based on the current transaction, or it doesn't respond at all, and we must wait up to 18 bit times for the transaction to time out and end the test. Your suggested code handles the timeout scenario well, but when the device responds with packets, it often results in incorrect packet identification (PID) or packet sizes smaller than expected. However, the monitor still accurately captures the packets. The main issue is that the code doesn't initiate at the right time to capture the device's response.

2024-04-19 10:43 UTC, MubashirSaleem775 commented
@rswarbrick @alees24  I am going to close this PR because there a few changes required in dv Env not all in this PR. I have tried to drop extra changes but not able to drop. So  I have added a new PR (#22722). Kindly review. Thanks

2024-04-19 10:43 UTC, closed without merging