[usbdev,dv] usbdev resume link active seq PR
lowRISC/opentitan pull request #21854
Opened 2024-03-06 07:07 UTC by Saad22386

This PR contains usbdev_resume_link_active_vseq that implements resume functionality of usbdev from link_powered_state

2024-03-06 09:53 UTC, Saad22386 commented
@rswarbrick, kindly review it
Thanks

2024-03-11 15:59 UTC, rswarbrick requested changes
Looking at the testplan, I see:
```
            - Read the link state from usbstate register to see if it is in powered state and then send the
              resume signal (K state) for 20 ms and set the usbctrl.resume_link_active.
```

I don't think I can see anything in the code that waits 20ms. Can you explain how your code matches the testplan? I suspect that we either need to fix the testplan or there's a minor bug in the code itself.

2024-03-11 15:59 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_resume_link_active_vseq.sv
> +    super.dut_init("HARD");
I don't think we actually need to do this extra initialisation. Is it required for the test at your end?

2024-03-11 15:59 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_resume_link_active_vseq.sv
> +    cfg.clk_rst_vif.wait_clks(154000);
That's reasonable but (obviously) depends on the clock speed. I'd probably add "... at 48MHz" to the end of the comment.

2024-03-11 18:00 UTC, Saad22386 commented
> Looking at the testplan, I see:
> 
> ```
>             - Read the link state from usbstate register to see if it is in powered state and then send the
>               resume signal (K state) for 20 ms and set the usbctrl.resume_link_active.
> ```
> 
> I don't think I can see anything in the code that waits 20ms. Can you explain how your code matches the testplan? I suspect that we either need to fix the testplan or there's a minor bug in the code itself.

We don't need to wait for 20ms i think description need to rewrite. To resume from link_powered state just need to set the usbctrl.resume_link_active.

2024-03-11 18:01 UTC, Saad22386 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_resume_link_active_vseq.sv
> +    super.dut_init("HARD");
Yes it's required at our end

2024-03-11 18:04 UTC, Saad22386 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_resume_link_active_vseq.sv
> +    cfg.clk_rst_vif.wait_clks(154000);
Ok I'll add

2024-03-14 10:47 UTC, Saad22386 commented
> Ok, that makes sense. Could you make that change? The best thing is probably to add another commit that comes first in this PR and tweaks the testpoint description.
> 
> If you think there might be some discussion, the other option would be to open a separate PR to track it.

yes i have made that change You can look at it.

2024-03-19 16:02 UTC, rswarbrick commented
I'm sorry: we're talking past each other slightly. I'm proposing that you change the testpoint description in a separate commit (and possibly separate PR). That way, the reviews of the two changes can proceed in parallel.

2024-03-20 07:10 UTC, Saad22386 commented
> I'm sorry: we're talking past each other slightly. I'm proposing that you change the testpoint description in a separate commit (and possibly separate PR). That way, the reviews of the two changes can proceed in parallel.

can you look into #22129 that contains the change in test description?

2024-05-08 09:21 UTC, closed without merging