Stall priority over nak sequence
lowRISC/opentitan pull request #21853
Opened 2024-03-06 06:22 UTC by Nadia-Hanif

This PR contains stall priority over nak response.
In this sequence we have set the endpoint to both stall and nak.
Stall will take priority and in response we will get the stall pid.

2024-03-06 08:45 UTC, Nadia-Hanif commented
@rswarbrick kindly reveiw this. Thanks.

2024-03-08 12:08 UTC, rswarbrick commented
Things have got a little messed up with the multiple commits here. I'm going to force-push to the branch, dropping all but the last commit and fixing the merge conflicts we end up with. I *think* the end result is the version that you intended to submit.

2024-03-08 12:16 UTC, rswarbrick requested changes
Some nitty comments on the style, but I've got a more fundamental question: why does this test the behaviour described in the testpoint?

I can't see anything where we check that the stall handshake took priority.

There's not much point in writing this test without that check...

2024-03-08 12:58 UTC, Nadia-Hanif commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_stall_priority_over_nak_vseq.sv
> +    csr_update(ral.set_nak_out[0]);
okay i will change this

2024-03-08 13:00 UTC, Nadia-Hanif commented on hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
> +      name: usbdev_stall_priority_over_NAK
This name is specified in the test plan, and I have to add this same in this file.

2024-03-08 13:06 UTC, Nadia-Hanif commented
> Some nitty comments on the style, but I've got a more fundamental question: why does this test the behaviour described in the testpoint?
> 
> I can't see anything where we check that the stall handshake took priority.
> 
> There's not much point in writing this test without that check...

We are currently verifying the behavior defined by the following code: get_out_response_from_device(m_usb20_item, PidTypeStall); According to this test scenario, we have configured the endpoint to exhibit both NAK and STALL conditions. However, in this specific case, the STALL condition is expected to take precedence, resulting in a stall response from the device.

Thus, the purpose of this check is to ensure that the device indeed responds with a stall. If the device responds with NAK instead, this verification check should fail.

2024-03-08 17:07 UTC, rswarbrick commented on hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
> +      name: usbdev_stall_priority_over_NAK
That makes sense, but I don't know how we ended up with stray capitals in the testplan. Could you file a PR in parallel that lower-cases the name again?

2024-03-08 17:12 UTC, rswarbrick commented
Ah, good point about the pid-type check: that makes loads of sense. Could you add a comment just above that line to make it stick out? Something like "Passing PidTypeStall here means that get_out_response_from_device checks this is was a stall (instead of a NAK)"

2024-03-11 07:07 UTC, Nadia-Hanif commented
> Ah, good point about the pid-type check: that makes loads of sense. Could you add a comment just above that line to make it stick out? Something like "Passing PidTypeStall here means that get_out_response_from_device checks this is was a stall (instead of a NAK)"

Okay i will add the comment and will push this again.

2024-03-14 10:35 UTC, rswarbrick commented
Thanks for the changes that you've made. I've just taken the top of this PR, dropped the unrelated commits, rebased and got everything compiling again.

I also dropped the stray `dut_init`.

The new version of the PR starts with a commit which comes from #22029 and is needed for getting stuff compiling again. We should merge that PR first.

2024-03-15 10:21 UTC, Nadia-Hanif commented
> Thanks for the changes that you've made. I've just taken the top of this PR, dropped the unrelated commits, rebased and got everything compiling again.
> 
> 
> 
> I also dropped the stray `dut_init`.
> 
> 
> 
> The new version of the PR starts with a commit which comes from #22029 and is needed for getting stuff compiling again. We should merge that PR first.

There is one check failing. Do i have to force push again?

2024-03-19 15:32 UTC, rswarbrick commented
The failing CI check is because of a line that's too long. If you click on the "details" link just to the right of the failed check, it should show you what's going wrong.

That will need fixing, and you'll also need to rebase onto the head of master.

However I notice that this will conflict with the change in #22030. Probably the best approach is to grab the commit at the head of that PR and stick it at the start of the merge queue for this one. That way, we'll be able to get this work reviewed in parallel.

2024-03-21 21:56 UTC, rswarbrick reviewed
Something has gone a little awry with the rebasing here. (The second commit deletes some of the stuff in the first commit!) Presumably you haven't run the head of this PR on any machine: it won't have worked, since it's calling a task that doesn't exist.

But that's just a silly git problem. I'm going to force-push with a fix for that issue. Otherwise, this looks pretty sensible to me.

2024-03-26 16:15 UTC, rswarbrick reviewed
I've just force-pushed to rebase over recent base sequence changes. One last question, but I think this is looking pretty sensible.

2024-03-26 16:15 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_stall_priority_over_nak_vseq.sv
> +    inter_packet_delay();
Do we actually need an extra delay here? I don't think I can see anything that is happening after the delay that needs to wait a bit. I think the test will still work if this goes away?

2024-03-27 12:05 UTC, rswarbrick approved these changes
Thanks for responding to all the comments. This looks good to me.

2024-03-27 12:05 UTC, merged