In status stage sequence
lowRISC/opentitan pull request #21852
Opened 2024-03-06 06:12 UTC by Nadia-Hanif

This PR contains in status stage sequence.

2024-03-08 11:27 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_in_status_stage_vseq.sv
> +    cfg.clk_rst_vif.wait_clks(10);
(Following up on: https://github.com/lowRISC/opentitan/pull/21326#discussion_r1511332046)

Thanks for explaining how we have to wait for a couple of bit times here. Please could you factor this out into a `wait_two_bit_times` task? (feel free to choose a better name!) That way, it should be a bit more obvious what's going on, and we'll slightly decouple the USB clock and the main clock in the code, at least.

2024-03-08 11:28 UTC, rswarbrick requested changes
Please can you squash the two commits together? I don't think I can see any reason that we'd want to keep them separate.

2024-03-08 11:41 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_in_status_stage_vseq.sv
> +    super.dut_init("HARD");
I can't see why this is necessary. Note that `dut_init` already gets called before the start of `body`.

2024-03-08 11:41 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_in_status_stage_vseq.sv
> +    rand_or_not = 0;
I'd suggest pulling the configuration into a separate task like this:
```systemverilog
  task pre_start();
    super.pre_start();
    num_of_bytes = 0;
    rand_or_not = 0;
  endtask

  task body();
    // Configure out transaction
    configure_out_trans();
    // Out token packet followed by a zero length data packet
    call_token_seq(PidTypeOutToken);
...
```

2024-03-21 22:03 UTC, rswarbrick reviewed
There's a minor git problem that needs sorting out.

Otherwise, the vseq seems sensibly written, but I'm not an expert on USB and I don't properly understand the testpoint. @alees24: Would you mind taking a look at this? I don't properly understand the description in the testpoint, and I'm not sure I understand how the vseq is implementing it. Can you help?

2024-03-21 22:03 UTC, rswarbrick commented on hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
> +>>>>>>> [usbdev] in status stage sequence
Nit: Something has gone a bit wrong with the merging here. Could you tidy it up?

2024-08-28 14:39 UTC, alees24 commented
Thanks for this PR. Superseded now that USBDEV has reached V2S status.

2024-08-28 14:39 UTC, closed without merging