[usbdev,dv] adds inter_pkt_delay() task in usbdev_base_seq
lowRISC/opentitan pull request #22030
Opened 2024-03-14 10:58 UTC by MubashirSaleem775

Introduces an inter-packet delay task in the base sequence, which will be utilized between packets in all sequence transactions.

2024-03-14 11:03 UTC, MubashirSaleem775 commented
@rswarbrick please review this PR.

2024-03-19 15:25 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
> +virtual task inter_packet_delay(int delay = 12);
Would it make sense to change this argument so that it's measured in bit times? Then we could end up calling `wait_clks(delay * 4)`.

The reason I'm asking is that I *think* there's never going to be a reason to call this function with a delay that isn't an integer number of bit times.

2024-03-19 15:38 UTC, MubashirSaleem775 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
> +virtual task inter_packet_delay(int delay = 12);
Okay, it make sense. i will change this argument as you suggested. Thanks

2024-03-19 16:10 UTC, alees24 requested changes
Please see comment.

2024-03-19 16:10 UTC, alees24 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
> +  // The interpacket delay ranges from 2 to 18 bit times.
This range has confused two different timing parameters within the specification. From section 7.1.18.1 the 'Inter-packet Delay' which is the time interval from the end of one packet to the start of the next packet _in the same direction_, must be at least 2 bit times and at most 6.5 bit times at the device port.
This means that the task needs to have a 'delay' value in the range [2,6] inclusive if specified in terms of usb20_driver clocks (= bit intervals).

The number 18 comes from the maximum time interval for the device to wait before deciding to timeout and give up on receiving a response from the host eg. with ACK or NAK in response to a DATA packet that the USB device sent as an IN transmission.

I think it would also be worth having this task randomize by default so that everywhere that it is enabled may benefit from the extra testing. If a specific, fixed delay is required then the code that enables the task may override the default.

Thanks.

2024-03-20 10:22 UTC, MubashirSaleem775 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
> +  // The interpacket delay ranges from 2 to 18 bit times.
Thank you for your review. I have made the necessary updates based on your feedback.

2024-03-20 13:58 UTC, alees24 requested changes
This looks okay thank you except for the use of 6.5 here, which will sometimes yield a delay of 7 cycles because randomizing across a range of 'real' values yields a result of type 'real' which is then rounded to nearest when casting to an integral data type.

Since the code is about to multiply by 4 to achieve USB device clocks, randomizing with $urandom_range(8, 26) in the case where 'delay' has defaulted to 0 would work, please.

2024-03-21 19:03 UTC, alees24 approved these changes

2024-03-21 19:04 UTC, merged