[usbdev] usbdev_disconnected seqeunce
lowRISC/opentitan pull request #22379
Opened 2024-04-02 10:35 UTC by MubashirSaleem775

Adds 'usbdev_disconnected' sequence to validate device functionality upon disconnection. Upon loss of usb_vbus, the device generates a disconnected interrupt.

2024-04-02 14:49 UTC, rswarbrick requested changes

2024-04-02 14:49 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    `DV_CHECK_EQ(get_field_val(ral.intr_state.disconnected, rd_data), 0)
Instead of using CSRs for this, please use the interrupt pin itself (visible through `intr_vif`). Similarly for the check in the loop below.

2024-04-02 14:49 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    inter_packet_delay();
Why is this delay required?

2024-04-02 14:49 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    csr_wr(.ptr(ral.intr_state.disconnected),  .value(1'b1));
You probably don't actually need to write the `intr_state` here, but it makes sense to check that the interrupt is false at this point. As I mentioned later on, you can look directly at the interrupt line through `intr_vif`.

2024-04-04 08:16 UTC, MubashirSaleem775 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    inter_packet_delay();
We need to introduce this delay because we're awaiting the assertion of the usb_ref_val_o signal, which occurs after a certain delay from the clock signal.

2024-04-04 08:20 UTC, MubashirSaleem775 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    csr_wr(.ptr(ral.intr_state.disconnected),  .value(1'b1));
Okay , I will read from intr_vif.

2024-04-04 08:20 UTC, MubashirSaleem775 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    `DV_CHECK_EQ(get_field_val(ral.intr_state.disconnected, rd_data), 0)
Okay

2024-04-08 10:28 UTC, rswarbrick requested changes

2024-04-08 10:28 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    cfg.m_usb20_agent_cfg.bif.usb_vbus = 1'b0;
This is going to need tweaking after recent changes to `usb20_block_if.sv`. I think this will work:
```systemverilog
    cfg.m_usb20_agent_cfg.bif.drive_vbus = 1'b0;
```

2024-04-08 10:28 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    // Disconnect the device vbus
Can you rephrase this? I think we're driving 0 on VBUS in order to tell the device that it has been disconnected. (We're not disconnecting the vbus signal...)

2024-04-08 10:28 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    end
I think this can be slightly simpler:
```systemverilog
    // Expect the disconnected interrupt within a short time
    for (int i = 0; i < 10; i++) begin
      @(posedge cfg.m_usb20_agent_cfg.bif.usb_clk);
      if (cfg.intr_vif.pins[IntrDisconnected]) break;
    end
    `DV_CHECK_EQ(cfg.intr_vif.pins[IntrDisconnected], 1)
```

2024-04-08 10:28 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    // Read intr_state register and veify that disconncted interrupt is 0.
Can you tweak this text, now that we're looking directly at the pin? I think something like this would work:
```
    // Check the disconnected interrupt isn't yet asserted
    `DV_CHECK_EQ(cfg.intr_vif.pins[IntrDisconnected], 1)
```
(I've also switched to looking at `pins[..]` directly: I don't think there's any need for explicitly calling the `sample_pin` function here)

Also nit: Missing "e" in "disconnected"

2024-04-08 10:38 UTC, MubashirSaleem775 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    cfg.m_usb20_agent_cfg.bif.usb_vbus = 1'b0;
Yes, i will update

2024-04-08 10:40 UTC, MubashirSaleem775 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    end
Yes

2024-04-08 10:43 UTC, MubashirSaleem775 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    // Read intr_state register and veify that disconncted interrupt is 0.
Okay , i will change this as you suggested. thanks

2024-04-08 10:50 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    inter_packet_delay();
I agree that there's a slight delay. Here's a screenshot of the waves from a run:
![image](https://github.com/lowRISC/opentitan/assets/104845/7fa3f683-e7e0-4e6f-833a-95f0d6a23f80)
The red line is the time where `call_sof_seq` completes.

I've taken a proper look at the signals. The required wait is a single cycle of the main clock. Can we switch over to the correct clock, then I think it makes sense.

2024-04-08 10:58 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    inter_packet_delay();
Er. I take that back! It's 2 cycles of the main clock :-) I've just taken a more careful look and this timing comes from the "packet end" signal coming out of `usb_fs_rx.sv`, which waits to see an EOP signal. It's a bit sad to have to snoop on the USB clock itself (which we're currently doing), but I guess it's a simple way to keep everything in sync for now.

2024-04-08 12:42 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
> +    `DV_CHECK_EQ(cfg.intr_vif.pins[IntrDisconnected], 1)
Ah, this was my fault: I had a typo in my initial suggestion! I think this probably needs to be `0` (otherwise the test will fail :-D)

2024-08-28 14:39 UTC, alees24 commented
Thanks for this PR. Superseded now that USBDEV has reached V2S status.

2024-08-28 14:39 UTC, closed without merging