[usbdev,dv] usbdev rx crc err seq
lowRISC/opentitan pull request #22376
Opened 2024-04-02 05:26 UTC by Saad22386

This PR incorporates the rx_crc_err sequence, where we send a packet with corrupted CRC and subsequently check the CRC status after sending the packet.

2024-04-02 08:07 UTC, Saad22386 commented
@rswarbrick, kindly review it.

2024-04-02 13:25 UTC, rswarbrick requested changes

2024-04-02 13:25 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_rx_crc_err_vseq.sv
> +    check_crc5_err();
Can we make this slightly simpler? I think we really want something like (in C pseudo-code)
```
seen_crc_err = 0;
for (i = 0; i < 10; i++) {
  if (rx_crc_err) {
    seen_crc_err = 1;
    break;
  }
}
if (!seen_crc_err) die("oh no...");
```
Doing it with this structure avoids us encoding the exact timing into the test.

2024-04-02 13:25 UTC, rswarbrick commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_rx_crc_err_vseq.sv
> +  virtual task call_token_seq(input pid_type_e pid_type);
I don't think that we should override a base task like this: you've ended up having to copy-paste the contents and then change a bit. Aargh!

I'd suggest a refactor: Change the base class so that it looks something like this (untested!):
```systemverilog
virtual task call_token_seq(input pid_type_e pid_type);
  create_token_pkt();
  m_usb20_item = m_token_pkt;
  start_item(m_token_pkt);
  finish_item(m_token_pkt);
endtask

virtual task create_token_pkt();
  `uvm_create_on(m_token_pkt, p_sequencer.usb20_sequencer_h)
  m_token_pkt.m_pkt_type = PktTypeToken;
  m_token_pkt.m_pid_type = pid_type;
  assert(m_token_pkt.randomize() with {m_token_pkt.address inside {7'b0};
                                       m_token_pkt.endpoint == endp;});
endtask
```

Now the derived class can just do this:
```systemverilog
virtual task create_token_pkt();
  super.create_token_pkt();
  // Flip the crc5 bits to corrupt the crc5
  m_token_pkt.crc5 = ~m_token_pkt.crc5;
endtask
```

2024-04-05 07:13 UTC, Saad22386 commented on hw/ip/usbdev/dv/env/seq_lib/usbdev_rx_crc_err_vseq.sv
> +    check_crc5_err();
I am not getting your point here.
Are you saying to replace check_crc5_err() task with your suggested approach?
Also, why are we using a loop to iterate 10 times to check for a CRC error?
Isn't it enough to check the error one time after sending the packet?

2024-08-28 14:38 UTC, alees24 commented
Thanks for this PR. Superseded now that USBDEV has reached V2S status.

2024-08-28 14:38 UTC, closed without merging