[hmac, rtl] Minor HMAC fixes
lowRISC/opentitan pull request #23197
Opened 2024-05-20 12:40 UTC by ballifatih

This PR includes two changes:

- Add endianness option to `KEY` register. Current implementation is hardcoded for big endian which does not match Ibex's endianness. https://github.com/lowRISC/opentitan/issues/23158#issuecomment-2120138498
- I encountered a bug that specifically prevents reloading context for 384 and 512-bit variants. Namely, SW cannot correctly set DIGEST registers during context reloading, because both 32-bit words of 64-bit sha_word is reloaded with the same copy. I tested this fix with my driver implementation.

2024-05-21 07:25 UTC, martin-velay requested changes
If this PR is merged, the DV will be broken as we are swapping the key according to an existing field which is randomized. I would prefer to add a dedicated field for that (see [comment](https://github.com/lowRISC/opentitan/issues/23158#issuecomment-2121914303)).

About the rest of the changes, if the regression is happy with that, I am too.

2024-05-21 07:25 UTC, martin-velay commented on hw/ip/hmac/rtl/hmac.sv
> +          secret_key_d[32*i+:32] = conv_endian32(reg2hw.key[31-i].q, digest_swap);
See [comment](https://github.com/lowRISC/opentitan/issues/23158#issuecomment-2121914303)

2024-05-21 07:25 UTC, martin-velay commented on hw/ip/hmac/rtl/hmac.sv
> +    hw2reg.digest = '0;
We usually tend to align the equals to make the code more readable (this comment is valuable on several places of your PR) -> [Coding Style - Tabular alignment](https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#tabular-alignment)

2024-05-21 08:34 UTC, gdessouky commented on hw/ip/hmac/rtl/hmac.sv
> +        // digest HW -> SW
nit: align block lines 238-244.

2024-05-21 08:35 UTC, gdessouky commented on hw/ip/hmac/rtl/hmac.sv
> +        digest_sw_we[i] = reg2hw.digest[2*i].qe | reg2hw.digest[2*i+1].qe;
I would assign `digest_sw` first then `digest_sw_we` just for consistency with the style in the block above for `SHA2_256`.

2024-05-21 08:41 UTC, gdessouky commented
Thanks @ballifatih for the fixes, glad to have the digest reloading for SHA-2 384/512 tested and ironed out, this LGTM! As for the key endianness swap change, I also think we hold back on this for now, as I mention here https://github.com/lowRISC/opentitan/issues/23158 and Martin as well. The DV to test the new features is yet to stabilize and this would break DV and require a lot more adaptations. We can introduce a dedicated swap and choose to test it later.

2024-05-21 13:59 UTC, ballifatih commented
Thanks @martin-velay and @gdessouky. I dropped the endianness change commit so that it can be further discussed and decided in the main issue #https://github.com/lowRISC/opentitan/issues/23158. I also made the nit changes for the other changes (mostly visual alignment around assignments).

2024-05-21 15:18 UTC, andreaskurth commented
Thx @ballifatih, I agree that the digest reloading fix is more urgent than supporting key endianness swapping, which we can do in a later PR. I took the liberty to edit the title and description of this PR. I'll review it

2024-05-21 18:32 UTC, gdessouky commented on hw/ip/hmac/rtl/hmac.sv
> +                                 digest[i][63:32];
this also ought use `conv_endian64` in order to implement digest swapping on the entire 64-bit digest word not individual 32-bit digest words for sizes SHA-2 284/512 (please see https://github.com/lowRISC/opentitan/pull/23236/files#diff-b5d831e613a1826ac147ecfa9963fa5c285c3f243cea8f9e31f3edec5904892d)
```
        inter_digest                  = conv_endian64(digest[i], digest_swap);
        hw2reg.digest[2*i].d   = inter_digest[63:32];
        hw2reg.digest[2*i+1].d = inter_digest[31:0];
```

I put up a PR https://github.com/lowRISC/opentitan/pull/23236/files#diff-b5d831e613a1826ac147ecfa9963fa5c285c3f243cea8f9e31f3edec5904892d that incorporates some of your changes here with additional changes I needed for other block-level tests and to try and fix the gating issue with switching between different digest-sized streams. Can you test this with your driver @ballifatih?

2024-05-21 18:44 UTC, andreaskurth requested changes
Agree with @gdessouky -- as is, this doesn't work

2024-05-21 23:36 UTC, ballifatih commented on hw/ip/hmac/rtl/hmac.sv
> +                                 digest[i][63:32];
DIGEST registers are `hwext: "true"` in the hjson file, which means they are only pass through and there is no actual register between TL-UL bus and this logic that updates `digest_sw` values. This means (which was visible to me in the waveforms earlier but I do not have it now), all `reg2hw.digest[i].q` values are actually equal when there is a write operation coming to any of the DIGEST registers. However only the matching `reg2hw.digest[i].qe` is raised. This essentially means when we see an incoming DIGEST write operation (signaled by `reg2hw.digest[i].qe`), we need to store it in the respective 32-bit of `digest_sw[i]` value. The logic here "picks" the correct half and copies the other half from the current value of `digest`.

For the endianness issue, I will double check with the driver but I suspect DV is using the wrong endianness here. Especially the mapping between `digest` values in the RTL and `DIGEST` CSRs should be as below (note that Ibex is little endian):

Example:
`digest[0] = 0x01234567_89ABCDEF`
 `digest[1] = 0x00112233_44556677`
...
should be translate to `DIGEST` CSRs as follows (noting the little endian representation from Ibex).
`DIGEST[0] = 0x67452301`
`DIGEST[1]  = 0xEFCDAB89`
`DIGEST[2] = 0x33221100`
`DIGEST[3] = 0x77665544`
...

whereas the current implementation (without this PR) implies:
`DIGEST[0] = 0xEFCDAB89`
`DIGEST[1]  = 0x67452301`
`DIGEST[2] = 0x77665544`
`DIGEST[3] = 0x33221100`

It means the driver needs to read the digest in the following order: 1, 0, 3, 2, 5, 4 ... I suspect this is also the reason why this PR is failing CI.

2024-05-22 08:09 UTC, gdessouky commented on hw/ip/hmac/rtl/hmac.sv
> +                                 digest[i][63:32];
> This means (which was visible to me in the waveforms earlier but I do not have it now), all `reg2hw.digest[i].q` values are actually equal when there is a write operation coming to any of the DIGEST registers. However only the matching `reg2hw.digest[i].qe` is raised. This essentially means when we see an incoming DIGEST write operation (signaled by `reg2hw.digest[i].qe`), we need to store it in the respective 32-bit of `digest_sw[i]` value. The logic here "picks" the correct half and copies the other half from the current value of `digest`.
> 
Thanks @ballifatih, I had not known the write operation writes to all the `reg2hw.digest[i]` equally, we need the `qe` to select indeed.

Regarding the endiannness, this is not yet being checked in CI for 384/512 yet, most CI runs from yesterday were breaking anyway. And the block-level DV is still stabilizing, in my other PR I make some DV fixes. But let's put DV and the current implementation aside. Our disagreement here is basically on how we are defining the endiannness for SHA-2 384/512 which are 64-bit (not 32-bit) words.

**BIG ENDIAN**
```
digest[0] = 0x01234567_89ABCDEF
digest[1] = 0x00112233_44556677
```

translates to the DIGEST CSRs as

```
DIGEST[0] = 0x01234567
DIGEST[1] = 0x89ABCDEF
DIGEST[2] = 0x00112233
DIGEST[3] = 0x44556677

```
We agree there. Now for little endian, I would be implementing a digest swap on the **entire 64-bit word** such that `{digest[0], swap} = 0xEFCDAB89_67452301`

**LITTLE ENDIAN**
```
{digest[0],swap}  = 0xEFCDAB89_67452301
{digest[1],swap}  = 0x77665544_33221100
```

translates to the DIGEST CSRs as

```
DIGEST[0] = 0xEFCDAB89
DIGEST[1] = 0x67452301
DIGEST[2] = 0x77665544
DIGEST[3] = 0x33221100

```
and you would be reading the digest CSRs in order 0, 1, 2, 3 and composing the 64-bit word, e.g., {DIGEST[0] ,DIGEST[1]} and endian swapping back again on the entire word to generate the big-endian 64-bit digest. 

End of the day, I think it doesn't really matter and either would work, it's a question of interpretation, and the DV checks can be adapted (this is not why CI is failing on any of the runs), so long as we just agree and have consistency between the HW and how the driver **interprets** the CSRs.

2024-05-22 08:17 UTC, gdessouky commented on hw/ip/hmac/rtl/hmac.sv
> +                                 digest[i][63:32];
From the HW end,  I don't see a particular preference. We just need to make consistency fixes in the DV and explain this nicely in the documentation and programmer's guide because endianness is always confusing and this even more so :-) Do you have a particular preference on how you want to interpret the CSRs in the driver implementation?

2024-05-22 09:40 UTC, ballifatih commented on hw/ip/hmac/rtl/hmac.sv
> +                                 digest[i][63:32];
We are on the same page expect for one minor point, when you change the endianness of 64-bit value, we should only change endianness within 32-bit blocks. The order of these two 32-bit blocks within 64-bit block should be same. This could again be interpretation issue of endianness but as it stands, but otherwise SW would need to read them in 1, 0, 3, 2... order.

Regarding endianness within 32-bit blocks, since we have digest_swap, HW can do whichever order.

2024-05-22 09:56 UTC, gdessouky commented on hw/ip/hmac/rtl/hmac.sv
> +                                 digest[i][63:32];
> This could again be interpretation issue of endianness but as it stands, but otherwise SW would need to read them in 1, 0, 3, 2... order.
> Yes, exactly this is the point I make above. However way makes the driver implementation easier will work. I will adjust the swapping in the RTL and DV then such that the **endianness is only swapped within 32-bit words.**

All good, we have no debate here.
> Regarding endianness within 32-bit blocks, since we have digest_swap, HW can do whichever order.

2024-05-24 09:45 UTC, ballifatih commented
Closing as relevant changes are added in https://github.com/lowRISC/opentitan/pull/23236.

I was able to run drivers on top of this change, but I will try with #23236.

2024-05-24 09:45 UTC, closed without merging