[hw/prim] Adapted primitives to no longer require `primgen.py`
lowRISC/opentitan pull request #23523
Opened 2024-06-06 07:02 UTC by HU90m

This change pulls in the previously generated primitive wrappers, so that the `primgen.py` generator is no longer needed.

With these changes, OpenTitan can be built with upstream FuseSoC (tested on version 2.2).

I think there is some reorganisation of the primatives that could be nice; these are simply the minimal changes to remove `primgen.py`.

Fixes: https://github.com/lowRISC/opentitan/issues/20379 https://github.com/lowRISC/opentitan/issues/6604

*@rswarbrick This follows [the initial plan](https://github.com/lowRISC/opentitan/issues/20379#issuecomment-1984403219) without any additional changes needed.*

2024-06-06 09:43 UTC, jwnrt commented on hw/ip/prim/rtl/prim_clock_div.sv
> +// This file is auto-generated.
What are they autogenerated by, primgen?

Will new primitive wrappers need writing by hand?

2024-06-06 09:43 UTC, jwnrt commented on hw/ip/prim/README.md
> +2. Copy the `prim_generic` folder into an arbitrary location (can be outside of this repository). Name the folder `prim_YOURLIBRARYNAME`.
Ah, I see the idea is to copy from an existing prim.

2024-06-06 10:06 UTC, marnovandermaas reviewed
Huge fan of being able to build with upstream FuseSoC!

I'm on board with the first commit so we don't depend on primgen in the build process. For the second commit, I wonder whether we should keep primgen around so that there is an automated way to update all the primitives through the templates. What do you think?

2024-06-06 10:15 UTC, jwnrt commented
Apologies for my SystemVerilog ignorance, but does the "abstract" file for these prims contain any real logic, or is it solely selecting which tech-specific prim to use?

If the latter, would the following work?

* Change the tech-specific prim modules from `prim_(generic|xilinx|xilinx_ultrascale)_NAME` to `prim_NAME` (which would conflict).
* Have fusesoc select which `*.sv` file to use depending on the tool flow, and not include the others at all.

2024-06-06 10:36 UTC, HU90m commented
> I'm on board with the first commit so we don't depend on primgen in the build process. For the second commit, I wonder whether we should keep primgen around so that there is an automated way to update all the primitives through the templates. What do you think?

I think if primgen is no longer used for builds it will start to bitrot, which would cause future devs pain. For the use case you are suggesting, primgen would need to be adapted to generate files in there expected locations in the repository. It can always be revived from the history, if we wish to do this.

Going forward there is a lot of cruft that could be removed and re-organised.

For example [`prim_xilinx_ultrascale_xor2.sv`](https://github.com/lowRISC/opentitan/blob/master/hw/ip/prim_xilinx_ultrascale/rtl/prim_xilinx_ultrascale_xor2.sv) and [`prim_xilinx_xor2.sv`](https://github.com/lowRISC/opentitan/blob/master/hw/ip/prim_xilinx/rtl/prim_xilinx_xor2.sv) are duplicate modules. One could have one module that is used for both:

```systemverilog
if ((Impl == prim_pkg::ImplXilinx) || (Impl == prim_pkg::ImplXilinx_ultrascale)) begin : gen_xilinx
    prim_xilinx_xor2 #(
      .Width(Width)
    ) u_impl_xilinx (
      .*
    );
end else begin : gen_generic
    prim_generic_xor2 #(
      .Width(Width)
    ) u_impl_generic (
      .*
    );
end
```

In fact, the only difference between `prim_xilinx_xor2` and `prim_generic_xor2` is an attribute, so these could potentially all be collapsed into one module. There is likely some directory restructuring we could do to make it more ergonomic for techlibs to share.

These sorts of changes would require further, significant changes to primgen.

2024-06-06 10:37 UTC, GregAC requested changes
Thanks for this @HU90m this looks like good work, however we must hold off on merging for now to avoid any possible disruption to M4.

So marking a 'Request changes' to prevent an accidental merge. I think this would be better off as a draft PR for now to make it clear the intent is early visibility and review.

2024-06-06 10:45 UTC, HU90m commented
> Apologies for my SystemVerilog ignorance, but does the "abstract" file for these prims contain any real logic, or is it solely selecting which tech-specific prim to use?
> 
> If the latter, would the following work?
> 
>     * Change the tech-specific prim modules from `prim_(generic|xilinx|xilinx_ultrascale)_NAME` to `prim_NAME` (which would conflict).
> 
>     * Have fusesoc select which `*.sv` file to use depending on the tool flow, and not include the others at all.

I had considered this and we could still do this.

A reason not to do this now is that we want to make the changes to the `prim`s to be reasonably small and incremental. This approach would require wider changes.

A reason not to do this ever is that the current approach is pure system verilog and easy to understand. Using FuseSoC would make it harder for people with less familiar with FuseSoC to understand what is going on and would make it harder for people injesting the RTL into a different build flow to swap at the technology library without re-injesting the RTL.

2024-06-06 13:27 UTC, a-will requested changes
I think this misses the reason we have primgen. What is it about primgen that makes it incompatible with upstream fusesoc?

An alternative that might not break the model would be to turn the abstract cores that were generated into virtual cores. Each tech lib would implement their own providers, and the particular tech lib would be chosen at the top level. This idea might need massaging for dealing with the chip-level cores that already specify the tech lib to use, though maybe _that_ could be the output of a simple fusesoc generator, where a simple VLNV string provides the tech lib to depend on.

2024-06-06 13:27 UTC, a-will commented on hw/ip/prim/README.md
> +5. Add the new technology library to the enum in `prim_pkg.sv` with a value in the form `prim_pkg::ImplTechlibname`.
This is what I would object to here. primgen's purpose is to allow out-of-tree primitives _without modifying the upstream repo_.

2024-06-06 13:27 UTC, a-will commented on hw/ip/prim/prim_and2.core
> +      - lowrisc:prim_xilinx:and2:0
Explicit dependencies here is going to make this not scale.

2024-06-06 13:36 UTC, jwnrt commented
> A reason not to do this ever is that the current approach is pure system verilog and easy to understand. Using FuseSoC would make it harder for people with less familiar with FuseSoC to understand what is going on and would make it harder for people injesting the RTL into a different build flow to swap at the technology library without re-injesting the RTL.

I get what you mean. Just for the record, this is what I did when porting prims to Bender, so it's not necessarily FuseSoC specific, it just needs an equivalent in whatever system you're using to build hardware.

2024-06-07 07:04 UTC, a-will commented
I haven't tested this beyond running fusesoc --setup on a few chip-level cores, but this might show what I was talking about with virtual cores: https://github.com/lowRISC/opentitan/pull/23555

This won't work without a very recent commit of fusesoc, though: The fixes to how virtual cores work aren't in a fusesoc release yet. On top of that, a more recent fusesoc appears to change the build directory compared to what dvsim currently expects, so that'll need to be fixed up.

2024-06-07 09:30 UTC, HU90m commented
Closing in favor of exploring a virtual core approach. See https://github.com/lowRISC/opentitan/pull/23555

2024-06-07 09:30 UTC, closed without merging