[hmac,dv] Block-level tests with SHA-2 NIST test vectors for new digest sizes 384/512
lowRISC/opentitan pull request #23541
Opened 2024-06-06 16:49 UTC by gdessouky

This adds block-level testing with SHA-2 NIST test vectors for newer digest sizes 384/512, which addresses https://github.com/lowRISC/opentitan/issues/22932 in part. 
Block-level testing for HMAC with different key lengths is not yet added. Once in, this would close out https://github.com/lowRISC/opentitan/issues/22932.

2024-06-07 06:59 UTC, martin-velay approved these changes
Could be merged once the comments have been taken into account

2024-06-07 06:59 UTC, martin-velay commented on hw/dv/sv/test_vectors/test_vectors_pkg.sv
> +  string hmac_256_file_list[]   = {"vectors/hmac/HMAC_RFC4868.rsp"};
Why not the HMAC 384/512?

2024-06-07 06:59 UTC, martin-velay commented on hw/dv/sv/test_vectors/test_vectors_pkg.sv
> +  // This function parses all NIST test vectors for SHA256/SHA384/SHA512/HMAC/SHA3SHAKE/CSHAKE/KMAC.
Here maybe precise SHA2:
`SHA2-256/SHA2-384/SHA2-512/HMAC/SHA3SHAKE/CSHAKE/KMAC`

2024-06-07 06:59 UTC, martin-velay commented on hw/dv/sv/test_vectors/test_vectors_pkg.sv
> +  // 1) This format is used for SHA256/SHA384/SHA512/SHA3 test vectors.
Same as above: Here maybe precise SHA2:
`SHA2-256/SHA2-384/SHA2-512/HMAC/SHA3SHAKE/CSHAKE/KMAC`

2024-06-07 06:59 UTC, martin-velay commented on hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
>        0 :/ 0    // Illegal -> should get casted to SHA2_None in HW
Maybe add a TODO here, as Illegal won't be hit and same for the digest size.
Do we need to raise an issue for that?

2024-06-07 06:59 UTC, martin-velay commented on hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
>    constraint key_digest_c {
I would prefer to have separated constraints, it will allow us more flexibility if we need to release one for a specific test:

```
  constraint key_length_c {
    $countones(key_length) == 1 dist {
      1 :/ 10,  // Key_128/Key_256/Key_384/Key_512/Key_1024/Key_None
      0 :/ 0    // Illegal -> should get casted to Key_None in HW
    };
  }

  constraint digest_size_c {
    $countones(digest_size) == 1 dist {
      1 :/ 10,  // SHA2_256/SHA2_384/SHA2_512/SHA2_None
      0 :/ 0    // Illegal -> should get casted to SHA2_None in HW
    };
  }

```

2024-06-07 06:59 UTC, martin-velay commented on hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_hmac_vseq.sv
> +// This vseq will read HMAC test vectors and compare computed results with the expected value
As we are changing this comment, can precise from where those vectors are coming as I spent time to understand the purpose of this test. I didn't get at all that those vectors are actually provided by the NIST as a golden reference.

2024-06-07 06:59 UTC, martin-velay commented on hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_hmac_vseq.sv
> +    //vector_list_384 = test_vectors_pkg::hmac_384_file_list;
Why commented out? Maybe add a TODO with an issue #?

2024-06-07 06:59 UTC, martin-velay commented on hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
> +// This vseq will read SHA-2 NIST vectors and compare computed results with the expected value
Same as above, can we say that those vectors and expected values are provided by the NIST as a golden reference?

2024-06-07 06:59 UTC, martin-velay commented on hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
> +  bit [5:0]  key_length;
I think `key_length` and `digest_size` are already declared into the `hmac_base_vseq`. So it should be removed from here.

Same for the `key`

2024-06-07 06:59 UTC, martin-velay commented on hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
> +        compare_digest(digest_size, parsed_vectors[j].exp_digest);
Can you swap `digest_size` with `parsed_vectors[j].exp_digest` tohave the same ordering as above? (and needs to be changed into the `base_seq` as well

2024-06-07 06:59 UTC, martin-velay commented on hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
> +    digest_size = 4'b0001;
Maybe better to point to the pkg parameters:
`SHA2_256` and `Key_256`

Same for the 2 others below

2024-06-07 06:59 UTC, martin-velay commented on hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
> +    `uvm_info(`gfn, $sformatf("SHA-2/HMAC 256 NIST test vectors..."), UVM_LOW)
Add something like:
```
uvm_info(`gfn, $sformatf("Starting SHA-2/HMAC 256 NIST test vectors..."), UVM_LOW)
```

2024-06-07 11:25 UTC, gdessouky commented on hw/dv/sv/test_vectors/test_vectors_pkg.sv
> +  // 1) This format is used for SHA256/SHA384/SHA512/SHA3 test vectors.
Here it is only the format for SHA-2 256/SHA-2 384/SHA-2 SHA512/HMAC/SHA3 test vectors. CSHAKE and KMAC test vectors format come below.

2024-06-07 11:43 UTC, gdessouky commented on hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
> +        compare_digest(digest_size, parsed_vectors[j].exp_digest);
does it make a difference? `feed_vectors` is a different function and its parameter is the vector list unparsed, so it is not the same, but I am fine with either order :)

2024-06-07 11:46 UTC, martin-velay commented on hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
> +        compare_digest(digest_size, parsed_vectors[j].exp_digest);
No it's more to keep the same logic and it's something I have in my PR https://github.com/lowRISC/opentitan/pull/23116 as it was causing me some troubles, and I took the order with digest at the end 😁

2024-06-07 11:47 UTC, martin-velay commented on hw/dv/sv/test_vectors/test_vectors_pkg.sv
> +  // 1) This format is used for SHA256/SHA384/SHA512/SHA3 test vectors.
Oh yes, sure it's bad copy/paste from me

2024-06-07 14:05 UTC, gdessouky commented on hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
> +    digest_size = 4'b0001;
good catch, yes

2024-06-07 14:24 UTC, gdessouky commented
Thanks @martin-velay I've pushed again now but a single test run (when it's not smoke) is now very long since it runs through all test vectors for each digest size: SHA-2 256 then 384 then 512, and some time out. I think we should be splitting these up into 3 tests for each digest size and we shouldn't merge now.

2024-06-12 13:43 UTC, gdessouky commented on hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
>        0 :/ 0    // Illegal -> should get casted to SHA2_None in HW
I tested them at some point in the weeks leading up to M4, to make sure they are correctly cast into `SHA2_None/Key_None` and predicted correctly in the scb, but I'll rework the constraint to hit these and run a block-level regression at my end to make sure.

2024-06-12 13:55 UTC, gdessouky commented
I've pushed again to this PR and split the test into 3 tests for each of the digest sizes (I think some timeouts might happen still but we'll see and adjust accordingly), and also released the constraints to hit illegal `digest size/key length`. I've tested/implemented changes for this before to make sure they are casted correctly in the HW and predicted correctly in the scoreboard, but I'm still running a local block-level regression at my end to confirm. Once merged, this should also close https://github.com/lowRISC/opentitan/issues/23592.

2024-06-13 09:41 UTC, martin-velay requested changes

2024-06-19 20:10 UTC, gdessouky commented on hw/ip/hmac/dv/env/hmac_env_pkg.sv
> +      default: return 0;     // Unsupported/invalid/all-zero values are mapped to Key_None
@martin-velay this is to also return 0 for all invalid input when we release the constraints to include invalid digest sizes/key lengths.

2024-06-19 20:13 UTC, gdessouky commented
@martin-velay, thanks for your feedback and comments, I've addressed them now in my last push after rebasing.
@vogelpi, can we go ahead and merge?

2024-06-20 06:36 UTC, martin-velay requested changes
There is at least one change which will require a change in case the sequence is misused

2024-06-20 06:36 UTC, martin-velay commented on hw/ip/hmac/dv/env/hmac_env_pkg.sv
> +      default: return 0;     // Unsupported/invalid/all-zero values are mapped to Key_None
Yes, I had done this modif but it looks like it has been lost during my rebase somehow. Thanks and sorry!

2024-06-20 06:36 UTC, martin-velay commented on hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
> +    int digest_index;
This `digest_index` is not used from what I can see

2024-06-20 06:36 UTC, martin-velay commented on hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
> +    void'($value$plusargs("sha2_digest_size=%s", digest_size_arg));
Here you should probably add a check like:
```
if (digest_size_arg == "") begin
  `uvm_fatal(`gfn, "This test sequence requires a command-line extra argument: sha2_digest_size=SHA2_256/SHA2_384/SHA2_512"
end
```

2024-06-20 07:01 UTC, gdessouky commented on hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
> +    int digest_index;
true, not anymore, thanks for catching.

2024-06-20 12:04 UTC, martin-velay approved these changes
Thanks for the changes, now it LGTM!

2024-06-20 12:15 UTC, rswarbrick approved these changes
This looks sensible to me and I'm pleased to see that @martin-velay (who knows much more about HMAC than I do) agrees. Thanks!

2024-06-20 14:38 UTC, gdessouky commented
The failing CI tests are unrelated to the changes in this PR, can we go ahead and merge @rswarbrick?

2024-06-20 15:35 UTC, merged