[hmac,dv] Fix rare issue with wipe_secret
lowRISC/opentitan pull request #23817
Opened 2024-06-26 13:54 UTC by martin-velay

- When wipe_secret test is triggered from stress test and if the last
triggered wipe secret type is WipeSecretBeforeStart and HMAC is
enabled then rd_digest is not exercised thus wipe_secret_triggered
is not pulled back to 0.

2024-06-27 10:46 UTC, rswarbrick requested changes
CI is currently failing because the first commit is missing a blank line in the commit message. Would you mind tidying that up?

That commit is also an RTL change which then gets undone by the following commit. Please could you tidy up the commits?

2024-06-27 12:41 UTC, martin-velay commented
@rswarbrick thanks for the explanation and for your review. Actually I have no idea why the RTL change came to the surface. I have rebased my commits. Now it should be clear and mergeable once the CI passes.

2024-06-27 13:00 UTC, gdessouky approved these changes
thanks, LGTM modulo minor comment, so long as it passes full regression!

2024-06-27 13:11 UTC, martin-velay commented on hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
> +    clear_wipe_secret();  // Ensure that wipe secret is cleared, as it may cause with stress tests
No, I think this won't update the exp digest in the SCB. It will just allow the next sequence to compare the digest by equality with the expected value, see the "if" condition line 309 and the "else" line 319.

But I'll update the comment to clarify a bit, into:
```
    // Ensure that wipe secret flag is cleared for the next sequence, as it may cause digest
    // comparison issue with the stress tests
```

2024-06-27 13:22 UTC, gdessouky commented on hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
> +    clear_wipe_secret();  // Ensure that wipe secret is cleared, as it may cause with stress tests
yes, that's what I meant to say :-)  I remember running into that issue actually and pushing a fix, but I'm not sure why/how did it re-triggered or if it got lost in a rebase perhaps.

2024-06-28 10:52 UTC, rswarbrick approved these changes
Looks sensible. Thanks for the tidy-up.

2024-06-28 10:53 UTC, merged

2024-07-01 08:43 UTC, gdessouky commented
I don't see why would be needing this change anymore as this https://github.com/lowRISC/opentitan/blob/master/hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv#L94-L97 at the start of every new transaction should already be taking care of this and related issues.

(I was sure I had seen this error and dealt with it at some point.)