[hw,dma,rtl] Set interrupt only when transition to done / error
lowRISC/opentitan pull request #23854
Opened 2024-06-30 16:23 UTC by Razer6

Previously, clearing the DONE or ERROR interrupt before clearing STATUS.done would raise the same interrupt a second time, which could bring FW out of sync.

With this change, the DONE and ERROR interrupt are only sent once when transitioning into the DONE or ERROR state.

/cc @neeraj-rv @sameo

2024-08-02 14:47 UTC, alees24 requested changes
This change will cause the 'dma_done' and 'dma_error' interrupt to become asserted as soon as the DMA controller leaves its Idle state. I think you want to set the `intr_state` bits only when the 'set' clause of '...status.done.de' or '...status.error.de' is true.

2024-08-02 23:20 UTC, Razer6 commented
Thats true indeed, lets AND the .d signal to it

2024-08-05 14:24 UTC, alees24 approved these changes

2024-11-12 13:52 UTC, Razer6 commented
This PR is not necessary anymore because we switched to status-type interrupts.

2024-11-12 13:52 UTC, closed without merging