[verilator, tests] Fix and tag failing & timed-out Verilator test targets
lowRISC/opentitan pull request #24197
Opened 2024-08-01 11:34 UTC by AlexJones0

This PR partially addresses issues #24182 and #24184.

All Verilator test targets were run using public CI overnight in preparation for the addition of a weekly/nightly Verilator job in PR #24145. Of the 390 targets (at the time of testing), 14 explicitly failed and 67 timed out (when using `--test_timeout=2400,2400,3600,-1`). This PR accordingly:

- Marks all 67 timed-out tests as "manual", as they take at least 40 (and many > 60) minutes to complete when run on our public CI infrastructure and as such are too long to run in any sort of regular CI. The confirmation of whether these tests truly take a long time or should be marked broken and/or fixed is tracked by #24184.
- Marks all 6 failing Verilator tests tracked in #24182 as `broken`, until they can be looked at further.
- Fixes the `example_mem_ujcmd_test` test for Verilator, which was incorrectly passing in the Firmware ELF as a keyword argument instead of a positional argument. This has been verified (`PASSED in 599.6s`) by running 
```
./bazelisk.sh test -t- --test_output=streamed --test_timeout=3600,3600,3600,3600 \
    //sw/device/tests:example_mem_ujcmd_test_sim_verilator
```
- Fixes the `spi_host_irq_test` target, which was failing on Verilator due to the SPI clock frequency being configured to 1 MHz, whereas Verilator's HiSpeed peripheral frequency is set to just 500 KHz. A conditional check is added and the SPI clock speed is reduced to 100 KHz if running on Verilator. This has been verified (`PASSED in 133.4s`) by running 
```
./bazelisk.sh test -t- --test_output=streamed --test_timeout=3600,3600,3600,3600 \
    //sw/device/tests:spi_host_irq_test_sim_verilator
```
- Correctly excludes the Verilator execution environment from `gpio_smoketest`, which previously erroneously had the `//hw/top_earlgrey:verilator` environment excluded instead of the correct `//hw/top_earlgrey:sim_verilator`. This occurrence is fixed in 3 other places in the `BUILD` file.
- Removes both the `sim_dv` and `sim_verilator` execution environments from the `usbdev_aon_wake_reset_test` Bazel test target, as [the test source already immediately fails if the device type is DV or Verilator](https://github.com/lowRISC/opentitan/blob/70142638925f66eae20f6232b5a7c1ffc51ff0e3/sw/device/tests/usbdev_aon_wake_reset_test.c#L120) - this lack of support for simulator environments is now made explicit in the Bazel parameters.
- Marks the `spi_host_winbond_flash_test` as being `manual` for the Verilator environment, as it requires access to Winbond flash, which is not currently available in CI.
- Removes the Verilator execution environment from `rv_core_ibex_mem_test_prod`, because [the `rv_core_ibex` tests are marked as being incompatible with test_rom](https://github.com/lowRISC/opentitan/blob/70142638925f66eae20f6232b5a7c1ffc51ff0e3/sw/device/tests/BUILD#L5756-L5757), which Verilator uses, and as such this environement should not be supported.
- Marks the `pwrmgr_all_reset_reqs_test` Verilator execution environment as broken alongside the existing broken `fpga_cw310_sival_rom_ext` environment, as the test provides the same error in both cases.
- Removes the Verilator execution environment from `spi_host_smoketest`, as that test requires a flash connected to the SPI bus which is not emulated by Verilator.

2024-08-01 14:08 UTC, jwnrt approved these changes
Thanks, this LGTM if it passes CI. Thanks also for commenting the reasons why they're broken / manual.

2024-08-01 15:02 UTC, AlexJones0 commented
CI failed because I didn't autogenerate the `plic` tests with the added manual verilator tag and comments. I've just pushed that change so hopefully CI should pass now with that

2024-08-01 16:20 UTC, AlexJones0 commented
CI failed because I didn't autogenerate the `plic` tests with the added manual verilator tag and comments, and because of two instances of failed Bazel BUILD linting. I've just pushed those changes so hopefully CI should pass now with that.

2024-08-02 14:04 UTC, engdoreis requested changes
Overall it LGTM, thanks @AlexJones0 for the good work, I suggested some changes below.
I'm also blocking this PR with the "Request Changes" to avoid it merge before the end of the quiet period.

2024-08-02 14:04 UTC, engdoreis commented on sw/device/tests/BUILD
> +    verilator = verilator_params(tags = ["manual"]),
Why manual? Isn't this test that needs a spi flash on the bus and therefore can't be tests in verilator?

2024-09-06 12:58 UTC, AlexJones0 commented
Now that quiet period has ended, I've rebased on the latest changes to `master`, and I've also addressed the remaining feedback on the comments, code style and `spi_host_winbond_flash_test`. 

Everything from the original PR should still be relevant, except for the comment on `spi_host_winbond_flash_test`. Rather than marking this as `manual` for the Verilator environment, the Verilator sim environment is now removed from this test entirely, as a result of the test requiring an SPI flash on the bus, which is not available in Verilator.

2024-09-25 08:24 UTC, engdoreis approved these changes

2024-09-25 08:25 UTC, merged