[hw,dma,rtl] Flexible address increment options
lowRISC/opentitan pull request #24268
Opened 2024-08-09 18:08 UTC by Razer6

This PR adds support for a flexible address increment mode. For the source and destination address, the DMA can be configured to perform:

* No address increment (FIX). The DMA always reads/writes from the same address.
* Wrapped increment (WRAP). The DMA increments and when finishing one chunk wraps back to the starting address.
* Linear increment (LINEAR). The DMA always increments the address

These modes are independent of the hardware handshake mode. These changes would allow the DMA to be used for a memset operation, where a chunked source pattern is replicated in the destination memory range.

2024-09-06 14:38 UTC, alees24 requested changes
Thanks for this. Let me first say I strongly approve of the change to the register API because I've never liked the previous 3 configuration bits where the memory/fifo bits changed significance upon the confusing/poorly-named 'data_direction' bit.
The new API also permits some additional functionality for which I tried to advocate when we were reviewing the original design, making the controller more useful with 'chunked' operation.

There are a couple of faults with the current proposed implementation and we shall obviously need at least to introduce changes in the DV to map its present behavior onto the new programming API, even if we have to impose some additional constraints until the DV can be fully-updated.

Is any of the DV work in-progress or planned presently?

As per my review of the 'memset' PR, has consideration been given to whether introducing register changes that are less/not backwards-compatible is a concern?

2024-09-06 14:38 UTC, alees24 commented on hw/ip/dma/data/dma.hjson
> +              desc: "Do not increment the address, always write to the same address."
Small point but I think mode 0 should be named 'FIXED' rather than 'FIX'

2024-09-06 14:38 UTC, alees24 commented on hw/ip/dma/data/dma.hjson
> +          name: "src_addr_increment"
These 'address increment' values sound like the numerical offset to be added to the src/dst address. Could they perhaps be renamed to 'src|dst_addr_mode' please? I think that's clearer.

2024-09-06 14:38 UTC, alees24 commented on hw/ip/dma/rtl/dma.sv
> -    // when finishing a DMA operation when transitioning from a data move state to the idle state
Having removed the address update logic the 'LINEAR' address incrementing mode will not work as expected in the hardware handshaking mode.

If my memory/understanding are correct it can still be employed in the non-handshaking mode but only by relying upon firmware to provide the updated addresses.

2024-11-22 21:21 UTC, Razer6 commented
@alees24 I re-designed the flexible addressing by introducing two different control registers for source and destination. Both implement a bit `increment` and `wrap` to implement the functionality described in the PR description. This leaves room for future extensions for src and destination and also keeps the configuration symmetry. 

Could you take another look into this one?

2024-11-22 21:22 UTC, Razer6 commented on hw/ip/dma/rtl/dma.sv
> -    // when finishing a DMA operation when transitioning from a data move state to the idle state
This implemented now differently. When doing a linear address increment, we need to update the register addresses when being in multi-chunk mode.

2024-12-06 21:07 UTC, alees24 approved these changes
Okay, I think this logic now does what's wanted, thank you.
Just a couple of errors in the comments.

2024-12-07 20:36 UTC, alees24 requested changes, later dismissed
Please see the comment about 'new_src_addr'

Also, whilst we're still finalizing this, could you perhaps change 'SRC|DST_CONTROL' to 'SRC|DST_CONFIG', please? I think these names are better because a control register typically causes actions to occur, plus additional configuration such as stride values may meaningfully be added to the registers later.

Lastly, as you may have seen, the linting is complaining that the CMDGEN documentation is out of date. (Run ` ./util/cmdgen.py -u '**/*.md' ` from the project root.)

2024-12-07 20:36 UTC, alees24 commented on hw/ip/dma/rtl/dma.sv
> +                    SYS_ADDR_WIDTH'(chunk_byte_q);
Apologies that I did not notice the use of 'chunk_byte_q' here sooner....this may not have been updated at the point that 'new_src_addr' is used, and I don't see any reason for the disparity between the dst/src address updating anyway.
This was spotted in nascent DV changes; I'll contact you with a branch that you can use.

2024-12-23 18:07 UTC, andreaskurth approved these changes

2024-12-23 18:25 UTC, merged