[reggen] Allow a multireg's resval to depend on the index and use this in pinmux
lowRISC/opentitan pull request #24748
Opened 2024-10-08 15:54 UTC by rswarbrick

Until the last two commits, this change is all about allowing a multireg to expand more cleanly so that e.g. it can have different resvals for the copies with indexes 0 and 1. There's a certain amount of code cleanup in the earlier commits, which I had to do in order to work out what on earth was going on in the code!

The last two commits use this new feature in pinmux.hjson. This resolves #24621, which motivated the change. Annoyingly, there's *still* a bit of a hack where we encode the index for the magic pad into `pinmux.hjson`, but we've got similar examples elsewhere in the repository and I think it's a bit cleaner than what we had.

2024-10-09 10:13 UTC, rswarbrick commented
Force-push fixes a silly bug where we didn't interpret the field resval for gpio's DATA_IN register. (It has reset value 'x' and is not hwext and my rewrite didn't handle that quite right. Now fixed)

2025-02-13 13:06 UTC, rswarbrick commented
Force-push fixes two problems:
1. The penultimate commit changes autogenerated files (intentionally!) and I hadn't updated them.
2. The "[reggen] Move Register.make_multi into MultiRegister" commit wasn't distinguishing between a field with resval x and empty resval. It should!

2025-04-07 21:32 UTC, rswarbrick commented
Well, that was rather painful. I've just rebased this past an enormous autoformatting rewrite. @andreaskurth: do you think you'll be able to take a look at this soon?

2025-04-24 19:42 UTC, Razer6 commented
I also would like to see that feature to land as we have an immediate use case for that. @andreaskurth Can this prioritized? I will review this PR tomorrow.

2025-04-25 14:53 UTC, rswarbrick commented on util/reggen/field.py
> +                resval = eval(raw_value, bindings)
I'm afraid it isn't:
```
>>> ast.literal_eval("1 == 2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/xm56r94jg7mxcqdr6r2q8wki795mjgda-python3-3.11.11/lib/python3.11/ast.py", line 110, in literal_eval
    return _convert(node_or_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xm56r94jg7mxcqdr6r2q8wki795mjgda-python3-3.11.11/lib/python3.11/ast.py", line 109, in _convert
    return _convert_signed_num(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xm56r94jg7mxcqdr6r2q8wki795mjgda-python3-3.11.11/lib/python3.11/ast.py", line 83, in _convert_signed_num
    return _convert_num(node)
           ^^^^^^^^^^^^^^^^^^
  File "/nix/store/xm56r94jg7mxcqdr6r2q8wki795mjgda-python3-3.11.11/lib/python3.11/ast.py", line 74, in _convert_num
    _raise_malformed_node(node)
  File "/nix/store/xm56r94jg7mxcqdr6r2q8wki795mjgda-python3-3.11.11/lib/python3.11/ast.py", line 71, in _raise_malformed_node
    raise ValueError(msg + f': {node!r}')
ValueError: malformed node or string on line 1: <ast.Compare object at 0x7f3ad4f75a80>
```

The [literal_eval](https://docs.python.org/3/library/ast.html#ast-helpers) function doesn't allow operators and the only place we're using it in this PR is like this:
```
resval: (multireg_idx == 30)
```

2025-04-25 14:54 UTC, rswarbrick commented
(Nothing interesting in the force-push: it's just a trivial rebase, pulling in the changes on master since last time)

2025-04-29 09:03 UTC, andreaskurth commented on hw/top_darjeeling/ip_autogen/pinmux/data/pinmux.hjson
> +                      resval: (multireg_idx == 30)
Does this work for Darjeeling? I'm asking because for Earlgrey we have
https://github.com/lowRISC/opentitan/blob/6289ededa021225d7d04157a64e4bf022e63da76/hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv#L99
but for Darjeeling it is
https://github.com/lowRISC/opentitan/blob/6289ededa021225d7d04157a64e4bf022e63da76/hw/top_darjeeling/rtl/autogen/chip_darjeeling_asic.sv#L122

CC @Razer6

2025-04-30 10:04 UTC, rswarbrick commented on hw/ip_templates/pinmux/data/pinmux.hjson.tpl
> +                      resval: (multireg_idx == 30)
Ah, that's a bit sad. On the plus side, we can probably cheat: because pinmux is already templated, we can add the index as a parameter that gets used in the expansion. I'll pick that up today.

2025-04-30 11:00 UTC, rswarbrick commented on hw/ip_templates/pinmux/data/pinmux.hjson.tpl
> +                      resval: (multireg_idx == 30)
Following up on this slightly:

Ok, I've finally understood properly :-) This seems to be (yet) another example of where SystemVerilog parameters don't really play very well with the reggen-style hjson flow.

The top-level configuration passes a `TargetCfg` parameter and one field of that parameter gives the index of the mio that should be used for strap0. The code in `pinmux.sv` then uses this to set some element of the constant `mio_pad_attr_q` array which, in turn, sets an element of the constant `hw2reg.mio_pad_attr`, affecting the reset value of some register.

This basically gives a path from a parameter to something that reggen cares about, which causes problems.

The laziest approach is probably:
- Add a "tap_strap0_idx" field to the pinmux Mako template
- Use that in `pinmux.hjson.tpl` instead of the literal 30
- Add a check in `pinmux.sv.tpl` to make sure that the parameter that comes in from the instantiation site matches the value that comes in through templating.

2025-04-30 12:52 UTC, rswarbrick commented on hw/top_darjeeling/ip_autogen/pinmux/data/pinmux.hjson
> +                      resval: (multireg_idx == 30)
I think the version I just force-pushed should sort this out.

2025-04-30 12:53 UTC, rswarbrick commented on hw/ip_templates/pinmux/data/pinmux.hjson.tpl
> +                      resval: (multireg_idx == 30)
(Lazy approach now done! :-D)

2025-04-30 14:28 UTC, Razer6 requested changes

2025-04-30 14:28 UTC, Razer6 commented on hw/top_darjeeling/ip_autogen/pinmux/data/pinmux.hjson
> +                      // Note: The special index where this has a different resval depends on the
The config should be an Earlgrey-only conifg and not render in Darjeelings pinmux instance.

2025-04-30 14:28 UTC, Razer6 commented on util/topgen.py
> +    if tap_strap0_idx >= n_mio_pads:
This is now pulling in an Earlgrey specific thing into the tooling. We should find a way to avoid that and provide the necessary information from the HJSONs and maybe ipgen parameters.

2025-05-01 12:00 UTC, rswarbrick commented on hw/top_darjeeling/ip_autogen/pinmux/data/pinmux.hjson
> +                      // Note: The special index where this has a different resval depends on the
Are you saying that there is no such pad in Darjeeling? If so, that's fine. We can just set that index to `-1`, I should think. But the current RTL does not do that!

2025-05-01 15:32 UTC, rswarbrick commented on util/topgen.py
> +    if tap_strap0_idx >= n_mio_pads:
Hmm, I think this has the same response as the previous note. I suspect the right thing to do is to set `tap_strap0_idx` to `-1` for Darjeeling (and then this code is completely reasonable, although it would be worth me adding a couple of documentation comments to explain what's going on)

Is that right?

2025-05-05 06:19 UTC, Razer6 commented on hw/top_darjeeling/ip_autogen/pinmux/data/pinmux.hjson
> +                      // Note: The special index where this has a different resval depends on the
Yes, that is correct. Straps are very integrator-specific. The EG/Nuvoton design is one integration, which needs that but that does not say anything about other designs. In fact DJ does not need since the TAP is outside of the top. even EG has efforts for changing that.

More importantly, this impacts any other TOP that uses a pinmux. They need to set an Earlgrey specific customization that is completely unrelated to them. Further, pulling EG-specific code into topgen is worse. It is topgen and not EGgen. How would you imagine this feature being used by someone else? Do they need to modify topgen for their variables?  

I think the right way moving forward is to pull in __all__ pinmux indices to ipgen such that the reserved value computation can access them in a clean fashion without adding a special case for one specific pin that only relates to one TOP.

2025-05-07 11:23 UTC, rswarbrick commented on hw/top_darjeeling/ip_autogen/pinmux/data/pinmux.hjson
> +                      // Note: The special index where this has a different resval depends on the
That makes sense. I'll set the default value to -1 (i.e. "not used") and override it for EarlGrey. I agree that we could definitely do this more cleanly, but that needn't gate the improvement that (I hope) is in this PR.

2025-05-23 12:03 UTC, Razer6 commented on hw/ip_templates/pinmux/data/pinmux.hjson.tpl
> +                      resval: (multireg_idx == ${tap_strap0_idx})
I think this code should only be rendered if `tap_strap0_idx ` > 0

2025-05-23 12:06 UTC, Razer6 commented on util/topgen.py
> +    if tap_strap0_idx >= n_mio_pads:
Can this check be moved to the parametrized pinmux template?

2025-05-23 15:19 UTC, rswarbrick commented on hw/ip_templates/pinmux/data/pinmux.hjson.tpl
> +                      resval: (multireg_idx == ${tap_strap0_idx})
Honestly, I'm really unconvinced that this PR has the "right way" to solve the problem! I think the better approach is probably a bodge on the UVM side (where we squirt in some information to tell the register model the correct resval to expect)

I'm going on holiday next week, but intend to come back to this and make the change more carefully. That's part of the reason that I factored out the "obviously right" bit into #27289.

2026-08-12 21:37 UTC, rswarbrick commented
I'm closing this because it has rather bit-rotted and we haven't had an immediate use for it. Some of the machinery is now merged, so we should be able to implement the specific example in future if we need it.

2026-08-12 21:37 UTC, closed without merging