[darjeeling] Instantiate Darjeeling from Master
lowRISC/opentitan pull request #25156
Opened 2024-11-15 11:19 UTC by Razer6

We are finally able to instantiate Darjeeling from the `master` branch. This commit is separated into 3 commits:

1. Gate `SEC_CM`'s in pinmux that are used only when hardware strap sampling is active. This is only the case for Earlgrey and English Breakfast
2. Add the HJSON files that define Darjeeling. That includes the top-level HKSON and all Crossbar definitions
3. Add Darjeeling to `hw/Makefile` and run `make -C hw top_and_cmdgen` to generate Darjeeling and all other artifacts.

2024-11-15 11:38 UTC, Razer6 commented
The verible lint job fails because this PR is exceeding the maximum number of files.

2024-11-15 14:29 UTC, andreaskurth commented
> The verible lint job fails because this PR is exceeding the maximum number of files.

Here's the output of a manual Verible lint run on the files changed by this PR:
```
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:30:27: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:32:26: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:34:30: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:36:32: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:37:32: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:38:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:39:22: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:40:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:41:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:42:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:43:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:44:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:45:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:46:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:47:27: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:48:28: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:49:28: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:51:24: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:52:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:53:27: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:54:28: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:55:27: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:56:28: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:57:28: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:58:27: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:59:17: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:60:17: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:61:16: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:62:18: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:63:17: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:64:17: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:65:20: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:66:17: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:67:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:68:30: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:69:33: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:70:32: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:71:33: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:72:32: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:73:16: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:74:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:75:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:76:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:77:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:78:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:79:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:80:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:81:27: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:82:28: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:83:28: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:84:18: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:85:17: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:86:17: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:87:22: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:88:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:89:21: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:90:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:91:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:92:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:93:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:94:27: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:95:27: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:96:26: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:97:24: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:98:26: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:99:36: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:100:35: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:101:26: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:102:16: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:103:22: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:104:22: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:105:22: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:106:22: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:107:22: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:108:22: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:109:22: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:110:27: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:111:27: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:112:23: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:113:26: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:114:25: syntax error at token "("
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:9:61: syntax error at token "\"
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:10:87: syntax error at token "\"
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:11:87: syntax error at token "\"
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:12:58: syntax error at token "\"
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:9:61: syntax error at token "\"
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:10:87: syntax error at token "\"
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:11:87: syntax error at token "\"
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:12:58: syntax error at token "\"
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:9:61: syntax error at token "\"
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:10:87: syntax error at token "\"
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:11:87: syntax error at token "\"
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:12:58: syntax error at token "\"
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:16:63: syntax error at token "\"
hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv:17:87: syntax error at token "\"
hw/top_darjeeling/dv/autog [...]

2024-11-15 15:03 UTC, andreaskurth commented
A manual run of _Check for and block unauthorized changes_ with
```
git diff --name-only $(git merge-base origin/master HEAD)..HEAD > changes-file
ci/scripts/check-pr-changes-allowed.py --pr-number 25156 changes-file
```
passed; thus there are no changes to authorize in this PR.

2024-11-15 15:06 UTC, andreaskurth approved these changes
This PR seems huge, but most changes are autogenerated and contained within one commit, which contains the command to generate them. I cross-checked the autogenerated file by repeating the command, and it matches. (This is in addition to a CI check that should catch mismatches, I think.)

LGTM!

2024-11-18 09:29 UTC, andreaskurth requested changes
Changes related to FuseSoC / virtual cores and linting / dvsim flows are needed to resolve conflicts with Earlgrey. This is ongoing work; withdrawing approval for now (architecturally still LGTM, though).

2024-11-19 22:06 UTC, matutem commented on hw/top_darjeeling/chip_darjeeling_asic.core
> +      - "fileset_partner ? (partner:systems:ast)"
The ast is a good example of a clumsy VLNV: the core should be "opentitan: earlgrey_systems:ast" and "opentitan:darjeeling_systems:ast". Heck, the "systems" part is also silly, and could just be "ip". The problem is that the current naming doesn't work well with real multitop: "partner" is a sort of singleton, and "systems" is too broad. I imagine we will have flags to name the top.

2024-11-19 22:17 UTC, matutem commented
I think the verible failures reflect a real problem. The tb__xbar_connect.sv file is meant to be included from some other file, so it would be within a module or interface, and it would also see a declaration of clk_rst_if. I don't see a core file that this is a part of. Perhaps that is needed?

2024-11-19 22:21 UTC, matutem requested changes
The worst part of this is the lack of context for linting things like tb__xbar_connect.sv. The actual code in integrated must solve it (or you have a bigger problem there), and that solution will be needed here for basic sanity.

2024-11-22 21:10 UTC, Razer6 commented
Closing this one as the other PR has been merged

2024-11-22 21:10 UTC, closed without merging