[entropy_src, dv] Replace the "+" operator incorrectly used to concatenate string literals in SystemVerilog code
lowRISC/opentitan pull request #25497
Opened 2024-12-03 13:37 UTC by dariuszst

The SystemBerilog LRM doesn't allow to use a  "+" operator for string literals concatenation. It should be replaced with correct form of concatenation expression (using {} brackets).

2024-12-04 10:16 UTC, rswarbrick commented on hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
> +                   "(supercedes count/threshold of %01d/%01d)"};
Thanks for the change: this looks good.

But...
- Please could you indent the second line so that the " characters line up?
- Since we're touching the code, can we also fix the spelling of "anticipated" and "supersedes"?

Thanks!

2024-12-04 12:05 UTC, dariuszst commented on hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
> +                   "(supercedes count/threshold of %01d/%01d)"};
I've made this corrections in a new commit. Is it OK?

2024-12-09 12:33 UTC, dariuszst commented on hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
> +                   "(supercedes count/threshold of %01d/%01d)"};
OK. I've squashed it.

2024-12-09 14:43 UTC, rswarbrick commented
Annoyingly, it looks like lint has failed because of the commit message. I think there's a missing newline, and the commit message would be nice if it had the [square brackets] stuff at the front like the message on the PR. Could you do that?

2024-12-13 01:04 UTC, matutem commented on hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
> +                   "(supersedes count/threshold of %01d/%01d)"};
```suggestion
            fmt = {"New alert anticipated with >= 2 failing windows ",
                   "(supersedes count/threshold of %01d/%01d)."};
```

2024-12-13 01:11 UTC, matutem requested changes
Could you also make the commit message more succinct to help the folks reading this in the future? Something like "Fix incorrect string concatenation" seems adequate to describe the change.

I also made a change suggestion.

2025-02-25 02:13 UTC, matutem commented
Perhaps you didn't do a "git commit --amend" in your update of Dec 13, since this shows two commits.

2025-02-25 02:14 UTC, matutem approved these changes

2025-05-07 08:31 UTC, rswarbrick commented
I've just squashed the commits together and rebased onto the head of master. Assuming nothing falls over in CI, this should be good to go.

2025-05-07 10:49 UTC, merged