[sw] Add assembler (as) to toolchain.txt
lowRISC/opentitan pull request #3310
Opened 2020-09-01 08:44 UTC by imphil

An assembler is part of the toolchain, and we need to make it available
for OTBN tooling.

2020-09-01 17:22 UTC, lenary requested changes
You need to also update the example toolchain.txt in `doc/ug/install_instructions/index.md`

2020-09-02 21:44 UTC, imphil commented
@lenary updated.

2020-09-03 00:26 UTC, alistair23 approved these changes

2020-09-03 10:08 UTC, lenary approved these changes
LGTM

2020-09-03 10:08 UTC, merged