[dv:tTL UL agent] updated tl_ul to select transctions ID from fifo ti support b2b transactions
lowRISC/opentitan pull request #3417
Opened 2020-09-11 11:15 UTC by rasmus-madsen

This PR contains The update that I was tasked with in the TL UL meeting + a fix to zero delays.

A queue is added to the tl_agent_cfg. The queue contains available transaction IDs from [0 : Max_outstanding_req-1] and is randomized before the test starts.

when the driver sends a transaction it pops an available ID from the queue,
when the Transaction is completed by the device the monitor will push the ID back into the queue.

Q: currently Ids are Popped from the front and pushed in the back.
this means all ID's will be cycled. another option is to push and pop on the same side of the queue which will only use the first few IDs

Q: currently the queue is randomized before the test starts, I don't think this hurts us - but realistically a host will probably start with id=0 and increment.

with this PR I also added a knob to control the pct of which zero_delays will be set 
this allows a designer to control the value from a test or a higher level config item.

there is also a little AES clean up that came about in the process of debugging an issue with controlling zero_delays.

should we merge this until we have a better suggestion or should we wait for @sriyerg and @weicaiyang solutions?
Aes is not blocked but scribbled as long as B2b is not an option

2020-09-11 13:36 UTC, rswarbrick requested changes
Hi ~~Magnus~~ Rasmus (sorry!)! Some nitty stuff, plus a proper question about replacement strategy into the queue. Also, could you split out the AES changes into a separate PR? As far as I can see, these aren't related to the ID queue?

2020-09-11 13:36 UTC, rswarbrick commented on hw/dv/sv/tl_agent/tl_host_driver.sv
> +    //                   wait(reset_asserted);)
I think you probably intended to remove this commented code? Also, I think the indentation in the replacement looks wonky: I realise this wasn't your doing, but let's fix it since we're touching the code!

2020-09-11 13:36 UTC, rswarbrick commented on hw/dv/sv/tl_agent/tl_monitor.sv
> +            cfg.outstanding_req_fifo.push_back(rsp.d_source);
I think this design means we always cycle through IDs in some fixed order. I wonder whether it would make sense to re-insert `rsp.d_source` at a random position in the queue of outstanding request IDs? Then you'd occasionally see consecutive requests with the same ID, for example.

... Ah! I just read the commit message again. Is this "maximum length between IDs" behaviour a particularly stressful mode for the DUT? Otherwise, I'd definitely consider making the replacement position random (and, if we need front or back replacement in future, we could always add a knob for it).

2020-09-11 13:36 UTC, rswarbrick commented on hw/ip/aes/dv/tests/aes_base_test.sv
> +    // configure_env();
What does removing this call do? (That's a genuine question!) And, if we want to remove it, I think it should be deleted rather than commented.

2020-09-11 13:37 UTC, rswarbrick commented
Oh, and the failing CI doesn't look like it's anything to do with you. I'm going to have a bit of a dig to understand that now.

2020-09-11 13:55 UTC, rasmus-madsen commented on hw/dv/sv/cip_lib/cip_base_env.sv
> +    `uvm_info(`gfn, $sformatf("RASMUS - Setting zero delays to %d",cfg.zero_delays), UVM_LOW)
Crap how did I miss that.. sorry

2020-09-11 13:58 UTC, rasmus-madsen commented on hw/dv/sv/dv_lib/dv_base_env_cfg.sv
> +  int zero_delay_pct    = 40;
Matter of opinion. some like to keep relevant variables together for easy readability.
but I will move it

2020-09-11 14:00 UTC, rasmus-madsen commented on hw/dv/sv/dv_lib/dv_base_env_cfg.sv
> +    zero_delays dist {1'b0 :/ 100-zero_delay_pct, 1'b1 :/ zero_delay_pct};
at least for clearity it should be there..  but it seem to work without it

2020-09-11 14:03 UTC, rasmus-madsen commented on hw/dv/sv/tl_agent/tl_host_driver.sv
> +    //                   wait(reset_asserted);)
no I kept it un purpose as I see my PR as a temp fix and this code might be needed for the final fix

2020-09-11 14:07 UTC, rasmus-madsen commented on hw/ip/aes/dv/tests/aes_base_test.sv
> +    // configure_env();
it configures the environment config.
it should be unneeded as the cfg variables should have default values. and the individual tests should reconfigure on their own.
I removed it because I released that I rerandomize the environment several times.

2020-09-11 14:12 UTC, rasmus-madsen commented on hw/dv/sv/tl_agent/tl_monitor.sv
> +            cfg.outstanding_req_fifo.push_back(rsp.d_source);
I will shuffle the queue before a pop that should resolve my own question and yours

2020-09-11 15:02 UTC, rasmus-madsen commented
@rswarbrick I think all your comments should be addressed by my latest update

2020-09-11 16:15 UTC, rswarbrick reviewed
I like the new shuffling code! (And had no idea it was so easy to do in SystemVerilog). I think there are still some AES changes in the first commit: maybe this needs a little more rejigging in git?

2020-09-11 16:15 UTC, rswarbrick commented on hw/dv/sv/dv_lib/dv_base_env_cfg.sv
> +    zero_delays dist {1'b0 :/ (100-zero_delay_pct), 1'b1 :/ zero_delay_pct};
I think there's still space missing around the '-' sign (I know it's a nit, but we have a style guide, so I guess we should follow it).

2020-09-11 16:15 UTC, rswarbrick commented on hw/dv/sv/tl_agent/tl_agent_cfg.sv
> +  };
Since you're shuffling on pop, I don't think you actually need to do this: you can just initialise `outstanding_req_fifo` in order, can't you?

2020-09-11 16:15 UTC, rswarbrick commented on hw/dv/sv/tl_agent/tl_host_driver.sv
> +    //                   wait(reset_asserted);)
Right, in which case you either need a comment above it of the form "`// Hey, this was the previous code and this is why I'm leaving it in...`" or just delete it - this is version controlled, so I'd hope that anyone can look up diffs easily enough!

2020-09-11 16:15 UTC, rswarbrick commented on hw/dv/sv/tl_agent/tl_host_driver.sv
> +                   wait(reset_asserted);)
Nit: I think line 73 needs 2 more spaces.

2020-09-11 16:15 UTC, rswarbrick commented on hw/dv/sv/tl_agent/tl_monitor.sv
> +            cfg.outstanding_req_fifo.push_back(rsp.d_source);
Sounds like a plan!

2020-09-11 16:16 UTC, rswarbrick commented
Oh, and the CI failures aren't spurious this time :-) You'll need to re-format your commit messages to the standard style (one short header line, a blank line, the body text).

2020-09-11 19:34 UTC, weicaiyang commented on hw/dv/sv/tl_agent/tl_agent_cfg.sv
> +  };
`max_outstanding_req` is only 2 for most of IPs. ID number can be from 0-255. we should put all available IDs

agree with @rswarbrick, we can simply create an in-order fifo like this.
nit: rename the fifo as it is to store all available ids
`for (int i = 0; i < (1 << SourceWidth); i++) avail_id_fifo.push_back(i);`

2020-09-11 19:34 UTC, weicaiyang commented on hw/dv/sv/tl_agent/tl_host_driver.sv
> +    //                   wait(reset_asserted);)
I feel we should also support to use the source from transaction. I have a test to control source in sequence item.
so, it's better to have knob to take source from either seq_item or cfg.

But if it's from seq_item, we still need these statement to wait until no outstanding item with same source id. it seems ok that seq sends item without looking at what source IDs are used, but it's driver's duty to send it without violating protocol.

2020-09-11 19:34 UTC, weicaiyang commented on hw/ip/aes/dv/tests/aes_wake_up_test.sv
> +     cfg.en_scb             = 0;
good to have comment why scb is disabled

2020-09-12 01:46 UTC, tunghoang290780 commented on hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
> +    csr_wr(.csr(ral.data_in_3), .value(data[3][31:0]), .blocking(0) );
Could the last csr_wr and csr_rd stay with blocking(1)? It does not hurt performance much but robust in terms of data persistent

2020-09-12 01:55 UTC, tunghoang290780 commented on hw/dv/sv/tl_agent/tl_agent_cfg.sv
> +  };
if there are only 256 IDs, can we initialize a unique, randomized id FIFO which is pop_front by driver and push_back by monitor? With this approach, there is no duplicate ID to be used in any window with the size of max_outstanding. When the fifo is full (no ID is used), the fifo can be re-randomized again if desired

2020-09-12 02:02 UTC, tunghoang290780 commented
> Hi ~Magnus~ Rasmus (sorry!)! Some nitty stuff, plus a proper question about replacement strategy into the queue. Also, could you split out the AES changes into a separate PR? As far as I can see, these aren't related to the ID queue?

Agree with @rswarbrick to make this PR focus on tl_agent only (submit AES's stuff in another PR). This is because tl_agent is widely adopted and would affect the other IPs.

2020-09-12 07:01 UTC, sriyerg reviewed
Consider spinning the `zero_delays_pct` stuff out into its own PR so that it can be merged ASAP. 
I have the alternate solution to the queuing (like we had discussed) in #3425.

2020-09-12 07:06 UTC, sriyerg commented on hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
> +    csr_wr(.csr(ral.data_in_3), .value(data[3][31:0]), .blocking(0) );
You can add barrier synchronization (wait for all non blocking CSR accesses to complete) by invoking 
```systemverilog
  csr_utils_pkg::wait_no_outstanding_access();
```

2020-09-12 07:15 UTC, sriyerg commented on hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
> +    csr_rd(.ptr(ral.data_out_3), .value(cypher_txt[3][31:0]), .blocking(1));
You can make these non blocking too if you want to be adventurous (just add the barrier sync at the end).

2020-09-14 08:56 UTC, rasmus-madsen commented on hw/dv/sv/dv_lib/dv_base_env_cfg.sv
> +    zero_delays dist {1'b0 :/ (100-zero_delay_pct), 1'b1 :/ zero_delay_pct};
I completely agree we should follow our style guide.

2020-09-14 09:08 UTC, rasmus-madsen commented on hw/dv/sv/tl_agent/tl_agent_cfg.sv
> +  };
@rswarbrick correct - after the added shuffle this can be reduced to a simple init.
@weicaiyang thanks for the suggestion 
I think @tunghoang290780 has a point.
There is nothing in the spec that prevents a host from starting with ID 200 vs 0. 
Also there is nothing preventing the host from cycling all IDs even with a max_outstanding_of 2.

so maybe queue length should be randomized to something between [max_outstanding_req : 256]

2020-09-14 09:10 UTC, rasmus-madsen commented on hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
> +    csr_rd(.ptr(ral.data_out_3), .value(cypher_txt[3][31:0]), .blocking(1));
@sriyerg Currently it seems there is a bug in the TL agent or RAL seq for non-blocking reads
which is why these are set to 1.
I have an issue ready but I figured it is unrelated to this PR - and until a fix for the B2B is merged it cannot be reproduced.

2020-09-14 09:13 UTC, rasmus-madsen commented
@rswarbrick @weicaiyang @sriyerg @tunghoang290780 
I am holding back on fixing the review comments here as we only need one of the 3 solutions (mine, @sriyerg or @weicaiyang )
and I think we will most likely go with @sriyerg suggestion (I have yet to review it) but we all agreed that it would be the cleanest in the meeting.

so unless we decided that my approach which was meant to be quick is the way we want to go I see no point in spending time updating it.
some good points were made though and we should make sure these are considered in the other two suggestions

2020-09-14 18:35 UTC, weicaiyang commented on hw/dv/sv/tl_agent/tl_agent_cfg.sv
> +  };
it makes sense to have queue length between [max_outstanding_req : 256], as it may reuse ID sooner as well as using all the possible IDs.

2020-11-12 20:02 UTC, closed without merging