[prim_ram_1p_adv/fpv] fix assertion
lowRISC/opentitan pull request #3573
Opened 2020-09-24 00:47 UTC by cindychip

The assertion `OnlyWordWritePossibleWithEccPortA_A` has two issues:
1. wmask_i is an input with width [Width-1:0], this assertion is always
false if `TotalWidth != Width`, means if `ParWidth != 0`.
2. since in formal, input `wmask_i` is driven randomly without any
constraint, I think might be better to change it from assertion to
assumption. And in simulation, assupmtions will be treated as
assertions.

I am not sure if this fix is correct, please let me know what you think.

Signed-off-by: Cindy Chen <chencindy@google.com>

2020-09-24 00:49 UTC, cindychip commented on hw/ip/prim/rtl/prim_ram_1p_adv.sv
> +          wmask_i == {Width{1'b1}})
Hey michael, please let me know what you think about the fix. I believe this would also work:
```
    `ASSUME(OnlyWordWritePossibleWithEccPortA_A, req_i |->
          wmask_d== {TotalWidth{1'b1}})
```

2020-09-24 01:13 UTC, msfschaffner approved these changes
Thanks for the fix, @cindychip!

2020-09-24 01:13 UTC, msfschaffner commented on hw/ip/prim/rtl/prim_ram_1p_adv.sv
> +          wmask_i == {Width{1'b1}})
Your fix looks correct to me. Can you also carry this over to the 2p_adv version?

2020-09-24 09:00 UTC, rswarbrick requested changes
I don't think it's right to change ASSERT to ASSUME in the design.

This assertion is a claim about the input behaviour. If we change it to an assumption, formal checks won't catch modules instantiating the RAMs that set bogus `wmask_i` values. I would suggest you fix the contents of the check, but leave it as an assertion, then add a corresponding assumption to the formal TB.

EDIT: It seems I mangled the original version of this comment, and added a half-finished version of the paragraph above afterwards. Deleted.

2020-09-24 16:36 UTC, cindychip commented
hi Rupert,

Thank you for the comments. I agree that for IPs that instantiate this
module, the assumption won't catch the issue. But this assertion will
surely fail if we only do formal at the module level (eg:
`prim_ram_1pm_adv` formal testbench). I think you are right for changing it
back to assert and maybe if we really do a FPV testbench at the module
level (eg: `prim_ram_1pm_adv`), then adding more assumptions to
support this would be necessary.


  Cindy Chen


On Thu, Sep 24, 2020 at 2:01 AM Rupert Swarbrick <notifications@github.com>
wrote:

> *@rswarbrick* requested changes on this pull request.
>
> I don't think it's right to change ASSERT to ASSUME in the design.
>
> This assertion is a claim about the input behaviour. If we change it to an
> assumption, formal checks won't catch modules that set bogus wmask_i
> values. I would suggest you fix the contents of the check, but leave it as
> an assertion, then add a corresponding assumption to the formal TB.
>
> Are you sure the ASSERT -> ASSUME change is the right thing to do? I would
> have thought an ASSUME belongs in a formal testbench in which you
> instantiate the ram. At the moment, this check will mask failures for
> blocks that send
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lowRISC/opentitan/pull/3573#pullrequestreview-495363476>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACXPOOJWP3P6RMMKPTIHUOTSHMDFLANCNFSM4RXVOBIQ>
> .
>

2020-09-25 09:17 UTC, rswarbrick commented
> I think you are right for changing it
back to assert and maybe if we really do a FPV testbench at the module
level (eg: `prim_ram_1pm_adv`), then adding more assumptions to
support this would be necessary.

Sounds sensible to me. Fundamentally, the RAM primitive only works if it's driven properly. So I think it doesn't really make sense to try to "test" it without a surrounding testbench that drives the signals in a valid way (which would then have the matching ASSUME statements)

2020-09-25 09:18 UTC, rswarbrick approved these changes
Looks good to me. Thanks!

2020-09-25 16:24 UTC, merged