entropy_src/rtl] rtl style review updates
lowRISC/opentitan pull request #3695
Opened 2020-10-05 16:13 UTC by mwbranstad

Signed-off-by: Mark Branstad <mark.branstad@wdc.com>

Comments made after the last entropy_src PR have been folded into this PR.

Changes relate to flop reset formats, block instantiation format, generate format, and sparse fsm updates.

2020-10-05 19:14 UTC, tjaychen commented on hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
> +  localparam int StateWidth = 6;
ah i left this comment in another PR, but @msfschaffner has created a small utility to do this function.
Up to you if you want to re-use it. 

The other part is that we've begun to declare `prim_flop` for the `state_q` to ensure synthesis won't do anything funny.

2020-10-05 19:15 UTC, tjaychen approved these changes
generally lgtm. just one comment on the sparse FSM

2020-10-05 19:50 UTC, mwbranstad commented on hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
> +  localparam int StateWidth = 6;
Is the prim_flop to ensure that the hamming code is not dropped/reduced?

2020-10-05 21:46 UTC, cdgori commented on hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
> +  localparam int StateWidth = 6;
Mostly yes.  There is some concern that higher levels of optimization + timing pressure will cause the tool to restructure the FSM encoding in a way that doesn't preserve the sparse encoding, so we manually put flops with `size_only` on them to try to prevent that.  I'm not sure it will work 100% (as the optimizer can be very clever sometimes, I've seen some truly amazing things in the past) but it's better than free reign.

2020-10-06 07:24 UTC, rswarbrick requested changes
Please update the commit message with the text that you put in the PR. Once this change is committed, the commit message is what appears in the repo; the text that you wrote in the PR will probably never be seen again (unless someone bothers to look it up on GitHub).

2020-10-06 22:31 UTC, mwbranstad commented
@rswarbrick thanks for pointing this out. I think I have figured out what you are saying and how to fix with @rasmus-madsen helping to explain it.

2020-10-07 07:11 UTC, rswarbrick commented
Thanks!

2020-10-08 18:13 UTC, msfschaffner approved these changes
Thanks for cleaning this up @mwbranstad. This LGTM, with a few small comments.

2020-10-08 18:13 UTC, msfschaffner commented on hw/ip/entropy_src/rtl/entropy_src_repcnt_ht.sv
> +    for (genvar sh = 0; sh < RngBusWidth; sh = sh+1) begin : gen_cntrs
nit: the indentation of this block can be 2 spaces now, since it is not wrapped in `generate` `endgenerate` (this also holds for other instances elsewhere).

2020-10-08 18:13 UTC, msfschaffner commented on hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
> +  localparam int StateWidth = 6;
if you use the script, please also copy the metadata comment header into the code (with the arguments) such that the state generation is repeatable. @cdgori what's the minimum HD that we would like to require? 3,4,5?

here's an example output of the script for your configuration:
`$ hw/ip/prim/util/sparse-fsm-encode.py -n 6 -m 6 -d 3`
```systemverilog
// Encoding generated with ./sparse-fsm-encode.py -d 3 -m 6 -n 6 -s 2831284722
// Hamming distance histogram:
//
// 0: --
// 1: --
// 2: --
// 3: |||||||||||||||||||| (53.33%)
// 4: ||||||||||||||| (40.00%)
// 5: || (6.67%)
// 6: --
//
// Minimum Hamming distance: 3
// Maximum Hamming distance: 5
//
localparam int StateWidth = 6;
typedef enum logic [StateWidth-1:0] {
  State0 = 6'b101101,
  State1 = 6'b001000,
  State2 = 6'b011110,
  State3 = 6'b100110,
  State4 = 6'b000011,
  State5 = 6'b110001
} state_e;

state_e state_d, state_q;
always_comb begin : p_fsm
  // Default assignments
  state_d = state_q;

  unique case (state_q)
    State0: ;
    State1: ;
    State2: ;
    State3: ;
    State4: ;
    State5: ;
    default: ; // Consider triggering an error or alert in this case.
  endcase
end

// This primitive is used to place a size-only constraint on the
// flops in order to prevent FSM state encoding optimizations.
prim_flop #(
  .Width(StateWidth),
  .ResetValue(StateWidth'(State0))
) u_state_regs (
  .clk_i,
  .rst_ni,
  .d_i ( state_d ),
  .q_o ( state_q )
);
```

2020-10-08 19:18 UTC, merged

2020-10-08 19:45 UTC, rasmus-madsen commented
The original change request was made by @msfschaffner  in #3004 
and he has approved this together with 1 additional approver.
so I will merge this

2020-10-08 23:16 UTC, cdgori commented on hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
> +  localparam int StateWidth = 6;
I think 3 is enough.