[dv] Fix tl_err due to no unmapped address
lowRISC/opentitan pull request #4343
Opened 2020-11-30 19:49 UTC by weicaiyang

Address #4317

Signed-off-by: Weicai Yang <weicai@google.com>

2020-12-01 08:13 UTC, rswarbrick requested changes

2020-12-01 08:13 UTC, rswarbrick commented on hw/dv/sv/dv_base_reg/dv_base_reg_block.sv
> +  protected function void compute_addr_mask(uvm_reg_map map = get_default_map());
I see no need for a default argument here: this is a protected method, so there won't be lots of call sites. I'd suggest making the choice of map explicit.

2020-12-01 08:13 UTC, rswarbrick commented on hw/dv/sv/dv_base_reg/dv_base_reg_block.sv
> +  function uvm_reg_addr_t get_addr_mask(uvm_reg_map map = get_default_map());
Is there a reason to change the way this default works? I think @sriyerg did it this way to match existing UVM functions. I'd suggest leaving it. Similarly for the methods below.

2020-12-01 08:13 UTC, rswarbrick commented on hw/dv/sv/cip_lib/cip_base_vseq__tl_errors.svh
> +  all_csrs.shuffle();
I don't see why this line has anything to do with what happens when there are no unmapped addresses. If it's unrelated, please split it into a different commit or at least add a note in the commit message that you've done something.

2020-12-01 08:13 UTC, rswarbrick commented on hw/dv/sv/dv_base_reg/dv_base_reg_block.sv
> +  // Return the max offset of the CSR or mem
Please expand this comment, explaining what the "max offset" is (the address of the highest byte contained in either a register or a memory).

2020-12-01 08:13 UTC, rswarbrick commented on hw/dv/sv/cip_lib/cip_base_vseq__tl_errors.svh
>    csr_addr_mask[1:0] = 0;
I think you probably need to switch these two lines around (to avoid problems where csr_addr_mask is greater than the maximum offset, but not after rounding down).

2020-12-01 18:55 UTC, weicaiyang commented on hw/dv/sv/cip_lib/cip_base_vseq__tl_errors.svh
>    csr_addr_mask[1:0] = 0;
I feel my code is right, since max_offset is the highest byte address of the reg/mem.
Assume we just have 1 reg in the IP. then, csr_addr_mask is 3, max_offset is also 3. has_unmapped_addr=0.
If `csr_addr_mask[1:0] = 0;` is executed before the comparison, csr_addr_mask becomes 0 and we have `has_unmapped_addr=1`

LMK if there is something wrong here

2020-12-01 18:55 UTC, weicaiyang commented on hw/dv/sv/dv_base_reg/dv_base_reg_block.sv
> +  protected function void compute_addr_mask(uvm_reg_map map = get_default_map());
since we assign default value to the map in the other function, I changed this too. But it's protected function, probably no need to provide default value.

2020-12-01 18:55 UTC, weicaiyang commented on hw/dv/sv/dv_base_reg/dv_base_reg_block.sv
> +  // Return the max offset of the CSR or mem
Added. Thanks

2020-12-01 18:55 UTC, weicaiyang commented on hw/dv/sv/cip_lib/cip_base_vseq__tl_errors.svh
> +  all_csrs.shuffle();
you're right. This is not related. It's just a very minor improvement. I made it in a separated commit.

2020-12-01 18:55 UTC, weicaiyang commented on hw/dv/sv/dv_base_reg/dv_base_reg_block.sv
> +  function uvm_reg_addr_t get_addr_mask(uvm_reg_map map = get_default_map());
I thought it might be cleaner since we check it and use default_map for null.
But I just realized upper level may pass a map with null down to this function, so the earlier approach is better. I reverted it back. Thanks

2020-12-01 20:07 UTC, sriyerg commented on hw/dv/sv/cip_lib/cip_base_vseq__tl_errors.svh
>    csr_addr_mask[1:0] = 0;
Assume DUT has only 1 CSR at address 0. `max_offset` will always be word aligned (unless I am reading something wrong). So, `max_offset` = 0 (not 3) and `csr_addr_mask` = 3. In this case, `has_unmapped_addr = 1`, but it should actually be 0, right?

2020-12-01 20:23 UTC, weicaiyang commented on hw/dv/sv/cip_lib/cip_base_vseq__tl_errors.svh
>    csr_addr_mask[1:0] = 0;
@sriyerg please see the comment for get_max_offset. 
> Return the offset of the highest byte contained in either a register or a memory

get_max_offset doesn't return the start offset of the csr or mem, instead, it returns the offset of the highest byte. so max_offset is 3 in the example.

2020-12-01 22:06 UTC, sriyerg commented on hw/dv/sv/cip_lib/cip_base_vseq__tl_errors.svh
>    csr_addr_mask[1:0] = 0;
i see, ok.

2020-12-01 22:07 UTC, sriyerg approved these changes

2020-12-02 08:13 UTC, rswarbrick commented on hw/dv/sv/cip_lib/cip_base_vseq__tl_errors.svh
>    csr_addr_mask[1:0] = 0;
Sorry, you're right. I was thinking about cases like `csr_addr_mask = 3` and `get_max_offset = 2`, where `has_unmapped_addr` would be true, but there wouldn't actually be any unmapped addresses once you rounded down. Of course, since `get_addr_mask` and `get_max_offset` are essentially the same computation (the address mask is just the max offset, rounded up to one less than the next power of 2), this can't happen.

I still think the code might be more obvious if you switched the two lines around. Otherwise, maybe it makes sense to leave a comment? The sequence `x = a > b; a  = something_less_than_a;` will probably trigger a "huh" from other readers in the future.

2020-12-02 08:16 UTC, rswarbrick approved these changes
As mentioned above, I think it would be good to switch around the lines or add a comment in the TL errors sequence. Otherwise, looks good to me.

2020-12-02 18:29 UTC, weicaiyang commented on hw/dv/sv/cip_lib/cip_base_vseq__tl_errors.svh
>    csr_addr_mask[1:0] = 0;
Thanks for the suggestion. I updated the comment to explain that, so that I don't need to manipulate the return value of `get_max_offset`.

2020-12-02 21:40 UTC, merged