[dv] Make width conversion explicit in dv_base_env_cfg::initialize
lowRISC/opentitan pull request #4400
Opened 2020-12-03 16:37 UTC by rswarbrick

This is needed if `BUS_AW` doesn't equal `UVM_REG_ADDR_WIDTH`. The
implicit (unsigned) conversion will do the right thing if
`csr_base_addr` is a fixed value, but will zero-extend `'1` to something
like `0x00000000ffffffff` if `BUS_AW = 32` and `UVM_REG_ADDR_WIDTH == 64`,
which breaks the magic address handling in `set_base_addr`.

2020-12-03 16:37 UTC, rswarbrick commented
This was prompted by discussion at #4377.

2020-12-04 02:55 UTC, sriyerg commented on hw/dv/sv/dv_lib/dv_base_env_cfg.sv
> +      // correctly handle the case where a bus address is narrower than a uvm_reg_addr_t).
But, `BUS_AW` already equals `UVM_REG_ADDR_WIDTH`. 

We override `UVM_REG_ADDR_WIDTH` to be 32 bits here:
https://github.com/lowRISC/opentitan/blob/5df71536d980235d00cd7bb0cd7aa218c51d11dc/hw/dv/tools/dvsim/common_sim_cfg.hjson#L634

See wave snippet here:
![image](https://user-images.githubusercontent.com/46467186/101115764-b9984f80-3598-11eb-9ed7-29c85f94550d.png)

We should instead add a fatal error check (somewhere) to ensure `$bits(uvm_reg_addr_t) == BUS_AW`, and likewise for all other params; otherwise we will end up with more such issues.

2020-12-04 02:56 UTC, sriyerg requested changes
I am not sure this patch is needed. The original problem which only affects Questa needs to be investigated further.

2020-12-04 18:31 UTC, weicaiyang commented
Let's see what the root cause of the failure is in Questa. This may be not needed.

2020-12-07 08:18 UTC, rswarbrick commented
@sriyerg: I thought that the DV classes were supposed to be re-usable outside of OpenTitan? Are we assuming that we'll always use them in a setting where `UVM_REG_ADDR_WIDTH` has been overridden to equal `BUS_AW`? If so, I agree that the assertion is a better way to go, but it seems a pity not to just "do it right".

2020-12-07 08:33 UTC, rswarbrick commented
Incidentally, I've just read the [end](https://github.com/lowRISC/opentitan/issues/4377#issuecomment-738970045) of the discussion on issue #4377. Most UVM tutorials I've read strongly advise against customising `UVM_REG_ADDR_WIDTH` to avoid exactly the problem that Srikrishna ran into. Maybe we should take their advice?

2020-12-07 18:38 UTC, sriyerg commented
Re-thinking, it doesn't hurt to do this check.

2020-12-07 18:38 UTC, sriyerg approved these changes
Doesn't hurt to have this

2020-12-08 08:42 UTC, merged