[dv] Update common intr_test seq
lowRISC/opentitan pull request #5270
Opened 2021-02-17 22:43 UTC by weicaiyang

1. predict intr_state in dv_base_reg_field when intr_test is written,
which is more in line with the behavior of enable/lock registers
2. simplify the intr_test seq to just randomly write all interrupt
related CSRs and then read back for check
3. solve the issue that IP has interrupt without intr_enable #5261

Signed-off-by: Weicai Yang <weicai@google.com>

2021-02-19 21:32 UTC, cindychip reviewed
I believe in the meeting discussed the performance concern of using `uvm_re_match`. If not too much performance issue this PR LGTM :)

2021-02-19 22:34 UTC, weicaiyang commented
> I believe in the meeting discussed the performance concern of using `uvm_re_match`. If not too much performance issue this PR LGTM :)

I ran a CSR bit_bash test to compare with/without this PR. The sim time different is really small, from 1% slower to 3% faster. I guess we can ignore the performance impact.

2021-02-20 00:19 UTC, tjaychen commented
do you guys want to merge this? i'm guessing this will solve the interrupt mismatch issue right?

2021-02-20 00:36 UTC, weicaiyang commented
> do you guys want to merge this? i'm guessing this will solve the interrupt mismatch issue right?

This should fix the aon_timer_intr_test, but probably don't fix other interrupt mismatch.

@sriyerg @cindychip LMK if you any other comment

2021-02-20 00:38 UTC, udinator approved these changes
LGTM

2021-02-20 00:38 UTC, cindychip approved these changes
LGTM

2021-02-20 01:25 UTC, sriyerg requested changes

2021-02-20 01:25 UTC, sriyerg commented on hw/dv/sv/dv_base_reg/dv_base_reg_field.sv
> +    return !(uvm_re_match("intr_test*", csr_name));
Not a fan of this approach. If this method is called 1000s of times in simulation, this could have a pretty big runtime impact. Could you set a `local bit is_intr_test_fld;` from the reggen instead?

2021-02-20 01:25 UTC, sriyerg commented on hw/dv/sv/dv_base_reg/dv_base_reg_field.sv
> +  local function uvm_reg_field get_related_intr_state_field_for_intr_test();
This name is too long! How about `get_intr_state_field()`? It could apply to both, `intr_test` and `intr_enable` CSRs. It should be apparent that _this_ field instance is itself not `intr_state`.

2021-02-20 01:25 UTC, sriyerg commented on hw/dv/sv/dv_base_reg/dv_base_reg.sv
> +    intr_enable_name = {"intr_enable", get_name_suffix(intr_state_name, no_suffix_intr_state_name)};
Perhaps you can do this using existing APIs:
```systemverilog
  string name, prefix, suffix, intr_enable_csr_name;
  name = get_name();
  prefix = "intr_state";
  suffix = name.substr(
      str_utils_pkg::str_find(name, prefix) + prefix.len(), name.len() - 1);
  intr_enable_csr_name = {"intr_enable", suffix};
```

A very good general solution would be to add `str_utils_pkg::str_replace()` method. With that, you should just be able to do this:
```systemverilog
  string intr_enable_csr_name;
  intr_enable_csr_name = str_utils_pkg::str_replace(get_name(), "state", "enable");
```

2021-02-20 01:25 UTC, sriyerg commented on hw/dv/sv/dv_base_reg/dv_base_reg.sv
> +    end
This is perhaps better written as:
```systemverilog
  uvm_reg_data_t result;
  result = get_mirrored_value();
  if (intr_enable_csr != null) begin
    result &= intr_enable_csr.get_mirrored_value();
  end
  return result;
```

2021-02-20 01:25 UTC, sriyerg commented on hw/dv/sv/dv_base_reg/dv_base_reg_field.sv
> +    dv_base_reg_block dv_blk;
Ditto comment as before.

2021-02-20 06:33 UTC, weicaiyang commented on hw/dv/sv/dv_base_reg/dv_base_reg.sv
> +    `downcast(get_dv_base_reg_field_by_name, fld)
Done

2021-02-20 06:33 UTC, weicaiyang commented on hw/dv/sv/cip_lib/cip_base_vseq.sv
> +    foreach (cfg.ral_models[i]) cfg.ral_models[i].get_dv_base_regs(all_csrs);
It was used in multiple places. but now I make all_csrs as a class variable

2021-02-20 06:33 UTC, weicaiyang commented on hw/dv/sv/cip_lib/cip_base_vseq.sv
> +        if (!cfg.under_reset) begin
Updated, thanks

2021-02-20 06:33 UTC, weicaiyang commented on hw/dv/sv/cip_lib/cip_base_vseq.sv
> +        intr_state_csrs.push_back(get_interrupt_csr(csr_name));
make `all_csrs` and `intr_state_csrs` as they're used in more than one place. `all_intr_csrs` is just used here, keep it local.

2021-02-20 06:33 UTC, weicaiyang commented on hw/dv/sv/dv_base_reg/dv_base_reg.sv
> +  virtual function uvm_reg_data_t get_intr_pin_mirrored_value();
changed to `get_intr_pins_exp_value` as `values` may be confusing here. like get_fields will return array. Thanks

2021-03-03 19:03 UTC, sriyerg approved these changes
LGTM, thanks!

2021-03-03 19:03 UTC, sriyerg commented on hw/dv/sv/cip_lib/cip_base_vseq.sv
> +          !uvm_re_match("intr_state*", csr_name)) begin
Okay.

2021-03-03 19:03 UTC, sriyerg commented on hw/dv/sv/str_utils/str_utils_pkg.sv
> +  // find the first match string of 'sub' and replace it with new 'sub'
nit: 
```suggestion
  // Find the first match string 'sub' in 's' and replace it with 'new_sub'.
  // TODO: Add support for global replacement. 
```

2021-03-03 19:03 UTC, sriyerg commented on hw/dv/sv/dv_base_reg/dv_base_reg_field.sv
> +    // the field localtion for intr_state and intr_test should be the same
```suggestion
    // the field location for intr_state and intr_test should be the same
```

2021-03-04 06:20 UTC, weicaiyang commented on hw/dv/sv/str_utils/str_utils_pkg.sv
> +  // find the first match string of 'sub' and replace it with new 'sub'
Updated, thanks

2021-03-04 06:20 UTC, weicaiyang commented on hw/dv/sv/dv_base_reg/dv_base_reg_field.sv
> +    // the field localtion for intr_state and intr_test should be the same
Good catch, updated.

2021-03-05 00:22 UTC, weicaiyang commented
last force push is just to solve the conflict

2021-03-08 17:50 UTC, merged