[prim_packer] Silence verilator width warnings
lowRISC/opentitan pull request #5329
Opened 2021-02-22 08:40 UTC by rswarbrick

There are two changes here. The first is to explicitly zero-extend
`wdata_i` from `InW` up to `OutW` when computing `wdata_shifted` in pack mode.
The second is to slice out just the bits we need from `MaxW / MinW` when
comparing `depth_q` against it (otherwise Verilator complains that we're
comparing a small bitvector against a 32-bit int).

2021-02-22 15:47 UTC, mwbranstad commented on hw/ip/prim/rtl/prim_packer_fifo.sv
> +  localparam bit [DepthW:0] FullDepth = WidthRatio[DepthW:0];
localparam bit [DepthW:0] FullDepth = WidthRatio[DepthW:0];
Part select of signed signal 'WidthRatio[DepthW:0]' encountered

Need to fix ascentlint error above.

2021-02-22 15:48 UTC, mwbranstad requested changes
Might fix Verilator lint, but I see a new ascentlint message pop up.

2021-02-22 15:51 UTC, rswarbrick commented on hw/ip/prim/rtl/prim_packer_fifo.sv
> +  localparam bit [DepthW:0] FullDepth = WidthRatio[DepthW:0];
Ah, good point. I don't have an AscentLint licence. Does declaring `WidthRatio` as `int unsigned` sort things out?

2021-02-22 16:18 UTC, mwbranstad commented on hw/ip/prim/rtl/prim_packer_fifo.sv
> +  localparam bit [DepthW:0] FullDepth = WidthRatio[DepthW:0];
Yes, that appears to fix the ascentlint issue. Thanks for cleaning this up.

2021-02-22 16:21 UTC, mwbranstad approved these changes
After adding "unsigned" to WidthRatio, ascentlint is clean.

2021-02-22 17:18 UTC, rswarbrick commented on hw/ip/prim/rtl/prim_packer_fifo.sv
> +  localparam bit [DepthW:0] FullDepth = WidthRatio[DepthW:0];
Great, thanks. (And it even fits in the whitespace :-))

2021-02-23 10:57 UTC, imphil approved these changes

2021-02-23 10:59 UTC, merged