[spi_device, dv] Refactor spi_agent to support spi_host rtl
lowRISC/opentitan pull request #5408
Opened 2021-02-28 18:38 UTC by tunghoang290780

Refactor spi_agent to support spi_host rtl

  - Extend spi_if to provide up to 4 channels required by spi_host rtl

Signed-off-by: Tung Hoang <hoang.tung@wdc.com>

2021-02-28 18:42 UTC, tunghoang290780 commented
@weicaiyang My plan is to extend `spi_agent `to support device mode which is used to verify `spi_host `rtl. I want to keep backward compatible to support `spi_device` rtl. Therefore, in any PR relating to the `spi_agent`, I always run both the regression test for `spi_device` and `spi_host` rtl.

2021-03-01 02:37 UTC, sriyerg requested changes

2021-03-01 02:37 UTC, sriyerg commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +  // enable monitor to collect trans on-the-fly in host mode
nit: the extra spaces after `bit` are looking a little ugly. Perhaps we can remove them?

2021-03-01 02:37 UTC, sriyerg commented on hw/dv/sv/spi_agent/spi_agent_pkg.sv
> +  parameter uint NUM_SPI_CHANNELS = 4;
It is preferable to make this mutable (like you did with `spi_if` below). That will allow different SPI agents with different parameter values to be instantiated in the same testbench.

2021-03-01 02:37 UTC, sriyerg commented on hw/dv/sv/spi_agent/spi_host_driver.sv
> +      cfg.vif.csb[0] <= 1'b1;
Should this reset all channels?

2021-03-01 02:37 UTC, sriyerg commented on hw/dv/sv/spi_agent/spi_host_driver.sv
> +    cfg.vif.csb[0] <= 1'b0;
I think you can proactively add `int channel` to `spi_item`, constraint it to be always 0 (for now) and use that here instead (unless @weicaiyang has other ideas).

2021-03-01 02:37 UTC, sriyerg commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +    host_analysis_port   = new("host_analysis_port", this);
Not sure I understand why is this needed. I think you could do with just one `analysis_port` that captures the SPI transactions. SPI is unlike UART, where TX and RX and completely disjoint lanes. 

`collect_curr_trans()` (original task below) already captures both, SDI and SDO.

2021-03-01 02:37 UTC, sriyerg commented on hw/dv/sv/spi_agent/spi_agent_pkg.sv
> +  parameter uint NUM_SPI_CHANNELS = 4;
A better approach is to make it runtime instead (add `int num_channels` to `spi_agent_cfg`). Remove `spi_if` parameterization too - assume its a quad SPI, but connect only the number of channels needed.

2021-03-01 02:40 UTC, sriyerg commented
> @weicaiyang I am going to extend `spi_agent` to support device mode which is used to verify `spi_host `rtl. The important point is to keep backward compatible to support `spi_device` rtl. Therefore, I always run both the regression test for `spi_device` and `spi_host` rtl before submitting any `spi_agent` PR.

Agree - SPI agent should contain both, host and device side functionality. Further, it must strive to remain as generic as possible, without making OpenTitan specific assumptions - i.e. it must work for any design that has a SPI interface. Also, refrain from parameterizing it. It causes parameter creep problem.

2021-03-01 07:03 UTC, tunghoang290780 commented on hw/dv/sv/spi_agent/spi_host_driver.sv
> +      cfg.vif.csb[0] <= 1'b1;
@sriyerg currently I think spi_driver just support standard SPI mode (single channel 0) and that code is not developed by me

2021-03-01 07:09 UTC, tunghoang290780 commented on hw/dv/sv/spi_agent/spi_agent_pkg.sv
> +  parameter uint NUM_SPI_CHANNELS = 4;
@sriyerg if I understand correctly, you want spi_if to represent a single channel, then in the testbench, we could instantiate as much as a number of required channel

2021-03-01 07:17 UTC, tunghoang290780 commented on hw/dv/sv/spi_agent/spi_host_driver.sv
> +    cfg.vif.csb[0] <= 1'b0;
@sriyerg not sure if @weicaiyang has a plan to support Dual-SPI and Quad-SPI mode for spi_device but if it is not then hardcore to channel 0 is better (otherwise it also requires channel in spi_device testbench). I want to avoid touching on spi_device as much as possible

2021-03-01 07:19 UTC, tunghoang290780 commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +    host_analysis_port   = new("host_analysis_port", this);
@sriyerg that is not my code so I do not know the motivation. However, IMO, using two separate ports for RX and TX would be fine for me.

2021-03-01 07:20 UTC, tunghoang290780 commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +  // enable monitor to collect trans on-the-fly in host mode
@sriyerg removed the spaces

2021-03-01 07:25 UTC, tunghoang290780 commented
@sriyerg I updated PR to address your comments

2021-03-01 17:13 UTC, tunghoang290780 commented on hw/dv/sv/spi_agent/spi_agent_pkg.sv
> +  parameter uint NUM_SPI_CHANNELS = 4;
@sriyerg remove spi_if parameter and NUM_SPI_CHANNELS in agent package

2021-03-01 19:45 UTC, weicaiyang commented on hw/dv/sv/spi_agent/spi_host_driver.sv
> +      cfg.vif.sdi <= 4'bxxxx;
nit: these can be signal/dual/qual
```suggestion
      cfg.vif.csb <= '1;
      cfg.vif.sdi <= 'x;
```

2021-03-01 19:45 UTC, weicaiyang commented on hw/dv/sv/spi_agent/spi_host_driver.sv
> +    cfg.vif.csb[0] <= 1'b0;
A big design update is adding soon to spi_device. I need to update device driver to support dual and qual mode.
I guess we can just hardcode it to 0 for now and I will fix it soon, so that Tung can move forward to develop the host.

2021-03-01 19:45 UTC, weicaiyang commented on hw/dv/sv/spi_agent/spi_if.sv
> +  logic [3:0] sdi;
we can parameterize these. Or leave a TODO, I can clean them up later.

2021-03-01 19:45 UTC, weicaiyang commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +    host_analysis_port   = new("host_analysis_port", this);
I guess Tung wants to use this monitor-sequencer port for reactive agent. But I feel this approach doesn't work for spi.
When the clock toggle, SPI drives data. We can't collect info in monitor and send that to driver.
TLUL has address and data phases. We can collect address in monitor for driver to send data. But SPI isn't like this.

2021-03-01 19:57 UTC, tunghoang290780 commented on hw/dv/sv/spi_agent/spi_if.sv
> +  logic [3:0] sdi;
@weicaiyang I think we can hardcode it to the maximum channels and in the testbench just connecting as much as we need

2021-03-01 20:01 UTC, tunghoang290780 commented
@weicaiyang I think spi agent does not need an analysis port between monitor and driver since it has only the data phase so I will remove the mon_analysis_port

2021-03-01 20:45 UTC, tunghoang290780 commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +    host_analysis_port   = new("host_analysis_port", this);
@weicaiyang I did not add host_analysis_port  and device_analysis_port. I think both ports are being used by spi_device dut. I added another mon_analysis_port for the reactive slave but I think that is not necessary because SPI has only the data phase (so I removed that port from PR)

2021-03-01 22:14 UTC, weicaiyang commented on hw/dv/sv/spi_agent/spi_if.sv
> +  logic [3:0] sdi;
I feel we should define
`logic [3:0] SIO;` 
if it's single mode, SIO[1:0] are for SDO, SDI, which are one direction. If dual or quad mode, SIO are bi-direction.
https://en.wikipedia.org/wiki/Serial_Peripheral_Interface#Quad_SPI

2021-03-01 22:14 UTC, weicaiyang commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +    host_analysis_port   = new("host_analysis_port", this);
we can probably remove `collect_trans_device_mode` and `collect_trans_host_mode` too, and just use the `collect_curr_trans`

2021-03-02 03:18 UTC, tunghoang290780 commented on hw/dv/sv/spi_agent/spi_if.sv
> +  logic [3:0] sdi;
@weicaiyang removed sdi and sdo and add sio instead. update sdi_device test and spi_agent to use sio[1:0] for single mode

2021-03-02 03:28 UTC, tunghoang290780 commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +    host_analysis_port   = new("host_analysis_port", this);
@weicaiyang if we want to use `collect_current_trans` to collect items for both host and device mode, "collect_current_trans" must check flags en_monitor_host_mode/en_monitor_device_mode then decide corresponding analysis port to send item to scoreboard. I mean spi_monitor can use one analysis port per mode. And each analysis port can carry both Rx and tx items. Correct me if I am wrong!

2021-03-02 05:02 UTC, sriyerg commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +    host_analysis_port   = new("host_analysis_port", this);
Sorry for the confusion - `host_analysis_port` and `device_analysis_port` are good to have. But I am not sure splitting `collect_curr_trans` into two tasks for host mode and device mode is needed. Wouldn't both tasks be exactly identical?

2021-03-02 06:39 UTC, tunghoang290780 commented on hw/dv/sv/spi_agent/spi_sequencer.sv
> +    mon_item_fifo = new("mon_item_fifo", this);
@sriyerg I thought mon_item_fifo is removed. we might not need to implement reactive slave for spi_agent in device mode because SPI does not have an address phase

2021-03-02 06:40 UTC, tunghoang290780 commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +    host_analysis_port   = new("host_analysis_port", this);
@sriyerg IMO, they are pretty similar (data phase only)

2021-03-02 06:50 UTC, tunghoang290780 commented
@weicaiyang I updated top_earlgrey testbench with new ports sio

2021-03-02 18:21 UTC, weicaiyang commented
> @weicaiyang, I think we should move this to dv_base_agent. WDYT? This would be needed to make device agents reactive.

agree, this is needed for reactive device. will make a PR to add that.

2021-03-02 18:22 UTC, weicaiyang commented on hw/dv/sv/spi_agent/spi_monitor.sv
> +    host_analysis_port   = new("host_analysis_port", this);
I feel we don't need to have both `host_analysis_port` and `device_analysis_port`. now both receive the same item at the same time. I will clean this up later.

2021-03-02 18:27 UTC, weicaiyang approved these changes
LGTM, thanks for updating the device side

2021-03-02 20:04 UTC, tunghoang290780 commented
@sriyerg any comments?

2021-03-02 22:38 UTC, tunghoang290780 commented
@weicaiyang minor change, add spi_mode/spi_mode_e flags in to spi_agent_cfg/spi_agent_pkg

2021-03-02 23:00 UTC, weicaiyang commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +  uint num_channels = 4; // support single-SPI, dual-SPI and quad-SPI
this may be not needed as we know what to drive from `spi_mode_e`

2021-03-03 08:38 UTC, tunghoang290780 commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +  uint num_channels = 4; // support single-SPI, dual-SPI and quad-SPI
@weicaiyang I removed the redundant variable

2021-03-03 18:27 UTC, sriyerg approved these changes
LGTM, thanks!

2021-03-03 18:38 UTC, weicaiyang commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> -  bit             en_monitor_collect_trans = 1'b1; // enable monitor to collect trans on-the-fly
Thanks for checking this. haven't thought of any case we need to disable the monitor. perhaps it's not needed

2021-03-04 02:56 UTC, tunghoang290780 commented on hw/dv/sv/spi_agent/spi_device_driver.sv
> +      cfg.vif.sio <= 'h0;
@sriyerg changed to 'hz

2021-03-04 18:05 UTC, merged