Aes func cover
lowRISC/opentitan pull request #5454
Opened 2021-03-04 13:27 UTC by rasmus-madsen

This has the initial steps for functional and code coverage for aes.
no attempt has been done to close coverage at this point and should only serve as the skeleton for AES - and as an example for the other xcelium driven IP

2021-03-04 20:20 UTC, weicaiyang commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +    cp_prng_reseed:          coverpoint aes_trigger[6];
are these indexes wrong? not sure why they're 4 and 6

2021-03-04 20:20 UTC, weicaiyang commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +  endfunction
not sure if it's better to call sample function directly in scb without creating these functions, since we define `sample` at the covergroup.
for aes_status_cg_inst, the input is  `status_t`, which may be a bit confusing when we use bit[31:0] in the sample function.

2021-03-04 20:20 UTC, weicaiyang commented on hw/ip/aes/dv/env/aes_scoreboard.sv
> +      //  end
please clean up these lines

2021-03-04 20:20 UTC, weicaiyang commented on hw/ip/aes/dv/env/aes_scoreboard.sv
> +          cov_if.cg_alert_test_sample(item.a_data);
consider to import cip_base_pkg to reuse interrupt coverages from it
https://github.com/lowRISC/opentitan/blob/master/hw/dv/sv/cip_lib/cip_base_env_cov.sv

2021-03-04 20:42 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov.vRefine
> +    <rule ccType="inst" domain="icc" entityName="aes/&quot;tl_o.d_user.rsvd1&quot;" entityType="toggle" excTime="1614852672" name="exclude" reviewer="unknown" user="0" vscope="default"></rule>
yes this i an unfortunate side effect of the common tcl file.
you only have the choice to save all or differences.
so if you are working in incremental steps the "all" option is really the only viable. 
so we would need to manually scrub these out.

but I don't think it matters?

2021-03-04 20:44 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins AES_ILLIGAL = { !(AES_ECB || AES_CBC || AES_CFB || AES_OFB || AES_CTR) };
Hi @weicaiyang this change is not viable as the illegal bin is going to make the test fail - and I am actually forcing things into the "illegal bins" to check we can recover and that we don't compromise security

2021-03-04 20:44 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins AES_ILLIGAL = {!(AES_128 || AES_192 || AES_256)};
same as above

2021-03-04 20:44 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +    cp_prng_reseed:          coverpoint aes_trigger[6];
ohh yes thanks that is a good catch

2021-03-04 20:45 UTC, imphil commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins AES_ILLIGAL = {!(AES_128 || AES_192 || AES_256)};
AES_ILLIGAL -> AES_ILLEGAL ?

2021-03-04 20:46 UTC, rasmus-madsen commented on hw/ip/aes/dv/env/aes_scoreboard.sv
> +      //  end
I added it to Make it clear that it is not used.

2021-03-04 20:48 UTC, rasmus-madsen commented on hw/ip/aes/dv/env/aes_scoreboard.sv
> +          cov_if.cg_alert_test_sample(item.a_data);
are the alerts covered in the interrupts?
thanks I will do that -but I think I need to also cover them on my own again

2021-03-04 21:57 UTC, weicaiyang commented on hw/ip/aes/dv/cov/aes_cov.vRefine
> +    <rule ccType="inst" domain="icc" entityName="aes/&quot;tl_o.d_user.rsvd1&quot;" entityType="toggle" excTime="1614852672" name="exclude" reviewer="unknown" user="0" vscope="default"></rule>
I see. perhaps we can clean them up later.

2021-03-04 21:57 UTC, weicaiyang commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins AES_ILLIGAL = { !(AES_ECB || AES_CBC || AES_CFB || AES_OFB || AES_CTR) };
does this work? this expression `!(AES_ECB || AES_CBC || AES_CFB || AES_OFB || AES_CTR)` is equal to 0. It looks like `!(0 || 1 || 2 || 3)`. Maybe I don't know this syntax for coverage.

2021-03-04 21:57 UTC, weicaiyang commented on hw/ip/aes/dv/env/aes_scoreboard.sv
> +          cov_if.cg_alert_test_sample(item.a_data);
ohh, looks like we don't create one for alert. it's good to have as it can be reused by others.

2021-03-08 08:41 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov.vRefine
> +    <rule ccType="inst" domain="icc" entityName="aes/&quot;tl_o.d_user.rsvd1&quot;" entityType="toggle" excTime="1614852672" name="exclude" reviewer="unknown" user="0" vscope="default"></rule>
@tunghoang290780 when you click save refines in the gui they are created.

2021-03-08 08:51 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins AES_ILLIGAL = { !(AES_ECB || AES_CBC || AES_CFB || AES_OFB || AES_CTR) };
@weicaiyang I don't follow ?
Maybe the fact that the bin name is the same as the struct name is the confusing part?

is this more clear?
```
    bins ofb     = { AES_OFB };
    bins ctr     = { AES_CTR };
    bins  none   = { AES_NONE };
    bins none_of_the_above = { !(AES_ECB || AES_CBC || AES_CFB || AES_OFB || AES_CTR) };
```
   the ILLIGAL statement is simply if aes_ctrl[6:1]  is not in the struct then count the illegal bin

2021-03-08 08:51 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins AES_ILLIGAL = {!(AES_128 || AES_192 || AES_256)};
oh yes thans phil

2021-03-08 08:55 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +  endfunction
there is also the small upside to this that you can sample several cover groups with only one line in the RTL.

2021-03-08 08:56 UTC, rasmus-madsen commented on hw/ip/aes/dv/env/aes_scoreboard.sv
> +          cov_if.cg_alert_test_sample(item.a_data);
let's touch base on this today or tomorrow. 
I am not sure I see how it can be re-used.

2021-03-08 08:57 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +   input logic my_aes_ctrl
@tunghoang290780 
I will add something to it at a later stage.
the reason I added it this early is as an example.

2021-03-08 18:59 UTC, weicaiyang commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +  endfunction
it makes sense if you sample several cover groups in a function. but we just have one covergroup in the function, which seems not necessary.

2021-03-08 18:59 UTC, weicaiyang commented on hw/ip/aes/dv/env/aes_scoreboard.sv
> +          cov_if.cg_alert_test_sample(item.a_data);
right, we can't reuse it when we put it in the interface. I feel we should add it as common coverage in [cip_base_env_cov](https://github.com/lowRISC/opentitan/blob/master/hw/dv/sv/cip_lib/cip_base_env_cov.sv)

All these covergroups are added in interface and sample in scb. But things in interface are hard to be reused across IPs. Since we sample in scb, it's also hard to reuse it in top-level.

Sorry, I know we had a similar discussion before, but I feel it may be not a best approach.

I kind of feel we could have these categories of coverages.
1. if a covergroup covers and samples design signals, put in the interface, so that it can be reused in top-level when we bind it. designer can help to implement this kind of coverage. Using assert cover is also fine too.
2. if a coverage covers and samples DV env variables, put in IP_env_cov. if it can be reused across IPs, put in cip/dv_base_env_cov. these covergroups are implemented by DV engineers.
3. if it's agent related coverage, put in agent_cov.

I can set up a meeting to further discuss this.

Add @sriyerg for visibility

2021-03-08 19:39 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +  endfunction
@weicaiyang somehow my first comment didn't get published.

this method is the only way of doing coverage in interfaces with xcelium. we did talk about this a while back.
in PR https://github.com/lowRISC/opentitan/pull/3681

2021-03-08 19:40 UTC, rasmus-madsen commented on hw/ip/aes/dv/env/aes_scoreboard.sv
> +          cov_if.cg_alert_test_sample(item.a_data);
sure wednesday and friday are pretty blocked for me. but thuesday and Thursday ( or next Monday) can work

2021-03-08 22:56 UTC, weicaiyang commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins AES_ILLIGAL = { !(AES_ECB || AES_CBC || AES_CFB || AES_OFB || AES_CTR) };
from
```
typedef enum logic [5:0] {
  AES_ECB  = 6'b00_0001,
  AES_CBC  = 6'b00_0010,
  AES_CFB  = 6'b00_0100,
  AES_OFB  = 6'b00_1000,
  AES_CTR  = 6'b01_0000,
  AES_NONE = 6'b10_0000
} aes_mode_e;
```

can we translate this 
`bins none_of_the_above = { !(AES_ECB || AES_CBC || AES_CFB || AES_OFB || AES_CTR) };
`
to 
`bins none_of_the_above = { !(1 || 2 || 4 || 8 || 16) };
`

 then `(1 || 2 || 4 || 8 || 16)` == 1, so that it becomes
`bins none_of_the_above = { 0 };
`

Sorry, please correct me if I'm wrong.

2021-03-08 22:57 UTC, weicaiyang commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +  endfunction
Thanks for the pointer. didn't know xcelium has this limitation.

2021-03-09 04:23 UTC, tunghoang290780 commented on hw/ip/aes/dv/cov/aes_cov.vRefine
> +    <rule ccType="inst" domain="icc" entityName="aes/&quot;tl_o.d_user.rsvd1&quot;" entityType="toggle" excTime="1614852672" name="exclude" reviewer="unknown" user="0" vscope="default"></rule>
@rasmus-madsen so I suppose the *.vRefine is not a part of PR? (it is a .xml output file generated by IMC gui)

2021-03-09 07:38 UTC, sriyerg requested changes

2021-03-09 07:38 UTC, sriyerg commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +    cp_operation: coverpoint aes_ctrl[0]
Not sure if this is robust (hard coded indices based on CSR field positions). I will probably recommend directly sampling individual fields instead. 
As mentioned before, you can directly sample `aes_core.aes_op_q` here rather than pass it as an arg since the interface is bound to the design. The entire AES hierarchy should be accessible here. 

Likewise for all covergroups and coverpoints below.

2021-03-09 07:38 UTC, sriyerg commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +    x_mode_key_len: cross cp_mode, cp_key_len;
Prefix crosses with `cr_`.

2021-03-09 07:42 UTC, sriyerg commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins AES_ILLIGAL = { !(AES_ECB || AES_CBC || AES_CFB || AES_OFB || AES_CTR) };
This should be `AES_ILLEGAL = default;`.

2021-03-09 07:43 UTC, sriyerg commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins AES_ILLEGAL = { !(AES_ECB || AES_CBC || AES_CFB || AES_OFB || AES_CTR) };
[I mentioned this in the other comment] This should probably be `AES_ILLEGAL = default;` to catch all other values.

2021-03-09 10:12 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins AES_ILLIGAL = { !(AES_ECB || AES_CBC || AES_CFB || AES_OFB || AES_CTR) };
@sriyerg Default bins are not counted towards coverage! i.e I would have to manually eyeball the result to check we have anything in that bin.
so I prefer my solution - I am not sure I understand why you don't think this method is ok?

2021-03-09 10:16 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins AES_ILLIGAL = { !(AES_ECB || AES_CBC || AES_CFB || AES_OFB || AES_CTR) };
@weicaiyang I think you are missing a key thing in your expression.
the way to read it is
```
if (aes_ctrl[6:1] != (1 || 2|| 4 || 8 || 16) ) begin
  count bins none_of_the_above += 1
end
```
does this answer your question? if not lets just have a 5 min call when you get in.
I think I might be missing your point?

2021-03-09 10:17 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +   input logic my_aes_ctrl
can I resolve this question tung?

2021-03-09 10:19 UTC, rasmus-madsen commented on hw/ip/aes/dv/aes_sim_cfg.hjson
> +      tests: ["aes_stress","aes_b2b", "aes_clear", "aes_config_error", "aes_smoke"]
for now it is just for me, but adding a note so others can use it wouldn't hurt.
I will add it to my doc updates coming soon.

2021-03-09 10:35 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +    x_mode_key_len: cross cp_mode, cp_key_len;
oh - why didn't we go with x?
not sure it is a defacto standard - but it is quite commonly used in my experience?

2021-03-09 10:36 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins AES_ILLEGAL = { !(AES_ECB || AES_CBC || AES_CFB || AES_OFB || AES_CTR) };
@sriyerg Default is not counted towards the scoring - I prefer my method.
I would like to understand why the resistance against what I have done here.
I think it makes perfect sense?

2021-03-10 12:23 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins AES_ILLIGAL = { !(AES_ECB || AES_CBC || AES_CFB || AES_OFB || AES_CTR) };
@weicaiyang thank you for clearifying your concern yesterday - I have chosen a different solution.
the "binsof" solution only works on crosses.

if you are ok with my solution please resolve this comment :D

2021-03-10 12:25 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +    cp_operation: coverpoint aes_ctrl[0]
@sriyerg I think we covered this in the meeting yesterday? 
are you ok with leaving as is?

2021-03-10 12:25 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +    x_mode_key_len: cross cp_mode, cp_key_len;
fixed

2021-03-10 12:26 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins AES_ILLEGAL = { !(AES_ECB || AES_CBC || AES_CFB || AES_OFB || AES_CTR) };
to elborate - when using default the scoring is not counted.
I.e you can 100% coverage of a cover group without hitting the default bin.
I want to make sure I actually tests values outside of the legal ones - so I will leaves as is if ok?

2021-03-10 12:30 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov.vRefine
> +    <cache-entry key="0" value="[NOT SUPPORTED] This is excluded from the common exclusion file
@sriyerg 
there are really only two options for commenting.
this is how the comments are added if using the gui. I have formatted it to match what is suggested in the methodology.
but it is not next to the exclusion - you have to match the `"comment=0"` in the line of the exclusion to the `"key=0"`
in the comments section

an alternate solution would be to manually add comments by `<!---- this is an exclusion ---> `
WDYT?

2021-03-10 19:21 UTC, weicaiyang approved these changes
LGTM, `bins with {}` solution is great, thanks

2021-03-10 19:21 UTC, weicaiyang commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins illegal = { [0:$] } with ($countones(item) > 1);
this looks great! 👍

2021-03-10 19:21 UTC, weicaiyang commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> + `DV_FCOV_INSTANTIATE_CG(aes_ctrl_cg, en_full_cov)
@rasmus-madsen can you also address this comment? looks like it's a good idea to put the sample function in this macro.

2021-03-11 10:20 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov.vRefine
> +    <rule ccType="inst" domain="icc" entityName="aes/&quot;tl_o.d_user.rsvd1&quot;" entityType="toggle" excTime="1614852672" name="exclude" reviewer="unknown" user="0" vscope="default"></rule>
the Refine should be in the PR - just like in this one.
but you need to clean it up and remove anything path specific - like I did in this  PR.
and as @sriyerg says - annotate it.

2021-03-11 10:23 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov.vRefine
> +    <cache-entry key="0" value="[NOT SUPPORTED] This is excluded from the common exclusion file
@sriyerg ahh yes good point.

Any suggestion on how to handle this the best?
I think we might be forced to have different approaches depending on the tool

2021-03-11 10:27 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +       bins illegal = { [0:$] } with ($countones(item) > 1);
ahh yes - I have updated to != 1

2021-03-11 10:43 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +    option.name         = "aes_ctrl_cg";
@sriyerg I am not sure I follow your logic here. why should the cover group declared name and the cover group field "name" be different than the actual name. That just seems inconsistent to me?

can you give an example of what you think is a more descriptive name for the control register cover group?

I can add a "option.comment" if you would like?

FYI: the practice of replicating the name is used in other places in our code.

2021-03-11 12:59 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> + `DV_FCOV_INSTANTIATE_CG(aes_ctrl_cg, en_full_cov)
@weicaiyang I don't think the suggestion is to put the sample function in the macro, I don't see how that is possible unless you somehow make an expansion for the number of inputs.

@sriyerg I ignored this as you put NIT on it.
personally, I think grouping it is more clutter than clear.
the functions and the macros don't have any interest - they are just a "needed evil" and the interesting stuff is the cover groups and cover points. so keeping these separate at the top makes the document more readable IMO.

in any case I don't feel that this is worth a lengthy argument. so let me know if you still prefer them together and I will make it happen

2021-03-11 13:01 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +    cp_operation: coverpoint aes_ctrl[0]
fixed

2021-03-11 17:58 UTC, sriyerg commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +    option.name         = "aes_ctrl_cg";
Whoops, sorry my bad. I mistook this for `option.comment`.

2021-03-11 18:28 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> +   input logic my_aes_ctrl
this port is currently not used - I can remove it  for now - it was mostly there as an example

2021-03-11 18:32 UTC, sriyerg commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> + `DV_FCOV_INSTANTIATE_CG(aes_ctrl_cg, en_full_cov)
I would say its better if you could respond back to nit comments so that the original commenter has closure, rather than ignoring it outright, which makes it hard for them to know if you are going to address it or not. Nitpicky comments are just that - nitpicky - it does not always mean optional. Typically people oblige and address them. 

Re. this specific comment, I am fine keeping them separate. It does look cleaner that way.

2021-03-11 18:32 UTC, sriyerg commented on hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
> +    if (ral.ctrl_shadowed.operation.get_mirrored_value() != operation) begin
Not sure I understand the need for this if condition. The `csr_update` already does exactly the same check underneath. Ditto below.

2021-03-11 18:32 UTC, sriyerg commented on hw/ip/aes/rtl/aes_pkg.sv
> +
Would you please get rid of these extra blanks (including other files as well)? They are inconsistent (2/3/4 blank lines in various places in the same file) and IMO do not add any value in making the code look better.

2021-03-11 18:33 UTC, sriyerg commented
This looks great and is almost ready to go in. Just need a few more questions addressed. Thanks!

2021-03-11 18:37 UTC, rasmus-madsen commented on hw/ip/aes/dv/cov/aes_cov_if.sv
> + `DV_FCOV_INSTANTIATE_CG(aes_ctrl_cg, en_full_cov)
@sriyerg sorry I miscommunicated here. what I meant was I was just ignoring this until the more serious concerns.
I would never ignore comment!.

sorry for the bad choice of words.

2021-03-11 19:26 UTC, weicaiyang commented on hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
> +    if (ral.ctrl_shadowed.operation.get_mirrored_value() != operation) begin
this CSR is volatile as HW may update it too. `csr_update` will always do write.
```
      operation.configure(
        .parent(this),
        .size(1),
        .lsb_pos(0),
        .access("RW"),
        .volatile(1),
        .reset(32'h0),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));
```


https://github.com/lowRISC/opentitan/blob/da3a0707b397a94406d59973920478ab3a5d52b8/hw/ip/aes/data/aes.hjson#L326-L335

2021-03-11 20:06 UTC, rasmus-madsen commented on hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
> +    if (ral.ctrl_shadowed.operation.get_mirrored_value() != operation) begin
@sriyerg looks like @weicaiyang  confirms the behavior I was experiencing.
so I assume you are ok with leaving this as is?

2021-03-11 20:11 UTC, rasmus-madsen commented on hw/ip/aes/rtl/aes_pkg.sv
> +
fixed

2021-03-11 20:12 UTC, rasmus-madsen commented
@sriyerg so I think we finally got all the way through..
thanks @weicaiyang @sriyerg @tunghoang290780  for your feedback.
let me know if you have any more comment. If not please approve

2021-03-11 20:19 UTC, sriyerg commented on hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
> +    if (ral.ctrl_shadowed.operation.get_mirrored_value() != operation) begin
Thanks for the clarification, @weicaiyang.

2021-03-11 20:20 UTC, sriyerg approved these changes
This looks great, thanks!

2021-03-12 12:13 UTC, merged