[pattgen, dv] Update pattgen dv
lowRISC/opentitan pull request #5488
Opened 2021-03-07 06:21 UTC by tunghoang290780

Update pattgen dv

  - Add functional coverage dv/cov
  - Update scoreboard for coverage

Signed-off-by: Hoang Tung <Hoang.Tung@wdc.com>

2021-03-07 06:24 UTC, tunghoang290780 commented
@martin-lueker I remove `u_` prefix in the instance name of pattgen_core (in pattgen.sv) that helps the coverage file more readable.

2021-03-09 21:39 UTC, rasmus-madsen reviewed
@tunghoang290780 is there a functional coverage doc we can compare to?
would it make sense to also check that you see different lengths, different data patterns etc?

Fyi dvsim should work correctly --cov to collect the coverage and --cov-analyze to open the results in the IMC gui

UNR coverage is on the way

2021-03-09 21:39 UTC, rasmus-madsen commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +    cp_ch0_enable: coverpoint {pattgen_core.ch0_ctrl.enable} {
if you want you can auto bin this as you are single binning the only two outcomes

2021-03-09 21:39 UTC, rasmus-madsen commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +  covergroup pattgen_op_cg @(posedge clk_i);
as we talked about sampling on every clock is probably not what you want.

2021-03-09 21:39 UTC, rasmus-madsen commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +                             pattgen_core.ch0_ctrl.prediv} {
I am not sure what you are trying to cover here?
each input here is a vector of different length.
what exactly is the size of the resulting vector? not 1 bit.
```4'b1001 | 4'b1100 => 4'b1101``` 

also do you want to cover that you saw different values for each of these?
in any combination?

2021-03-09 23:10 UTC, weicaiyang commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +                         binsof(cp_ch0_perf);
this seems better
```suggestion
      bins CH0_ENABLE =  binsof(cp_ch0_enable) intersect {1'b1};
```

2021-03-09 23:10 UTC, weicaiyang commented on hw/ip/pattgen/dv/env/pattgen_scoreboard.sv
> +      )
for loop should work. please try this.
```suggestion
      `DV_SPINWAIT_EXIT(
        for (uint i = 0; i < NUM_PATTGEN_CHANNELS; i++) begin
          fork
            automatic uint channel = i;
            compare_trans(channel);
          join_none
        end
        wait fork;,
        @(negedge cfg.clk_rst_vif.rst_n),
      )
```

2021-03-10 03:39 UTC, tunghoang290780 commented
@rasmus-madsen @weicaiyang per our DV discussion, I am going to significantly update this PR

2021-03-11 09:07 UTC, tunghoang290780 commented on hw/ip/pattgen/dv/env/pattgen_scoreboard.sv
> +      )
@weicaiyang updated

2021-03-11 09:07 UTC, tunghoang290780 commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +                         binsof(cp_ch0_perf);
fixed

2021-03-11 09:07 UTC, tunghoang290780 commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +                             pattgen_core.ch0_ctrl.prediv} {
fixed

2021-03-11 09:07 UTC, tunghoang290780 commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +  covergroup pattgen_op_cg @(posedge clk_i);
fixed, sampling at events

2021-03-11 09:08 UTC, tunghoang290780 commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +    cp_ch0_enable: coverpoint {pattgen_core.ch0_ctrl.enable} {
updated

2021-03-11 13:11 UTC, rasmus-madsen reviewed
@tunghoang290780 
I still have a few comments but this looks almost good to go

2021-03-11 13:11 UTC, rasmus-madsen commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +      bins TX_CLK_RISE = default;
@tunghoang290780 be aware that the default bin is not counted towards the scoring.
I.e this coverpoint will reach 100% coverage once TX_CLK_FALL reaches option.at_least 
even if TX_CLK_RISE has not been hit!

similar for all your defaults!

2021-03-11 13:11 UTC, rasmus-madsen commented on hw/ip/pattgen/dv/env/pattgen_scoreboard.sv
> +            cfg.clk_rst_vif.wait_clks(1);
why is the scoreboard timing-sensitive?
generally the scoreboard should not know of any clocks

2021-03-11 16:53 UTC, tunghoang290780 commented on hw/ip/pattgen/dv/env/pattgen_scoreboard.sv
> +            cfg.clk_rst_vif.wait_clks(1);
@rasmus-madsen if you clear the interrupt by writing to intr_state, the value of the interrupt bit of the intr_state will be cleared and updated after at least one cycle (register latency). The interrupt bits are both value and time-sensitive

2021-03-11 23:04 UTC, tunghoang290780 commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +      bins TX_CLK_RISE = default;
@rasmus-madsen you are right, checked LRM and found that `default` bin is not scored. I fixed that

2021-03-12 10:11 UTC, rasmus-madsen requested changes
looks great. a few nits then it is ready to go

2021-03-12 10:11 UTC, rasmus-madsen commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +    cp_ch0_op: cross cp_enable, cp_ch0_polarity, cp_ch0_perf {
prefix should be cr_ for crosses

2021-03-12 10:11 UTC, rasmus-madsen commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +    cp_ch1_op: cross cp_enable, cp_ch1_polarity, cp_ch1_perf {
same as above

2021-03-12 10:11 UTC, rasmus-madsen commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +    cp_chx_op: cross cp_enable, cp_ch0_polarity, cp_ch0_perf, cp_ch1_polarity, cp_ch1_perf {
same as above

2021-03-12 18:54 UTC, weicaiyang commented on hw/ip/pattgen/dv/cov/pattgen_cov_bind.sv
> +  bind pattgen_core pattgen_core_cov_if u_pattgen_core_cov_if (.*);
pattgen_core_cov_if isn't used. we directly use `pattgen_core.*". perhaps we can remove it

2021-03-12 18:54 UTC, weicaiyang commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +  end
like the comment above, pattgen_core_cov_vif isn't used. we directly use `pattgen_core.*". perhaps we don't need these

2021-03-12 19:51 UTC, tunghoang290780 commented
Update the PR
@rasmus-madsen replace `cp_` by `cr_` for cross coverage
@weicaiyang clean up `pattgen_core_cov_if ` stuffs

2021-03-12 21:25 UTC, weicaiyang approved these changes
LGTM with another suggestion

2021-03-12 21:25 UTC, weicaiyang commented on hw/ip/pattgen/rtl/pattgen.sv
> +  pattgen_core pattgen_core (
why rename this? perhaps we can revert this and replace `pattgen_core` to `u_pattgen_core` in the pattgen_cov_if

2021-03-13 00:21 UTC, tunghoang290780 commented on hw/ip/pattgen/rtl/pattgen.sv
> +  pattgen_core pattgen_core (
@weicaiyang just my preference

2021-03-15 14:13 UTC, rasmus-madsen requested changes
@tunghoang290780 I few nits I think you accidentally committed some typo.

I would like to have @sriyerg  or @weicaiyang take a look at the interrupt handling.
just to confirm this is the preferred way to handle this.

2021-03-15 14:13 UTC, rasmus-madsen commented on hw/dv/sv/pattgen_agent/pattgen_agent_pkg.sv
> +g
I think you accidentally committed some stuff here?

2021-03-15 14:13 UTC, rasmus-madsen commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +      bins TX_CLK_FALL = {1'b0} ;
remove space before ;

2021-03-15 14:13 UTC, rasmus-madsen commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +      bins TX_CLK_FALL = {1'b0} ;
space before ;

2021-03-15 14:13 UTC, rasmus-madsen commented on hw/ip/pattgen/dv/env/pattgen_scoreboard.sv
> +            cfg.clk_rst_vif.wait_clks(1);
hmm ok i guess
@sriyerg @weicaiyang I haven't looked into how we handle interrupts - is this the preferred method?
it seems to me that having timing sensitivity in the scoreboard is something to be avoided?

2021-03-15 17:50 UTC, weicaiyang commented on hw/ip/pattgen/dv/env/pattgen_scoreboard.sv
> +            cfg.clk_rst_vif.wait_clks(1);
I feel it's fine. If we check the interrupt at any time in seq, we do need to predict the value cycle accurately. Or we need to add some delay in seq to avoid checking at the period that scb and design are not in sync. either way is fine to me

2021-03-15 18:05 UTC, tunghoang290780 commented on hw/dv/sv/pattgen_agent/pattgen_agent_pkg.sv
> +g
fixed

2021-03-15 18:05 UTC, tunghoang290780 commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +      bins TX_CLK_FALL = {1'b0} ;
fixed

2021-03-15 18:06 UTC, tunghoang290780 commented on hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
> +      bins TX_CLK_FALL = {1'b0} ;
fixed

2021-03-15 18:51 UTC, rasmus-madsen approved these changes
Nice work
LGTM

2021-03-15 20:56 UTC, cindychip approved these changes

2021-03-15 21:02 UTC, merged