[dv/flash] Some changes to rand_ops_vseq and added some more configurations
lowRISC/opentitan pull request #6244
Opened 2021-04-22 07:17 UTC by eshapira

Hi,
This PR includes:
* Removed some forgotten trailing spaces.
* Added some configurations to make it possible to externally configure and activate **flash_ctrl_rand_ops_vseq** by other sequences.
* Changed power_down signal edge creation to be correctly affected by reset in **tb.sv**.

Signed-off-by: Eitan Shapira <eitan.shapira@nuvoton.com>

2021-04-22 16:41 UTC, sriyerg requested changes
Left a few comments, hopefully easy to address. Thanks!

2021-04-22 16:41 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv
> +  //  by some external vseq (possibly partner vseq)
IMO no need to indicated what could the external vseq be...
```suggestion
  //  Set by a higher level vseq that invokes this vseq
```

2021-04-22 16:41 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv
> +    //  by some external vseq (possibly partner vseq)
I think the comment need not be duplicated here. Reader can follow the signal to know what it is used for.

2021-04-22 16:41 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv
> +    //  and actions.
Don;t these fit in 1 line without violating 100 chars per line limit?

2021-04-22 16:41 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rand_ops_vseq.sv
> +      // If external_cfg=1 it means this sequence is being randomized by another sequence and this randomization will possibly override the upper randomization (Added specifically for partner sequenc
Comment length is too long. We have a 100 chars per line limit.

2021-04-22 16:41 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rand_ops_vseq.sv
> +      if(!cfg.seq_cfg.external_cfg) `DV_CHECK_RANDOMIZE_FATAL(this)
Add space after `if`
Prefer to always put macro invocations in `begin` .. `end` - it often leads to avoidable bugs in the code. 
```suggestion
      if (!cfg.seq_cfg.external_cfg) begin
        `DV_CHECK_RANDOMIZE_FATAL(this)
      end
```

2021-04-22 16:41 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/tb/tb.sv
> +        begin : CHANGE_INIT
Use upper case only for parameters and macros. 
```suggestion
        begin : change_init
```

2021-04-22 16:41 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/tb/tb.sv
> +          if(rst_n) begin
```suggestion
          if (rst_n) begin
```

2021-04-22 16:41 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/tb/tb.sv
> +    end
The `disable fork` without an isolation fork is potentially hazardous since it can disable other threads forked off from the main thread even before the `forever` loop. It is _always_ safer to put this logic within an isolation fork.

2021-04-22 16:41 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/tb/tb.sv
> +          wait(0); // Wait for reset change.
What happens if we remove this? It seems like it should not be needed.

2021-04-22 16:41 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/tb/tb.sv
> +          if(rst_n) begin
If `rst_n` is X, then `init` gets asserted. IMO this is probably a bit more robust:
```systemverilog
  if (rst_n === 1'b1) begin
    ...
  end
  else if (rst_n === 1'b0) begin
    ...
  end
  else begin
    init = 1'bx;
  end
```

2021-04-22 18:10 UTC, eshapira commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv
> +  //  by some external vseq (possibly partner vseq)
Done.

2021-04-22 18:13 UTC, eshapira commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv
> +    //  by some external vseq (possibly partner vseq)
Done for all fields.
I thought it will make it easier to understand but I get that it's an overdoing.

2021-04-22 18:14 UTC, eshapira commented on hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv
> +    //  and actions.
Sure, done.

2021-04-22 18:16 UTC, eshapira commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rand_ops_vseq.sv
> +      // If external_cfg=1 it means this sequence is being randomized by another sequence and this randomization will possibly override the upper randomization (Added specifically for partner sequenc
Right, missed it. Done.

2021-04-22 18:17 UTC, eshapira commented on hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rand_ops_vseq.sv
> +      if(!cfg.seq_cfg.external_cfg) `DV_CHECK_RANDOMIZE_FATAL(this)
I keep forgetting this requirement. Done.

2021-04-22 18:19 UTC, eshapira commented on hw/ip/flash_ctrl/dv/tb/tb.sv
> +        begin : CHANGE_INIT
Done.

2021-04-22 18:19 UTC, eshapira commented on hw/ip/flash_ctrl/dv/tb/tb.sv
> +          if(rst_n) begin
Done.

2021-04-22 18:23 UTC, eshapira commented on hw/ip/flash_ctrl/dv/tb/tb.sv
> +    end
Noted and done, thanks!

2021-04-22 18:28 UTC, eshapira commented on hw/ip/flash_ctrl/dv/tb/tb.sv
> +          if(rst_n) begin
OK, agreed and done.

2021-04-22 18:34 UTC, eshapira commented on hw/ip/flash_ctrl/dv/tb/tb.sv
> +          wait(0); // Wait for reset change.
If we'll remove this, the fork will just keep opening, check the condition on the reset and closing for no reason until reset change. No? This way as long as reset doesn't change, this code will just wait.

2021-04-22 20:01 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/tb/tb.sv
> +    end
Ohh, I now understand - the `wait(0)` indefinitely blocks that thread from exiting. If we never want that thread to exit, we can perhaps write this slightly differently:

```systemverilog
    forever begin
      fork
        begin : isolation_fork
          // Fork off a thread that updates the init value. 
          fork
            begin : change_init
              if (rst_n === 1'b1) begin
                clk_rst_if.wait_clks(5);
                init = 1'b0;
              end else if (rst_n === 1'b0) begin
                init = 1'b1;
              end else begin
                init = 1'bx;
              end
            end : change_init
          join_none

          // Wait for the rst_n to change. 
          @(rst_n);
          disable fork;
        end : isolation_fork
      join
    end
```

Does this work?

2021-04-26 06:12 UTC, eshapira commented on hw/ip/flash_ctrl/dv/tb/tb.sv
> +    end
This seems to work the same. Changed to your suggestion.

2021-04-26 16:43 UTC, sriyerg approved these changes

2021-04-26 16:43 UTC, sriyerg commented on hw/ip/flash_ctrl/dv/tb/tb.sv
> +    end
Thanks!

2021-04-26 16:43 UTC, merged

2021-04-26 17:03 UTC, eshapira commented
Thank you!