[dv/mem_bkdr] Support memory backdoor write with ECC error injection
lowRISC/opentitan pull request #6515
Opened 2021-05-13 01:06 UTC by cindychip

This PR support memory backdoor write with ECC errors:
1. Add a input `ecc_corrupt_second_bit`, is set to 1, it will corrupt
two bits and have a ECC uncorrectable error.
2. Adjust OTP testbench to use the new write function with ECC error.

Signed-off-by: Cindy Chen <chencindy@google.com>

2021-05-13 01:07 UTC, cindychip commented on hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_base_vseq.sv
> +    // TODO: debug why write16 and write32 won't work.
Hey @udinator I left a comment here and still debugging why write16/32 won't work. But other than that, this ECC backdoor inject error works!

2021-05-13 01:48 UTC, udinator requested changes

2021-05-13 01:48 UTC, udinator commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +              second_idx_to_corrupt != idx_to_corrupt;,
I think this calculation is incorrect, in situations where `idx_to_corrupt` is not in the lowest data byte of the memory line.
I think it needs to be:
```
second_idx_to_corrupt != (addr[1:0] * MEM_BYTE_MSB + idx_to_corrupt);,...
```
if there are two bytes in each memory line, and similarly for different numbers of bytes in each memory line - meaning that this randomization may have to go inside of the case statements, wdyt?

2021-05-13 01:48 UTC, udinator commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +              "mem_bkdr_if")
nit: you can use `path` here instead

2021-05-13 01:48 UTC, udinator commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +              rw_data[idx_to_corrupt] = ~rw_data[idx_to_corrupt];
not sure if we discussed this offline, but this index needs to be offset by the proper byte addressing in the memory line:
`addr[1:0] * MEM_BYTE_MSB + idx_to_corrupt` and so on for different memory line widths

2021-05-13 01:48 UTC, udinator commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +      return prim_secded_hamming_22_16_dec(mem_data);
nit: need to rebase on my recent PR to update these return values

2021-05-13 04:37 UTC, udinator commented on hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_base_vseq.sv
> +    // TODO: debug why write16 and write32 won't work.
awesome, thanks a lot!

2021-05-13 04:49 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +                                 input bit ecc_corrupt_second_bit = $urandom_range(0, 1));
How about `int inject_num_errors = 0`? Seems sufficient to allow the user to express his intent (inject 0, 1, 2, more errors).

2021-05-13 04:49 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +              ecc_corrupt_second_bit);
So it looks like we inject the first and 2nd error on all byte lanes? Might be worth explaining this in the comment above.

2021-05-13 04:54 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +              ecc_corrupt_second_bit);
Wonder if we should randomize further between "pick all byte lanes" and "just pick one". How does the external logic that does the ECC correction react to this? Does it count 4 ECC errors corrected?

2021-05-13 04:54 UTC, udinator commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +              ecc_corrupt_second_bit);
I believe the bulk of this was actually implemented in #6441 - the idea is that a random bit `inject_err_in_first_sub_write` is created and then used as an enable bit for `inject_err`.

we make sure to invert this enable bit for one of the `write##()` subroutine calls (the same logic applies to `write16`, `write32`, `write64`) such that only one of the subroutine calls thinks that it should inject an error, and this continues all the way down until we hit `write8`, where only one of the method instances will inject an error.

e.g. if we call `write32` and set `inject_err`, `write8()` will be called 4 separate times, but only one of those 4 invocations will actually inject an error.

2021-05-13 05:02 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +              ecc_corrupt_second_bit);
Aah, sorry I somehow overlooked the `!` in the second one. This is well thought out! Thanks!

2021-05-13 17:07 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +              second_idx_to_corrupt != idx_to_corrupt;,
Yes! I totally agree with that.. I see I see, that could be the issue with doing `write16`? Let me change that and give it a try!

2021-05-13 17:49 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +              rw_data[idx_to_corrupt] = ~rw_data[idx_to_corrupt];
Sorry about that.. i think this should work? Would you mind taking a look again?

2021-05-13 17:49 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +                                 input bit ecc_corrupt_second_bit = $urandom_range(0, 1));
Thanks Sri, updated it!

2021-05-13 17:52 UTC, matutem reviewed
This seems complicated. An alternative is to introduce errors via a word of the same size as the memory word size that has one or two bits set (all others being zero), and just xor that against the memory contents. Clearly in normal operation that word should be all zero.

2021-05-13 17:53 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +                                 input int inject_num_ecc_err = 0);
I think these can be combined into a single arg - `inject_num_ecc_errors = 0`. 0 means don't inject any errors.

2021-05-13 19:26 UTC, udinator commented
> This seems complicated. An alternative is to introduce errors via a word of the same size as the memory word size that has one or two bits set (all others being zero), and just xor that against the memory contents. Clearly in normal operation that word should be all zero.

@matutem I think this approach would work as well, but in either method we still have to keep track a variable number of indices to corrupt - in your proposal we'd have to flip each corresponding bit in the mask and then xor, vs just directly flipping the bits in the data word to be written to memory.

2021-05-13 19:27 UTC, udinator commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +                    !(next_idx_to_corrupt inside {corrupted_idx_q});,
do we want to support scenarios where the same bit position can get "corrupted' multiple times?
@sriyerg

2021-05-13 19:29 UTC, udinator commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +                                  input bit ecc_corrupt_second_bit = $urandom_range(0, 1));
should this input be changed to `inject_num_ecc_errors` ?

2021-05-13 19:42 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +                                  input bit ecc_corrupt_second_bit = $urandom_range(0, 1));
Good eye, thanks Udi, sorry I missed that..

2021-05-13 19:54 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +                    !(next_idx_to_corrupt inside {corrupted_idx_q});,
Sorry Udi, I might not understand this correctly. How can we corrupted it multiple times? i thought if the bit is already corrupted, and we flip it again, it will be reverted to the uncorrupted value right?

2021-05-13 20:16 UTC, udinator commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +                    !(next_idx_to_corrupt inside {corrupted_idx_q});,
yup, sorry that's what I mean by "corrupted" - just flipping the same bit multiple times, instead of explicitly making sure that any given bit is only flipped once

2021-05-13 20:16 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +                corrupted_idx_q.push_back(next_idx_to_corrupt);
How about we do it like this as Matute suggested:
```systemverilog
  if (inject_num_errors) begin
    bit [MEM_MAX_WIDTH-1:0] err_mask;
    `DV_CHECK_STD_RANDOMIZE_WITH_FATAL(err_mask, $countones(err_mask) == inject_num_errors)
    rw_data ^= err_mask
  end
```

2021-05-13 20:21 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +                                 input int inject_num_ecc_errors = 0);
Could we just have a single arg here? Call it `int num_inject_errors = 0` - It should work for parity case as well.

2021-05-13 20:24 UTC, udinator commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +                corrupted_idx_q.push_back(next_idx_to_corrupt);
+1, I like this option - simplifies some of the logic, and allows support for parity errors as well.

2021-05-13 20:42 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +                                 input int inject_num_ecc_errors = 0);
sounds good. I will update that. thanks Sri

2021-05-13 20:58 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +      write8(addr + 1, data[15:8], !inject_err_in_first_sub_write ? 0 : inject_num_ecc_errors);
Perhaps we could distribute the errors to each half:
```systemverilog
  int inject_num_errors_split[2];
  `DV_CHECK_STD_RANDOMIZE_WITH_FATAL(inject_num_errors_split,
      inject_num_errors_split[0] + inject_num_errors_split[1] == inject_num_errors;)

      write8(addr, data[7:0], inject_num_errors_split[0]);
      write8(addr + 1, data[15:8], inject_num_errors_split[1]);
```

2021-05-13 21:00 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +      write8(addr + 1, data[15:8], !inject_err_in_first_sub_write ? 0 : inject_num_ecc_errors);
Also, put it in a helper function to avoid duplication of code.

2021-05-13 22:46 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +      write8(addr + 1, data[15:8], !inject_err_in_first_sub_write ? 0 : inject_num_ecc_errors);
Thank you for the suggestion! Further split into different 8 bits sounds good! But for a helper function, since different write (write8, 16, 32) all have different addr increment number, and have different data index. I think we may not save that much duplicated code?

2021-05-14 01:59 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
>                rw_data[addr[0] * MEM_BYTE_MSB +: MEM_BYTE_MSB] = corrupted_data;
It is not clear to me though, why is error being injected twice?

2021-05-14 01:59 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
>                rw_data[addr[0] * MEM_BYTE_MSB +: MEM_BYTE_MSB] = corrupted_data;
I am also not sure I understand why the data corruption is done twice.

2021-05-14 01:59 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +
This is also duplicated a couple of times. Perhaps we could create a simple helper data structure and function:
```systemverilog
  typedef struct {
    int x;
    int y;
  } int_pair_t;
  
  function automatic int_pair_t rand_split(int num);
    rand_split.x = $urandom_range(0, num);
    rand_split.y = num - rand_split.x;
  endfunction

  ....
      int_pair inject_num_errors_split = rand_split(inject_num_errors)
      write8(addr, data[7:0], inject_num_errors_split.x);
      write8(addr + 1, data[15:8], inject_num_errors_split.y);
 ```

Plus use of `$urandom_range` avoids the constraint solver.

2021-05-14 02:59 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
>                rw_data[addr[0] * MEM_BYTE_MSB +: MEM_BYTE_MSB] = corrupted_data;
I might not be the best person to answer this. @udinator could you provide any insight? Can we use the same code for ECC and Parity? I remembered you mentioned something as -  "not in the lowest data byte of the memory line"?

2021-05-14 03:42 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
>        bit [MEM_BYTE_MSB-1:0] corrupted_data;
Thanks Sri. I think this question will have the same answer as the question below. If Parity error can share the same method as ECC, then we do not need this. But I will let @udinator confirm this :)

2021-05-14 04:56 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +  endfunction
Nit: perhaps `inject_errors` is a more simple function name. I don't think you need to make it about ecc.

2021-05-14 04:56 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +    data_with_ecc_errors ^= data;
Its perhaps clearer to declare `err_mask` as a separate variable and `return data ^ err_mask` instead.

2021-05-14 04:56 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
>      `DV_CHECK_FATAL(!(MEM_PARITY && MEM_ECC != SecdedNone),
These checks should be moved inside `if (!initialized)`. There is no value in checking them on every single access.

2021-05-14 04:56 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +      end
Not sure if it's worth checking these on every access. A better strategy might be to inject `min(inject_num_errors, max_errors_supported)` in the error injection function. Thoughts?

2021-05-14 04:56 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
>                rw_data[addr[0] * MEM_BYTE_MSB +: MEM_BYTE_MSB] = corrupted_data;
Should the inject error function operate on `[MEM_BYTE_MSB:0]` sized data? Not sure if we made a mistake here - the `write8` function should only manipulate the specific byte of the mem array, not the whole array. It could then be reused to inject error for the parity case also.

2021-05-14 05:41 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +    data_with_ecc_errors ^= data;
That is true, thanks Sri I will update that.

2021-05-14 05:41 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +  endfunction
Thanks for pointing that out. My bad. I keep thinking this is only for ECC. Yeah let me update that.

2021-05-14 05:41 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
>      `DV_CHECK_FATAL(!(MEM_PARITY && MEM_ECC != SecdedNone),
Sounds good, thanks I will update that.

2021-05-14 05:50 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +      end
So just want to double check, we won't return an error if the `inject_num_errors` are larger than the `max_errors_supported`?

2021-05-14 06:17 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +      end
Just asking for thoughts and opinions here - I am myself on the fence.

2021-05-14 06:44 UTC, udinator commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
>                rw_data[addr[0] * MEM_BYTE_MSB +: MEM_BYTE_MSB] = corrupted_data;
so, my initial idea was to inject the first error into the byte that is currently being written, and then any subsequent errors get injected randomly into the entire memory line - that's why it was necessary to differentiate between the first time that data corrupted vs any following times data gets corrupted

2021-05-14 06:49 UTC, udinator commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +      end
+1 to @sriyerg's idea

2021-05-14 06:53 UTC, udinator commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +      write8(addr + 1, data[15:8], inject_num_errors_split.y);
question here that also refers to my comment [here](https://github.com/lowRISC/opentitan/pull/6515/files#r632320735) - do we not want to provide a guarantee that at least one of the injected errors is injected into the byte being operated on?
If I'm misunderstanding the new approach of injection, please let me know

2021-05-14 17:30 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
>                rw_data[addr[0] * MEM_BYTE_MSB +: MEM_BYTE_MSB] = corrupted_data;
Hey @sriyerg  and @udinator,
Thanks for your time and help. I discussed with Udi offline and here is what we thought. With the entire myth of write8 function actually polls the entire memory line, we have two method of injecting ECC and Parity errors:
(As an example, the memory line is 16 bits and we are writing 8 bits to the lower byte)

1). (The current method): For parity errors, only inject on the lower byte (written bytes) + 1 bit parity associated with it.
     For ECC errors: injecting on the entire 16 bits + ECC bits.   ---> This current way we believe caused the error for `wirte16` because it triggers two `write8`, there could be a possibility that first `write8` injected the error on the higher bytes, and second `write8` writes the correct value to the higher bytes, and thus flipped the error bits back.

2). As Sri proposed, because we are writing only the lower 8 bits, we only inject ECC and parity error to the lower 8 bits. For this, we can re-use the `inject_errors` function, but: 
  (1): We need to know which byte we are injecting. (This could be resolved by input address to the `inject_errors` function)
  (2): ECC bits are associated with the entire 16 bits memory line (unlike parity bits, each bit associated with specific 8 bits data). We need to think of a way to randomly inject ECC bits errors in the two separate `write8` functions. 

But I am leaning towards the second method. Any thoughts? and please correct me if I misunderstand anything :)

2021-05-14 18:57 UTC, matutem commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
>                rw_data[addr[0] * MEM_BYTE_MSB +: MEM_BYTE_MSB] = corrupted_data;
Sorry, I am not tracking this closely, but I don't understand why the concern about adding error on the subword or not. I think the hardware needs to access the full item protected by either parity or ECC, and selecting subwords is typically done in a mux structure after the access is done. This means if there are errors in the full item the hardware has no option but to report it. What am I missing?

2021-05-14 20:29 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
>                rw_data[addr[0] * MEM_BYTE_MSB +: MEM_BYTE_MSB] = corrupted_data;
No worries Matute, and thank you for raising this up.
I think the origin intend of this `write` functions are all trying to trace down to `write8`. So `write16` will trigger two `write8`, `write32` will trigger four `write8` etc.. And the eventual write and error (ecc or parity) will be written in `write8` function.
As you probably already observed, the issue here is OTP_CTRL access memory in 16 bits chunk instead of 8, but parity is always 8 bit chunk..
Does that answer your question?

2021-05-14 21:55 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
>                rw_data[addr[0] * MEM_BYTE_MSB +: MEM_BYTE_MSB] = corrupted_data;
In any case, I think `inject_errors` function can be enhanced to cater to the parity case as well (where error is injected only in the byte).

2021-05-14 22:16 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> +            if (inject_num_errors) rw_data = inject_errors(rw_data, inject_num_errors);
IMO the error injection here should happen only within the bits `[addr[0] * MEM_BYTE_MSB +: 8]`. Likewise in below cases. So maybe `inject_errors` should take only the byte size data `write8` is touching as arg.

2021-05-14 23:08 UTC, cindychip commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
>                rw_data[addr[0] * MEM_BYTE_MSB +: MEM_BYTE_MSB] = corrupted_data;
I think Matute brings out a good concern that the parity bits might not always be 8 bits data + 1 bit parity. Maybe we can discuss more on the DV meeting togather?

2021-05-14 23:22 UTC, udinator commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
>                rw_data[addr[0] * MEM_BYTE_MSB +: MEM_BYTE_MSB] = corrupted_data;
agree with @cindychip , I think this issue warrants some discussion in our DV meeting

2021-05-15 01:32 UTC, sriyerg commented on hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
>                rw_data[addr[0] * MEM_BYTE_MSB +: MEM_BYTE_MSB] = corrupted_data;
In the interest of making progress, let's get this PR merged and make further updates later.

2021-05-15 01:32 UTC, sriyerg approved these changes

2021-05-15 03:36 UTC, msfschaffner commented
You may also want to double check coverage after the LC token hashing mechanism has been removed from OTP: #6558

2021-05-17 17:03 UTC, udinator approved these changes
lgtm - agree with Sri, we can merge now to unblock progress and discuss further enhancements later.

2021-05-17 19:32 UTC, merged