[csrng/dv] Verifying csrng_cmds, aes_disabled
lowRISC/opentitan pull request #6588
Opened 2021-05-18 13:56 UTC by senelson7

Signed-off-by: Steve Nelson <steve.nelson@wdc.com>

Implemented NIST algorithms in sequences to verify, but will be moving prediction to scoreboard.

2021-05-18 19:48 UTC, rasmus-madsen requested changes
@senelson7 mostly looks good but I think there is room for a little cleanup

2021-05-18 19:48 UTC, rasmus-madsen commented on hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
> +  bit [csrng_pkg::GENBITS_BUS_WIDTH-1:0]   v;
v seems like a bad choice for a signal?

2021-05-18 19:48 UTC, rasmus-madsen commented on hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
> +//    `DV_CHECK_FATAL(clen == data_q.size())
Maybe remove this if not needed

2021-05-18 19:48 UTC, rasmus-madsen commented on hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv
> +//      for (int i = 0; i < num_trans; i++) begin
do you need to keep this around?

2021-05-18 19:48 UTC, rasmus-madsen commented on hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv
> +//        for (int i = 0; i < 1; i++)
do we need to keep this around?

2021-05-18 19:51 UTC, senelson7 commented on hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
> +  bit [csrng_pkg::GENBITS_BUS_WIDTH-1:0]   v;
The variable names match the names used in the NIST algorithms. Easier to debug if the names are the same.

2021-05-18 19:53 UTC, rasmus-madsen commented on hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
> +  bit [csrng_pkg::GENBITS_BUS_WIDTH-1:0]   v;
ok that seem like a resonable argument

2021-05-18 20:03 UTC, senelson7 commented on hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
> +//    `DV_CHECK_FATAL(clen == data_q.size())
Don't know yet, hence the TODO that this sequence is still under development. Want to merge at this point since basic algorithms match. Will move/remove later.

2021-05-18 20:03 UTC, senelson7 commented on hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
> +//    `DV_CHECK_FATAL(clen == data_q.size())
Don't know yet, hence the TODO that this sequence is still under development. Want to merge at this point since basic algorithms match. Will move/remove later.

2021-05-18 20:04 UTC, senelson7 commented on hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
> +//    `DV_CHECK_FATAL(clen == data_q.size())
Ditto for other comments.

2021-05-18 21:35 UTC, mwbranstad approved these changes
LGTM

2021-05-18 21:35 UTC, mwbranstad commented on hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
> +  bit [csrng_pkg::GENBITS_BUS_WIDTH-1:0]   v;
Prefer a new define called BLK_LEN. Not sure if GENBITS_BUS_WIDTH and v will always be linked in this way.

2021-05-18 21:35 UTC, mwbranstad commented on hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
> +  uint                                     reseed_counter;
Any reason not to have a new define for the reseed counter?

2021-05-18 21:35 UTC, mwbranstad commented on hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
> +//    `DV_CHECK_FATAL(clen == data_q.size())
Seems like a reasonable check to me.

2021-05-19 12:33 UTC, senelson7 commented on hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
> +  bit [csrng_pkg::GENBITS_BUS_WIDTH-1:0]   v;
Done

2021-05-19 14:54 UTC, rasmus-madsen approved these changes

2021-05-19 14:54 UTC, merged