[dv/otp_ctrl] Add more functional coverage to otp_ctrl
lowRISC/opentitan pull request #6624
Opened 2021-05-19 16:44 UTC by cindychip

This PR adds the following functional coverages to OTP_CTRL:
1. Error code coverage
2. Status coverage
3. CSR read/write after alert happened
4. LC_escalation On during dai busy

Signed-off-by: Cindy Chen <chencindy@opentitan.org>

2021-05-19 18:58 UTC, matutem commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +    }
Does it make sense to have some sort of default bucket?

2021-05-19 19:12 UTC, matutem commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +  // This covergroup samples CSRs being read checked after fatal alert is issued.
... being read checked ...? It seems it is either one.

2021-05-19 19:16 UTC, cindychip commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +  // This covergroup samples CSRs being read checked after fatal alert is issued.
ohh. Good catch, here i mean the CSR being read and the read value is checked...

2021-05-19 19:18 UTC, matutem commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +    read_csr_after_alert_issued: coverpoint csr_offset {
Is there a better way to determine the literals below? They seem a bit brittle.

2021-05-19 19:29 UTC, cindychip commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +    read_csr_after_alert_issued: coverpoint csr_offset {
Yeah I agree, here is what I tried but does not work:
1. directly sample the csr names with `string` input. -> This does not work because coverpoint does not allow me to sample a `string`.
2. Instead of hardcode the offset, use `cfg.ral.{csr_name}.get_offset()` -> This does not work because ral has not been created when declaring this coverpoint.

But totally agree this is not a good way.. Would be appreciated if there is any better ideas :)

2021-05-19 20:14 UTC, cindychip commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +    }
agree! Thanks Matute, added an illegal bin for that.

2021-05-20 05:49 UTC, udinator commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +    read_csr_after_alert_issued: coverpoint csr_offset {
I'm not sure about a more elegant solution for this, but for the time being, maybe it's worth creating an enum for this in the env_pkg and using those values here?
I think that may make this a bit more readable.

2021-05-20 19:12 UTC, matutem commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +    read_csr_after_alert_issued: coverpoint csr_offset {
Good idea, and you can perhaps check during some of the early UVM phases the enums against the CSRs, since they should be available then.

2021-05-20 19:17 UTC, matutem commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
> +          bit [TL_AW-1:0] dai_addr = `gmv(ral.direct_access_address) >> 2 << 2;
This masks off the lower 2 bits. We should have a utility function to generate such a mask. Or better yet, a utility function to align addresses, since that is what you are really doing.

2021-05-20 19:20 UTC, matutem commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +    foreach(status_csr_cg[i]) begin
Add space after foreach: https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#space-around-keywords.

2021-05-20 19:21 UTC, matutem commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +    case(field_idx)
Add space after case: https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#space-around-keywords

2021-05-20 19:21 UTC, matutem commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
>        wait(cfg.otp_ctrl_vif.alert_reqs == 1 && cfg.en_scb);
Add space after wait: https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#space-around-keywords

2021-05-20 23:35 UTC, cindychip commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +    foreach(status_csr_cg[i]) begin
Thanks for catching that :)

2021-05-20 23:35 UTC, cindychip commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +    case(field_idx)
Good catch, thanks Matute.

2021-05-20 23:35 UTC, cindychip commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
>        wait(cfg.otp_ctrl_vif.alert_reqs == 1 && cfg.en_scb);
updated! appreciate your suggestion :)

2021-05-21 07:43 UTC, sriyerg commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_pkg.sv
> +  // This enum is mainly used for functional coverage collection.
I don't think this is a good idea - the register spec is considered fluid and can change any time (which is why we always auto-generate it from the spec). Perhaps the issue you solved by creating these enums can be solved some other way?

2021-05-21 07:44 UTC, sriyerg commented on hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_macro_invalid_cmd_vseq.sv
> +  int               dai_macro_err_part_idx = DaiIdx;
nit: no need to align if its a new code block (i.e. separated from the previous code block by blank line)

2021-05-21 07:50 UTC, sriyerg requested changes

2021-05-21 07:50 UTC, sriyerg commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +    power_on_cg                   = new();
You can `new` all of these in `build_phase` where `cfg`. `ral` etc are available.

2021-05-21 07:50 UTC, sriyerg commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +    read_csr_after_alert_issued: coverpoint csr_offset {
You can define the covergroups as:
```systemverilog
  covergroup csr_rd_after_alert_cg(otp_ctrl_reg_block ral) with function sample(bit[TL_DW-1:0] csr_offset);
```

Move the covergroup instantiation to `build_phase` (yes you can, because they are defined outside the class) and use your option 2.

2021-05-21 07:50 UTC, sriyerg commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_pkg.sv
> +  // This enum is mainly used for functional coverage collection.
See my earlier comments on alternate solution.

2021-05-21 07:54 UTC, sriyerg commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
>        wait(cfg.otp_ctrl_vif.alert_reqs == 1 && cfg.en_scb);
Sorry, I disagree. `wait` statement is more like a function / statement call where spaces are not added between the keyword and `(`.

2021-05-21 16:27 UTC, cindychip commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +    read_csr_after_alert_issued: coverpoint csr_offset {
That is a great idea! thanks Sri!

2021-05-21 18:59 UTC, cindychip commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +    power_on_cg                   = new();
I think for covergroups that created in this class, we have to new it in this new function, otherwise here is an error:
```
Error-[PCECGNNA] Improper new call to embedded covergroup
../src/lowrisc_dv_otp_ctrl_env_0.1/otp_ctrl_env_cov.sv, 224
  Procedural call to 'new' of embedded covergroup 
  otp_ctrl_env_cov::power_on_cg not allowed outside new function of 
  encompassing class otp_ctrl_env_cov or its derived classes.
```
But I did move the wrapper `new` method to the `build_phase`.

2021-05-21 19:03 UTC, udinator commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
> +      wait(cfg.otp_ctrl_vif.lc_prog_req == 1);
could you do a `@(negedge cfg.otp_ctrl_vif.lc_prog_req)` ?

2021-05-21 19:06 UTC, cindychip commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
> +          bit [TL_AW-1:0] dai_addr = `gmv(ral.direct_access_address) >> 2 << 2;
Thank you for your comments! Actually there is one for general tl_i.a_addr: https://github.com/lowRISC/opentitan/blob/master/hw/dv/sv/dv_base_reg/dv_base_reg_block.sv#L163
I will create s separate PR for that.

2021-05-21 19:20 UTC, sriyerg commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
>        wait(cfg.otp_ctrl_vif.alert_reqs == 1 && cfg.en_scb);
@matutem, I filed https://github.com/lowRISC/style-guides/pull/54 to update the style guide to factor this in. PTAL, thanks!

2021-05-21 19:33 UTC, sriyerg commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +    power_on_cg                   = new();
Right - that's a nonsensical SV limitation which I hope is fixed in future revisions. Those covergroups need to be `new`ed here.

2021-05-21 23:46 UTC, cindychip commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
> +      wait(cfg.otp_ctrl_vif.lc_prog_req == 1);
I believe either method is fine, but if we use `wait`, I think it looks more uniformed with line 226.

2021-05-24 17:41 UTC, udinator commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +      OtpDaiErrIdx: dai_err_code_cg.sample(val, part_idx);
really small style nit: i think we prefer to use the same formatting for each case (`begin...end` vs one-liners)

2021-05-24 18:47 UTC, matutem approved these changes

2021-05-25 05:26 UTC, sriyerg commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
> +          bit [TL_AW-1:0] dai_addr = `gmv(ral.direct_access_address) >> 2 << 2;
You are retrieving the data written to that CSR, which should be sized to TL_DW. `dai_addr` should probably be `TL_DW` wide?

2021-05-25 19:25 UTC, cindychip commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
> +          bit [TL_AW-1:0] dai_addr = `gmv(ral.direct_access_address) >> 2 << 2;
oops. that was my bad. Thanks for pointing that out. Let me update that.

2021-05-25 19:29 UTC, cindychip commented on hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv
> +      OtpDaiErrIdx: dai_err_code_cg.sample(val, part_idx);
Sorry I missed this, I see. Thanks for pointing that out. I will update that.

2021-05-26 06:07 UTC, udinator approved these changes

2021-06-14 18:31 UTC, sriyerg approved these changes

2021-06-14 18:32 UTC, merged