[prim_clock_div] Add DFT step down inhibition signal
lowRISC/opentitan pull request #6706
Opened 2021-05-25 16:07 UTC by msfschaffner

Signed-off-by: Michael Schaffner <msf@opentitan.org>

2021-05-25 19:30 UTC, arnonsha requested changes

2021-05-25 19:30 UTC, arnonsha commented on hw/ip/prim/rtl/prim_clock_div.sv
> +    logic dft_inhibit_step_down;
Could you please make this an input to the block (connected to '0) ? We cannot connect to a wire. It needs to be a port.

thanks

2021-05-25 19:56 UTC, msfschaffner commented on hw/ip/prim/rtl/prim_clock_div.sv
> +    logic dft_inhibit_step_down;
ah ok I see. sure, but please see comment above.

2021-05-26 16:21 UTC, arnonsha commented
I'm not sure. Need to check

2021-05-28 05:37 UTC, arnonsha commented
Thanks @msfschaffner . This seems to work. No need to change RTL. I'll go ahead and close this PR.

2021-05-28 05:37 UTC, closed without merging