[dv/sram] implement covergroups
lowRISC/opentitan pull request #6720
Opened 2021-05-26 06:05 UTC by udinator

This PR implements the covergroups listed in #6710,
and sample them in the scoreboard when appropriate.

Signed-off-by: Udi Jonnalagadda <udij@google.com>

2021-05-26 18:00 UTC, matutem commented on hw/ip/sram_ctrl/dv/env/sram_ctrl_env_cov.sv
> +      bins sram_ifetch_invalid_disable = {[0 : DisSramIfetch-1],
Could you just use "default" here and in some of the other coverpoints below?

2021-05-26 18:07 UTC, udinator commented on hw/ip/sram_ctrl/dv/env/sram_ctrl_env_cov.sv
> +      bins sram_ifetch_invalid_disable = {[0 : DisSramIfetch-1],
No I need to explicitly specify the bin values here, as I want to be able to collect coverage on these values too (need to ensure the design can handle seeing these values when they are not set to the explicit Enable/Disable enum values).

2021-05-26 18:17 UTC, matutem requested changes
Can you try "default" as suggested?

2021-05-26 18:29 UTC, matutem approved these changes
LGTM

2021-05-26 19:18 UTC, cindychip commented on hw/ip/sram_ctrl/dv/env/sram_ctrl_env_cov.sv
> +  endgroup
As we discussed offline, maybe we can add this coverpoint to general TLUL interface and memory interface?

2021-05-26 19:18 UTC, cindychip approved these changes

2021-05-26 19:22 UTC, udinator commented on hw/ip/sram_ctrl/dv/env/sram_ctrl_env_cov.sv
> +  endgroup
sure, will do!

2021-05-26 19:41 UTC, udinator commented on hw/ip/sram_ctrl/dv/env/sram_ctrl_env_cov.sv
> +  endgroup
from offline discussion - moving this cg to common TL interface would require a RAL model for any affected memories, which controllers like SRAM/ROM/etc... currently do not have.
opening an issue to track this implementation after multi-RAL is implemented for SRAM and others.

2021-05-27 20:12 UTC, msfschaffner approved these changes
LGTM

2021-06-02 02:12 UTC, merged