[pwm, rtl] Support all pwm operational modes for D1
lowRISC/opentitan pull request #6786
Opened 2021-06-01 23:15 UTC by Muqing-Liu

Add RTL design for D1

- Completed the RTL design of standard blink mode and heartbeat mode for the PWM IP
- Fixed the bug for issue #6526

Signed-off-by: Muqing Liu muqing.liu@wdc.com

2021-06-03 06:03 UTC, tunghoang290780 commented on hw/ip/pwm/rtl/pwm_chan.sv
> +   end
Lines 69-71 must be aligned by 2 spaces

2021-06-03 06:04 UTC, tunghoang290780 commented on hw/ip/pwm/rtl/pwm_chan.sv
> +	 end
Require line alignment, see above comment

2021-06-03 06:05 UTC, tunghoang290780 commented on hw/ip/pwm/rtl/pwm_chan.sv
> +	 end
Require line alighment

2021-06-03 06:05 UTC, tunghoang290780 requested changes
Few style issue, otherwise LGTM

2021-06-03 10:43 UTC, imphil commented on hw/ip/pwm/rtl/pwm_chan.sv
> +   end
And please replace the tabs with spaces.

2021-06-03 15:28 UTC, martin-lueker requested changes
Thanks for the PR @Muqing!

Echoing @tunghoang290780 and @imphil's comments about the whitespace.

Also please see the comments above about cio_pwm_en_o, you should revert those particular changes (and all the related ports)   cio_pwm_en_o has nothing to do with the pwm_en register.

2021-06-03 15:28 UTC, martin-lueker commented on hw/ip/pwm/rtl/pwm.sv
> +  assign cio_pwm_en_o = reg2hw_sync.pwm_en;
I don't think this is correct.   The "enable" here isn't meant to communicate the enable state of the IP, it is meant to enable the output driver, and these pins always be enabled as outputs.  That said I think you should revert this change.

2021-06-03 15:28 UTC, martin-lueker commented on hw/ip/pwm/rtl/pwm.sv
> +    .reg2hw_sync,
If we are not pulling out the enable signal do we need this port?

2021-06-03 15:28 UTC, martin-lueker commented on hw/ip/pwm/rtl/pwm_chan.sv
> +   assign duty_cycle_heartbeat_end = cycle_end_i & (heartbeat_ctr_q == blink_param_x_i);
Thanks for implementing this Muqing.  When I was thinking about this it seemed there could be a lot finicky cases related to rounding.   (e.g. the heartbeat is supposed to increment 10 units, in steps of 3... when you get to the end what happens? What if you reach the max value?)  These details are not really of much practical concern... the effect will still *look* the same.  However they will cause headaches in verification.   That said, I suggest that you and @tunghoang290780 carefully discuss all the corner cases, and if there are any details that are hard to work, feel free to update the documentation. In the end for the fine details IP what is most important here is that the DV, Implementation all match.

2021-06-03 15:28 UTC, martin-lueker commented on hw/ip/pwm/rtl/pwm_chan.sv
> +	 end
Agreed.  It takes a while to remember all the details style guide, but this collaboration is fairly strict about it.  I suggest reading though it very closely while looking at your code.  Also your editor may have a whitespace mode that will help you clearly see tabs vs. spaces.

2021-06-03 15:28 UTC, martin-lueker commented on hw/ip/pwm/rtl/pwm_core.sv
> +  output pwm_reg_pkg::pwm_reg2hw_t reg2hw_sync,
See above in pwm.sv, I don't think this port needs to be exported.

2021-06-10 01:12 UTC, martin-lueker approved these changes
Thanks.  Muqing.  This LGTM.   I have one very minor nit-picky request.  Could you amend the commit log to not say "for D1".   This IP is now at D1 milestone already (Meaning it is already started).   Saying that you are moving it to D1 with this commit could cause someone confusion.

Other than that I think this is GTG if you are ready to merge it.

2021-06-10 14:44 UTC, imphil reviewed
Thanks for your pull request @Muqing-Liu! I didn't double-check the functionality, but please have a look at the operators in the ternaries. Thanks a lot!

2021-06-10 14:44 UTC, imphil commented on hw/ip/pwm/rtl/pwm_chan.sv
> +                                (dc_htbt_q == duty_cycle_a_i & pattern_repeat) ?
Please double-check the precedence of `&` vs `&&`. Is the current design really what you want? If so, add parentheses around `(duty_cycle_a_i & pattern_repeat)`.

2021-06-10 14:44 UTC, imphil commented on hw/ip/pwm/rtl/pwm_chan.sv
> +        else htbt_direction <= 1'b0;
You can simplify this as

```suggestion
        htbt_direction <= negative_htbt;
```

2021-06-15 09:50 UTC, imphil approved these changes
Thanks @Muqing-Liu for the update. Only a small thing requires changing, beyond that we're good to go.

If you make changes to a pull request could you please:
* Click on "Resolve" here on GitHub for all comments which you've addressed?
* Leave a short notice that you've updated the PR, including what changes you roughly made, and it is ready for re-review?
* Re-request review by clicking on the small icon next to the reviewer name (top-right of the PR). It will then show up in the reviewer's review queue again and they can have another look. (Otherwise there's a risk that reviews get lost.)

2021-06-15 09:50 UTC, imphil commented on hw/ip/pwm/rtl/pwm_chan.sv
> +  assign duty_cycle_scaled = duty_cycle_actual << (15 - dc_resn_i);
Please ensure that the signals you're using in an expression have the same width to avoid bits which are ignored or overflowing without you noticing. (And our lint tools will check for that as well.)

```suggestion
  assign phase_delay_scaled = phase_delay_i << (4'd15 - dc_resn_i);
  assign duty_cycle_scaled = duty_cycle_actual << (4'd15 - dc_resn_i);
```

or alternatively `4'hF`

2021-06-15 12:31 UTC, Muqing-Liu commented on hw/ip/pwm/rtl/pwm_chan.sv
> +  assign duty_cycle_scaled = duty_cycle_actual << (15 - dc_resn_i);
Hi Philipp, thank you very much for your suggestion. I have fixed that bit width issue and committed again. Please take a look. Thanks!

2021-06-16 08:24 UTC, merged