[dv,cip] Guarantee ordering of sampled A and D transactions
lowRISC/opentitan pull request #7042
Opened 2021-06-18 16:33 UTC by rswarbrick

When TileLink transactions are observed by `tl_monitor.sv`, it writes
items to "A" and "D" ports, depending on what channel observed them.
These writes race against each other, so there's no order guaranteed
between an A and D transaction sampled on the same clock edge.

These ports are connected to fifos in `cip_base_scoreboard.sv`. Before
this commit, the scoreboard used two tasks (`process_tl_a_chan_fifo` and
`process_tl_d_chan_fifo`) to sample from the two fifos. Once an item was
found on either fifo, the corresponding task called `process_tl_access`,
which itself is a task implemented in the subclass.

The problem is that the subclass implementation couldn't guarantee the
ordering that it would see if there was an A and D transaction on the
same cycle.

But why does this matter? Suppose that my block has a register, FOO,
whose value can be written by hardware but in a way that we can
predict. Then I need to somehow store an expected value when I see the
A channel transaction for a read of FOO, then check it matches the
transaction data for the following D response. The obvious way to do
this is to mirror the expected value in the RAL with a call to
`uvm_reg::predict()` when I handle the A channel transaction, and this
is what code like `keymgr_scoreboard::process_tl_access` does.

What happens if I see two back-to-back reads of FOO, where it changes
value between the two? That is, what if the following transactions
happen? (the (1) and (2) are indices to match up the A-side request
with the D-side response)

```
    Cycle | A channel   | D channel
   ---------------------------------
    0     | Get FOO (1) |
    1     | Get FOO (2) | FOO rdata (1)
    2     |             | FOO rdata (2)
```

Before this patch, there were two possible orderings for the resulting
calls to `process_tl_access()`. We'd either see

    A (1); D(1); A(2); D(2)

or we'd see

    A (1); A(2); D(1); D(2)

If the expected value of FOO changes between the two transactions, the
second ordering (AADD) is a disaster if we're trying to use the RAL to
mirror things: we'll end up checking the D(1) rdata against the A(2)
expected value.

This patch guarantees that, in the (common) case where the device
always responds on the next cycle, we always see the nice "ADAD"
order. To do this, we make sure to handle D before A, meaning that on
the "middle cycle" above, we see D(1) then A(2).

This isn't a completely general solution. For example, if the device
might take multiple cycles to respond, we might get something like this:

```
    Cycle | A channel   | D channel
   ---------------------------------
    0     | Get FOO (1) |
    1     | Get FOO (2) |
    2     |             | FOO rdata (1)
    3     |             | FOO rdata (2)
```

and no amount of cleverness can guarantee the "ADAD" ordering. In that
case, the device's scoreboard is going to need to be cleverer.

Similarly, if the device can respond on the same cycle, we might get
something like this:

```
    Cycle | A channel   | D channel
   ---------------------------------
    0     | Get FOO (1) | FOO rdata (1)
```

in which case we'll actually have a "DA" ordering, which is a bit
confusing! A future version of this code could be cleverer to avoid
this problem (by counting transactions to realise that the two items
were supposed to match). But that's harder and we don't have any
devices in OpenTitan that respond in zero time at the moment. The
behaviour with this patch is one of two behaviours that the previous
code might have had, so it's no worse at least.

2021-06-18 17:53 UTC, sriyerg commented
The D(*) packets already contains the corresponding A(*) channel information, which is what should be used by the scoreboard to develop the prediction logic, with 'completed transaction' packets. 

See:
https://github.com/lowRISC/opentitan/blob/e1d02b58bcbb8bf3d0c4f70ba62e4d03d760d309/hw/dv/sv/tl_agent/tl_monitor.sv#L145

2021-06-18 20:57 UTC, weicaiyang commented
I feel we need to let scb know the transaction occurs ASAP.
As I know, our design latches the value when a channel handshaking is done for read. then compares the read value when d channel is completed. There is a gap. So sometimes, when I need cycle accurate check, I have to store the predicted value when a channel is done (same cycle as design latches the value) and compare it when d channel is done.

For write, design also stores the write value or trigger some logic when a_channel is completed. 

In the IP level, if the block contains CSRs and mem, then it can support 2 outstanding transactions, one is CSR, one is mem access.
In the case below, 2 items are accepted by the design, but driver sets d_ready low for a long while. With this PR, we want to wait for CSR (A) and CSR (D) to complete, before let scb know mem(A) is done. It may be too late as design has taken the mem write value and start to process something.

```
 Cycle | A channel    | D channel
   ---------------------------------
    0    | write (csr) |
    1    | write(mem)  |
    driver  set d_ready low for a while, DUT can't accept new items
    n+1  |             | write done (csr)
    n+2  |             | write done (mem)
```

this is too late to know mem(A) is done
>  CSR (A) ->  N cycle   -> CSR (D) -> **mem(A)** -> mem(D)

prefer to see the transaction in scb like this, as it's closer to how design processes it
 > CSR (A) ->  **mem(A)** -> N cycle -> CSR (D) -> mem(D)

WDYT? @rswarbrick

2021-06-20 17:17 UTC, rswarbrick commented
Hi both.

@sriyerg: I don't think your answer is really addressing what this PR is about. The problem isn't that the D channel handling doesn't understand what the A channel transaction was doing. The problem is that it might need to know something about the state of the *block* when the A channel transaction came in.

@weicaiyang: I'm not completely sure I've understood your message, but in the example you've put forward, I think the scoreboard would see things in the order you want (with or without this patch!). The only time that this patch should have any effect is when an A and D transaction come in *on the same cycle*. With the code in master, the ordering of events at the scoreboard depends on the simulator's scheduling algorithm. With this patch, it will always be D then A.

2021-06-20 17:20 UTC, rswarbrick commented
@sriyerg: Actually, reading the tl_monitor code a bit more carefully, what happens if there are two back-to-back reads at a the same address, where the D response is delayed for a few cycles? If I understand the code correctly, we'll generate a spurious error from line 95 (`DV_CHECK_EQ_FATAL(pending_a_req.exists(cloned_req.a_source), 0)`). @weicaiyang: Does that sound right to you?

2021-06-21 05:18 UTC, sriyerg commented
> @sriyerg: Actually, reading the tl_monitor code a bit more carefully, what happens if there are two back-to-back reads at a the same address, where the D response is delayed for a few cycles? If I understand the code correctly, we'll generate a spurious error from line 95 (`DV_CHECK_EQ_FATAL(pending_a_req.exists(cloned_req.a_source), 0)`). @weicaiyang: Does that sound right to you?

By design, a back-to-back request to the same address with the same a_source (i.e. the same host) cannot occur (@weicaiyang, @eunchan). The TL agent will will always randomize `a_source` such that it does not match a pending request that has not yet completed (i.e. mimicking multiple hosts accessing the same device). See here:
https://github.com/lowRISC/opentitan/blob/7252f1753991938e0109767b3d8c029c442681e3/hw/dv/sv/tl_agent/seq_lib/tl_host_base_seq.sv#L12

2021-06-21 05:34 UTC, weicaiyang reviewed
sorry, I misunderstood that we changed to always have ADAD order.
Looks like we just fixed the race condition of A(2) and D(1), when both are done in the `cycle 1`. And we want to the order to process the item is D(1) -> A(2). 

```
    Cycle | A channel   | D channel
   ---------------------------------
    0     | Get FOO (1) |
    1     | Get FOO (2) | FOO rdata (1)
    2     |             | FOO rdata (2)
```

It looks like a nice enhancement to me.
But we may want to monitor the regression to see if this change affects some existing scb. If scb has cycle accurate check and it already relies on on the simulator's scheduling algorithm, this change may break it.

2021-06-21 05:34 UTC, weicaiyang commented on hw/dv/sv/cip_lib/cip_base_scoreboard.sv
> +      join_none
need to store `i` to another local variable, otherwise, all the threads use the same value at highest index.
```
   foreach (cfg.m_tl_agent_cfgs[i]) begin
      automatic string ral_name = i;
      fork
        process_tl_fifos(ral_name, tl_a_chan_fifos[ral_name], tl_d_chan_fifos[ral_name]);
      join_none
```

2021-06-21 05:35 UTC, weicaiyang commented
> > @sriyerg: Actually, reading the tl_monitor code a bit more carefully, what happens if there are two back-to-back reads at a the same address, where the D response is delayed for a few cycles? If I understand the code correctly, we'll generate a spurious error from line 95 (`DV_CHECK_EQ_FATAL(pending_a_req.exists(cloned_req.a_source), 0)`). @weicaiyang: Does that sound right to you?
> 
> By design, a back-to-back request to the same address with the same a_source (i.e. the same host) cannot occur (@weicaiyang, @eunchan). The TL agent will will always randomize `a_source` such that it does not match a pending request that has not yet completed (i.e. mimicking multiple hosts accessing the same device). See here:
> https://github.com/lowRISC/opentitan/blob/7252f1753991938e0109767b3d8c029c442681e3/hw/dv/sv/tl_agent/seq_lib/tl_host_base_seq.sv#L12

Agree with Sri, that check looks right to me. And seems like it isn't related to the change in this PR.

2021-06-21 05:52 UTC, sriyerg commented
> Hi both.
> 
> @sriyerg: I don't think your answer is really addressing what this PR is about. The problem isn't that the D channel handling doesn't understand what the A channel transaction was doing. The problem is that it might need to know something about the state of the _block_ when the A channel transaction came in.
> 
> @weicaiyang: I'm not completely sure I've understood your message, but in the example you've put forward, I think the scoreboard would see things in the order you want (with or without this patch!). The only time that this patch should have any effect is when an A and D transaction come in _on the same cycle_. With the code in master, the ordering of events at the scoreboard depends on the simulator's scheduling algorithm. With this patch, it will always be D then A.

Right - the TL monitor already internally matches the D channel response with the corresponding A channel request that _must_ have occurred in the past. We surely don't want to be seeing a random response occurring on D channel with the corresponding req on A channel missing! As a bonus, the D channel packet the monitor writes tacks on the A channel information after the matching is done so that the external scoreboards have the full picture and dont have to worry about matching responses with requests (as you do in this PR). 

If you are developing a cycle accurate model (which is almost always a bad idea!) of the design, then you my need to predict the reads / writes on the A channel packet to align it perfectly with the design. There may also be cases where you may need to know the state of the block when the A channel req came in (as you said so), which you would maintain in your scoreboard. Eventually when the D channel resp arrives, you ought to be using the source ID to match it instead (i.e. rely on TLUL spec).

2021-06-21 06:19 UTC, sriyerg requested changes
IMO there should not be a need to guarantee A-D ordering when you can match the D channel rsp with the A channel req using the source ID. By spec, we cannot have 2 outstanding requests with the same source ID. 

The addition of #1 delay likely worsens the runtime perf (we should confirm this). The IP scoreboard has access to both, A channel and D channel packets, so I am not sure if there is really a need to touch the base class.

2021-06-21 08:19 UTC, rswarbrick commented
Ok, looks like this won't fly. I'll add something careful to the IP-level scoreboards I'm writing and let's hope we don't trigger the race condition for anyone else. If we do, maybe someone will rediscover this solution.

2021-06-21 08:19 UTC, closed without merging