[csrng/dv] csrng_cmds_test/instantiate cmd
lowRISC/opentitan pull request #7208
Opened 2021-07-01 12:51 UTC by senelson7

Requires fix in PR #7196 

Signed-off-by: Steve Nelson <steve.nelson@wdc.com>

2021-07-01 16:23 UTC, mwbranstad requested changes
Need to add additional check or TODO on internal state checking.

2021-07-01 16:23 UTC, mwbranstad commented on hw/dv/sv/csrng_agent/csrng_item.sv
> +    clen inside {[0:12]};
Refresher - "inside" includes 0 and 12, not 1 to 11, correct?

2021-07-01 16:23 UTC, mwbranstad commented on hw/ip/csrng/dv/env/csrng_env_cfg.sv
> +    end
Need to check for the instance status bit, fips status, etc. or add TODO to check.

2021-07-01 17:08 UTC, senelson7 commented on hw/dv/sv/csrng_agent/csrng_item.sv
> +    clen inside {[0:12]};
Correct

2021-07-01 17:34 UTC, senelson7 commented on hw/ip/csrng/dv/env/csrng_env_cfg.sv
> +    end
Bits added and checked

2021-07-01 18:09 UTC, mwbranstad approved these changes

2021-07-01 18:09 UTC, mwbranstad commented on hw/ip/csrng/dv/env/csrng_env_cfg.sv
> +    hw_status     = rdata[0];
looks good thanks.

2021-07-08 15:41 UTC, rasmus-madsen approved these changes
LGTM - only very nit comments I think this can be merged

2021-07-08 15:41 UTC, rasmus-madsen commented on hw/dv/sv/csrng_agent/csrng_item.sv
> +    solve clen before cmd_data_q;
this is fine - but you just put in the post_randomize() function and not have the constraints solver worry

2021-07-08 15:41 UTC, rasmus-madsen commented on hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
> +//  bit [csrng_pkg::CSRNG_CMD_WIDTH-1:0]   cmd_data_q[$];
do you need this later or can it be removed

2021-07-08 15:43 UTC, merged