[spi, dv] Updated spi agent to support SPI_host
lowRISC/opentitan pull request #8829
Opened 2021-10-22 08:46 UTC by rasmus-madsen

This Commit contains updates to the SPI agent that will make it support the spi host.
the main difference is the updated spi_device_seq and the new extended sequence.
this is needed for the Device to recognize a set of commands and respond proberly.

this could at some point in time be further developed into a spi device BFM.

2021-11-01 12:02 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +              end
@weicaiyang I don't see how your solution would work - the next item is never an address - it is either more data or a new command. so doing what you suggest would require an additional branch in the address state - to skip the address state.

either way this sequence will be updated further as  spi host is going into V2 - so I think we are maybe spending a bit too much time on a small implementation detail ?

2021-11-01 12:12 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/spi_device_driver.sv
> +      Dual:     cfg.vif.sio[1:0] <= sio_bits[1:0];
fixed

2021-11-01 12:13 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/spi_device_driver.sv
> +  virtual task send_data_to_sio(ref spi_mode_e mode, input logic [3:0] sio_bits);
fixed

2021-11-01 12:22 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/spi_if.sv
> +  task automatic get_data_from_sio(ref spi_agent_pkg::spi_mode_e mode, output bit sio_bits[]);
fixed

2021-11-01 12:23 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/spi_item.sv
> +    txt = {txt, $sformatf("\n ----| Dummy Sck Lengtht: \t%d ns",  dummy_sck_length_ns) };
fixed

2021-11-01 12:23 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/spi_item.sv
> +      txt = {txt, $sformatf("%0h", data[i])};
fixed

2021-11-01 22:40 UTC, weicaiyang commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +              end
This part looks a bit replicated. Maybe we could enhance it later.

2021-11-01 22:40 UTC, weicaiyang approved these changes
LGTM, thanks

2021-11-01 23:21 UTC, sriyerg commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +class spi_device_extended_seq extends spi_device_seq;
`spi_device_extended_seq` provides no clue as to what this sequence does. It is already evident that it an extension of `spi_device_seq` by virtue of the `extends` keyword. 

How about `spi_device_cmd_resp_seq`, given that it responds to command requests from the host?

2021-11-01 23:22 UTC, sriyerg requested changes

2021-11-01 23:22 UTC, sriyerg commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +      send_req(rsp_q);
Should be `send_rsp()`

2021-11-01 23:44 UTC, sriyerg requested changes

2021-11-01 23:44 UTC, sriyerg commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +  endfunction : swap_byte_order
I wonder if we could invoke `dv_utils_pkg::endian_swap_byte_arr()` directly wherever needed, rather than add this wrapper function.

2021-11-01 23:44 UTC, sriyerg commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +  bit [15:0]       clkdiv[MAX_CS];
nit: for readability.
```suggestion
  bit [3:0]        csn_lead[MAX_CS];
  bit [3:0]        csn_trail[MAX_CS];
  bit [3:0]        csn_idle[MAX_CS];
  bit [15:0]       clk_div[MAX_CS];
```

2021-11-01 23:44 UTC, sriyerg commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +  bit [15:0]       clkdiv[MAX_CS];
The `clkdiv` seems unused.

2021-11-01 23:44 UTC, sriyerg commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +  virtual task send_req(ref spi_item item_q[$]);
Should be `send_rsp`.

2021-11-01 23:44 UTC, sriyerg commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +  endtask
This waits for SPI request to appear from host, then loops back the same as response back to host. Isn't SPI "full duplex" where host and device can independently sent simultaneously?

The base SPI device sequence should populate `rsp_q` with random junk bytes independent of the `req` thread to facilitate this.

2021-11-01 23:44 UTC, sriyerg commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +  virtual task send_req(ref spi_item item_q[$]);
IMO, `send_rsp` should wait on in independent `rsp_q` which should be a class attribute, rather than passed as task arg. The class attribute can be manipulated at runtime by other threads.

2021-11-01 23:44 UTC, sriyerg commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +  endtask
Should be called `generate_rsp_q()` that generates random responses forever, as and when `rsp_q` size is approaching 0. 

The extended class `spi_device_extended_seq` will then override this task to generate more meaningful responses.

2021-11-01 23:44 UTC, sriyerg commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +      spi_item  req;
```suggestion
      spi_item req;
```

2021-11-01 23:44 UTC, sriyerg commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +          end
Should there be an else clause where you would throw an error? That would indicate your FSM is out of whack and help debug issues (if they exist) quicker.

2021-11-01 23:54 UTC, sriyerg commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +              req = new();
IMO this clause can be written like this:
```systemverilog
              rsp = spi_item::type_id::create("rsp");
              `DV_CHECK_RANDOMIZE_FATAL(rsp)
              rsp_q.push_back(rsp);
```

2021-11-02 15:11 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +              req = new();
@sriyerg I don't see any reason for registering the item with the factory.
also at some point I want to be able to read back the write data - in which case the current solution will be cleaner IMO

2021-11-02 15:13 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +          end
@sriyerg the current idea is just to ignore anything that is not a valid command - not to throw an error.
but If you feel it is needed I'd be happy to add a warning

2021-11-02 15:13 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +      spi_item  req;
fixed

2021-11-02 15:51 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +  endtask
@sriyerg I am not sure I follow your suggestion here.
the task above is used to fetch incoming write transactions, so naming it something with rsp does not seem right.

also as per my answer above, IMO we do not want to generate random responses forever - WDYT

2021-11-02 16:05 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +  virtual task send_req(ref spi_item item_q[$]);
@sriyerg I am ok with the name change, but what are the benefits of changing the queue to a class member?
isn't that just a question of preference?
I like that I can call this task with different queues vs having to copy my local queue into the class queue before calling the task

2021-11-02 16:08 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +  bit [15:0]       clkdiv[MAX_CS];
fixed

2021-11-02 16:09 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +  endfunction : swap_byte_order
this is legacy from the previous SPI_HOST dv.
I will add a to do to check once I start verify endianess

2021-11-02 16:10 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +      send_req(rsp_q);
fixed

2021-11-02 16:11 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +class spi_device_extended_seq extends spi_device_seq;
or spi_device_simple_bfm_seq?

2021-11-02 17:33 UTC, sriyerg commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +          end
My question is related `item.first_byte`. Is it acceptable for it to be 0 while you are in the `SPI_IDLE` state?

2021-11-02 17:33 UTC, sriyerg commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +              req = new();
It is useful for other testbenches to be able to factory override `spi_item` with `extended_spi_item` with additional functionality / settings / constraints. We do this for `uart_item` at the full chip. 

I think my suggested code is functionally equivalent to yours.

2021-11-02 17:33 UTC, sriyerg commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +  endtask
Yes, but this base device vseq does not follow the standard protocol, the extended seq does.

2021-11-02 17:33 UTC, sriyerg commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +  endtask
The base device seq does not cater to any specific protocol. It just keeps the device driver populated with junk data. The extended sequences can override base class tasks to follow a specific protocol. 

I think it is fine to keep this function since it serves a different purpose. However, I will suggest renaming it to `get_next_req(spi_item req)`. Note that class objects are passed by ref by default so the ref keyword is not needed.

2021-11-02 17:33 UTC, sriyerg commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +  endfunction : swap_byte_order
I don't see this in upstream. This is the first time this method is added. It is only invoked in `spi_agent_cfg`. It should be easy to just search and replace...

2021-11-02 17:33 UTC, sriyerg commented on hw/dv/sv/spi_agent/spi_item.sv
> +      if (i%8 == 0) txt = {txt, "\n"};
super nit: 
```systemverilog
      if (!i[2:0]) txt = {txt, "\n"};
```

2021-11-02 17:33 UTC, sriyerg commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +  endfunction
How about:
```systemverilog
  function spi_cmd_e get_cmd(bit[7:0] data);
    spi_cmd_e cmd;
    `downcast(cmd, data, "Illegal Command seen, check CSB is not high at unexpected time")
    return cmd;
  endfunction
```

2021-11-02 19:46 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +  endfunction
sure that will work too.. in the end I think Illegal Command seen is enough.
the rest was mostly for my self while figuring out what could go wrong

2021-11-02 19:48 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/spi_item.sv
> +      if (i%8 == 0) txt = {txt, "\n"};
sure - it's DV so don't think it makes much difference.

2021-11-02 19:54 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +          end
@sriyerg ahh I can see I add to the confusion with my answer - sorry about that.
it should throw a fatal if the command is invalid - but only if `item.first_byte == 1`
anything else is considered garbage and ignored.

2021-11-02 19:55 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +              req = new();
ok - that is a good argument for changing it - I agree it was functionally the same.

2021-11-02 20:17 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +              req = new();
don we still need to clone it?

2021-11-02 20:47 UTC, rasmus-madsen commented
@sriyerg I think I have addressed all your comments, thank you for the very detailed review

2021-11-12 18:53 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +class spi_device_extended_seq extends spi_device_seq;
fixed

2021-11-12 18:59 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +  endtask
@sriyerg you suggestion has some implications.
since the device sequence has no knowledge of the spi mode - it will try to send data when in DUAL and QUAD mode which is not allowed.
so we would either need to redesign the device sequence or somehow mark it as only valid for standard mode.

either way I think this can be pushed to another discussion outside of this PR.
WDYT?

2021-11-12 19:00 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +  endtask
fixed

2021-11-12 19:03 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_extended_seq.sv
> +              req = new();
fixed

2021-11-17 05:14 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +  endfunction : swap_byte_order
Just to elaborate on this
the data i n the spi_item is of type dynamic array and the macro is a queue of packed array - so not directly useable as is. 
I added a todo that can be looked into later if anyone has time

2021-11-17 17:42 UTC, weicaiyang commented on hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv
> +        SPI_IDLE: begin
can you address this one?

2021-11-17 17:43 UTC, weicaiyang commented
@sriyerg please take a look at this PR

2021-11-17 22:58 UTC, sriyerg commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +  endfunction : swap_byte_order
It should be directly usable - just wrap in curly braces to assign to a queue var directly: `{dv_utils_pkg::endian_swap_byte_arr()}`.

2021-11-17 23:04 UTC, sriyerg commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +  endtask
The SPI device seq has the handle to the `cfg` object via the sequencer, so it does know what SPI mode we are currently running with. If single mode, then you could make the change I am requesting so that it meets the SPI specification. For dual and quad, we need to understand what the SPI specification expects. The SPI agent must align with the SPI specification.

2021-11-17 23:07 UTC, sriyerg commented on hw/dv/sv/spi_agent/spi_agent_pkg.sv
> +  typedef enum bit [7:0] {
I am not sure if this is needed. The `spi_mode_e` already qualifies the mode. You could just use `dv_utils_pkg::bus_op_e` to qualify a read or a write op.

2021-11-17 23:07 UTC, sriyerg commented on hw/dv/sv/spi_agent/spi_agent_pkg.sv
> +    RsvdSpd  = 2'b11   // RFU
Should we call this `Invalid` instead?

2021-11-18 09:34 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +  endfunction : swap_byte_order
I have never seen that notation without an assignment ( = )
anyway I tested it and it does not compile

2021-11-18 09:35 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +  virtual task send_req(ref spi_item item_q[$]);
can I assume this is resolved?

2021-11-18 09:41 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +  endtask
The spi mode is not a fixed configuration - but fluent.
you could easily imagine one transaction in one mode and then the next using another mode.
in fact this is expected behavior depending on data access or register access.

either way I think we are arguing about detail in a sequence no one is currently using.
I think @weicaiyang added this when he did the spi_agent for the SPI_DEVICE tests to have something basic in place for the HOST tests also.

my first idea was to complete remove the spi_device_seq, but then I thought it would be ok to keep it for very basic behavior that we could extend at a later stage if we need different behavior than the command_rsp sequence.

IMO it is perfectly ok to leave as is - with the expectation that anyone who needs to talk to a spi_device will extend it and customize the behavior!

2021-11-18 09:43 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv
> +        SPI_IDLE: begin
@weicaiyang I believe I already fixed it?

2021-11-18 09:51 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/spi_agent_pkg.sv
> +  typedef enum bit [7:0] {
@sriyerg these are needed.
the spi_mode_e/and the bus_op_e are settings

the spi_cmd_e, is a look up table of legal commands used to check if an incoming cmd on spi is a legal command.
if one wanted to do a full BFM of the spi_fslah winbond W25Q that we are using as target device
you would extend this list with 
commands for instructions and register access (page 27-29)
but for now it is just very basic

2021-11-18 09:52 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/spi_agent_pkg.sv
> +    RsvdSpd  = 2'b11   // RFU
Tung Chose this name - not sure it matters, IMO reserved is fine

2021-11-18 09:55 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv
> +        SPI_IDLE: begin
I think there is a problem with the but - the request -review doesn't work for that one.
so I think that is why it still seems listed as an issue. but I double checked it was fixed already

2021-11-18 22:08 UTC, weicaiyang commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +  endtask
This is a good point. 
For single mode, TX/RX are sending in parallel, so this req-rsp sequence handshake doesn't work for it.
For dual/quad mode, it has cmd, addr and data. cmd and addr can be captured in req item, but rsp is only needed when this transaction requires return data from device.

So we probably need to update this sequence when testing spi_host. If you want to get this PR in first, then at least capture what we have discussed here in a TODO.

2021-11-22 10:17 UTC, rasmus-madsen commented
@sriyerg could you review the last comments thank :D

2021-11-22 18:12 UTC, weicaiyang commented on hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv
> +        SPI_IDLE: begin
the robot check is passing now. The reason that it still shows here is because this part of codes haven't been changed. Let me resolve this conversation.

2021-11-22 18:15 UTC, weicaiyang commented on hw/dv/sv/spi_agent/seq_lib/spi_device_seq.sv
> +  endtask
@rasmus-madsen what do you think about this?

2021-11-23 20:35 UTC, weicaiyang commented
@sriyerg can you check what comments are still unaddressed?

2021-12-06 20:05 UTC, sriyerg approved these changes

2021-12-07 14:09 UTC, merged