[rom_cntrl, dv] Test to verify successful rom check
lowRISC/opentitan pull request #9330
Opened 2021-11-22 17:13 UTC by prajwalaputtappa

Following files have been added/ modified in this commit:
1. rom_ctrl_chk_successful_vseq: Sequence that writes the top 8 address
spaces to ensure we have the expected digest matching with KMAC digest.
2. kmac_app_device_seq: It assigns the rsp_digest_share0/1 fields from the values
present in kmac_app_agent_cfg. Randomization of the rsp_digest_share0/1
fields has been removed.
3. rom_ctrl_env: Sets the value of rsp_digest_share0/1 in
kmac_app_agent_cfg.
4. kmac_app_agent_cfg: rsp_digest_share0/1 fields have been added.

2021-11-23 16:55 UTC, rswarbrick commented
This PR contains a merge commit. Could you clean things up? (I think you probably just need to do a hard reset to the commit before the merge, then a rebase: if the output of `git log` is confusing, it's probably clearer with `gitk`)

2021-11-23 16:58 UTC, rswarbrick requested changes

2021-11-23 16:58 UTC, rswarbrick commented on hw/dv/sv/kmac_app_agent/seq_lib/kmac_app_device_seq.sv
> +      rsp.rsp_digest_share1 = cfg.rsp_digest_share1;
This can't be committed. I think what you probably want is to put a flag into the configuration ("fixed_digest", maybe?). Then add constraints to `randomize_item` that force `rsp_digest_share*`.

2021-11-24 22:48 UTC, rswarbrick commented on hw/dv/sv/kmac_app_agent/kmac_app_item.sv
> -
I don't feel strongly about things like this, but I'd probably avoid whitespace tweaks in someone else's code (unless fixing something that's obviously wrong!)

2021-11-24 22:48 UTC, rswarbrick commented on hw/dv/sv/kmac_app_agent/kmac_app_item.sv
> +
There are still trailing spaces here.

2021-11-24 22:48 UTC, rswarbrick commented on hw/dv/sv/kmac_app_agent/seq_lib/kmac_app_device_seq.sv
> +  )
We seem to have lost a column of indentation here (which is why the diff looks so big). Also, missing space after the `if`.

2021-11-24 22:48 UTC, rswarbrick commented on hw/dv/sv/kmac_app_agent/kmac_app_agent_cfg.sv
> +  bit set_digest;
I don't think this should mention rom_ctrl at all: this is a (somewhat) generic agent for the KMAC app interface. Also can you expand the comment to explain what `set_digest` does?

2021-11-24 22:48 UTC, rswarbrick commented on hw/ip/rom_ctrl/dv/env/rom_ctrl_env.sv
> +  rand bit [kmac_pkg::AppDigestW-1:0] rsp_digest_share1;
Since the corresponding fields in the KMAC agent config are randomised, I don't think you actually need these any more?

2021-11-24 22:48 UTC, rswarbrick commented on hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_chk_successful_vseq.sv
> +    bit [31:0] mem_data;
Nit: Probably best either to align everything or not. (I'd suggest just removing the multiple spaces before "digest")

2021-11-24 22:50 UTC, rswarbrick commented
@weicaiyang: This PR touches the KMAC app agent because the sequence on the rom_ctrl side needs to be able to predict the digest that we're going to get as a response. Would you mind taking a look at this? I want to make sure we're not messing up your code! :-)

2021-11-24 23:30 UTC, weicaiyang commented on hw/dv/sv/kmac_app_agent/kmac_app_agent_cfg.sv
> +  bit set_digest;
if we prefer to supply the digest through cfg, I would suggest to create a queue like push_pull_agent. Once queue is not empty, use it, otherwise, use random value.

https://github.com/lowRISC/opentitan/blob/399af406069a3123f13380368bef66db0f17a62a/hw/dv/sv/push_pull_agent/push_pull_agent_cfg.sv#L58

2021-11-24 23:30 UTC, weicaiyang commented on hw/ip/rom_ctrl/dv/env/rom_ctrl_env.sv
> +    cfg.m_kmac_agent_cfg.rsp_digest_share1 = rsp_digest_share1;
if you just need some random values for digest, existing sequence already does that.

2021-11-24 23:32 UTC, rswarbrick commented on hw/ip/rom_ctrl/dv/env/rom_ctrl_env.sv
> +    cfg.m_kmac_agent_cfg.rsp_digest_share1 = rsp_digest_share1;
The problem is that the existing sequence picks the random values as it responds with them. Unfortunately, that's miles after we've picked our ROM contents and we need to ensure that the top few words of the ROM match the digest that comes back from KMAC.

2021-11-24 23:32 UTC, rswarbrick commented on hw/dv/sv/kmac_app_agent/kmac_app_agent_cfg.sv
> +  bit set_digest;
Ooh! That's a much nicer way of doing things!

2021-11-26 14:22 UTC, prajwalaputtappa commented on hw/dv/sv/kmac_app_agent/kmac_app_item.sv
> -
I've reset the entire file to a previous version.

2021-11-26 14:24 UTC, prajwalaputtappa commented on hw/dv/sv/kmac_app_agent/seq_lib/kmac_app_device_seq.sv
> +  )
Added the necessary changes

2021-11-26 18:06 UTC, prajwalaputtappa commented on hw/dv/sv/kmac_app_agent/kmac_app_agent_cfg.sv
> +  bit set_digest;
I've made necessary changes

2021-11-26 18:07 UTC, prajwalaputtappa commented on hw/ip/rom_ctrl/dv/env/rom_ctrl_env.sv
> +  rand bit [kmac_pkg::AppDigestW-1:0] rsp_digest_share1;
This code doesn't exist anymore

2021-11-29 16:13 UTC, rswarbrick commented on hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv
> +    randomize(rsp_digest_share0);
This should probably use the `DV_CHECK_STD_RANDOMIZE_FATAL` macro (which checks that randomisation succeeded). Also, I don't think there's any need for `rsp_digest_share0` and `rsp_digest_share1` to be fields: can't they just be locals in this function?

2021-11-29 19:21 UTC, weicaiyang commented on hw/dv/sv/kmac_app_agent/kmac_app_agent_cfg.sv
> +  endfunction
Agree, we can create a struct for these 2 shares.
```
  typedef struct packed {
    logic [AppDigestW-1:0] digest_share0;
    logic [AppDigestW-1:0] digest_share1;
  } rsp_digest_t;
```

2021-11-30 09:41 UTC, prajwalaputtappa commented on hw/dv/sv/kmac_app_agent/kmac_app_agent_cfg.sv
> +  endfunction
Changed accordingly

2021-11-30 19:03 UTC, weicaiyang approved these changes

2021-12-01 17:16 UTC, merged