[clkmgr] Fix documentation ambiguity around clock switching
lowRISC/opentitan pull request #9348
Opened 2021-11-23 01:55 UTC by tjaychen

- Documentation fix specifically for clkmgr in #9273

Signed-off-by: Timothy Chen <timothytim@google.com>

2021-11-30 07:47 UTC, matutem requested changes

2021-11-30 07:47 UTC, matutem commented on hw/ip/clkmgr/data/clkmgr.hjson.tpl
> +            no impact.
```suggestion
            When the current value is not kMultiBitBool4True, writing a value of kMultiBitBool4True
            selects external clock as clock for the system, and writing any other value has no
            impact.
```

2021-11-30 07:47 UTC, matutem commented on hw/ip/clkmgr/data/clkmgr.hjson.tpl
> +            impact.
```suggestion
            When the current value is kMultiBitBool4True, writing a value of kMultiBitBool4False
            selects internal clock as clock for the system, and writing any other value has no
            impact.
```

2021-11-30 07:47 UTC, matutem commented on hw/ip/clkmgr/data/clkmgr.hjson.tpl
> +            is in life cycle TEST, DEV or RMA states when hardware debug is enabled.
https://docs.opentitan.org/doc/security/specs/device_life_cycle/ seems to say dft is not enabled in DEV state, so

```suggestion

            While this register can always be programmed, it only takes effect when DFT functions
            are enabled, which is in life cycle TEST_UNLOCKED or RMA states.
```

2021-11-30 23:14 UTC, tjaychen commented
updated! please have a look.

2021-12-01 17:55 UTC, matutem approved these changes
LGTM

2021-12-01 17:56 UTC, merged