[ entropy_src, dv ] Support for all phases of entropy generation
lowRISC/opentitan pull request #9451
Opened 2021-12-01 06:05 UTC by martin-lueker

Now supports conditioning bypass, boot phase, startup phase & continuous phase.

- This commit adds functionality to the entropy_source environment to predicte the
current phase of entropy_src operation: BOOT, STARTUP or CONTINUOUS. Tracking
this phase is essential both for scoreboarding and for planning sequences.

- RNG Sequence generation is redesigned to assign certain AST-RNG outputs to
particular entropy_src output seeds.  Each seed is tracked by a particular "seed
index", which can be used to predict what phase the entropy source will be in
when it receives that seed.  Knowing the phase is important, as it also indicates
how much RNG data must be provided to generate the this seed..

- The progression from one phase to another can be halted by health test failures.
Therefore this commit introduces a stub of a function to predict whether a particular
RNG sub-sequence will fail a health-check.  This function is currently unimplemented.
For the purposes of sequence generation, it is not important to know which health test
will fail, only that _some_ health test will fail.  Thus it is envisioned that
the stub that is currently in entropy_src_base_vseq.sv will eventually be constructed
from smaller functions, one for each type of health check.
  - Note: these fine-grain health check functions will be needed for both
    scoreboarding and sequence generation purposes.

- Includes various configuration registers which will be useful for controlling
the size of the health-check windows, via CSRs.

Signed-off-by: Martin Lueker-Boden <martin.lueker-boden@wdc.com>

2021-12-01 15:24 UTC, mwbranstad commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_smoke_vseq.sv
> +  int rng_count = 0;
I am guessing that this overhaul of infrastructure affects the smoke test long term, but should it change right away? Since CI passed, smoke must run ok now. Given that, I suppose the risk is low to update it.

2021-12-01 15:35 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_smoke_vseq.sv
> +  int rng_count = 0;
Hi Mark, 
   Smoke test does indeed pass.  I could leave the smoke test alone (and in fact I did do all my original testing in an extra bogus test), though if we did that how should I demonstrate that these changes actually work?

2021-12-02 01:30 UTC, weicaiyang commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +    status = 1;
nit: not needed, as it will be assign value at line 114

2021-12-02 01:30 UTC, weicaiyang commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +      load_rng_push_seq_single_seed(i);
this function has a return value. not sure how you want to use it.

2021-12-02 01:30 UTC, weicaiyang commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +      window_sample = generate_rng_data(window_size/4);
```suggestion
      window_sample = generate_rng_data(window_size / 4);
```

2021-12-02 09:33 UTC, rasmus-madsen requested changes
@martin there are some comments from @weicaiyang and I there needs to be addressed before this can be approved

2021-12-02 09:33 UTC, rasmus-madsen commented on hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
> +  function automatic phase_t convert_seed_idx_to_phase(int seed_idx, bit bypass, bit boot_disable);
@martin-lueker 
the bypass bit is not used!

2021-12-02 09:33 UTC, rasmus-madsen commented on hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
> +   end
nit indentation

2021-12-02 09:33 UTC, rasmus-madsen commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +  int total_seed_cnt = 1;
this seem like something that you want to put in the seq_cfg  so it can be randomized at some point?

2021-12-02 09:33 UTC, rasmus-madsen commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +    // Register write enable
do you need to check main_sm_idle before actually writing to DUT registers?

2021-12-02 09:33 UTC, rasmus-madsen commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +    end
this code will never be reached as the do-while will continue until status=0

2021-12-02 09:33 UTC, rasmus-madsen commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +    return status;
will always return 0

2021-12-02 09:33 UTC, rasmus-madsen commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +      load_rng_push_seq_single_seed(i);
and the return value is always 0... maybe make the function void?

2021-12-02 09:33 UTC, rasmus-madsen commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +  endtask
we generally do not have a body task in the base sequence. 
the base sequence is not meant to be used stand-alone so the body is not needed and should be set in a higher-level sequence.

2021-12-02 09:33 UTC, rasmus-madsen commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_smoke_vseq.sv
> +  int rng_count = 0;
I think either is fine - the smoke test should be basic, so what was there was demostrating basic DUT behavior.
but I also think it is perfectly ok to update the smoke sequence to use the new environment functions to demonstrate the same behavior.
the more advanced sequences should for sure due this.
so I am ok with this update

2021-12-02 16:39 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
> +  typedef enum { BOOT, STARTUP, CONTINUOUS } phase_t;
Agreed, I was thinking much the same when I started using this in the scoreboard.

2021-12-02 16:39 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
> +  function automatic string phase_to_string(phase_t phase);
Ah thanks for pointing this out!

2021-12-02 16:39 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
> +    // TODO move to package
Hahaha, leftover from a previous edit.  Thanks for the catch.

2021-12-02 16:41 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +      result.push_back(4'b0);
The base sequence is meant to be trivial.   I could also leave this as a virtual function unimplemented if you prefer.

2021-12-02 16:42 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +  int total_seed_cnt = 1;
Ah that would make sense.  Good idea.

2021-12-02 16:44 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +    end
There is a break statement in the previous while loop.

2021-12-02 16:45 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +    return status;
There is a break in the previous while loop to detect the fact that this RNG sequence will not be able to actually make a seed (and that is okay, the sequence just needs to know).

2021-12-02 16:54 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +  endtask
This is common functionality that is needed by all future sequences, so where should I put it?

2021-12-02 16:57 UTC, senelson7 commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +  endtask
In the base sequence as a function.

2021-12-02 17:07 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +      load_rng_push_seq_single_seed(i);
Again, the return value is not always 0.

I'd like to use it to let sequences know that they are about to feed unacceptable entropy into the entropy_src, and so they should be aware that they shouldn't expect to get total_seed_cnt seeds out.

Frankly I do have some questions about how to deal with verifying this block, as it is by design meant to frequently discard inputs with very little feedback to the user.  (This can happen because of a failing health check or simply if it doesn't need any more data at the moment.)   

I'm currently trying to figure out how to properly manage this for this sort of block.  Maybe someone can help?  The big issue is that the push_pull_agent for the rng wants to know before it starts how many seq_items it will need for a certain sequence of output seeds.

However in certain cases, it is impossible to know whether a candidate seed will be dropped, in such cases I imagine it will be hard to prevent the sequences from timing out.

2021-12-02 17:57 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +      load_rng_push_seq_single_seed(i);
Weicai: back to your original question, I would can make this so that the function returns the number of seeds that the sequence should _expect_ to get out.  

NOTE to Rasmus: this will be different than your proposed cfg variable, that will indicate how many seeds the test should _attempt_ to generate.   

The _attempted_ seed count, _excpected_ seed count, and _final_ seed count could however all be different because of failed health checks or dropped seeds.  

As far as I can tell now, both the sequence and the scoreboard can predict how many seeds will fail health checks, but    there we are having debate as to how to monitor or deal with the unpredictable number of dropped seeds.

2021-12-02 19:23 UTC, weicaiyang commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +      load_rng_push_seq_single_seed(i);
> Weicai: back to your original question, I would can make this so that the function returns the number of seeds that the sequence should expect to get out.

This sounds good. 
We could do some basic check in sequence, and let scb/monitor do the completed check. Not really sure how the seeds and health check work. maybe the IP designer owner can help to sort it out.

2021-12-03 01:04 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
> +  typedef enum { BOOT, STARTUP, CONTINUOUS } phase_t;
```suggestion
  typedef enum { BOOT, STARTUP, CONTINUOUS } entropy_phase_e;
```

2021-12-03 01:05 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
> +    // TODO move to package
```suggestion
```

2021-12-03 01:28 UTC, martin-lueker reviewed
Converting comments to suggestions for online edit.

2021-12-03 01:28 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
> +  endfunction
```suggestion
```

2021-12-03 01:28 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +    status = 1;
I guess that's true with the do-while.

2021-12-03 01:28 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +    status = 1;
```suggestion
```

2021-12-03 01:28 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +
```suggestion
```

2021-12-03 01:28 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +  int total_seed_cnt = 1;
```suggestion
BROKEN: total_seed_cnt to be moved to cfg
```

2021-12-03 01:28 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +    // Register write enable
```suggestion
    // Register write enable
    // TODO Do we need to check main_sm_idle before writing DUT registers?
```

Adding as a TODO.

2021-12-03 01:28 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
> +  function automatic phase_t convert_seed_idx_to_phase(int seed_idx, bit bypass, bit boot_disable);
```suggestion
  function automatic phase_t convert_seed_idx_to_phase(int seed_idx, bit boot_disable);
```
So it would seem, I guess that is only needed for estimating window_size (not that the phase matters at all in bypass mode)... or does it?  It might for health tests.  I'll remove this anyhow.

2021-12-03 01:28 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
> +        return "???";
Noted.  Thanks.

2021-12-03 01:28 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +  virtual task load_rng_push_seq();
```suggestion
  virtual function int load_rng_push_seq();
    int seed_cnt = 0;

```

2021-12-03 01:28 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +      load_rng_push_seq_single_seed(i);
```suggestion
      seed_cnt += (load_rng_push_seq_single_seed(i) == 0);
```

2021-12-03 01:31 UTC, martin-lueker reviewed
More suggestions.

2021-12-03 01:31 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +  endtask;
```suggestion

  return seed_cnt;
  endfunction
```

2021-12-03 05:13 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +      result.push_back(4'b0);
Changed to a uvm_fatal message.

2021-12-03 05:20 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
> +  endtask
You mean as function with a different name?

Done with new task:init_rng_push_seq.  (Though FWIW, having a virtual body task, and calling it in each sub-task should work just fine, and serve the same purpose)  Note this apparently cannot be done in a function as the push_seq initialization routines have some delays, so this has to be a base sequence task and not a function.

2021-12-03 05:27 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
> +   end
Fixed.

2021-12-03 15:00 UTC, mwbranstad commented on hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv
>         m_csrng_agent_cfg;
Same comment as above on package reference.

2021-12-03 15:29 UTC, rasmus-madsen approved these changes
LGTM

2021-12-03 15:38 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv
>         m_rng_agent_cfg;
As suggested by Rupert in the other PR, that package has now been imported at the top.

2021-12-03 15:39 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv
>         m_csrng_agent_cfg;
See answer above.

2021-12-03 15:39 UTC, martin-lueker commented on hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv
>         m_rng_agent_cfg;
"Other PR" being #9466

2021-12-03 18:13 UTC, weicaiyang approved these changes
LGTM

2021-12-03 18:13 UTC, merged