[spi_device] Passthrough command filtering
lowRISC/opentitan pull request #9834
Opened 2021-12-28 11:16 UTC by kosta-kojdic

Added scenario for filtering out randomized opcode commands. Checking for filtered out data. Added capability to tb and spi_agent for getting data from passthrough_o. Driving passthrough_i.

Signed-off-by: Kosta Kojdic <kosta.kojdic@ensilica.com>

2021-12-28 21:37 UTC, weicaiyang commented on hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_cmd_filtering_vseq.sv
> +    ral.control.mode.set(2'h2); // Passthrough Mode
perhaps create an enum for the `mode`

2021-12-28 21:37 UTC, weicaiyang commented on hw/ip/spi_device/dv/tb/tb.sv
> +    .passthrough_o  (pass_out  ),
IIUC, we need to create another SPI agent for passthrough interface and set it to device mode. And device should receive the passthrough SPI transaction from host.

If it's a read command, the passthrough device should return data for the host. @eunchan please confirm

2021-12-29 08:59 UTC, kosta-kojdic commented on hw/ip/spi_device/dv/tb/tb.sv
> +    .passthrough_o  (pass_out  ),
I think for most of passthrough features checking we don't need agent connected, just to collect and check output data, and it is done by this addtion of monitoring sdo0 for passthrough config

2022-01-04 17:39 UTC, eunchan commented on hw/ip/spi_device/dv/tb/tb.sv
> +    .passthrough_o  (pass_out  ),
SPI_DEVICE has configuration knobs to return the read data, status, jedec from internal hardware or not. For read, only the address falls into the mailbox address range is processed internally.

2022-01-04 19:11 UTC, weicaiyang commented on hw/ip/spi_device/dv/tb/tb.sv
> +    .passthrough_o  (pass_out  ),
when the req is passthrough, we should observe the changes on these signals. How can we just connect one signal to sdo0 for check?
```
  typedef struct packed {
    // passthrough_en: switch the mux for downstream SPI pad to host system not
    // the internal SPI_HOST IP
    logic       passthrough_en;

    // Passthrough includes SCK also. The sck_en is pad out enable not CG
    // enable. The CG is placed in SPI_DEVICE IP.
    logic       sck;
    logic       sck_gate_en; // TBD: place for CG?
    logic       sck_en;

    // CSb should be pull-up pad. In passthrough mode, CSb is directly connected
    // to the host systems CSb except when SPI_DEVICE decides to drop the
    // command.
    logic       csb;
    logic       csb_en;

    // SPI data from host system to downstream flash device.
    logic [3:0] s;
    logic [3:0] s_en;
  } passthrough_req_t;


```

2022-01-04 19:11 UTC, weicaiyang commented on hw/ip/spi_device/dv/tb/tb.sv
> +  assign spi_if.sio[2] = pass_out.csb ? 1'bz : pass_out.s;
looks like there is a data width mismatch.
spi_if.sio[2] is one bit wide, but pass_out.s is 4 bits.

2022-01-10 12:51 UTC, kosta-kojdic commented on hw/ip/spi_device/dv/tb/tb.sv
> +  assign spi_if.sio[2] = pass_out.csb ? 1'bz : pass_out.s;
In the current configuration only one bit of these 4 was relevant. But it has to be changed for all modes.

2022-01-10 12:52 UTC, kosta-kojdic commented on hw/ip/spi_device/dv/tb/tb.sv
> +    .passthrough_o  (pass_out  ),
What is the conclusion here? Do we need new spi_agent or it is just enough to observe all data signals in 1, 2 and 4 bit modes?

2022-01-10 19:30 UTC, weicaiyang commented on hw/ip/spi_device/dv/tb/tb.sv
> +    .passthrough_o  (pass_out  ),
I'd prefer to add an agent to monitor and respond the SPI request.

2022-01-31 10:33 UTC, rasmus-madsen requested changes
This test is a very directed test, I would have liked to see a more generic approach, as a set of tasks that the other tests could use to mix it in with the other traffic for better test coverage.

as a minimum, the passthrough should be randomized on/off per SPI-transaction.
as there are plenty of important cases to cover in the timing of enabling passthrough, 

I don't see the coverage plan updated with coverpoints for passthrough

2022-01-31 10:33 UTC, rasmus-madsen commented on hw/dv/sv/spi_agent/spi_agent_cfg.sv
> +  bit passthrough_on;     // Using passthrough mode
maybe rename this to passthrough? - the on, will be indicated by its value
```suggestion
  bit passthrough;     // Using passthrough mode
```

2022-01-31 10:33 UTC, rasmus-madsen commented on hw/ip/spi_device/data/spi_device_testplan.hjson
> +    }
I feel this is more describing a test than a test point.

2022-01-31 10:33 UTC, rasmus-madsen commented on hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_cmd_filtering_vseq.sv
> +      ral.cmd_info[11].addr_mode.set(2'h2); //  3B address for this scenario
do we want to randomize the address with to also verify this for 4Byte addresses?

2022-01-31 10:33 UTC, rasmus-madsen commented on hw/ip/spi_device/dv/env/spi_device_env.sv
> +   //       scoreboard.device_spi_data_fifo.analysis_export);
remove commented code

2022-01-31 10:33 UTC, rasmus-madsen commented on hw/ip/spi_device/dv/env/spi_device_env.sv
> +   // end
again remove commented code

2022-01-31 10:40 UTC, kosta-kojdic commented
> This test is a very directed test, I would have liked to see a more generic approach, as a set of tasks that the other tests could use to mix it in with the other traffic for better test coverage.
> 
> as a minimum, the passthrough should be randomized on/off per SPI-transaction. as there are plenty of important cases to cover in the timing of enabling passthrough,
> 
> I don't see the coverage plan updated with coverpoints for passthrough

I agree, this was intended as starting point in development, and @patel-madhuri will add more randomization this week. We can have on/off on passthrough as separate test, and still maybe keep this one as dedicated scenario.

2022-02-03 19:20 UTC, kosta-kojdic commented
Closing this, @patel-madhuri took changes and will make separate clean PR

2022-02-03 19:20 UTC, closed without merging