[sw/testing] IRQ vector configuration cleanup to fix #9787.
lowRISC/opentitan pull request #9877
Opened 2022-01-05 00:49 UTC by timothytrippel

This PR fixes #9787 by defining the IRQ vector configurations in the asm startup code for both the **Test** ROM/ROM_EXT.

Additionally, this PR cleans up the IRQ vector configurations for the test boot  stages.

2022-01-06 16:34 UTC, mcy approved these changes

2022-01-06 22:43 UTC, drewmacrae requested changes
It looks like sw/device/lib/testing/test_rom_ext/BUILD still depends on sw/device/lib/testing/test_rom_ext/test_rom_ext_irq_vector.S which is removed.

2022-01-07 00:44 UTC, timothytrippel commented
> It looks like sw/device/lib/testing/test_rom_ext/BUILD still depends on sw/device/lib/testing/test_rom_ext/test_rom_ext_irq_vector.S which is removed.

Fixed.

2022-01-12 14:00 UTC, drewmacrae approved these changes

2022-01-12 18:36 UTC, merged