[edn, dv] EDN interrupt, alert and error verification
lowRISC/opentitan pull request #9896
Opened 2022-01-06 00:36 UTC by Muqing-Liu

- Add vseqs for EDN interrupt, alert and error tests
  - Update related config files to include the interrupt, alert and error tests

Signed-off-by: Muqing Liu <muqing.liu@wdc.com>

2022-01-20 15:09 UTC, rasmus-madsen commented
@Muqing-Liu do you need help with the issues in this PR?

2022-01-28 22:23 UTC, cindychip commented
Right now CI failed due to this message:
```
                Error-[SV-LCM-HRP] Hierarchical reference in package
                ../src/lowrisc_dv_edn_env_0.1/seq_lib/edn_intr_vseq.sv, 59
                edn_env_pkg, "tb.dut.u_edn_core.u_prim_count_max_reqs_cntr.gen_cross_cnt_hardening.CrossCntErrBackward_A"
                  Hierarchical reference from package 'edn_env_pkg' into module 'tb' is not
                  allowed.

```

2022-02-04 18:19 UTC, Muqing-Liu commented on hw/ip/edn/dv/env/seq_lib/edn_alert_vseq.sv
> +    m_endpoint_pull_seq.start(p_sequencer.endpoint_sequencer_h[0]);
Yes, sure, I have randomized which endport to request data.

2022-02-04 18:43 UTC, Muqing-Liu commented
> Right now CI failed due to this message:
> 
> ```
>                 Error-[SV-LCM-HRP] Hierarchical reference in package
>                 ../src/lowrisc_dv_edn_env_0.1/seq_lib/edn_intr_vseq.sv, 59
>                 edn_env_pkg, "tb.dut.u_edn_core.u_prim_count_max_reqs_cntr.gen_cross_cnt_hardening.CrossCntErrBackward_A"
>                   Hierarchical reference from package 'edn_env_pkg' into module 'tb' is not
>                   allowed.
> ```
> 
> I wonder if it is because you need to make it a string?

Yes, there are some differences between xcelium and vcs, it worked in xcelium, but not in vcs, we have created a virtual assert interface to turn off the assertions with long paths.

2022-02-04 18:55 UTC, sriyerg commented on hw/ip/edn/dv/tests/edn_alert_test.sv
> +    `uvm_info("edn_intr_dbg", $sformatf("%s", cfg.convert2string()), UVM_LOW)
It is quite strange to have to re-randomize the cfg here. 
I suggest adding an empty `virtual function void configure_env()` in `hw/dv/sv/da_base_test.sv` and invoke it before `cfg` is randomized, so that we do not have to re-randomize here.

2022-02-04 18:57 UTC, sriyerg commented on hw/ip/edn/dv/sva/edn_assert_if.sv
> +
If you bind the `edn_assert_if` in `tb.sv` to `tb.dut`, then these paths are partial hierarchies within the DUT. That way, the EDN env is fully reusable (in other testbenches such as chip level).

2022-02-04 18:59 UTC, sriyerg commented on hw/ip/edn/dv/sva/edn_assert_if.sv
> +    tb.dut.u_edn_core.u_prim_mubi4_sync_cmd_fifo_rst
You could bind another assertion interface to `prim_mubi4_sync` module, so that these paths become immaterial.

2022-02-04 19:02 UTC, sriyerg commented on hw/ip/edn/dv/env/seq_lib/edn_intr_vseq.sv
> +        end
This is already tested in a common shared sequence - @weicaiyang

2022-02-04 19:02 UTC, sriyerg commented on hw/ip/edn/dv/env/seq_lib/edn_intr_vseq.sv
> +        path = "tb.dut.u_edn_core.u_edn_main_sm.state_q";
I would advise against having sequences referencing full paths in the DUT. Instead, create functions in an interface to facilitate the forces.

2022-02-09 19:47 UTC, Muqing-Liu commented on hw/ip/edn/dv/env/seq_lib/edn_intr_vseq.sv
> +        path = "tb.dut.u_edn_core.u_edn_main_sm.state_q";
Hi @sriyerg Thanks a lot for your advise! The forces involves various modules, do you think I should create different interfaces for different modules or just one interface for all those forces? Thanks!

2022-02-10 23:16 UTC, rasmus-madsen commented
> If you bind the edn_assert_if in tb.sv to tb.dut, then these paths are partial hierarchies within the DUT. That way, the EDN env is fully reusable (in other testbenches such as chip level).

@sriyerg  I think we need some guidance here.
as far as I can tell what you are suggesting is not possible for `$assertoff`
I have tried almost anything I can think of with the bind.

if you could make a small example that worked that would be very helpfull

2022-02-11 16:06 UTC, mwbranstad commented
Is this still a work in progress? Or is it close to approval stage?

2022-02-11 18:12 UTC, Muqing-Liu commented
> Is this still a work in progress? Or is it close to approval stage?

I am working on the last comments, but I am not sure whether there will be new comments or not.

2022-02-13 11:00 UTC, rasmus-madsen commented
@sriyerg @Muqing-Liu in order to move this forward so @senelson7 can have the V2 review
would you be ok with merging this.
and moving the requests of generic paths to an issue?

2022-02-13 11:01 UTC, rasmus-madsen commented
@Muqing-Liu can you rebase this and resolve the conflicts?

2022-02-16 22:28 UTC, martin-lueker commented
> @sriyerg @Muqing-Liu in order to move this forward so @senelson7 can have the V2 review would you be ok with merging this. and moving the requests of generic paths to an issue?

Hi @rasmus-madsen, 
   With the review so close I would strongly advise deferring this to an issue.  It can even be Priority:P1.  We just need these merged by Friday.  @sriyerg, would you approve this?

2022-02-16 22:29 UTC, martin-lueker commented
Hi Reviewers,
   Anka has scheduled a V2 review for this block on Friday.   Are there any substantial blocking issues here?  We would like to move the remaining formatting issues to follow-up/cleanup issues so that the review can proceed.

2022-02-16 23:06 UTC, Muqing-Liu commented on hw/ip/edn/dv/tests/edn_alert_test.sv
> +    `uvm_info("edn_intr_dbg", $sformatf("%s", cfg.convert2string()), UVM_LOW)
Done.

2022-02-16 23:08 UTC, Muqing-Liu commented on hw/ip/edn/dv/sva/edn_assert_if.sv
> +
I have binded edn_assert_if to tb.dut, but it seems that I still cannot remove the full paths in $assertoff. I will move this to an issue.

2022-02-16 23:08 UTC, Muqing-Liu commented on hw/ip/edn/dv/sva/edn_assert_if.sv
> +    tb.dut.u_edn_core.u_prim_mubi4_sync_cmd_fifo_rst
Similarly, I will move this to an issue.

2022-02-16 23:13 UTC, Muqing-Liu commented on hw/ip/edn/dv/env/seq_lib/edn_intr_vseq.sv
> +        end
This edn_cntr_err is part of the edn fatal_err interrupt, so for the completeness of this interrupt test, can I keep this?

2022-02-16 23:22 UTC, Muqing-Liu commented on hw/ip/edn/dv/env/seq_lib/edn_intr_vseq.sv
> +        path = "tb.dut.u_edn_core.u_edn_main_sm.state_q";
I have created a virtual path interface to deal with all the path references.

2022-02-18 05:09 UTC, matutem requested changes
I am sorry it took so long to review this: I had looked at it before and there were lots of suggestions which seemed to require changes. I was hoping the code would get somewhat cleaner after taking care of those suggestions. Anyway, I think this code needs work. Please follow some of these suggestions.

2022-02-18 05:09 UTC, matutem commented on hw/ip/edn/dv/env/seq_lib/edn_err_vseq.sv
> +      sfifo_rescmd_err_test: begin // ERR_CODE_TEST: SFIFO_RESCMD_ERR
Please use RAL to determine the value you write in err_code_test. For example ral.err_code.edn_cntr_err.get_lsb_pos() is 22, which is the value in line 168.

2022-02-18 20:42 UTC, Muqing-Liu commented on hw/ip/edn/dv/tests/edn_smoke_test.sv
> +    cfg.num_endpoints = 1;
Sure, line 16 deleted.

2022-02-18 20:42 UTC, Muqing-Liu commented on hw/ip/edn/dv/env/edn_env_cfg.sv
> +  constraint which_fatal_err_c { which_fatal_err inside {[0:4]};}
Thank you very much for your suggestion. I have removed all these random unit variables and constraints and randomize the enum directly.

2022-02-18 20:43 UTC, Muqing-Liu commented on hw/ip/edn/dv/env/edn_env_cfg.sv
> +  constraint which_fifo_write_err_c { which_fifo_write_err inside {[0:1]};}
Sure, I have created a new enum and randomize it instead.

2022-02-18 20:43 UTC, Muqing-Liu commented on hw/ip/edn/dv/env/edn_env_cfg.sv
> +  constraint which_fifo_err_c { which_fifo_err inside {[0:2]};}
Sure, I have created a enum and randomize it directly.

2022-02-18 20:43 UTC, Muqing-Liu commented on hw/ip/edn/dv/env/seq_lib/edn_alert_vseq.sv
> +    // Load constant genbits data to induce edn bus cmp alert
Sorry for the confusion here. I meant to say for different tests, the fips and genbits are randomly generated, but they only got randomized once at the beginning and stay constant through the test. I have updated the comments in the test to better clarify.

2022-02-18 20:43 UTC, Muqing-Liu commented on hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv
> +    // Clear the interrupt bit
Thank you for pointing this out. I have updated the comment.

2022-02-18 20:43 UTC, Muqing-Liu commented on hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv
> +      // Clear the interrupt bit
Comment updated.

2022-02-18 20:44 UTC, Muqing-Liu commented on hw/ip/edn/dv/env/seq_lib/edn_err_vseq.sv
> +        if (!uvm_hdl_check_path(path)) begin
Yes, sure. I called the force_path_err here.

2022-02-18 20:45 UTC, Muqing-Liu commented on hw/ip/edn/dv/env/seq_lib/edn_err_vseq.sv
> +      sfifo_rescmd_err_test: begin // ERR_CODE_TEST: SFIFO_RESCMD_ERR
Thank you for your suggestion. I have updated accordingly.

2022-02-25 01:42 UTC, martin-lueker approved these changes
More suggestions (based on @matutem's advise) on how to stream line this block.

2022-02-25 01:42 UTC, martin-lueker commented on hw/ip/edn/dv/env/edn_path_if.sv
> +  function automatic string sfifo_rescmd_err_path_push();
More functions that can probably be mapped to arrays, or otherwise into a few functions with a lot more incommon.

2022-02-25 01:42 UTC, martin-lueker commented on hw/ip/edn/dv/env/seq_lib/edn_err_vseq.sv
> +    case (cfg.which_err_code)
Can this case statement be reduced any?

2022-02-25 01:42 UTC, martin-lueker commented on hw/ip/edn/dv/env/seq_lib/edn_intr_vseq.sv
> +  task test_edn_fatal_err();
Another task with a long case statement.

2022-02-25 01:42 UTC, martin-lueker commented on hw/ip/edn/dv/env/seq_lib/edn_err_vseq.sv
> +    $assertoff(0, "tb.dut.u_edn_core.u_prim_fifo_sync_rescmd.DataKnown_A");
You can use core_path here, can't you?

2022-02-25 01:42 UTC, martin-lueker commented on hw/ip/edn/dv/sva/edn_assert_if.sv
> +    tb.dut.u_edn_core.u_prim_count_max_reqs_cntr.gen_cross_cnt_hardening
Can core_path be used here?

2022-02-25 01:42 UTC, martin-lueker commented on hw/ip/edn/dv/sva/edn_assert_if.sv
> +    tb.dut.u_edn_core.u_prim_mubi4_sync_edn_enable
Can these be made into a n array?

2022-02-25 01:42 UTC, martin-lueker commented on hw/ip/edn/dv/sva/edn_assert_if.sv
> +    $assertoff(0, `DV_STRINGIFY(`PATH2.PrimMubi4SyncCheckTransients_A));
Make the macros and array and this can become a fore loop

2022-02-25 19:05 UTC, matutem reviewed
As in https://github.com/lowRISC/opentitan/pull/10089, I hope you and Martin can change the code for better readability.

2022-02-28 18:57 UTC, Muqing-Liu commented on hw/ip/edn/dv/env/edn_path_if.sv
> +  function automatic string sfifo_rescmd_err_path_push();
Done.

2022-02-28 18:57 UTC, Muqing-Liu commented on hw/ip/edn/dv/env/seq_lib/edn_err_vseq.sv
> +    case (cfg.which_err_code)
Done.

2022-02-28 18:57 UTC, Muqing-Liu commented on hw/ip/edn/dv/env/seq_lib/edn_intr_vseq.sv
> +  task test_edn_fatal_err();
Done.

2022-03-01 13:15 UTC, martin-lueker approved these changes
Thanks for the changes @Muqing-Liu!

2022-03-01 13:16 UTC, martin-lueker commented
Hi @Muqing-Liu, It seems this needs a manual rebase again. (It happens with long-lived PRs!)

2022-03-16 19:41 UTC, matutem approved these changes
With a couple minor issues, LGTM.

2022-03-16 19:41 UTC, matutem commented on hw/ip/edn/dv/env/edn_env_cfg.sv
> +  virtual edn_assert_if edn_assert_if;
```suggestion
  virtual edn_assert_if edn_assert_vif;
```

2022-03-16 19:41 UTC, matutem commented on hw/ip/edn/dv/env/seq_lib/edn_alert_vseq.sv
> +    // Set the fields to invalid values
Could you clarify one of the values below will be invalid, per which_invalid_mubi.

2022-03-18 17:06 UTC, martin-lueker approved these changes

2022-03-18 17:06 UTC, martin-lueker commented on hw/ip/edn/dv/env/seq_lib/edn_alert_vseq.sv
> +    // One of the values below will be invalid, per which_invalid_mubi
Regarding @matutem's comment.  This might clear things up:
```suggestion
    // Depending on the value of cfg.which_invalid_mubi, one of the following ctrl register fields 
    // will be set to an invalid MuBI value.  
    // Apply the bad settings, and confirm the corresponding alert is fired.
```

2022-03-18 18:55 UTC, martin-lueker commented on hw/ip/edn/dv/env/edn_env_cfg.sv
> +  virtual edn_assert_if edn_assert_if;
I see @Muqing-Liu has adopted this.

2022-03-18 19:56 UTC, martin-lueker commented on hw/ip/edn/dv/env/seq_lib/edn_alert_vseq.sv
> +    // Set the fields to invalid values
Thanks @matutem.  This has been Clarified using comment below.

2022-03-18 19:56 UTC, merged